using EngineeringUnits;
using EngineeringUnits.Units;

namespace EngineeringUnits.NumberExtensions.NumberToElectricCurrent;

// <auto-generated/>
// This file is auto-generated; changes will be overwritten.
public static class NumberToElectricCurrentExtensions
{
    // double receiver
    extension(double value)
    {
        public ElectricCurrent Ampere => new ElectricCurrent(value, ElectricCurrentUnit.Ampere);
        public ElectricCurrent Centiampere => new ElectricCurrent(value, ElectricCurrentUnit.Centiampere);
        public ElectricCurrent Kiloampere => new ElectricCurrent(value, ElectricCurrentUnit.Kiloampere);
        public ElectricCurrent Megaampere => new ElectricCurrent(value, ElectricCurrentUnit.Megaampere);
        public ElectricCurrent Microampere => new ElectricCurrent(value, ElectricCurrentUnit.Microampere);
        public ElectricCurrent Milliampere => new ElectricCurrent(value, ElectricCurrentUnit.Milliampere);
        public ElectricCurrent Nanoampere => new ElectricCurrent(value, ElectricCurrentUnit.Nanoampere);
        public ElectricCurrent Picoampere => new ElectricCurrent(value, ElectricCurrentUnit.Picoampere);
    }

    // int receiver
    extension(int value)
    {
        public ElectricCurrent Ampere => new ElectricCurrent(value, ElectricCurrentUnit.Ampere);
        public ElectricCurrent Centiampere => new ElectricCurrent(value, ElectricCurrentUnit.Centiampere);
        public ElectricCurrent Kiloampere => new ElectricCurrent(value, ElectricCurrentUnit.Kiloampere);
        public ElectricCurrent Megaampere => new ElectricCurrent(value, ElectricCurrentUnit.Megaampere);
        public ElectricCurrent Microampere => new ElectricCurrent(value, ElectricCurrentUnit.Microampere);
        public ElectricCurrent Milliampere => new ElectricCurrent(value, ElectricCurrentUnit.Milliampere);
        public ElectricCurrent Nanoampere => new ElectricCurrent(value, ElectricCurrentUnit.Nanoampere);
        public ElectricCurrent Picoampere => new ElectricCurrent(value, ElectricCurrentUnit.Picoampere);
    }

    // decimal receiver (convert as needed)
    extension(decimal value)
    {
        public ElectricCurrent Ampere => new ElectricCurrent((double)value, ElectricCurrentUnit.Ampere);
        public ElectricCurrent Centiampere => new ElectricCurrent((double)value, ElectricCurrentUnit.Centiampere);
        public ElectricCurrent Kiloampere => new ElectricCurrent((double)value, ElectricCurrentUnit.Kiloampere);
        public ElectricCurrent Megaampere => new ElectricCurrent((double)value, ElectricCurrentUnit.Megaampere);
        public ElectricCurrent Microampere => new ElectricCurrent((double)value, ElectricCurrentUnit.Microampere);
        public ElectricCurrent Milliampere => new ElectricCurrent((double)value, ElectricCurrentUnit.Milliampere);
        public ElectricCurrent Nanoampere => new ElectricCurrent((double)value, ElectricCurrentUnit.Nanoampere);
        public ElectricCurrent Picoampere => new ElectricCurrent((double)value, ElectricCurrentUnit.Picoampere);
    }
}