using EngineeringUnits;
using EngineeringUnits.Units;

namespace EngineeringUnits.NumberExtensions.NumberToPressure;

// <auto-generated/>
// This file is auto-generated; changes will be overwritten.
public static class NumberToPressureExtensions
{
    // double receiver
    extension(double value)
    {
        public Pressure Atmosphere => new Pressure(value, PressureUnit.Atmosphere);
        public Pressure Bar => new Pressure(value, PressureUnit.Bar);
        public Pressure BarA => new Pressure(value, PressureUnit.BarA);
        public Pressure BarG => new Pressure(value, PressureUnit.BarG);
        public Pressure Centibar => new Pressure(value, PressureUnit.Centibar);
        public Pressure Decapascal => new Pressure(value, PressureUnit.Decapascal);
        public Pressure Decibar => new Pressure(value, PressureUnit.Decibar);
        public Pressure DynePerSquareCentimeter => new Pressure(value, PressureUnit.DynePerSquareCentimeter);
        public Pressure FootOfHead => new Pressure(value, PressureUnit.FootOfHead);
        public Pressure Gigapascal => new Pressure(value, PressureUnit.Gigapascal);
        public Pressure Hectopascal => new Pressure(value, PressureUnit.Hectopascal);
        public Pressure InchOfMercury => new Pressure(value, PressureUnit.InchOfMercury);
        public Pressure InchOfWaterColumn => new Pressure(value, PressureUnit.InchOfWaterColumn);
        public Pressure Kilobar => new Pressure(value, PressureUnit.Kilobar);
        public Pressure KilogramForcePerSquareCentimeter => new Pressure(value, PressureUnit.KilogramForcePerSquareCentimeter);
        public Pressure KilogramForcePerSquareMeter => new Pressure(value, PressureUnit.KilogramForcePerSquareMeter);
        public Pressure KilogramForcePerSquareMillimeter => new Pressure(value, PressureUnit.KilogramForcePerSquareMillimeter);
        public Pressure KilonewtonPerSquareCentimeter => new Pressure(value, PressureUnit.KilonewtonPerSquareCentimeter);
        public Pressure KilonewtonPerSquareMeter => new Pressure(value, PressureUnit.KilonewtonPerSquareMeter);
        public Pressure KilonewtonPerSquareMillimeter => new Pressure(value, PressureUnit.KilonewtonPerSquareMillimeter);
        public Pressure Kilopascal => new Pressure(value, PressureUnit.Kilopascal);
        public Pressure KilopoundForcePerSquareFoot => new Pressure(value, PressureUnit.KilopoundForcePerSquareFoot);
        public Pressure KilopoundForcePerSquareInch => new Pressure(value, PressureUnit.KilopoundForcePerSquareInch);
        public Pressure Megabar => new Pressure(value, PressureUnit.Megabar);
        public Pressure MeganewtonPerSquareMeter => new Pressure(value, PressureUnit.MeganewtonPerSquareMeter);
        public Pressure Megapascal => new Pressure(value, PressureUnit.Megapascal);
        public Pressure MeterOfHead => new Pressure(value, PressureUnit.MeterOfHead);
        public Pressure Microbar => new Pressure(value, PressureUnit.Microbar);
        public Pressure Micropascal => new Pressure(value, PressureUnit.Micropascal);
        public Pressure Millibar => new Pressure(value, PressureUnit.Millibar);
        public Pressure MillimeterOfMercury => new Pressure(value, PressureUnit.MillimeterOfMercury);
        public Pressure Millipascal => new Pressure(value, PressureUnit.Millipascal);
        public Pressure NewtonPerSquareCentimeter => new Pressure(value, PressureUnit.NewtonPerSquareCentimeter);
        public Pressure NewtonPerSquareMeter => new Pressure(value, PressureUnit.NewtonPerSquareMeter);
        public Pressure NewtonPerSquareMillimeter => new Pressure(value, PressureUnit.NewtonPerSquareMillimeter);
        public Pressure Pascal => new Pressure(value, PressureUnit.Pascal);
        public Pressure PoundForcePerSquareFoot => new Pressure(value, PressureUnit.PoundForcePerSquareFoot);
        public Pressure PoundForcePerSquareInch => new Pressure(value, PressureUnit.PoundForcePerSquareInch);
        public Pressure PoundPerInchSecondSquared => new Pressure(value, PressureUnit.PoundPerInchSecondSquared);
        public Pressure TechnicalAtmosphere => new Pressure(value, PressureUnit.TechnicalAtmosphere);
        public Pressure TonneForcePerSquareCentimeter => new Pressure(value, PressureUnit.TonneForcePerSquareCentimeter);
        public Pressure TonneForcePerSquareMeter => new Pressure(value, PressureUnit.TonneForcePerSquareMeter);
        public Pressure TonneForcePerSquareMillimeter => new Pressure(value, PressureUnit.TonneForcePerSquareMillimeter);
        public Pressure Torr => new Pressure(value, PressureUnit.Torr);
    }

    // int receiver
    extension(int value)
    {
        public Pressure Atmosphere => new Pressure(value, PressureUnit.Atmosphere);
        public Pressure Bar => new Pressure(value, PressureUnit.Bar);
        public Pressure BarA => new Pressure(value, PressureUnit.BarA);
        public Pressure BarG => new Pressure(value, PressureUnit.BarG);
        public Pressure Centibar => new Pressure(value, PressureUnit.Centibar);
        public Pressure Decapascal => new Pressure(value, PressureUnit.Decapascal);
        public Pressure Decibar => new Pressure(value, PressureUnit.Decibar);
        public Pressure DynePerSquareCentimeter => new Pressure(value, PressureUnit.DynePerSquareCentimeter);
        public Pressure FootOfHead => new Pressure(value, PressureUnit.FootOfHead);
        public Pressure Gigapascal => new Pressure(value, PressureUnit.Gigapascal);
        public Pressure Hectopascal => new Pressure(value, PressureUnit.Hectopascal);
        public Pressure InchOfMercury => new Pressure(value, PressureUnit.InchOfMercury);
        public Pressure InchOfWaterColumn => new Pressure(value, PressureUnit.InchOfWaterColumn);
        public Pressure Kilobar => new Pressure(value, PressureUnit.Kilobar);
        public Pressure KilogramForcePerSquareCentimeter => new Pressure(value, PressureUnit.KilogramForcePerSquareCentimeter);
        public Pressure KilogramForcePerSquareMeter => new Pressure(value, PressureUnit.KilogramForcePerSquareMeter);
        public Pressure KilogramForcePerSquareMillimeter => new Pressure(value, PressureUnit.KilogramForcePerSquareMillimeter);
        public Pressure KilonewtonPerSquareCentimeter => new Pressure(value, PressureUnit.KilonewtonPerSquareCentimeter);
        public Pressure KilonewtonPerSquareMeter => new Pressure(value, PressureUnit.KilonewtonPerSquareMeter);
        public Pressure KilonewtonPerSquareMillimeter => new Pressure(value, PressureUnit.KilonewtonPerSquareMillimeter);
        public Pressure Kilopascal => new Pressure(value, PressureUnit.Kilopascal);
        public Pressure KilopoundForcePerSquareFoot => new Pressure(value, PressureUnit.KilopoundForcePerSquareFoot);
        public Pressure KilopoundForcePerSquareInch => new Pressure(value, PressureUnit.KilopoundForcePerSquareInch);
        public Pressure Megabar => new Pressure(value, PressureUnit.Megabar);
        public Pressure MeganewtonPerSquareMeter => new Pressure(value, PressureUnit.MeganewtonPerSquareMeter);
        public Pressure Megapascal => new Pressure(value, PressureUnit.Megapascal);
        public Pressure MeterOfHead => new Pressure(value, PressureUnit.MeterOfHead);
        public Pressure Microbar => new Pressure(value, PressureUnit.Microbar);
        public Pressure Micropascal => new Pressure(value, PressureUnit.Micropascal);
        public Pressure Millibar => new Pressure(value, PressureUnit.Millibar);
        public Pressure MillimeterOfMercury => new Pressure(value, PressureUnit.MillimeterOfMercury);
        public Pressure Millipascal => new Pressure(value, PressureUnit.Millipascal);
        public Pressure NewtonPerSquareCentimeter => new Pressure(value, PressureUnit.NewtonPerSquareCentimeter);
        public Pressure NewtonPerSquareMeter => new Pressure(value, PressureUnit.NewtonPerSquareMeter);
        public Pressure NewtonPerSquareMillimeter => new Pressure(value, PressureUnit.NewtonPerSquareMillimeter);
        public Pressure Pascal => new Pressure(value, PressureUnit.Pascal);
        public Pressure PoundForcePerSquareFoot => new Pressure(value, PressureUnit.PoundForcePerSquareFoot);
        public Pressure PoundForcePerSquareInch => new Pressure(value, PressureUnit.PoundForcePerSquareInch);
        public Pressure PoundPerInchSecondSquared => new Pressure(value, PressureUnit.PoundPerInchSecondSquared);
        public Pressure TechnicalAtmosphere => new Pressure(value, PressureUnit.TechnicalAtmosphere);
        public Pressure TonneForcePerSquareCentimeter => new Pressure(value, PressureUnit.TonneForcePerSquareCentimeter);
        public Pressure TonneForcePerSquareMeter => new Pressure(value, PressureUnit.TonneForcePerSquareMeter);
        public Pressure TonneForcePerSquareMillimeter => new Pressure(value, PressureUnit.TonneForcePerSquareMillimeter);
        public Pressure Torr => new Pressure(value, PressureUnit.Torr);
    }

    // decimal receiver (convert as needed)
    extension(decimal value)
    {
        public Pressure Atmosphere => new Pressure((double)value, PressureUnit.Atmosphere);
        public Pressure Bar => new Pressure((double)value, PressureUnit.Bar);
        public Pressure BarA => new Pressure((double)value, PressureUnit.BarA);
        public Pressure BarG => new Pressure((double)value, PressureUnit.BarG);
        public Pressure Centibar => new Pressure((double)value, PressureUnit.Centibar);
        public Pressure Decapascal => new Pressure((double)value, PressureUnit.Decapascal);
        public Pressure Decibar => new Pressure((double)value, PressureUnit.Decibar);
        public Pressure DynePerSquareCentimeter => new Pressure((double)value, PressureUnit.DynePerSquareCentimeter);
        public Pressure FootOfHead => new Pressure((double)value, PressureUnit.FootOfHead);
        public Pressure Gigapascal => new Pressure((double)value, PressureUnit.Gigapascal);
        public Pressure Hectopascal => new Pressure((double)value, PressureUnit.Hectopascal);
        public Pressure InchOfMercury => new Pressure((double)value, PressureUnit.InchOfMercury);
        public Pressure InchOfWaterColumn => new Pressure((double)value, PressureUnit.InchOfWaterColumn);
        public Pressure Kilobar => new Pressure((double)value, PressureUnit.Kilobar);
        public Pressure KilogramForcePerSquareCentimeter => new Pressure((double)value, PressureUnit.KilogramForcePerSquareCentimeter);
        public Pressure KilogramForcePerSquareMeter => new Pressure((double)value, PressureUnit.KilogramForcePerSquareMeter);
        public Pressure KilogramForcePerSquareMillimeter => new Pressure((double)value, PressureUnit.KilogramForcePerSquareMillimeter);
        public Pressure KilonewtonPerSquareCentimeter => new Pressure((double)value, PressureUnit.KilonewtonPerSquareCentimeter);
        public Pressure KilonewtonPerSquareMeter => new Pressure((double)value, PressureUnit.KilonewtonPerSquareMeter);
        public Pressure KilonewtonPerSquareMillimeter => new Pressure((double)value, PressureUnit.KilonewtonPerSquareMillimeter);
        public Pressure Kilopascal => new Pressure((double)value, PressureUnit.Kilopascal);
        public Pressure KilopoundForcePerSquareFoot => new Pressure((double)value, PressureUnit.KilopoundForcePerSquareFoot);
        public Pressure KilopoundForcePerSquareInch => new Pressure((double)value, PressureUnit.KilopoundForcePerSquareInch);
        public Pressure Megabar => new Pressure((double)value, PressureUnit.Megabar);
        public Pressure MeganewtonPerSquareMeter => new Pressure((double)value, PressureUnit.MeganewtonPerSquareMeter);
        public Pressure Megapascal => new Pressure((double)value, PressureUnit.Megapascal);
        public Pressure MeterOfHead => new Pressure((double)value, PressureUnit.MeterOfHead);
        public Pressure Microbar => new Pressure((double)value, PressureUnit.Microbar);
        public Pressure Micropascal => new Pressure((double)value, PressureUnit.Micropascal);
        public Pressure Millibar => new Pressure((double)value, PressureUnit.Millibar);
        public Pressure MillimeterOfMercury => new Pressure((double)value, PressureUnit.MillimeterOfMercury);
        public Pressure Millipascal => new Pressure((double)value, PressureUnit.Millipascal);
        public Pressure NewtonPerSquareCentimeter => new Pressure((double)value, PressureUnit.NewtonPerSquareCentimeter);
        public Pressure NewtonPerSquareMeter => new Pressure((double)value, PressureUnit.NewtonPerSquareMeter);
        public Pressure NewtonPerSquareMillimeter => new Pressure((double)value, PressureUnit.NewtonPerSquareMillimeter);
        public Pressure Pascal => new Pressure((double)value, PressureUnit.Pascal);
        public Pressure PoundForcePerSquareFoot => new Pressure((double)value, PressureUnit.PoundForcePerSquareFoot);
        public Pressure PoundForcePerSquareInch => new Pressure((double)value, PressureUnit.PoundForcePerSquareInch);
        public Pressure PoundPerInchSecondSquared => new Pressure((double)value, PressureUnit.PoundPerInchSecondSquared);
        public Pressure TechnicalAtmosphere => new Pressure((double)value, PressureUnit.TechnicalAtmosphere);
        public Pressure TonneForcePerSquareCentimeter => new Pressure((double)value, PressureUnit.TonneForcePerSquareCentimeter);
        public Pressure TonneForcePerSquareMeter => new Pressure((double)value, PressureUnit.TonneForcePerSquareMeter);
        public Pressure TonneForcePerSquareMillimeter => new Pressure((double)value, PressureUnit.TonneForcePerSquareMillimeter);
        public Pressure Torr => new Pressure((double)value, PressureUnit.Torr);
    }
}