using EngineeringUnits;
using EngineeringUnits.Units;

namespace EngineeringUnits.NumberExtensions.NumberToElectricChargeDensity;

// <auto-generated/>
// This file is auto-generated; changes will be overwritten.
public static class NumberToElectricChargeDensityExtensions
{
    // double receiver
    extension(double value)
    {
        public ElectricChargeDensity CoulombPerCubicMeter => new ElectricChargeDensity(value, ElectricChargeDensityUnit.CoulombPerCubicMeter);
    }

    // int receiver
    extension(int value)
    {
        public ElectricChargeDensity CoulombPerCubicMeter => new ElectricChargeDensity(value, ElectricChargeDensityUnit.CoulombPerCubicMeter);
    }

    // decimal receiver (convert as needed)
    extension(decimal value)
    {
        public ElectricChargeDensity CoulombPerCubicMeter => new ElectricChargeDensity((double)value, ElectricChargeDensityUnit.CoulombPerCubicMeter);
    }
}