using EngineeringUnits;
using EngineeringUnits.Units;

namespace EngineeringUnits.NumberExtensions.NumberToLapseRate;

// <auto-generated/>
// This file is auto-generated; changes will be overwritten.
public static class NumberToLapseRateExtensions
{
    // double receiver
    extension(double value)
    {
        public LapseRate DegreeCelsiusPerKilometer => new LapseRate(value, LapseRateUnit.DegreeCelsiusPerKilometer);
    }

    // int receiver
    extension(int value)
    {
        public LapseRate DegreeCelsiusPerKilometer => new LapseRate(value, LapseRateUnit.DegreeCelsiusPerKilometer);
    }

    // decimal receiver (convert as needed)
    extension(decimal value)
    {
        public LapseRate DegreeCelsiusPerKilometer => new LapseRate((double)value, LapseRateUnit.DegreeCelsiusPerKilometer);
    }
}