using EngineeringUnits;
using EngineeringUnits.Units;

namespace EngineeringUnits.NumberExtensions.NumberToInformation;

// <auto-generated/>
// This file is auto-generated; changes will be overwritten.
public static class NumberToInformationExtensions
{
    // double receiver
    extension(double value)
    {
        public Information Bit => new Information(value, InformationUnit.Bit);
        public Information Byte => new Information(value, InformationUnit.Byte);
        public Information Exabit => new Information(value, InformationUnit.Exabit);
        public Information Exabyte => new Information(value, InformationUnit.Exabyte);
        public Information Exbibit => new Information(value, InformationUnit.Exbibit);
        public Information Exbibyte => new Information(value, InformationUnit.Exbibyte);
        public Information Gibibit => new Information(value, InformationUnit.Gibibit);
        public Information Gibibyte => new Information(value, InformationUnit.Gibibyte);
        public Information Gigabit => new Information(value, InformationUnit.Gigabit);
        public Information Gigabyte => new Information(value, InformationUnit.Gigabyte);
        public Information Kibibit => new Information(value, InformationUnit.Kibibit);
        public Information Kibibyte => new Information(value, InformationUnit.Kibibyte);
        public Information Kilobit => new Information(value, InformationUnit.Kilobit);
        public Information Kilobyte => new Information(value, InformationUnit.Kilobyte);
        public Information Mebibit => new Information(value, InformationUnit.Mebibit);
        public Information Mebibyte => new Information(value, InformationUnit.Mebibyte);
        public Information Megabit => new Information(value, InformationUnit.Megabit);
        public Information Megabyte => new Information(value, InformationUnit.Megabyte);
        public Information Pebibit => new Information(value, InformationUnit.Pebibit);
        public Information Pebibyte => new Information(value, InformationUnit.Pebibyte);
        public Information Petabit => new Information(value, InformationUnit.Petabit);
        public Information Petabyte => new Information(value, InformationUnit.Petabyte);
        public Information Tebibit => new Information(value, InformationUnit.Tebibit);
        public Information Tebibyte => new Information(value, InformationUnit.Tebibyte);
        public Information Terabit => new Information(value, InformationUnit.Terabit);
        public Information Terabyte => new Information(value, InformationUnit.Terabyte);
    }

    // int receiver
    extension(int value)
    {
        public Information Bit => new Information(value, InformationUnit.Bit);
        public Information Byte => new Information(value, InformationUnit.Byte);
        public Information Exabit => new Information(value, InformationUnit.Exabit);
        public Information Exabyte => new Information(value, InformationUnit.Exabyte);
        public Information Exbibit => new Information(value, InformationUnit.Exbibit);
        public Information Exbibyte => new Information(value, InformationUnit.Exbibyte);
        public Information Gibibit => new Information(value, InformationUnit.Gibibit);
        public Information Gibibyte => new Information(value, InformationUnit.Gibibyte);
        public Information Gigabit => new Information(value, InformationUnit.Gigabit);
        public Information Gigabyte => new Information(value, InformationUnit.Gigabyte);
        public Information Kibibit => new Information(value, InformationUnit.Kibibit);
        public Information Kibibyte => new Information(value, InformationUnit.Kibibyte);
        public Information Kilobit => new Information(value, InformationUnit.Kilobit);
        public Information Kilobyte => new Information(value, InformationUnit.Kilobyte);
        public Information Mebibit => new Information(value, InformationUnit.Mebibit);
        public Information Mebibyte => new Information(value, InformationUnit.Mebibyte);
        public Information Megabit => new Information(value, InformationUnit.Megabit);
        public Information Megabyte => new Information(value, InformationUnit.Megabyte);
        public Information Pebibit => new Information(value, InformationUnit.Pebibit);
        public Information Pebibyte => new Information(value, InformationUnit.Pebibyte);
        public Information Petabit => new Information(value, InformationUnit.Petabit);
        public Information Petabyte => new Information(value, InformationUnit.Petabyte);
        public Information Tebibit => new Information(value, InformationUnit.Tebibit);
        public Information Tebibyte => new Information(value, InformationUnit.Tebibyte);
        public Information Terabit => new Information(value, InformationUnit.Terabit);
        public Information Terabyte => new Information(value, InformationUnit.Terabyte);
    }

    // decimal receiver (convert as needed)
    extension(decimal value)
    {
        public Information Bit => new Information((double)value, InformationUnit.Bit);
        public Information Byte => new Information((double)value, InformationUnit.Byte);
        public Information Exabit => new Information((double)value, InformationUnit.Exabit);
        public Information Exabyte => new Information((double)value, InformationUnit.Exabyte);
        public Information Exbibit => new Information((double)value, InformationUnit.Exbibit);
        public Information Exbibyte => new Information((double)value, InformationUnit.Exbibyte);
        public Information Gibibit => new Information((double)value, InformationUnit.Gibibit);
        public Information Gibibyte => new Information((double)value, InformationUnit.Gibibyte);
        public Information Gigabit => new Information((double)value, InformationUnit.Gigabit);
        public Information Gigabyte => new Information((double)value, InformationUnit.Gigabyte);
        public Information Kibibit => new Information((double)value, InformationUnit.Kibibit);
        public Information Kibibyte => new Information((double)value, InformationUnit.Kibibyte);
        public Information Kilobit => new Information((double)value, InformationUnit.Kilobit);
        public Information Kilobyte => new Information((double)value, InformationUnit.Kilobyte);
        public Information Mebibit => new Information((double)value, InformationUnit.Mebibit);
        public Information Mebibyte => new Information((double)value, InformationUnit.Mebibyte);
        public Information Megabit => new Information((double)value, InformationUnit.Megabit);
        public Information Megabyte => new Information((double)value, InformationUnit.Megabyte);
        public Information Pebibit => new Information((double)value, InformationUnit.Pebibit);
        public Information Pebibyte => new Information((double)value, InformationUnit.Pebibyte);
        public Information Petabit => new Information((double)value, InformationUnit.Petabit);
        public Information Petabyte => new Information((double)value, InformationUnit.Petabyte);
        public Information Tebibit => new Information((double)value, InformationUnit.Tebibit);
        public Information Tebibyte => new Information((double)value, InformationUnit.Tebibyte);
        public Information Terabit => new Information((double)value, InformationUnit.Terabit);
        public Information Terabyte => new Information((double)value, InformationUnit.Terabyte);
    }
}