using EngineeringUnits;
using EngineeringUnits.Units;

namespace EngineeringUnits.NumberExtensions.NumberToElectricResistivity;

// <auto-generated/>
// This file is auto-generated; changes will be overwritten.
public static class NumberToElectricResistivityExtensions
{
    // double receiver
    extension(double value)
    {
        public ElectricResistivity KiloohmCentimeter => new ElectricResistivity(value, ElectricResistivityUnit.KiloohmCentimeter);
        public ElectricResistivity KiloohmMeter => new ElectricResistivity(value, ElectricResistivityUnit.KiloohmMeter);
        public ElectricResistivity MegaohmCentimeter => new ElectricResistivity(value, ElectricResistivityUnit.MegaohmCentimeter);
        public ElectricResistivity MegaohmMeter => new ElectricResistivity(value, ElectricResistivityUnit.MegaohmMeter);
        public ElectricResistivity MicroohmCentimeter => new ElectricResistivity(value, ElectricResistivityUnit.MicroohmCentimeter);
        public ElectricResistivity MicroohmMeter => new ElectricResistivity(value, ElectricResistivityUnit.MicroohmMeter);
        public ElectricResistivity MilliohmCentimeter => new ElectricResistivity(value, ElectricResistivityUnit.MilliohmCentimeter);
        public ElectricResistivity MilliohmMeter => new ElectricResistivity(value, ElectricResistivityUnit.MilliohmMeter);
        public ElectricResistivity NanoohmCentimeter => new ElectricResistivity(value, ElectricResistivityUnit.NanoohmCentimeter);
        public ElectricResistivity NanoohmMeter => new ElectricResistivity(value, ElectricResistivityUnit.NanoohmMeter);
        public ElectricResistivity OhmCentimeter => new ElectricResistivity(value, ElectricResistivityUnit.OhmCentimeter);
        public ElectricResistivity OhmMeter => new ElectricResistivity(value, ElectricResistivityUnit.OhmMeter);
        public ElectricResistivity PicoohmCentimeter => new ElectricResistivity(value, ElectricResistivityUnit.PicoohmCentimeter);
        public ElectricResistivity PicoohmMeter => new ElectricResistivity(value, ElectricResistivityUnit.PicoohmMeter);
    }

    // int receiver
    extension(int value)
    {
        public ElectricResistivity KiloohmCentimeter => new ElectricResistivity(value, ElectricResistivityUnit.KiloohmCentimeter);
        public ElectricResistivity KiloohmMeter => new ElectricResistivity(value, ElectricResistivityUnit.KiloohmMeter);
        public ElectricResistivity MegaohmCentimeter => new ElectricResistivity(value, ElectricResistivityUnit.MegaohmCentimeter);
        public ElectricResistivity MegaohmMeter => new ElectricResistivity(value, ElectricResistivityUnit.MegaohmMeter);
        public ElectricResistivity MicroohmCentimeter => new ElectricResistivity(value, ElectricResistivityUnit.MicroohmCentimeter);
        public ElectricResistivity MicroohmMeter => new ElectricResistivity(value, ElectricResistivityUnit.MicroohmMeter);
        public ElectricResistivity MilliohmCentimeter => new ElectricResistivity(value, ElectricResistivityUnit.MilliohmCentimeter);
        public ElectricResistivity MilliohmMeter => new ElectricResistivity(value, ElectricResistivityUnit.MilliohmMeter);
        public ElectricResistivity NanoohmCentimeter => new ElectricResistivity(value, ElectricResistivityUnit.NanoohmCentimeter);
        public ElectricResistivity NanoohmMeter => new ElectricResistivity(value, ElectricResistivityUnit.NanoohmMeter);
        public ElectricResistivity OhmCentimeter => new ElectricResistivity(value, ElectricResistivityUnit.OhmCentimeter);
        public ElectricResistivity OhmMeter => new ElectricResistivity(value, ElectricResistivityUnit.OhmMeter);
        public ElectricResistivity PicoohmCentimeter => new ElectricResistivity(value, ElectricResistivityUnit.PicoohmCentimeter);
        public ElectricResistivity PicoohmMeter => new ElectricResistivity(value, ElectricResistivityUnit.PicoohmMeter);
    }

    // decimal receiver (convert as needed)
    extension(decimal value)
    {
        public ElectricResistivity KiloohmCentimeter => new ElectricResistivity((double)value, ElectricResistivityUnit.KiloohmCentimeter);
        public ElectricResistivity KiloohmMeter => new ElectricResistivity((double)value, ElectricResistivityUnit.KiloohmMeter);
        public ElectricResistivity MegaohmCentimeter => new ElectricResistivity((double)value, ElectricResistivityUnit.MegaohmCentimeter);
        public ElectricResistivity MegaohmMeter => new ElectricResistivity((double)value, ElectricResistivityUnit.MegaohmMeter);
        public ElectricResistivity MicroohmCentimeter => new ElectricResistivity((double)value, ElectricResistivityUnit.MicroohmCentimeter);
        public ElectricResistivity MicroohmMeter => new ElectricResistivity((double)value, ElectricResistivityUnit.MicroohmMeter);
        public ElectricResistivity MilliohmCentimeter => new ElectricResistivity((double)value, ElectricResistivityUnit.MilliohmCentimeter);
        public ElectricResistivity MilliohmMeter => new ElectricResistivity((double)value, ElectricResistivityUnit.MilliohmMeter);
        public ElectricResistivity NanoohmCentimeter => new ElectricResistivity((double)value, ElectricResistivityUnit.NanoohmCentimeter);
        public ElectricResistivity NanoohmMeter => new ElectricResistivity((double)value, ElectricResistivityUnit.NanoohmMeter);
        public ElectricResistivity OhmCentimeter => new ElectricResistivity((double)value, ElectricResistivityUnit.OhmCentimeter);
        public ElectricResistivity OhmMeter => new ElectricResistivity((double)value, ElectricResistivityUnit.OhmMeter);
        public ElectricResistivity PicoohmCentimeter => new ElectricResistivity((double)value, ElectricResistivityUnit.PicoohmCentimeter);
        public ElectricResistivity PicoohmMeter => new ElectricResistivity((double)value, ElectricResistivityUnit.PicoohmMeter);
    }
}