using EngineeringUnits;
using EngineeringUnits.Units;

namespace EngineeringUnits.NumberExtensions.NumberToArea;

// <auto-generated/>
// This file is auto-generated; changes will be overwritten.
public static class NumberToAreaExtensions
{
    // double receiver
    extension(double value)
    {
        public Area Acre => new Area(value, AreaUnit.Acre);
        public Area Hectare => new Area(value, AreaUnit.Hectare);
        public Area SquareCentimeter => new Area(value, AreaUnit.SquareCentimeter);
        public Area SquareChain => new Area(value, AreaUnit.SquareChain);
        public Area SquareDecimeter => new Area(value, AreaUnit.SquareDecimeter);
        public Area SquareFoot => new Area(value, AreaUnit.SquareFoot);
        public Area SquareInch => new Area(value, AreaUnit.SquareInch);
        public Area SquareKilometer => new Area(value, AreaUnit.SquareKilometer);
        public Area SquareMeter => new Area(value, AreaUnit.SquareMeter);
        public Area SquareMicrometer => new Area(value, AreaUnit.SquareMicrometer);
        public Area SquareMile => new Area(value, AreaUnit.SquareMile);
        public Area SquareMillimeter => new Area(value, AreaUnit.SquareMillimeter);
        public Area SquareNanometer => new Area(value, AreaUnit.SquareNanometer);
        public Area SquareNauticalMile => new Area(value, AreaUnit.SquareNauticalMile);
        public Area SquareYard => new Area(value, AreaUnit.SquareYard);
    }

    // int receiver
    extension(int value)
    {
        public Area Acre => new Area(value, AreaUnit.Acre);
        public Area Hectare => new Area(value, AreaUnit.Hectare);
        public Area SquareCentimeter => new Area(value, AreaUnit.SquareCentimeter);
        public Area SquareChain => new Area(value, AreaUnit.SquareChain);
        public Area SquareDecimeter => new Area(value, AreaUnit.SquareDecimeter);
        public Area SquareFoot => new Area(value, AreaUnit.SquareFoot);
        public Area SquareInch => new Area(value, AreaUnit.SquareInch);
        public Area SquareKilometer => new Area(value, AreaUnit.SquareKilometer);
        public Area SquareMeter => new Area(value, AreaUnit.SquareMeter);
        public Area SquareMicrometer => new Area(value, AreaUnit.SquareMicrometer);
        public Area SquareMile => new Area(value, AreaUnit.SquareMile);
        public Area SquareMillimeter => new Area(value, AreaUnit.SquareMillimeter);
        public Area SquareNanometer => new Area(value, AreaUnit.SquareNanometer);
        public Area SquareNauticalMile => new Area(value, AreaUnit.SquareNauticalMile);
        public Area SquareYard => new Area(value, AreaUnit.SquareYard);
    }

    // decimal receiver (convert as needed)
    extension(decimal value)
    {
        public Area Acre => new Area((double)value, AreaUnit.Acre);
        public Area Hectare => new Area((double)value, AreaUnit.Hectare);
        public Area SquareCentimeter => new Area((double)value, AreaUnit.SquareCentimeter);
        public Area SquareChain => new Area((double)value, AreaUnit.SquareChain);
        public Area SquareDecimeter => new Area((double)value, AreaUnit.SquareDecimeter);
        public Area SquareFoot => new Area((double)value, AreaUnit.SquareFoot);
        public Area SquareInch => new Area((double)value, AreaUnit.SquareInch);
        public Area SquareKilometer => new Area((double)value, AreaUnit.SquareKilometer);
        public Area SquareMeter => new Area((double)value, AreaUnit.SquareMeter);
        public Area SquareMicrometer => new Area((double)value, AreaUnit.SquareMicrometer);
        public Area SquareMile => new Area((double)value, AreaUnit.SquareMile);
        public Area SquareMillimeter => new Area((double)value, AreaUnit.SquareMillimeter);
        public Area SquareNanometer => new Area((double)value, AreaUnit.SquareNanometer);
        public Area SquareNauticalMile => new Area((double)value, AreaUnit.SquareNauticalMile);
        public Area SquareYard => new Area((double)value, AreaUnit.SquareYard);
    }
}