using EngineeringUnits;
using EngineeringUnits.Units;

namespace EngineeringUnits.NumberExtensions.NumberToForceChangeRate;

// <auto-generated/>
// This file is auto-generated; changes will be overwritten.
public static class NumberToForceChangeRateExtensions
{
    // double receiver
    extension(double value)
    {
        public ForceChangeRate CentinewtonPerSecond => new ForceChangeRate(value, ForceChangeRateUnit.CentinewtonPerSecond);
        public ForceChangeRate DecanewtonPerMinute => new ForceChangeRate(value, ForceChangeRateUnit.DecanewtonPerMinute);
        public ForceChangeRate DecanewtonPerSecond => new ForceChangeRate(value, ForceChangeRateUnit.DecanewtonPerSecond);
        public ForceChangeRate DecinewtonPerSecond => new ForceChangeRate(value, ForceChangeRateUnit.DecinewtonPerSecond);
        public ForceChangeRate KilonewtonPerMinute => new ForceChangeRate(value, ForceChangeRateUnit.KilonewtonPerMinute);
        public ForceChangeRate KilonewtonPerSecond => new ForceChangeRate(value, ForceChangeRateUnit.KilonewtonPerSecond);
        public ForceChangeRate KilopoundForcePerMinute => new ForceChangeRate(value, ForceChangeRateUnit.KilopoundForcePerMinute);
        public ForceChangeRate KilopoundForcePerSecond => new ForceChangeRate(value, ForceChangeRateUnit.KilopoundForcePerSecond);
        public ForceChangeRate MicronewtonPerSecond => new ForceChangeRate(value, ForceChangeRateUnit.MicronewtonPerSecond);
        public ForceChangeRate MillinewtonPerSecond => new ForceChangeRate(value, ForceChangeRateUnit.MillinewtonPerSecond);
        public ForceChangeRate NanonewtonPerSecond => new ForceChangeRate(value, ForceChangeRateUnit.NanonewtonPerSecond);
        public ForceChangeRate NewtonPerMinute => new ForceChangeRate(value, ForceChangeRateUnit.NewtonPerMinute);
        public ForceChangeRate NewtonPerSecond => new ForceChangeRate(value, ForceChangeRateUnit.NewtonPerSecond);
        public ForceChangeRate PoundForcePerMinute => new ForceChangeRate(value, ForceChangeRateUnit.PoundForcePerMinute);
        public ForceChangeRate PoundForcePerSecond => new ForceChangeRate(value, ForceChangeRateUnit.PoundForcePerSecond);
    }

    // int receiver
    extension(int value)
    {
        public ForceChangeRate CentinewtonPerSecond => new ForceChangeRate(value, ForceChangeRateUnit.CentinewtonPerSecond);
        public ForceChangeRate DecanewtonPerMinute => new ForceChangeRate(value, ForceChangeRateUnit.DecanewtonPerMinute);
        public ForceChangeRate DecanewtonPerSecond => new ForceChangeRate(value, ForceChangeRateUnit.DecanewtonPerSecond);
        public ForceChangeRate DecinewtonPerSecond => new ForceChangeRate(value, ForceChangeRateUnit.DecinewtonPerSecond);
        public ForceChangeRate KilonewtonPerMinute => new ForceChangeRate(value, ForceChangeRateUnit.KilonewtonPerMinute);
        public ForceChangeRate KilonewtonPerSecond => new ForceChangeRate(value, ForceChangeRateUnit.KilonewtonPerSecond);
        public ForceChangeRate KilopoundForcePerMinute => new ForceChangeRate(value, ForceChangeRateUnit.KilopoundForcePerMinute);
        public ForceChangeRate KilopoundForcePerSecond => new ForceChangeRate(value, ForceChangeRateUnit.KilopoundForcePerSecond);
        public ForceChangeRate MicronewtonPerSecond => new ForceChangeRate(value, ForceChangeRateUnit.MicronewtonPerSecond);
        public ForceChangeRate MillinewtonPerSecond => new ForceChangeRate(value, ForceChangeRateUnit.MillinewtonPerSecond);
        public ForceChangeRate NanonewtonPerSecond => new ForceChangeRate(value, ForceChangeRateUnit.NanonewtonPerSecond);
        public ForceChangeRate NewtonPerMinute => new ForceChangeRate(value, ForceChangeRateUnit.NewtonPerMinute);
        public ForceChangeRate NewtonPerSecond => new ForceChangeRate(value, ForceChangeRateUnit.NewtonPerSecond);
        public ForceChangeRate PoundForcePerMinute => new ForceChangeRate(value, ForceChangeRateUnit.PoundForcePerMinute);
        public ForceChangeRate PoundForcePerSecond => new ForceChangeRate(value, ForceChangeRateUnit.PoundForcePerSecond);
    }

    // decimal receiver (convert as needed)
    extension(decimal value)
    {
        public ForceChangeRate CentinewtonPerSecond => new ForceChangeRate((double)value, ForceChangeRateUnit.CentinewtonPerSecond);
        public ForceChangeRate DecanewtonPerMinute => new ForceChangeRate((double)value, ForceChangeRateUnit.DecanewtonPerMinute);
        public ForceChangeRate DecanewtonPerSecond => new ForceChangeRate((double)value, ForceChangeRateUnit.DecanewtonPerSecond);
        public ForceChangeRate DecinewtonPerSecond => new ForceChangeRate((double)value, ForceChangeRateUnit.DecinewtonPerSecond);
        public ForceChangeRate KilonewtonPerMinute => new ForceChangeRate((double)value, ForceChangeRateUnit.KilonewtonPerMinute);
        public ForceChangeRate KilonewtonPerSecond => new ForceChangeRate((double)value, ForceChangeRateUnit.KilonewtonPerSecond);
        public ForceChangeRate KilopoundForcePerMinute => new ForceChangeRate((double)value, ForceChangeRateUnit.KilopoundForcePerMinute);
        public ForceChangeRate KilopoundForcePerSecond => new ForceChangeRate((double)value, ForceChangeRateUnit.KilopoundForcePerSecond);
        public ForceChangeRate MicronewtonPerSecond => new ForceChangeRate((double)value, ForceChangeRateUnit.MicronewtonPerSecond);
        public ForceChangeRate MillinewtonPerSecond => new ForceChangeRate((double)value, ForceChangeRateUnit.MillinewtonPerSecond);
        public ForceChangeRate NanonewtonPerSecond => new ForceChangeRate((double)value, ForceChangeRateUnit.NanonewtonPerSecond);
        public ForceChangeRate NewtonPerMinute => new ForceChangeRate((double)value, ForceChangeRateUnit.NewtonPerMinute);
        public ForceChangeRate NewtonPerSecond => new ForceChangeRate((double)value, ForceChangeRateUnit.NewtonPerSecond);
        public ForceChangeRate PoundForcePerMinute => new ForceChangeRate((double)value, ForceChangeRateUnit.PoundForcePerMinute);
        public ForceChangeRate PoundForcePerSecond => new ForceChangeRate((double)value, ForceChangeRateUnit.PoundForcePerSecond);
    }
}