using EngineeringUnits;
using EngineeringUnits.Units;

namespace EngineeringUnits.NumberExtensions.NumberToPowerCost;

// <auto-generated/>
// This file is auto-generated; changes will be overwritten.
public static class NumberToPowerCostExtensions
{
    // double receiver
    extension(double value)
    {
        public PowerCost USDollarPerKilowatt => new PowerCost(value, PowerCostUnit.USDollarPerKilowatt);
        public PowerCost USDollarPerWatt => new PowerCost(value, PowerCostUnit.USDollarPerWatt);
    }

    // int receiver
    extension(int value)
    {
        public PowerCost USDollarPerKilowatt => new PowerCost(value, PowerCostUnit.USDollarPerKilowatt);
        public PowerCost USDollarPerWatt => new PowerCost(value, PowerCostUnit.USDollarPerWatt);
    }

    // decimal receiver (convert as needed)
    extension(decimal value)
    {
        public PowerCost USDollarPerKilowatt => new PowerCost((double)value, PowerCostUnit.USDollarPerKilowatt);
        public PowerCost USDollarPerWatt => new PowerCost((double)value, PowerCostUnit.USDollarPerWatt);
    }
}