using EngineeringUnits;
using EngineeringUnits.Units;

namespace EngineeringUnits.NumberExtensions.NumberToAreaDensity;

// <auto-generated/>
// This file is auto-generated; changes will be overwritten.
public static class NumberToAreaDensityExtensions
{
    // double receiver
    extension(double value)
    {
        public AreaDensity KilogramPerSquareMeter => new AreaDensity(value, AreaDensityUnit.KilogramPerSquareMeter);
    }

    // int receiver
    extension(int value)
    {
        public AreaDensity KilogramPerSquareMeter => new AreaDensity(value, AreaDensityUnit.KilogramPerSquareMeter);
    }

    // decimal receiver (convert as needed)
    extension(decimal value)
    {
        public AreaDensity KilogramPerSquareMeter => new AreaDensity((double)value, AreaDensityUnit.KilogramPerSquareMeter);
    }
}