using EngineeringUnits;
using EngineeringUnits.Units;

namespace EngineeringUnits.NumberExtensions.NumberToSpecificHeatCapacity;

// <auto-generated/>
// This file is auto-generated; changes will be overwritten.
public static class NumberToSpecificHeatCapacityExtensions
{
    // double receiver
    extension(double value)
    {
        public SpecificHeatCapacity BtuPerPoundFahrenheit => new SpecificHeatCapacity(value, SpecificHeatCapacityUnit.BtuPerPoundFahrenheit);
        public SpecificHeatCapacity BtuPerPoundKelvin => new SpecificHeatCapacity(value, SpecificHeatCapacityUnit.BtuPerPoundKelvin);
        public SpecificHeatCapacity BtuPerPoundRankine => new SpecificHeatCapacity(value, SpecificHeatCapacityUnit.BtuPerPoundRankine);
        public SpecificHeatCapacity CaloriePerGramKelvin => new SpecificHeatCapacity(value, SpecificHeatCapacityUnit.CaloriePerGramKelvin);
        public SpecificHeatCapacity JoulePerKilogramDegreeCelsius => new SpecificHeatCapacity(value, SpecificHeatCapacityUnit.JoulePerKilogramDegreeCelsius);
        public SpecificHeatCapacity JoulePerKilogramKelvin => new SpecificHeatCapacity(value, SpecificHeatCapacityUnit.JoulePerKilogramKelvin);
        public SpecificHeatCapacity JoulePerKilogramRankine => new SpecificHeatCapacity(value, SpecificHeatCapacityUnit.JoulePerKilogramRankine);
        public SpecificHeatCapacity KilocaloriePerGramKelvin => new SpecificHeatCapacity(value, SpecificHeatCapacityUnit.KilocaloriePerGramKelvin);
        public SpecificHeatCapacity KilojoulePerKilogramDegreeCelsius => new SpecificHeatCapacity(value, SpecificHeatCapacityUnit.KilojoulePerKilogramDegreeCelsius);
        public SpecificHeatCapacity KilojoulePerKilogramKelvin => new SpecificHeatCapacity(value, SpecificHeatCapacityUnit.KilojoulePerKilogramKelvin);
        public SpecificHeatCapacity MegajoulePerKilogramDegreeCelsius => new SpecificHeatCapacity(value, SpecificHeatCapacityUnit.MegajoulePerKilogramDegreeCelsius);
        public SpecificHeatCapacity MegajoulePerKilogramKelvin => new SpecificHeatCapacity(value, SpecificHeatCapacityUnit.MegajoulePerKilogramKelvin);
    }

    // int receiver
    extension(int value)
    {
        public SpecificHeatCapacity BtuPerPoundFahrenheit => new SpecificHeatCapacity(value, SpecificHeatCapacityUnit.BtuPerPoundFahrenheit);
        public SpecificHeatCapacity BtuPerPoundKelvin => new SpecificHeatCapacity(value, SpecificHeatCapacityUnit.BtuPerPoundKelvin);
        public SpecificHeatCapacity BtuPerPoundRankine => new SpecificHeatCapacity(value, SpecificHeatCapacityUnit.BtuPerPoundRankine);
        public SpecificHeatCapacity CaloriePerGramKelvin => new SpecificHeatCapacity(value, SpecificHeatCapacityUnit.CaloriePerGramKelvin);
        public SpecificHeatCapacity JoulePerKilogramDegreeCelsius => new SpecificHeatCapacity(value, SpecificHeatCapacityUnit.JoulePerKilogramDegreeCelsius);
        public SpecificHeatCapacity JoulePerKilogramKelvin => new SpecificHeatCapacity(value, SpecificHeatCapacityUnit.JoulePerKilogramKelvin);
        public SpecificHeatCapacity JoulePerKilogramRankine => new SpecificHeatCapacity(value, SpecificHeatCapacityUnit.JoulePerKilogramRankine);
        public SpecificHeatCapacity KilocaloriePerGramKelvin => new SpecificHeatCapacity(value, SpecificHeatCapacityUnit.KilocaloriePerGramKelvin);
        public SpecificHeatCapacity KilojoulePerKilogramDegreeCelsius => new SpecificHeatCapacity(value, SpecificHeatCapacityUnit.KilojoulePerKilogramDegreeCelsius);
        public SpecificHeatCapacity KilojoulePerKilogramKelvin => new SpecificHeatCapacity(value, SpecificHeatCapacityUnit.KilojoulePerKilogramKelvin);
        public SpecificHeatCapacity MegajoulePerKilogramDegreeCelsius => new SpecificHeatCapacity(value, SpecificHeatCapacityUnit.MegajoulePerKilogramDegreeCelsius);
        public SpecificHeatCapacity MegajoulePerKilogramKelvin => new SpecificHeatCapacity(value, SpecificHeatCapacityUnit.MegajoulePerKilogramKelvin);
    }

    // decimal receiver (convert as needed)
    extension(decimal value)
    {
        public SpecificHeatCapacity BtuPerPoundFahrenheit => new SpecificHeatCapacity((double)value, SpecificHeatCapacityUnit.BtuPerPoundFahrenheit);
        public SpecificHeatCapacity BtuPerPoundKelvin => new SpecificHeatCapacity((double)value, SpecificHeatCapacityUnit.BtuPerPoundKelvin);
        public SpecificHeatCapacity BtuPerPoundRankine => new SpecificHeatCapacity((double)value, SpecificHeatCapacityUnit.BtuPerPoundRankine);
        public SpecificHeatCapacity CaloriePerGramKelvin => new SpecificHeatCapacity((double)value, SpecificHeatCapacityUnit.CaloriePerGramKelvin);
        public SpecificHeatCapacity JoulePerKilogramDegreeCelsius => new SpecificHeatCapacity((double)value, SpecificHeatCapacityUnit.JoulePerKilogramDegreeCelsius);
        public SpecificHeatCapacity JoulePerKilogramKelvin => new SpecificHeatCapacity((double)value, SpecificHeatCapacityUnit.JoulePerKilogramKelvin);
        public SpecificHeatCapacity JoulePerKilogramRankine => new SpecificHeatCapacity((double)value, SpecificHeatCapacityUnit.JoulePerKilogramRankine);
        public SpecificHeatCapacity KilocaloriePerGramKelvin => new SpecificHeatCapacity((double)value, SpecificHeatCapacityUnit.KilocaloriePerGramKelvin);
        public SpecificHeatCapacity KilojoulePerKilogramDegreeCelsius => new SpecificHeatCapacity((double)value, SpecificHeatCapacityUnit.KilojoulePerKilogramDegreeCelsius);
        public SpecificHeatCapacity KilojoulePerKilogramKelvin => new SpecificHeatCapacity((double)value, SpecificHeatCapacityUnit.KilojoulePerKilogramKelvin);
        public SpecificHeatCapacity MegajoulePerKilogramDegreeCelsius => new SpecificHeatCapacity((double)value, SpecificHeatCapacityUnit.MegajoulePerKilogramDegreeCelsius);
        public SpecificHeatCapacity MegajoulePerKilogramKelvin => new SpecificHeatCapacity((double)value, SpecificHeatCapacityUnit.MegajoulePerKilogramKelvin);
    }
}