using EngineeringUnits;
using EngineeringUnits.Units;

namespace EngineeringUnits.NumberExtensions.NumberToMolarEnergy;

// <auto-generated/>
// This file is auto-generated; changes will be overwritten.
public static class NumberToMolarEnergyExtensions
{
    // double receiver
    extension(double value)
    {
        public MolarEnergy JoulePerMole => new MolarEnergy(value, MolarEnergyUnit.JoulePerMole);
        public MolarEnergy KilojoulePerMole => new MolarEnergy(value, MolarEnergyUnit.KilojoulePerMole);
        public MolarEnergy MegajoulePerMole => new MolarEnergy(value, MolarEnergyUnit.MegajoulePerMole);
    }

    // int receiver
    extension(int value)
    {
        public MolarEnergy JoulePerMole => new MolarEnergy(value, MolarEnergyUnit.JoulePerMole);
        public MolarEnergy KilojoulePerMole => new MolarEnergy(value, MolarEnergyUnit.KilojoulePerMole);
        public MolarEnergy MegajoulePerMole => new MolarEnergy(value, MolarEnergyUnit.MegajoulePerMole);
    }

    // decimal receiver (convert as needed)
    extension(decimal value)
    {
        public MolarEnergy JoulePerMole => new MolarEnergy((double)value, MolarEnergyUnit.JoulePerMole);
        public MolarEnergy KilojoulePerMole => new MolarEnergy((double)value, MolarEnergyUnit.KilojoulePerMole);
        public MolarEnergy MegajoulePerMole => new MolarEnergy((double)value, MolarEnergyUnit.MegajoulePerMole);
    }
}