using EngineeringUnits;
using EngineeringUnits.Units;

namespace EngineeringUnits.NumberExtensions.NumberToFuelEfficiency;

// <auto-generated/>
// This file is auto-generated; changes will be overwritten.
public static class NumberToFuelEfficiencyExtensions
{
    // double receiver
    extension(double value)
    {
        public FuelEfficiency KilometerPerLiter => new FuelEfficiency(value, FuelEfficiencyUnit.KilometerPerLiter);
        public FuelEfficiency MilePerUkGallon => new FuelEfficiency(value, FuelEfficiencyUnit.MilePerUkGallon);
        public FuelEfficiency MilePerUsGallon => new FuelEfficiency(value, FuelEfficiencyUnit.MilePerUsGallon);
    }

    // int receiver
    extension(int value)
    {
        public FuelEfficiency KilometerPerLiter => new FuelEfficiency(value, FuelEfficiencyUnit.KilometerPerLiter);
        public FuelEfficiency MilePerUkGallon => new FuelEfficiency(value, FuelEfficiencyUnit.MilePerUkGallon);
        public FuelEfficiency MilePerUsGallon => new FuelEfficiency(value, FuelEfficiencyUnit.MilePerUsGallon);
    }

    // decimal receiver (convert as needed)
    extension(decimal value)
    {
        public FuelEfficiency KilometerPerLiter => new FuelEfficiency((double)value, FuelEfficiencyUnit.KilometerPerLiter);
        public FuelEfficiency MilePerUkGallon => new FuelEfficiency((double)value, FuelEfficiencyUnit.MilePerUkGallon);
        public FuelEfficiency MilePerUsGallon => new FuelEfficiency((double)value, FuelEfficiencyUnit.MilePerUsGallon);
    }
}