using EngineeringUnits;
using EngineeringUnits.Units;

namespace EngineeringUnits.NumberExtensions.NumberToSpecificEntropy;

// <auto-generated/>
// This file is auto-generated; changes will be overwritten.
public static class NumberToSpecificEntropyExtensions
{
    // double receiver
    extension(double value)
    {
        public SpecificEntropy BtuPerPoundFahrenheit => new SpecificEntropy(value, SpecificEntropyUnit.BtuPerPoundFahrenheit);
        public SpecificEntropy BtuPerPoundKelvin => new SpecificEntropy(value, SpecificEntropyUnit.BtuPerPoundKelvin);
        public SpecificEntropy BtuPerPoundRankine => new SpecificEntropy(value, SpecificEntropyUnit.BtuPerPoundRankine);
        public SpecificEntropy CaloriePerGramKelvin => new SpecificEntropy(value, SpecificEntropyUnit.CaloriePerGramKelvin);
        public SpecificEntropy JoulePerKilogramDegreeCelsius => new SpecificEntropy(value, SpecificEntropyUnit.JoulePerKilogramDegreeCelsius);
        public SpecificEntropy JoulePerKilogramKelvin => new SpecificEntropy(value, SpecificEntropyUnit.JoulePerKilogramKelvin);
        public SpecificEntropy JoulePerKilogramRankine => new SpecificEntropy(value, SpecificEntropyUnit.JoulePerKilogramRankine);
        public SpecificEntropy KilocaloriePerGramKelvin => new SpecificEntropy(value, SpecificEntropyUnit.KilocaloriePerGramKelvin);
        public SpecificEntropy KilojoulePerKilogramDegreeCelsius => new SpecificEntropy(value, SpecificEntropyUnit.KilojoulePerKilogramDegreeCelsius);
        public SpecificEntropy KilojoulePerKilogramKelvin => new SpecificEntropy(value, SpecificEntropyUnit.KilojoulePerKilogramKelvin);
        public SpecificEntropy MegajoulePerKilogramDegreeCelsius => new SpecificEntropy(value, SpecificEntropyUnit.MegajoulePerKilogramDegreeCelsius);
        public SpecificEntropy MegajoulePerKilogramKelvin => new SpecificEntropy(value, SpecificEntropyUnit.MegajoulePerKilogramKelvin);
    }

    // int receiver
    extension(int value)
    {
        public SpecificEntropy BtuPerPoundFahrenheit => new SpecificEntropy(value, SpecificEntropyUnit.BtuPerPoundFahrenheit);
        public SpecificEntropy BtuPerPoundKelvin => new SpecificEntropy(value, SpecificEntropyUnit.BtuPerPoundKelvin);
        public SpecificEntropy BtuPerPoundRankine => new SpecificEntropy(value, SpecificEntropyUnit.BtuPerPoundRankine);
        public SpecificEntropy CaloriePerGramKelvin => new SpecificEntropy(value, SpecificEntropyUnit.CaloriePerGramKelvin);
        public SpecificEntropy JoulePerKilogramDegreeCelsius => new SpecificEntropy(value, SpecificEntropyUnit.JoulePerKilogramDegreeCelsius);
        public SpecificEntropy JoulePerKilogramKelvin => new SpecificEntropy(value, SpecificEntropyUnit.JoulePerKilogramKelvin);
        public SpecificEntropy JoulePerKilogramRankine => new SpecificEntropy(value, SpecificEntropyUnit.JoulePerKilogramRankine);
        public SpecificEntropy KilocaloriePerGramKelvin => new SpecificEntropy(value, SpecificEntropyUnit.KilocaloriePerGramKelvin);
        public SpecificEntropy KilojoulePerKilogramDegreeCelsius => new SpecificEntropy(value, SpecificEntropyUnit.KilojoulePerKilogramDegreeCelsius);
        public SpecificEntropy KilojoulePerKilogramKelvin => new SpecificEntropy(value, SpecificEntropyUnit.KilojoulePerKilogramKelvin);
        public SpecificEntropy MegajoulePerKilogramDegreeCelsius => new SpecificEntropy(value, SpecificEntropyUnit.MegajoulePerKilogramDegreeCelsius);
        public SpecificEntropy MegajoulePerKilogramKelvin => new SpecificEntropy(value, SpecificEntropyUnit.MegajoulePerKilogramKelvin);
    }

    // decimal receiver (convert as needed)
    extension(decimal value)
    {
        public SpecificEntropy BtuPerPoundFahrenheit => new SpecificEntropy((double)value, SpecificEntropyUnit.BtuPerPoundFahrenheit);
        public SpecificEntropy BtuPerPoundKelvin => new SpecificEntropy((double)value, SpecificEntropyUnit.BtuPerPoundKelvin);
        public SpecificEntropy BtuPerPoundRankine => new SpecificEntropy((double)value, SpecificEntropyUnit.BtuPerPoundRankine);
        public SpecificEntropy CaloriePerGramKelvin => new SpecificEntropy((double)value, SpecificEntropyUnit.CaloriePerGramKelvin);
        public SpecificEntropy JoulePerKilogramDegreeCelsius => new SpecificEntropy((double)value, SpecificEntropyUnit.JoulePerKilogramDegreeCelsius);
        public SpecificEntropy JoulePerKilogramKelvin => new SpecificEntropy((double)value, SpecificEntropyUnit.JoulePerKilogramKelvin);
        public SpecificEntropy JoulePerKilogramRankine => new SpecificEntropy((double)value, SpecificEntropyUnit.JoulePerKilogramRankine);
        public SpecificEntropy KilocaloriePerGramKelvin => new SpecificEntropy((double)value, SpecificEntropyUnit.KilocaloriePerGramKelvin);
        public SpecificEntropy KilojoulePerKilogramDegreeCelsius => new SpecificEntropy((double)value, SpecificEntropyUnit.KilojoulePerKilogramDegreeCelsius);
        public SpecificEntropy KilojoulePerKilogramKelvin => new SpecificEntropy((double)value, SpecificEntropyUnit.KilojoulePerKilogramKelvin);
        public SpecificEntropy MegajoulePerKilogramDegreeCelsius => new SpecificEntropy((double)value, SpecificEntropyUnit.MegajoulePerKilogramDegreeCelsius);
        public SpecificEntropy MegajoulePerKilogramKelvin => new SpecificEntropy((double)value, SpecificEntropyUnit.MegajoulePerKilogramKelvin);
    }
}