using EngineeringUnits;
using EngineeringUnits.Units;

namespace EngineeringUnits.NumberExtensions.NumberToMagneticField;

// <auto-generated/>
// This file is auto-generated; changes will be overwritten.
public static class NumberToMagneticFieldExtensions
{
    // double receiver
    extension(double value)
    {
        public MagneticField Gauss => new MagneticField(value, MagneticFieldUnit.Gauss);
        public MagneticField Microtesla => new MagneticField(value, MagneticFieldUnit.Microtesla);
        public MagneticField Milligauss => new MagneticField(value, MagneticFieldUnit.Milligauss);
        public MagneticField Millitesla => new MagneticField(value, MagneticFieldUnit.Millitesla);
        public MagneticField Nanotesla => new MagneticField(value, MagneticFieldUnit.Nanotesla);
        public MagneticField Tesla => new MagneticField(value, MagneticFieldUnit.Tesla);
    }

    // int receiver
    extension(int value)
    {
        public MagneticField Gauss => new MagneticField(value, MagneticFieldUnit.Gauss);
        public MagneticField Microtesla => new MagneticField(value, MagneticFieldUnit.Microtesla);
        public MagneticField Milligauss => new MagneticField(value, MagneticFieldUnit.Milligauss);
        public MagneticField Millitesla => new MagneticField(value, MagneticFieldUnit.Millitesla);
        public MagneticField Nanotesla => new MagneticField(value, MagneticFieldUnit.Nanotesla);
        public MagneticField Tesla => new MagneticField(value, MagneticFieldUnit.Tesla);
    }

    // decimal receiver (convert as needed)
    extension(decimal value)
    {
        public MagneticField Gauss => new MagneticField((double)value, MagneticFieldUnit.Gauss);
        public MagneticField Microtesla => new MagneticField((double)value, MagneticFieldUnit.Microtesla);
        public MagneticField Milligauss => new MagneticField((double)value, MagneticFieldUnit.Milligauss);
        public MagneticField Millitesla => new MagneticField((double)value, MagneticFieldUnit.Millitesla);
        public MagneticField Nanotesla => new MagneticField((double)value, MagneticFieldUnit.Nanotesla);
        public MagneticField Tesla => new MagneticField((double)value, MagneticFieldUnit.Tesla);
    }
}