using EngineeringUnits;
using EngineeringUnits.Units;

namespace EngineeringUnits.NumberExtensions.NumberToTorquePerLength;

// <auto-generated/>
// This file is auto-generated; changes will be overwritten.
public static class NumberToTorquePerLengthExtensions
{
    // double receiver
    extension(double value)
    {
        public TorquePerLength KilogramForceCentimeterPerMeter => new TorquePerLength(value, TorquePerLengthUnit.KilogramForceCentimeterPerMeter);
        public TorquePerLength KilogramForceMeterPerMeter => new TorquePerLength(value, TorquePerLengthUnit.KilogramForceMeterPerMeter);
        public TorquePerLength KilogramForceMillimeterPerMeter => new TorquePerLength(value, TorquePerLengthUnit.KilogramForceMillimeterPerMeter);
        public TorquePerLength KilonewtonCentimeterPerMeter => new TorquePerLength(value, TorquePerLengthUnit.KilonewtonCentimeterPerMeter);
        public TorquePerLength KilonewtonMeterPerMeter => new TorquePerLength(value, TorquePerLengthUnit.KilonewtonMeterPerMeter);
        public TorquePerLength KilonewtonMillimeterPerMeter => new TorquePerLength(value, TorquePerLengthUnit.KilonewtonMillimeterPerMeter);
        public TorquePerLength KilopoundForceFootPerFoot => new TorquePerLength(value, TorquePerLengthUnit.KilopoundForceFootPerFoot);
        public TorquePerLength KilopoundForceInchPerFoot => new TorquePerLength(value, TorquePerLengthUnit.KilopoundForceInchPerFoot);
        public TorquePerLength MeganewtonCentimeterPerMeter => new TorquePerLength(value, TorquePerLengthUnit.MeganewtonCentimeterPerMeter);
        public TorquePerLength MeganewtonMeterPerMeter => new TorquePerLength(value, TorquePerLengthUnit.MeganewtonMeterPerMeter);
        public TorquePerLength MeganewtonMillimeterPerMeter => new TorquePerLength(value, TorquePerLengthUnit.MeganewtonMillimeterPerMeter);
        public TorquePerLength MegapoundForceFootPerFoot => new TorquePerLength(value, TorquePerLengthUnit.MegapoundForceFootPerFoot);
        public TorquePerLength MegapoundForceInchPerFoot => new TorquePerLength(value, TorquePerLengthUnit.MegapoundForceInchPerFoot);
        public TorquePerLength NewtonCentimeterPerMeter => new TorquePerLength(value, TorquePerLengthUnit.NewtonCentimeterPerMeter);
        public TorquePerLength NewtonMeterPerMeter => new TorquePerLength(value, TorquePerLengthUnit.NewtonMeterPerMeter);
        public TorquePerLength NewtonMillimeterPerMeter => new TorquePerLength(value, TorquePerLengthUnit.NewtonMillimeterPerMeter);
        public TorquePerLength PoundForceFootPerFoot => new TorquePerLength(value, TorquePerLengthUnit.PoundForceFootPerFoot);
        public TorquePerLength PoundForceInchPerFoot => new TorquePerLength(value, TorquePerLengthUnit.PoundForceInchPerFoot);
        public TorquePerLength TonneForceCentimeterPerMeter => new TorquePerLength(value, TorquePerLengthUnit.TonneForceCentimeterPerMeter);
        public TorquePerLength TonneForceMeterPerMeter => new TorquePerLength(value, TorquePerLengthUnit.TonneForceMeterPerMeter);
        public TorquePerLength TonneForceMillimeterPerMeter => new TorquePerLength(value, TorquePerLengthUnit.TonneForceMillimeterPerMeter);
    }

    // int receiver
    extension(int value)
    {
        public TorquePerLength KilogramForceCentimeterPerMeter => new TorquePerLength(value, TorquePerLengthUnit.KilogramForceCentimeterPerMeter);
        public TorquePerLength KilogramForceMeterPerMeter => new TorquePerLength(value, TorquePerLengthUnit.KilogramForceMeterPerMeter);
        public TorquePerLength KilogramForceMillimeterPerMeter => new TorquePerLength(value, TorquePerLengthUnit.KilogramForceMillimeterPerMeter);
        public TorquePerLength KilonewtonCentimeterPerMeter => new TorquePerLength(value, TorquePerLengthUnit.KilonewtonCentimeterPerMeter);
        public TorquePerLength KilonewtonMeterPerMeter => new TorquePerLength(value, TorquePerLengthUnit.KilonewtonMeterPerMeter);
        public TorquePerLength KilonewtonMillimeterPerMeter => new TorquePerLength(value, TorquePerLengthUnit.KilonewtonMillimeterPerMeter);
        public TorquePerLength KilopoundForceFootPerFoot => new TorquePerLength(value, TorquePerLengthUnit.KilopoundForceFootPerFoot);
        public TorquePerLength KilopoundForceInchPerFoot => new TorquePerLength(value, TorquePerLengthUnit.KilopoundForceInchPerFoot);
        public TorquePerLength MeganewtonCentimeterPerMeter => new TorquePerLength(value, TorquePerLengthUnit.MeganewtonCentimeterPerMeter);
        public TorquePerLength MeganewtonMeterPerMeter => new TorquePerLength(value, TorquePerLengthUnit.MeganewtonMeterPerMeter);
        public TorquePerLength MeganewtonMillimeterPerMeter => new TorquePerLength(value, TorquePerLengthUnit.MeganewtonMillimeterPerMeter);
        public TorquePerLength MegapoundForceFootPerFoot => new TorquePerLength(value, TorquePerLengthUnit.MegapoundForceFootPerFoot);
        public TorquePerLength MegapoundForceInchPerFoot => new TorquePerLength(value, TorquePerLengthUnit.MegapoundForceInchPerFoot);
        public TorquePerLength NewtonCentimeterPerMeter => new TorquePerLength(value, TorquePerLengthUnit.NewtonCentimeterPerMeter);
        public TorquePerLength NewtonMeterPerMeter => new TorquePerLength(value, TorquePerLengthUnit.NewtonMeterPerMeter);
        public TorquePerLength NewtonMillimeterPerMeter => new TorquePerLength(value, TorquePerLengthUnit.NewtonMillimeterPerMeter);
        public TorquePerLength PoundForceFootPerFoot => new TorquePerLength(value, TorquePerLengthUnit.PoundForceFootPerFoot);
        public TorquePerLength PoundForceInchPerFoot => new TorquePerLength(value, TorquePerLengthUnit.PoundForceInchPerFoot);
        public TorquePerLength TonneForceCentimeterPerMeter => new TorquePerLength(value, TorquePerLengthUnit.TonneForceCentimeterPerMeter);
        public TorquePerLength TonneForceMeterPerMeter => new TorquePerLength(value, TorquePerLengthUnit.TonneForceMeterPerMeter);
        public TorquePerLength TonneForceMillimeterPerMeter => new TorquePerLength(value, TorquePerLengthUnit.TonneForceMillimeterPerMeter);
    }

    // decimal receiver (convert as needed)
    extension(decimal value)
    {
        public TorquePerLength KilogramForceCentimeterPerMeter => new TorquePerLength((double)value, TorquePerLengthUnit.KilogramForceCentimeterPerMeter);
        public TorquePerLength KilogramForceMeterPerMeter => new TorquePerLength((double)value, TorquePerLengthUnit.KilogramForceMeterPerMeter);
        public TorquePerLength KilogramForceMillimeterPerMeter => new TorquePerLength((double)value, TorquePerLengthUnit.KilogramForceMillimeterPerMeter);
        public TorquePerLength KilonewtonCentimeterPerMeter => new TorquePerLength((double)value, TorquePerLengthUnit.KilonewtonCentimeterPerMeter);
        public TorquePerLength KilonewtonMeterPerMeter => new TorquePerLength((double)value, TorquePerLengthUnit.KilonewtonMeterPerMeter);
        public TorquePerLength KilonewtonMillimeterPerMeter => new TorquePerLength((double)value, TorquePerLengthUnit.KilonewtonMillimeterPerMeter);
        public TorquePerLength KilopoundForceFootPerFoot => new TorquePerLength((double)value, TorquePerLengthUnit.KilopoundForceFootPerFoot);
        public TorquePerLength KilopoundForceInchPerFoot => new TorquePerLength((double)value, TorquePerLengthUnit.KilopoundForceInchPerFoot);
        public TorquePerLength MeganewtonCentimeterPerMeter => new TorquePerLength((double)value, TorquePerLengthUnit.MeganewtonCentimeterPerMeter);
        public TorquePerLength MeganewtonMeterPerMeter => new TorquePerLength((double)value, TorquePerLengthUnit.MeganewtonMeterPerMeter);
        public TorquePerLength MeganewtonMillimeterPerMeter => new TorquePerLength((double)value, TorquePerLengthUnit.MeganewtonMillimeterPerMeter);
        public TorquePerLength MegapoundForceFootPerFoot => new TorquePerLength((double)value, TorquePerLengthUnit.MegapoundForceFootPerFoot);
        public TorquePerLength MegapoundForceInchPerFoot => new TorquePerLength((double)value, TorquePerLengthUnit.MegapoundForceInchPerFoot);
        public TorquePerLength NewtonCentimeterPerMeter => new TorquePerLength((double)value, TorquePerLengthUnit.NewtonCentimeterPerMeter);
        public TorquePerLength NewtonMeterPerMeter => new TorquePerLength((double)value, TorquePerLengthUnit.NewtonMeterPerMeter);
        public TorquePerLength NewtonMillimeterPerMeter => new TorquePerLength((double)value, TorquePerLengthUnit.NewtonMillimeterPerMeter);
        public TorquePerLength PoundForceFootPerFoot => new TorquePerLength((double)value, TorquePerLengthUnit.PoundForceFootPerFoot);
        public TorquePerLength PoundForceInchPerFoot => new TorquePerLength((double)value, TorquePerLengthUnit.PoundForceInchPerFoot);
        public TorquePerLength TonneForceCentimeterPerMeter => new TorquePerLength((double)value, TorquePerLengthUnit.TonneForceCentimeterPerMeter);
        public TorquePerLength TonneForceMeterPerMeter => new TorquePerLength((double)value, TorquePerLengthUnit.TonneForceMeterPerMeter);
        public TorquePerLength TonneForceMillimeterPerMeter => new TorquePerLength((double)value, TorquePerLengthUnit.TonneForceMillimeterPerMeter);
    }
}