using EngineeringUnits;
using EngineeringUnits.Units;

namespace EngineeringUnits.NumberExtensions.NumberToRotationalSpeed;

// <auto-generated/>
// This file is auto-generated; changes will be overwritten.
public static class NumberToRotationalSpeedExtensions
{
    // double receiver
    extension(double value)
    {
        public RotationalSpeed BeatPerMinute => new RotationalSpeed(value, RotationalSpeedUnit.BeatPerMinute);
        public RotationalSpeed CyclePerHour => new RotationalSpeed(value, RotationalSpeedUnit.CyclePerHour);
        public RotationalSpeed CyclePerMinute => new RotationalSpeed(value, RotationalSpeedUnit.CyclePerMinute);
        public RotationalSpeed Gigahertz => new RotationalSpeed(value, RotationalSpeedUnit.Gigahertz);
        public RotationalSpeed Hertz => new RotationalSpeed(value, RotationalSpeedUnit.Hertz);
        public RotationalSpeed Kilohertz => new RotationalSpeed(value, RotationalSpeedUnit.Kilohertz);
        public RotationalSpeed Megahertz => new RotationalSpeed(value, RotationalSpeedUnit.Megahertz);
        public RotationalSpeed PerSecond => new RotationalSpeed(value, RotationalSpeedUnit.PerSecond);
        public RotationalSpeed RadianPerSecond => new RotationalSpeed(value, RotationalSpeedUnit.RadianPerSecond);
        public RotationalSpeed Terahertz => new RotationalSpeed(value, RotationalSpeedUnit.Terahertz);
    }

    // int receiver
    extension(int value)
    {
        public RotationalSpeed BeatPerMinute => new RotationalSpeed(value, RotationalSpeedUnit.BeatPerMinute);
        public RotationalSpeed CyclePerHour => new RotationalSpeed(value, RotationalSpeedUnit.CyclePerHour);
        public RotationalSpeed CyclePerMinute => new RotationalSpeed(value, RotationalSpeedUnit.CyclePerMinute);
        public RotationalSpeed Gigahertz => new RotationalSpeed(value, RotationalSpeedUnit.Gigahertz);
        public RotationalSpeed Hertz => new RotationalSpeed(value, RotationalSpeedUnit.Hertz);
        public RotationalSpeed Kilohertz => new RotationalSpeed(value, RotationalSpeedUnit.Kilohertz);
        public RotationalSpeed Megahertz => new RotationalSpeed(value, RotationalSpeedUnit.Megahertz);
        public RotationalSpeed PerSecond => new RotationalSpeed(value, RotationalSpeedUnit.PerSecond);
        public RotationalSpeed RadianPerSecond => new RotationalSpeed(value, RotationalSpeedUnit.RadianPerSecond);
        public RotationalSpeed Terahertz => new RotationalSpeed(value, RotationalSpeedUnit.Terahertz);
    }

    // decimal receiver (convert as needed)
    extension(decimal value)
    {
        public RotationalSpeed BeatPerMinute => new RotationalSpeed((double)value, RotationalSpeedUnit.BeatPerMinute);
        public RotationalSpeed CyclePerHour => new RotationalSpeed((double)value, RotationalSpeedUnit.CyclePerHour);
        public RotationalSpeed CyclePerMinute => new RotationalSpeed((double)value, RotationalSpeedUnit.CyclePerMinute);
        public RotationalSpeed Gigahertz => new RotationalSpeed((double)value, RotationalSpeedUnit.Gigahertz);
        public RotationalSpeed Hertz => new RotationalSpeed((double)value, RotationalSpeedUnit.Hertz);
        public RotationalSpeed Kilohertz => new RotationalSpeed((double)value, RotationalSpeedUnit.Kilohertz);
        public RotationalSpeed Megahertz => new RotationalSpeed((double)value, RotationalSpeedUnit.Megahertz);
        public RotationalSpeed PerSecond => new RotationalSpeed((double)value, RotationalSpeedUnit.PerSecond);
        public RotationalSpeed RadianPerSecond => new RotationalSpeed((double)value, RotationalSpeedUnit.RadianPerSecond);
        public RotationalSpeed Terahertz => new RotationalSpeed((double)value, RotationalSpeedUnit.Terahertz);
    }
}