using EngineeringUnits;
using EngineeringUnits.Units;

namespace EngineeringUnits.NumberExtensions.NumberToIrradiance;

// <auto-generated/>
// This file is auto-generated; changes will be overwritten.
public static class NumberToIrradianceExtensions
{
    // double receiver
    extension(double value)
    {
        public Irradiance KilowattPerSquareCentimeter => new Irradiance(value, IrradianceUnit.KilowattPerSquareCentimeter);
        public Irradiance KilowattPerSquareMeter => new Irradiance(value, IrradianceUnit.KilowattPerSquareMeter);
        public Irradiance MegawattPerSquareCentimeter => new Irradiance(value, IrradianceUnit.MegawattPerSquareCentimeter);
        public Irradiance MegawattPerSquareMeter => new Irradiance(value, IrradianceUnit.MegawattPerSquareMeter);
        public Irradiance MicrowattPerSquareCentimeter => new Irradiance(value, IrradianceUnit.MicrowattPerSquareCentimeter);
        public Irradiance MicrowattPerSquareMeter => new Irradiance(value, IrradianceUnit.MicrowattPerSquareMeter);
        public Irradiance MilliwattPerSquareCentimeter => new Irradiance(value, IrradianceUnit.MilliwattPerSquareCentimeter);
        public Irradiance MilliwattPerSquareMeter => new Irradiance(value, IrradianceUnit.MilliwattPerSquareMeter);
        public Irradiance NanowattPerSquareCentimeter => new Irradiance(value, IrradianceUnit.NanowattPerSquareCentimeter);
        public Irradiance NanowattPerSquareMeter => new Irradiance(value, IrradianceUnit.NanowattPerSquareMeter);
        public Irradiance PicowattPerSquareCentimeter => new Irradiance(value, IrradianceUnit.PicowattPerSquareCentimeter);
        public Irradiance PicowattPerSquareMeter => new Irradiance(value, IrradianceUnit.PicowattPerSquareMeter);
        public Irradiance WattPerSquareCentimeter => new Irradiance(value, IrradianceUnit.WattPerSquareCentimeter);
        public Irradiance WattPerSquareMeter => new Irradiance(value, IrradianceUnit.WattPerSquareMeter);
    }

    // int receiver
    extension(int value)
    {
        public Irradiance KilowattPerSquareCentimeter => new Irradiance(value, IrradianceUnit.KilowattPerSquareCentimeter);
        public Irradiance KilowattPerSquareMeter => new Irradiance(value, IrradianceUnit.KilowattPerSquareMeter);
        public Irradiance MegawattPerSquareCentimeter => new Irradiance(value, IrradianceUnit.MegawattPerSquareCentimeter);
        public Irradiance MegawattPerSquareMeter => new Irradiance(value, IrradianceUnit.MegawattPerSquareMeter);
        public Irradiance MicrowattPerSquareCentimeter => new Irradiance(value, IrradianceUnit.MicrowattPerSquareCentimeter);
        public Irradiance MicrowattPerSquareMeter => new Irradiance(value, IrradianceUnit.MicrowattPerSquareMeter);
        public Irradiance MilliwattPerSquareCentimeter => new Irradiance(value, IrradianceUnit.MilliwattPerSquareCentimeter);
        public Irradiance MilliwattPerSquareMeter => new Irradiance(value, IrradianceUnit.MilliwattPerSquareMeter);
        public Irradiance NanowattPerSquareCentimeter => new Irradiance(value, IrradianceUnit.NanowattPerSquareCentimeter);
        public Irradiance NanowattPerSquareMeter => new Irradiance(value, IrradianceUnit.NanowattPerSquareMeter);
        public Irradiance PicowattPerSquareCentimeter => new Irradiance(value, IrradianceUnit.PicowattPerSquareCentimeter);
        public Irradiance PicowattPerSquareMeter => new Irradiance(value, IrradianceUnit.PicowattPerSquareMeter);
        public Irradiance WattPerSquareCentimeter => new Irradiance(value, IrradianceUnit.WattPerSquareCentimeter);
        public Irradiance WattPerSquareMeter => new Irradiance(value, IrradianceUnit.WattPerSquareMeter);
    }

    // decimal receiver (convert as needed)
    extension(decimal value)
    {
        public Irradiance KilowattPerSquareCentimeter => new Irradiance((double)value, IrradianceUnit.KilowattPerSquareCentimeter);
        public Irradiance KilowattPerSquareMeter => new Irradiance((double)value, IrradianceUnit.KilowattPerSquareMeter);
        public Irradiance MegawattPerSquareCentimeter => new Irradiance((double)value, IrradianceUnit.MegawattPerSquareCentimeter);
        public Irradiance MegawattPerSquareMeter => new Irradiance((double)value, IrradianceUnit.MegawattPerSquareMeter);
        public Irradiance MicrowattPerSquareCentimeter => new Irradiance((double)value, IrradianceUnit.MicrowattPerSquareCentimeter);
        public Irradiance MicrowattPerSquareMeter => new Irradiance((double)value, IrradianceUnit.MicrowattPerSquareMeter);
        public Irradiance MilliwattPerSquareCentimeter => new Irradiance((double)value, IrradianceUnit.MilliwattPerSquareCentimeter);
        public Irradiance MilliwattPerSquareMeter => new Irradiance((double)value, IrradianceUnit.MilliwattPerSquareMeter);
        public Irradiance NanowattPerSquareCentimeter => new Irradiance((double)value, IrradianceUnit.NanowattPerSquareCentimeter);
        public Irradiance NanowattPerSquareMeter => new Irradiance((double)value, IrradianceUnit.NanowattPerSquareMeter);
        public Irradiance PicowattPerSquareCentimeter => new Irradiance((double)value, IrradianceUnit.PicowattPerSquareCentimeter);
        public Irradiance PicowattPerSquareMeter => new Irradiance((double)value, IrradianceUnit.PicowattPerSquareMeter);
        public Irradiance WattPerSquareCentimeter => new Irradiance((double)value, IrradianceUnit.WattPerSquareCentimeter);
        public Irradiance WattPerSquareMeter => new Irradiance((double)value, IrradianceUnit.WattPerSquareMeter);
    }
}