using EngineeringUnits;
using EngineeringUnits.Units;

namespace EngineeringUnits.NumberExtensions.NumberToForcePerLength;

// <auto-generated/>
// This file is auto-generated; changes will be overwritten.
public static class NumberToForcePerLengthExtensions
{
    // double receiver
    extension(double value)
    {
        public ForcePerLength CentinewtonPerCentimeter => new ForcePerLength(value, ForcePerLengthUnit.CentinewtonPerCentimeter);
        public ForcePerLength CentinewtonPerMeter => new ForcePerLength(value, ForcePerLengthUnit.CentinewtonPerMeter);
        public ForcePerLength CentinewtonPerMillimeter => new ForcePerLength(value, ForcePerLengthUnit.CentinewtonPerMillimeter);
        public ForcePerLength DecanewtonPerCentimeter => new ForcePerLength(value, ForcePerLengthUnit.DecanewtonPerCentimeter);
        public ForcePerLength DecanewtonPerMeter => new ForcePerLength(value, ForcePerLengthUnit.DecanewtonPerMeter);
        public ForcePerLength DecanewtonPerMillimeter => new ForcePerLength(value, ForcePerLengthUnit.DecanewtonPerMillimeter);
        public ForcePerLength DecinewtonPerCentimeter => new ForcePerLength(value, ForcePerLengthUnit.DecinewtonPerCentimeter);
        public ForcePerLength DecinewtonPerMeter => new ForcePerLength(value, ForcePerLengthUnit.DecinewtonPerMeter);
        public ForcePerLength DecinewtonPerMillimeter => new ForcePerLength(value, ForcePerLengthUnit.DecinewtonPerMillimeter);
        public ForcePerLength KilogramForcePerCentimeter => new ForcePerLength(value, ForcePerLengthUnit.KilogramForcePerCentimeter);
        public ForcePerLength KilogramForcePerMeter => new ForcePerLength(value, ForcePerLengthUnit.KilogramForcePerMeter);
        public ForcePerLength KilogramForcePerMillimeter => new ForcePerLength(value, ForcePerLengthUnit.KilogramForcePerMillimeter);
        public ForcePerLength KilonewtonPerCentimeter => new ForcePerLength(value, ForcePerLengthUnit.KilonewtonPerCentimeter);
        public ForcePerLength KilonewtonPerMeter => new ForcePerLength(value, ForcePerLengthUnit.KilonewtonPerMeter);
        public ForcePerLength KilonewtonPerMillimeter => new ForcePerLength(value, ForcePerLengthUnit.KilonewtonPerMillimeter);
        public ForcePerLength KilopoundForcePerFoot => new ForcePerLength(value, ForcePerLengthUnit.KilopoundForcePerFoot);
        public ForcePerLength KilopoundForcePerInch => new ForcePerLength(value, ForcePerLengthUnit.KilopoundForcePerInch);
        public ForcePerLength MeganewtonPerCentimeter => new ForcePerLength(value, ForcePerLengthUnit.MeganewtonPerCentimeter);
        public ForcePerLength MeganewtonPerMeter => new ForcePerLength(value, ForcePerLengthUnit.MeganewtonPerMeter);
        public ForcePerLength MeganewtonPerMillimeter => new ForcePerLength(value, ForcePerLengthUnit.MeganewtonPerMillimeter);
        public ForcePerLength MicronewtonPerCentimeter => new ForcePerLength(value, ForcePerLengthUnit.MicronewtonPerCentimeter);
        public ForcePerLength MicronewtonPerMeter => new ForcePerLength(value, ForcePerLengthUnit.MicronewtonPerMeter);
        public ForcePerLength MicronewtonPerMillimeter => new ForcePerLength(value, ForcePerLengthUnit.MicronewtonPerMillimeter);
        public ForcePerLength MillinewtonPerCentimeter => new ForcePerLength(value, ForcePerLengthUnit.MillinewtonPerCentimeter);
        public ForcePerLength MillinewtonPerMeter => new ForcePerLength(value, ForcePerLengthUnit.MillinewtonPerMeter);
        public ForcePerLength MillinewtonPerMillimeter => new ForcePerLength(value, ForcePerLengthUnit.MillinewtonPerMillimeter);
        public ForcePerLength NanonewtonPerCentimeter => new ForcePerLength(value, ForcePerLengthUnit.NanonewtonPerCentimeter);
        public ForcePerLength NanonewtonPerMeter => new ForcePerLength(value, ForcePerLengthUnit.NanonewtonPerMeter);
        public ForcePerLength NanonewtonPerMillimeter => new ForcePerLength(value, ForcePerLengthUnit.NanonewtonPerMillimeter);
        public ForcePerLength NewtonPerCentimeter => new ForcePerLength(value, ForcePerLengthUnit.NewtonPerCentimeter);
        public ForcePerLength NewtonPerMeter => new ForcePerLength(value, ForcePerLengthUnit.NewtonPerMeter);
        public ForcePerLength NewtonPerMillimeter => new ForcePerLength(value, ForcePerLengthUnit.NewtonPerMillimeter);
        public ForcePerLength PoundForcePerFoot => new ForcePerLength(value, ForcePerLengthUnit.PoundForcePerFoot);
        public ForcePerLength PoundForcePerInch => new ForcePerLength(value, ForcePerLengthUnit.PoundForcePerInch);
        public ForcePerLength PoundForcePerYard => new ForcePerLength(value, ForcePerLengthUnit.PoundForcePerYard);
        public ForcePerLength TonneForcePerCentimeter => new ForcePerLength(value, ForcePerLengthUnit.TonneForcePerCentimeter);
        public ForcePerLength TonneForcePerMeter => new ForcePerLength(value, ForcePerLengthUnit.TonneForcePerMeter);
        public ForcePerLength TonneForcePerMillimeter => new ForcePerLength(value, ForcePerLengthUnit.TonneForcePerMillimeter);
    }

    // int receiver
    extension(int value)
    {
        public ForcePerLength CentinewtonPerCentimeter => new ForcePerLength(value, ForcePerLengthUnit.CentinewtonPerCentimeter);
        public ForcePerLength CentinewtonPerMeter => new ForcePerLength(value, ForcePerLengthUnit.CentinewtonPerMeter);
        public ForcePerLength CentinewtonPerMillimeter => new ForcePerLength(value, ForcePerLengthUnit.CentinewtonPerMillimeter);
        public ForcePerLength DecanewtonPerCentimeter => new ForcePerLength(value, ForcePerLengthUnit.DecanewtonPerCentimeter);
        public ForcePerLength DecanewtonPerMeter => new ForcePerLength(value, ForcePerLengthUnit.DecanewtonPerMeter);
        public ForcePerLength DecanewtonPerMillimeter => new ForcePerLength(value, ForcePerLengthUnit.DecanewtonPerMillimeter);
        public ForcePerLength DecinewtonPerCentimeter => new ForcePerLength(value, ForcePerLengthUnit.DecinewtonPerCentimeter);
        public ForcePerLength DecinewtonPerMeter => new ForcePerLength(value, ForcePerLengthUnit.DecinewtonPerMeter);
        public ForcePerLength DecinewtonPerMillimeter => new ForcePerLength(value, ForcePerLengthUnit.DecinewtonPerMillimeter);
        public ForcePerLength KilogramForcePerCentimeter => new ForcePerLength(value, ForcePerLengthUnit.KilogramForcePerCentimeter);
        public ForcePerLength KilogramForcePerMeter => new ForcePerLength(value, ForcePerLengthUnit.KilogramForcePerMeter);
        public ForcePerLength KilogramForcePerMillimeter => new ForcePerLength(value, ForcePerLengthUnit.KilogramForcePerMillimeter);
        public ForcePerLength KilonewtonPerCentimeter => new ForcePerLength(value, ForcePerLengthUnit.KilonewtonPerCentimeter);
        public ForcePerLength KilonewtonPerMeter => new ForcePerLength(value, ForcePerLengthUnit.KilonewtonPerMeter);
        public ForcePerLength KilonewtonPerMillimeter => new ForcePerLength(value, ForcePerLengthUnit.KilonewtonPerMillimeter);
        public ForcePerLength KilopoundForcePerFoot => new ForcePerLength(value, ForcePerLengthUnit.KilopoundForcePerFoot);
        public ForcePerLength KilopoundForcePerInch => new ForcePerLength(value, ForcePerLengthUnit.KilopoundForcePerInch);
        public ForcePerLength MeganewtonPerCentimeter => new ForcePerLength(value, ForcePerLengthUnit.MeganewtonPerCentimeter);
        public ForcePerLength MeganewtonPerMeter => new ForcePerLength(value, ForcePerLengthUnit.MeganewtonPerMeter);
        public ForcePerLength MeganewtonPerMillimeter => new ForcePerLength(value, ForcePerLengthUnit.MeganewtonPerMillimeter);
        public ForcePerLength MicronewtonPerCentimeter => new ForcePerLength(value, ForcePerLengthUnit.MicronewtonPerCentimeter);
        public ForcePerLength MicronewtonPerMeter => new ForcePerLength(value, ForcePerLengthUnit.MicronewtonPerMeter);
        public ForcePerLength MicronewtonPerMillimeter => new ForcePerLength(value, ForcePerLengthUnit.MicronewtonPerMillimeter);
        public ForcePerLength MillinewtonPerCentimeter => new ForcePerLength(value, ForcePerLengthUnit.MillinewtonPerCentimeter);
        public ForcePerLength MillinewtonPerMeter => new ForcePerLength(value, ForcePerLengthUnit.MillinewtonPerMeter);
        public ForcePerLength MillinewtonPerMillimeter => new ForcePerLength(value, ForcePerLengthUnit.MillinewtonPerMillimeter);
        public ForcePerLength NanonewtonPerCentimeter => new ForcePerLength(value, ForcePerLengthUnit.NanonewtonPerCentimeter);
        public ForcePerLength NanonewtonPerMeter => new ForcePerLength(value, ForcePerLengthUnit.NanonewtonPerMeter);
        public ForcePerLength NanonewtonPerMillimeter => new ForcePerLength(value, ForcePerLengthUnit.NanonewtonPerMillimeter);
        public ForcePerLength NewtonPerCentimeter => new ForcePerLength(value, ForcePerLengthUnit.NewtonPerCentimeter);
        public ForcePerLength NewtonPerMeter => new ForcePerLength(value, ForcePerLengthUnit.NewtonPerMeter);
        public ForcePerLength NewtonPerMillimeter => new ForcePerLength(value, ForcePerLengthUnit.NewtonPerMillimeter);
        public ForcePerLength PoundForcePerFoot => new ForcePerLength(value, ForcePerLengthUnit.PoundForcePerFoot);
        public ForcePerLength PoundForcePerInch => new ForcePerLength(value, ForcePerLengthUnit.PoundForcePerInch);
        public ForcePerLength PoundForcePerYard => new ForcePerLength(value, ForcePerLengthUnit.PoundForcePerYard);
        public ForcePerLength TonneForcePerCentimeter => new ForcePerLength(value, ForcePerLengthUnit.TonneForcePerCentimeter);
        public ForcePerLength TonneForcePerMeter => new ForcePerLength(value, ForcePerLengthUnit.TonneForcePerMeter);
        public ForcePerLength TonneForcePerMillimeter => new ForcePerLength(value, ForcePerLengthUnit.TonneForcePerMillimeter);
    }

    // decimal receiver (convert as needed)
    extension(decimal value)
    {
        public ForcePerLength CentinewtonPerCentimeter => new ForcePerLength((double)value, ForcePerLengthUnit.CentinewtonPerCentimeter);
        public ForcePerLength CentinewtonPerMeter => new ForcePerLength((double)value, ForcePerLengthUnit.CentinewtonPerMeter);
        public ForcePerLength CentinewtonPerMillimeter => new ForcePerLength((double)value, ForcePerLengthUnit.CentinewtonPerMillimeter);
        public ForcePerLength DecanewtonPerCentimeter => new ForcePerLength((double)value, ForcePerLengthUnit.DecanewtonPerCentimeter);
        public ForcePerLength DecanewtonPerMeter => new ForcePerLength((double)value, ForcePerLengthUnit.DecanewtonPerMeter);
        public ForcePerLength DecanewtonPerMillimeter => new ForcePerLength((double)value, ForcePerLengthUnit.DecanewtonPerMillimeter);
        public ForcePerLength DecinewtonPerCentimeter => new ForcePerLength((double)value, ForcePerLengthUnit.DecinewtonPerCentimeter);
        public ForcePerLength DecinewtonPerMeter => new ForcePerLength((double)value, ForcePerLengthUnit.DecinewtonPerMeter);
        public ForcePerLength DecinewtonPerMillimeter => new ForcePerLength((double)value, ForcePerLengthUnit.DecinewtonPerMillimeter);
        public ForcePerLength KilogramForcePerCentimeter => new ForcePerLength((double)value, ForcePerLengthUnit.KilogramForcePerCentimeter);
        public ForcePerLength KilogramForcePerMeter => new ForcePerLength((double)value, ForcePerLengthUnit.KilogramForcePerMeter);
        public ForcePerLength KilogramForcePerMillimeter => new ForcePerLength((double)value, ForcePerLengthUnit.KilogramForcePerMillimeter);
        public ForcePerLength KilonewtonPerCentimeter => new ForcePerLength((double)value, ForcePerLengthUnit.KilonewtonPerCentimeter);
        public ForcePerLength KilonewtonPerMeter => new ForcePerLength((double)value, ForcePerLengthUnit.KilonewtonPerMeter);
        public ForcePerLength KilonewtonPerMillimeter => new ForcePerLength((double)value, ForcePerLengthUnit.KilonewtonPerMillimeter);
        public ForcePerLength KilopoundForcePerFoot => new ForcePerLength((double)value, ForcePerLengthUnit.KilopoundForcePerFoot);
        public ForcePerLength KilopoundForcePerInch => new ForcePerLength((double)value, ForcePerLengthUnit.KilopoundForcePerInch);
        public ForcePerLength MeganewtonPerCentimeter => new ForcePerLength((double)value, ForcePerLengthUnit.MeganewtonPerCentimeter);
        public ForcePerLength MeganewtonPerMeter => new ForcePerLength((double)value, ForcePerLengthUnit.MeganewtonPerMeter);
        public ForcePerLength MeganewtonPerMillimeter => new ForcePerLength((double)value, ForcePerLengthUnit.MeganewtonPerMillimeter);
        public ForcePerLength MicronewtonPerCentimeter => new ForcePerLength((double)value, ForcePerLengthUnit.MicronewtonPerCentimeter);
        public ForcePerLength MicronewtonPerMeter => new ForcePerLength((double)value, ForcePerLengthUnit.MicronewtonPerMeter);
        public ForcePerLength MicronewtonPerMillimeter => new ForcePerLength((double)value, ForcePerLengthUnit.MicronewtonPerMillimeter);
        public ForcePerLength MillinewtonPerCentimeter => new ForcePerLength((double)value, ForcePerLengthUnit.MillinewtonPerCentimeter);
        public ForcePerLength MillinewtonPerMeter => new ForcePerLength((double)value, ForcePerLengthUnit.MillinewtonPerMeter);
        public ForcePerLength MillinewtonPerMillimeter => new ForcePerLength((double)value, ForcePerLengthUnit.MillinewtonPerMillimeter);
        public ForcePerLength NanonewtonPerCentimeter => new ForcePerLength((double)value, ForcePerLengthUnit.NanonewtonPerCentimeter);
        public ForcePerLength NanonewtonPerMeter => new ForcePerLength((double)value, ForcePerLengthUnit.NanonewtonPerMeter);
        public ForcePerLength NanonewtonPerMillimeter => new ForcePerLength((double)value, ForcePerLengthUnit.NanonewtonPerMillimeter);
        public ForcePerLength NewtonPerCentimeter => new ForcePerLength((double)value, ForcePerLengthUnit.NewtonPerCentimeter);
        public ForcePerLength NewtonPerMeter => new ForcePerLength((double)value, ForcePerLengthUnit.NewtonPerMeter);
        public ForcePerLength NewtonPerMillimeter => new ForcePerLength((double)value, ForcePerLengthUnit.NewtonPerMillimeter);
        public ForcePerLength PoundForcePerFoot => new ForcePerLength((double)value, ForcePerLengthUnit.PoundForcePerFoot);
        public ForcePerLength PoundForcePerInch => new ForcePerLength((double)value, ForcePerLengthUnit.PoundForcePerInch);
        public ForcePerLength PoundForcePerYard => new ForcePerLength((double)value, ForcePerLengthUnit.PoundForcePerYard);
        public ForcePerLength TonneForcePerCentimeter => new ForcePerLength((double)value, ForcePerLengthUnit.TonneForcePerCentimeter);
        public ForcePerLength TonneForcePerMeter => new ForcePerLength((double)value, ForcePerLengthUnit.TonneForcePerMeter);
        public ForcePerLength TonneForcePerMillimeter => new ForcePerLength((double)value, ForcePerLengthUnit.TonneForcePerMillimeter);
    }
}