using EngineeringUnits;
using EngineeringUnits.Units;

namespace EngineeringUnits.NumberExtensions.NumberToVolumeCost;

// <auto-generated/>
// This file is auto-generated; changes will be overwritten.
public static class NumberToVolumeCostExtensions
{
    // double receiver
    extension(double value)
    {
        public VolumeCost EuroPerCubicMeter => new VolumeCost(value, VolumeCostUnit.EuroPerCubicMeter);
        public VolumeCost USDollarPerCubicMeter => new VolumeCost(value, VolumeCostUnit.USDollarPerCubicMeter);
    }

    // int receiver
    extension(int value)
    {
        public VolumeCost EuroPerCubicMeter => new VolumeCost(value, VolumeCostUnit.EuroPerCubicMeter);
        public VolumeCost USDollarPerCubicMeter => new VolumeCost(value, VolumeCostUnit.USDollarPerCubicMeter);
    }

    // decimal receiver (convert as needed)
    extension(decimal value)
    {
        public VolumeCost EuroPerCubicMeter => new VolumeCost((double)value, VolumeCostUnit.EuroPerCubicMeter);
        public VolumeCost USDollarPerCubicMeter => new VolumeCost((double)value, VolumeCostUnit.USDollarPerCubicMeter);
    }
}