using EngineeringUnits;
using EngineeringUnits.Units;

namespace EngineeringUnits.NumberExtensions.NumberToCost;

// <auto-generated/>
// This file is auto-generated; changes will be overwritten.
public static class NumberToCostExtensions
{
    // double receiver
    extension(double value)
    {
        public Cost BritishPound => new Cost(value, CostUnit.BritishPound);
        public Cost DanishKrone => new Cost(value, CostUnit.DanishKrone);
        public Cost Euro => new Cost(value, CostUnit.Euro);
        public Cost MillionUSDollar => new Cost(value, CostUnit.MillionUSDollar);
        public Cost USDollar => new Cost(value, CostUnit.USDollar);
    }

    // int receiver
    extension(int value)
    {
        public Cost BritishPound => new Cost(value, CostUnit.BritishPound);
        public Cost DanishKrone => new Cost(value, CostUnit.DanishKrone);
        public Cost Euro => new Cost(value, CostUnit.Euro);
        public Cost MillionUSDollar => new Cost(value, CostUnit.MillionUSDollar);
        public Cost USDollar => new Cost(value, CostUnit.USDollar);
    }

    // decimal receiver (convert as needed)
    extension(decimal value)
    {
        public Cost BritishPound => new Cost((double)value, CostUnit.BritishPound);
        public Cost DanishKrone => new Cost((double)value, CostUnit.DanishKrone);
        public Cost Euro => new Cost((double)value, CostUnit.Euro);
        public Cost MillionUSDollar => new Cost((double)value, CostUnit.MillionUSDollar);
        public Cost USDollar => new Cost((double)value, CostUnit.USDollar);
    }
}