using EngineeringUnits;
using EngineeringUnits.Units;

namespace EngineeringUnits.NumberExtensions.NumberToMolarity;

// <auto-generated/>
// This file is auto-generated; changes will be overwritten.
public static class NumberToMolarityExtensions
{
    // double receiver
    extension(double value)
    {
        public Molarity CentimolesPerLiter => new Molarity(value, MolarityUnit.CentimolesPerLiter);
        public Molarity DecimolesPerLiter => new Molarity(value, MolarityUnit.DecimolesPerLiter);
        public Molarity MicromolesPerLiter => new Molarity(value, MolarityUnit.MicromolesPerLiter);
        public Molarity MillimolesPerLiter => new Molarity(value, MolarityUnit.MillimolesPerLiter);
        public Molarity MolesPerCubicMeter => new Molarity(value, MolarityUnit.MolesPerCubicMeter);
        public Molarity MolesPerLiter => new Molarity(value, MolarityUnit.MolesPerLiter);
        public Molarity NanomolesPerLiter => new Molarity(value, MolarityUnit.NanomolesPerLiter);
        public Molarity PicomolesPerLiter => new Molarity(value, MolarityUnit.PicomolesPerLiter);
    }

    // int receiver
    extension(int value)
    {
        public Molarity CentimolesPerLiter => new Molarity(value, MolarityUnit.CentimolesPerLiter);
        public Molarity DecimolesPerLiter => new Molarity(value, MolarityUnit.DecimolesPerLiter);
        public Molarity MicromolesPerLiter => new Molarity(value, MolarityUnit.MicromolesPerLiter);
        public Molarity MillimolesPerLiter => new Molarity(value, MolarityUnit.MillimolesPerLiter);
        public Molarity MolesPerCubicMeter => new Molarity(value, MolarityUnit.MolesPerCubicMeter);
        public Molarity MolesPerLiter => new Molarity(value, MolarityUnit.MolesPerLiter);
        public Molarity NanomolesPerLiter => new Molarity(value, MolarityUnit.NanomolesPerLiter);
        public Molarity PicomolesPerLiter => new Molarity(value, MolarityUnit.PicomolesPerLiter);
    }

    // decimal receiver (convert as needed)
    extension(decimal value)
    {
        public Molarity CentimolesPerLiter => new Molarity((double)value, MolarityUnit.CentimolesPerLiter);
        public Molarity DecimolesPerLiter => new Molarity((double)value, MolarityUnit.DecimolesPerLiter);
        public Molarity MicromolesPerLiter => new Molarity((double)value, MolarityUnit.MicromolesPerLiter);
        public Molarity MillimolesPerLiter => new Molarity((double)value, MolarityUnit.MillimolesPerLiter);
        public Molarity MolesPerCubicMeter => new Molarity((double)value, MolarityUnit.MolesPerCubicMeter);
        public Molarity MolesPerLiter => new Molarity((double)value, MolarityUnit.MolesPerLiter);
        public Molarity NanomolesPerLiter => new Molarity((double)value, MolarityUnit.NanomolesPerLiter);
        public Molarity PicomolesPerLiter => new Molarity((double)value, MolarityUnit.PicomolesPerLiter);
    }
}