using EngineeringUnits;
using EngineeringUnits.Units;

namespace EngineeringUnits.NumberExtensions.NumberToPowerDensity;

// <auto-generated/>
// This file is auto-generated; changes will be overwritten.
public static class NumberToPowerDensityExtensions
{
    // double receiver
    extension(double value)
    {
        public PowerDensity DecawattPerCubicFoot => new PowerDensity(value, PowerDensityUnit.DecawattPerCubicFoot);
        public PowerDensity DecawattPerCubicInch => new PowerDensity(value, PowerDensityUnit.DecawattPerCubicInch);
        public PowerDensity DecawattPerCubicMeter => new PowerDensity(value, PowerDensityUnit.DecawattPerCubicMeter);
        public PowerDensity DecawattPerLiter => new PowerDensity(value, PowerDensityUnit.DecawattPerLiter);
        public PowerDensity DeciwattPerCubicFoot => new PowerDensity(value, PowerDensityUnit.DeciwattPerCubicFoot);
        public PowerDensity DeciwattPerCubicInch => new PowerDensity(value, PowerDensityUnit.DeciwattPerCubicInch);
        public PowerDensity DeciwattPerCubicMeter => new PowerDensity(value, PowerDensityUnit.DeciwattPerCubicMeter);
        public PowerDensity DeciwattPerLiter => new PowerDensity(value, PowerDensityUnit.DeciwattPerLiter);
        public PowerDensity GigawattPerCubicFoot => new PowerDensity(value, PowerDensityUnit.GigawattPerCubicFoot);
        public PowerDensity GigawattPerCubicInch => new PowerDensity(value, PowerDensityUnit.GigawattPerCubicInch);
        public PowerDensity GigawattPerCubicMeter => new PowerDensity(value, PowerDensityUnit.GigawattPerCubicMeter);
        public PowerDensity GigawattPerLiter => new PowerDensity(value, PowerDensityUnit.GigawattPerLiter);
        public PowerDensity KilowattPerCubicFoot => new PowerDensity(value, PowerDensityUnit.KilowattPerCubicFoot);
        public PowerDensity KilowattPerCubicInch => new PowerDensity(value, PowerDensityUnit.KilowattPerCubicInch);
        public PowerDensity KilowattPerCubicMeter => new PowerDensity(value, PowerDensityUnit.KilowattPerCubicMeter);
        public PowerDensity KilowattPerLiter => new PowerDensity(value, PowerDensityUnit.KilowattPerLiter);
        public PowerDensity MegawattPerCubicFoot => new PowerDensity(value, PowerDensityUnit.MegawattPerCubicFoot);
        public PowerDensity MegawattPerCubicInch => new PowerDensity(value, PowerDensityUnit.MegawattPerCubicInch);
        public PowerDensity MegawattPerCubicMeter => new PowerDensity(value, PowerDensityUnit.MegawattPerCubicMeter);
        public PowerDensity MegawattPerLiter => new PowerDensity(value, PowerDensityUnit.MegawattPerLiter);
        public PowerDensity MicrowattPerCubicFoot => new PowerDensity(value, PowerDensityUnit.MicrowattPerCubicFoot);
        public PowerDensity MicrowattPerCubicInch => new PowerDensity(value, PowerDensityUnit.MicrowattPerCubicInch);
        public PowerDensity MicrowattPerCubicMeter => new PowerDensity(value, PowerDensityUnit.MicrowattPerCubicMeter);
        public PowerDensity MicrowattPerLiter => new PowerDensity(value, PowerDensityUnit.MicrowattPerLiter);
        public PowerDensity MilliwattPerCubicFoot => new PowerDensity(value, PowerDensityUnit.MilliwattPerCubicFoot);
        public PowerDensity MilliwattPerCubicInch => new PowerDensity(value, PowerDensityUnit.MilliwattPerCubicInch);
        public PowerDensity MilliwattPerCubicMeter => new PowerDensity(value, PowerDensityUnit.MilliwattPerCubicMeter);
        public PowerDensity MilliwattPerLiter => new PowerDensity(value, PowerDensityUnit.MilliwattPerLiter);
        public PowerDensity NanowattPerCubicFoot => new PowerDensity(value, PowerDensityUnit.NanowattPerCubicFoot);
        public PowerDensity NanowattPerCubicInch => new PowerDensity(value, PowerDensityUnit.NanowattPerCubicInch);
        public PowerDensity NanowattPerCubicMeter => new PowerDensity(value, PowerDensityUnit.NanowattPerCubicMeter);
        public PowerDensity NanowattPerLiter => new PowerDensity(value, PowerDensityUnit.NanowattPerLiter);
        public PowerDensity PicowattPerCubicFoot => new PowerDensity(value, PowerDensityUnit.PicowattPerCubicFoot);
        public PowerDensity PicowattPerCubicInch => new PowerDensity(value, PowerDensityUnit.PicowattPerCubicInch);
        public PowerDensity PicowattPerCubicMeter => new PowerDensity(value, PowerDensityUnit.PicowattPerCubicMeter);
        public PowerDensity PicowattPerLiter => new PowerDensity(value, PowerDensityUnit.PicowattPerLiter);
        public PowerDensity TerawattPerCubicFoot => new PowerDensity(value, PowerDensityUnit.TerawattPerCubicFoot);
        public PowerDensity TerawattPerCubicInch => new PowerDensity(value, PowerDensityUnit.TerawattPerCubicInch);
        public PowerDensity TerawattPerCubicMeter => new PowerDensity(value, PowerDensityUnit.TerawattPerCubicMeter);
        public PowerDensity TerawattPerLiter => new PowerDensity(value, PowerDensityUnit.TerawattPerLiter);
        public PowerDensity WattPerCubicFoot => new PowerDensity(value, PowerDensityUnit.WattPerCubicFoot);
        public PowerDensity WattPerCubicInch => new PowerDensity(value, PowerDensityUnit.WattPerCubicInch);
        public PowerDensity WattPerCubicMeter => new PowerDensity(value, PowerDensityUnit.WattPerCubicMeter);
        public PowerDensity WattPerLiter => new PowerDensity(value, PowerDensityUnit.WattPerLiter);
    }

    // int receiver
    extension(int value)
    {
        public PowerDensity DecawattPerCubicFoot => new PowerDensity(value, PowerDensityUnit.DecawattPerCubicFoot);
        public PowerDensity DecawattPerCubicInch => new PowerDensity(value, PowerDensityUnit.DecawattPerCubicInch);
        public PowerDensity DecawattPerCubicMeter => new PowerDensity(value, PowerDensityUnit.DecawattPerCubicMeter);
        public PowerDensity DecawattPerLiter => new PowerDensity(value, PowerDensityUnit.DecawattPerLiter);
        public PowerDensity DeciwattPerCubicFoot => new PowerDensity(value, PowerDensityUnit.DeciwattPerCubicFoot);
        public PowerDensity DeciwattPerCubicInch => new PowerDensity(value, PowerDensityUnit.DeciwattPerCubicInch);
        public PowerDensity DeciwattPerCubicMeter => new PowerDensity(value, PowerDensityUnit.DeciwattPerCubicMeter);
        public PowerDensity DeciwattPerLiter => new PowerDensity(value, PowerDensityUnit.DeciwattPerLiter);
        public PowerDensity GigawattPerCubicFoot => new PowerDensity(value, PowerDensityUnit.GigawattPerCubicFoot);
        public PowerDensity GigawattPerCubicInch => new PowerDensity(value, PowerDensityUnit.GigawattPerCubicInch);
        public PowerDensity GigawattPerCubicMeter => new PowerDensity(value, PowerDensityUnit.GigawattPerCubicMeter);
        public PowerDensity GigawattPerLiter => new PowerDensity(value, PowerDensityUnit.GigawattPerLiter);
        public PowerDensity KilowattPerCubicFoot => new PowerDensity(value, PowerDensityUnit.KilowattPerCubicFoot);
        public PowerDensity KilowattPerCubicInch => new PowerDensity(value, PowerDensityUnit.KilowattPerCubicInch);
        public PowerDensity KilowattPerCubicMeter => new PowerDensity(value, PowerDensityUnit.KilowattPerCubicMeter);
        public PowerDensity KilowattPerLiter => new PowerDensity(value, PowerDensityUnit.KilowattPerLiter);
        public PowerDensity MegawattPerCubicFoot => new PowerDensity(value, PowerDensityUnit.MegawattPerCubicFoot);
        public PowerDensity MegawattPerCubicInch => new PowerDensity(value, PowerDensityUnit.MegawattPerCubicInch);
        public PowerDensity MegawattPerCubicMeter => new PowerDensity(value, PowerDensityUnit.MegawattPerCubicMeter);
        public PowerDensity MegawattPerLiter => new PowerDensity(value, PowerDensityUnit.MegawattPerLiter);
        public PowerDensity MicrowattPerCubicFoot => new PowerDensity(value, PowerDensityUnit.MicrowattPerCubicFoot);
        public PowerDensity MicrowattPerCubicInch => new PowerDensity(value, PowerDensityUnit.MicrowattPerCubicInch);
        public PowerDensity MicrowattPerCubicMeter => new PowerDensity(value, PowerDensityUnit.MicrowattPerCubicMeter);
        public PowerDensity MicrowattPerLiter => new PowerDensity(value, PowerDensityUnit.MicrowattPerLiter);
        public PowerDensity MilliwattPerCubicFoot => new PowerDensity(value, PowerDensityUnit.MilliwattPerCubicFoot);
        public PowerDensity MilliwattPerCubicInch => new PowerDensity(value, PowerDensityUnit.MilliwattPerCubicInch);
        public PowerDensity MilliwattPerCubicMeter => new PowerDensity(value, PowerDensityUnit.MilliwattPerCubicMeter);
        public PowerDensity MilliwattPerLiter => new PowerDensity(value, PowerDensityUnit.MilliwattPerLiter);
        public PowerDensity NanowattPerCubicFoot => new PowerDensity(value, PowerDensityUnit.NanowattPerCubicFoot);
        public PowerDensity NanowattPerCubicInch => new PowerDensity(value, PowerDensityUnit.NanowattPerCubicInch);
        public PowerDensity NanowattPerCubicMeter => new PowerDensity(value, PowerDensityUnit.NanowattPerCubicMeter);
        public PowerDensity NanowattPerLiter => new PowerDensity(value, PowerDensityUnit.NanowattPerLiter);
        public PowerDensity PicowattPerCubicFoot => new PowerDensity(value, PowerDensityUnit.PicowattPerCubicFoot);
        public PowerDensity PicowattPerCubicInch => new PowerDensity(value, PowerDensityUnit.PicowattPerCubicInch);
        public PowerDensity PicowattPerCubicMeter => new PowerDensity(value, PowerDensityUnit.PicowattPerCubicMeter);
        public PowerDensity PicowattPerLiter => new PowerDensity(value, PowerDensityUnit.PicowattPerLiter);
        public PowerDensity TerawattPerCubicFoot => new PowerDensity(value, PowerDensityUnit.TerawattPerCubicFoot);
        public PowerDensity TerawattPerCubicInch => new PowerDensity(value, PowerDensityUnit.TerawattPerCubicInch);
        public PowerDensity TerawattPerCubicMeter => new PowerDensity(value, PowerDensityUnit.TerawattPerCubicMeter);
        public PowerDensity TerawattPerLiter => new PowerDensity(value, PowerDensityUnit.TerawattPerLiter);
        public PowerDensity WattPerCubicFoot => new PowerDensity(value, PowerDensityUnit.WattPerCubicFoot);
        public PowerDensity WattPerCubicInch => new PowerDensity(value, PowerDensityUnit.WattPerCubicInch);
        public PowerDensity WattPerCubicMeter => new PowerDensity(value, PowerDensityUnit.WattPerCubicMeter);
        public PowerDensity WattPerLiter => new PowerDensity(value, PowerDensityUnit.WattPerLiter);
    }

    // decimal receiver (convert as needed)
    extension(decimal value)
    {
        public PowerDensity DecawattPerCubicFoot => new PowerDensity((double)value, PowerDensityUnit.DecawattPerCubicFoot);
        public PowerDensity DecawattPerCubicInch => new PowerDensity((double)value, PowerDensityUnit.DecawattPerCubicInch);
        public PowerDensity DecawattPerCubicMeter => new PowerDensity((double)value, PowerDensityUnit.DecawattPerCubicMeter);
        public PowerDensity DecawattPerLiter => new PowerDensity((double)value, PowerDensityUnit.DecawattPerLiter);
        public PowerDensity DeciwattPerCubicFoot => new PowerDensity((double)value, PowerDensityUnit.DeciwattPerCubicFoot);
        public PowerDensity DeciwattPerCubicInch => new PowerDensity((double)value, PowerDensityUnit.DeciwattPerCubicInch);
        public PowerDensity DeciwattPerCubicMeter => new PowerDensity((double)value, PowerDensityUnit.DeciwattPerCubicMeter);
        public PowerDensity DeciwattPerLiter => new PowerDensity((double)value, PowerDensityUnit.DeciwattPerLiter);
        public PowerDensity GigawattPerCubicFoot => new PowerDensity((double)value, PowerDensityUnit.GigawattPerCubicFoot);
        public PowerDensity GigawattPerCubicInch => new PowerDensity((double)value, PowerDensityUnit.GigawattPerCubicInch);
        public PowerDensity GigawattPerCubicMeter => new PowerDensity((double)value, PowerDensityUnit.GigawattPerCubicMeter);
        public PowerDensity GigawattPerLiter => new PowerDensity((double)value, PowerDensityUnit.GigawattPerLiter);
        public PowerDensity KilowattPerCubicFoot => new PowerDensity((double)value, PowerDensityUnit.KilowattPerCubicFoot);
        public PowerDensity KilowattPerCubicInch => new PowerDensity((double)value, PowerDensityUnit.KilowattPerCubicInch);
        public PowerDensity KilowattPerCubicMeter => new PowerDensity((double)value, PowerDensityUnit.KilowattPerCubicMeter);
        public PowerDensity KilowattPerLiter => new PowerDensity((double)value, PowerDensityUnit.KilowattPerLiter);
        public PowerDensity MegawattPerCubicFoot => new PowerDensity((double)value, PowerDensityUnit.MegawattPerCubicFoot);
        public PowerDensity MegawattPerCubicInch => new PowerDensity((double)value, PowerDensityUnit.MegawattPerCubicInch);
        public PowerDensity MegawattPerCubicMeter => new PowerDensity((double)value, PowerDensityUnit.MegawattPerCubicMeter);
        public PowerDensity MegawattPerLiter => new PowerDensity((double)value, PowerDensityUnit.MegawattPerLiter);
        public PowerDensity MicrowattPerCubicFoot => new PowerDensity((double)value, PowerDensityUnit.MicrowattPerCubicFoot);
        public PowerDensity MicrowattPerCubicInch => new PowerDensity((double)value, PowerDensityUnit.MicrowattPerCubicInch);
        public PowerDensity MicrowattPerCubicMeter => new PowerDensity((double)value, PowerDensityUnit.MicrowattPerCubicMeter);
        public PowerDensity MicrowattPerLiter => new PowerDensity((double)value, PowerDensityUnit.MicrowattPerLiter);
        public PowerDensity MilliwattPerCubicFoot => new PowerDensity((double)value, PowerDensityUnit.MilliwattPerCubicFoot);
        public PowerDensity MilliwattPerCubicInch => new PowerDensity((double)value, PowerDensityUnit.MilliwattPerCubicInch);
        public PowerDensity MilliwattPerCubicMeter => new PowerDensity((double)value, PowerDensityUnit.MilliwattPerCubicMeter);
        public PowerDensity MilliwattPerLiter => new PowerDensity((double)value, PowerDensityUnit.MilliwattPerLiter);
        public PowerDensity NanowattPerCubicFoot => new PowerDensity((double)value, PowerDensityUnit.NanowattPerCubicFoot);
        public PowerDensity NanowattPerCubicInch => new PowerDensity((double)value, PowerDensityUnit.NanowattPerCubicInch);
        public PowerDensity NanowattPerCubicMeter => new PowerDensity((double)value, PowerDensityUnit.NanowattPerCubicMeter);
        public PowerDensity NanowattPerLiter => new PowerDensity((double)value, PowerDensityUnit.NanowattPerLiter);
        public PowerDensity PicowattPerCubicFoot => new PowerDensity((double)value, PowerDensityUnit.PicowattPerCubicFoot);
        public PowerDensity PicowattPerCubicInch => new PowerDensity((double)value, PowerDensityUnit.PicowattPerCubicInch);
        public PowerDensity PicowattPerCubicMeter => new PowerDensity((double)value, PowerDensityUnit.PicowattPerCubicMeter);
        public PowerDensity PicowattPerLiter => new PowerDensity((double)value, PowerDensityUnit.PicowattPerLiter);
        public PowerDensity TerawattPerCubicFoot => new PowerDensity((double)value, PowerDensityUnit.TerawattPerCubicFoot);
        public PowerDensity TerawattPerCubicInch => new PowerDensity((double)value, PowerDensityUnit.TerawattPerCubicInch);
        public PowerDensity TerawattPerCubicMeter => new PowerDensity((double)value, PowerDensityUnit.TerawattPerCubicMeter);
        public PowerDensity TerawattPerLiter => new PowerDensity((double)value, PowerDensityUnit.TerawattPerLiter);
        public PowerDensity WattPerCubicFoot => new PowerDensity((double)value, PowerDensityUnit.WattPerCubicFoot);
        public PowerDensity WattPerCubicInch => new PowerDensity((double)value, PowerDensityUnit.WattPerCubicInch);
        public PowerDensity WattPerCubicMeter => new PowerDensity((double)value, PowerDensityUnit.WattPerCubicMeter);
        public PowerDensity WattPerLiter => new PowerDensity((double)value, PowerDensityUnit.WattPerLiter);
    }
}