using EngineeringUnits;
using EngineeringUnits.Units;

namespace EngineeringUnits.NumberExtensions.NumberToElectricPotentialChangeRate;

// <auto-generated/>
// This file is auto-generated; changes will be overwritten.
public static class NumberToElectricPotentialChangeRateExtensions
{
    // double receiver
    extension(double value)
    {
        public ElectricPotentialChangeRate KilovoltPerHour => new ElectricPotentialChangeRate(value, ElectricPotentialChangeRateUnit.KilovoltPerHour);
        public ElectricPotentialChangeRate KilovoltPerMicrosecond => new ElectricPotentialChangeRate(value, ElectricPotentialChangeRateUnit.KilovoltPerMicrosecond);
        public ElectricPotentialChangeRate KilovoltPerMinute => new ElectricPotentialChangeRate(value, ElectricPotentialChangeRateUnit.KilovoltPerMinute);
        public ElectricPotentialChangeRate KilovoltPerSecond => new ElectricPotentialChangeRate(value, ElectricPotentialChangeRateUnit.KilovoltPerSecond);
        public ElectricPotentialChangeRate MegavoltPerHour => new ElectricPotentialChangeRate(value, ElectricPotentialChangeRateUnit.MegavoltPerHour);
        public ElectricPotentialChangeRate MegavoltPerMicrosecond => new ElectricPotentialChangeRate(value, ElectricPotentialChangeRateUnit.MegavoltPerMicrosecond);
        public ElectricPotentialChangeRate MegavoltPerMinute => new ElectricPotentialChangeRate(value, ElectricPotentialChangeRateUnit.MegavoltPerMinute);
        public ElectricPotentialChangeRate MegavoltPerSecond => new ElectricPotentialChangeRate(value, ElectricPotentialChangeRateUnit.MegavoltPerSecond);
        public ElectricPotentialChangeRate MicrovoltPerHour => new ElectricPotentialChangeRate(value, ElectricPotentialChangeRateUnit.MicrovoltPerHour);
        public ElectricPotentialChangeRate MicrovoltPerMicrosecond => new ElectricPotentialChangeRate(value, ElectricPotentialChangeRateUnit.MicrovoltPerMicrosecond);
        public ElectricPotentialChangeRate MicrovoltPerMinute => new ElectricPotentialChangeRate(value, ElectricPotentialChangeRateUnit.MicrovoltPerMinute);
        public ElectricPotentialChangeRate MicrovoltPerSecond => new ElectricPotentialChangeRate(value, ElectricPotentialChangeRateUnit.MicrovoltPerSecond);
        public ElectricPotentialChangeRate MillivoltPerHour => new ElectricPotentialChangeRate(value, ElectricPotentialChangeRateUnit.MillivoltPerHour);
        public ElectricPotentialChangeRate MillivoltPerMicrosecond => new ElectricPotentialChangeRate(value, ElectricPotentialChangeRateUnit.MillivoltPerMicrosecond);
        public ElectricPotentialChangeRate MillivoltPerMinute => new ElectricPotentialChangeRate(value, ElectricPotentialChangeRateUnit.MillivoltPerMinute);
        public ElectricPotentialChangeRate MillivoltPerSecond => new ElectricPotentialChangeRate(value, ElectricPotentialChangeRateUnit.MillivoltPerSecond);
        public ElectricPotentialChangeRate VoltPerHour => new ElectricPotentialChangeRate(value, ElectricPotentialChangeRateUnit.VoltPerHour);
        public ElectricPotentialChangeRate VoltPerMicrosecond => new ElectricPotentialChangeRate(value, ElectricPotentialChangeRateUnit.VoltPerMicrosecond);
        public ElectricPotentialChangeRate VoltPerMinute => new ElectricPotentialChangeRate(value, ElectricPotentialChangeRateUnit.VoltPerMinute);
        public ElectricPotentialChangeRate VoltPerSecond => new ElectricPotentialChangeRate(value, ElectricPotentialChangeRateUnit.VoltPerSecond);
    }

    // int receiver
    extension(int value)
    {
        public ElectricPotentialChangeRate KilovoltPerHour => new ElectricPotentialChangeRate(value, ElectricPotentialChangeRateUnit.KilovoltPerHour);
        public ElectricPotentialChangeRate KilovoltPerMicrosecond => new ElectricPotentialChangeRate(value, ElectricPotentialChangeRateUnit.KilovoltPerMicrosecond);
        public ElectricPotentialChangeRate KilovoltPerMinute => new ElectricPotentialChangeRate(value, ElectricPotentialChangeRateUnit.KilovoltPerMinute);
        public ElectricPotentialChangeRate KilovoltPerSecond => new ElectricPotentialChangeRate(value, ElectricPotentialChangeRateUnit.KilovoltPerSecond);
        public ElectricPotentialChangeRate MegavoltPerHour => new ElectricPotentialChangeRate(value, ElectricPotentialChangeRateUnit.MegavoltPerHour);
        public ElectricPotentialChangeRate MegavoltPerMicrosecond => new ElectricPotentialChangeRate(value, ElectricPotentialChangeRateUnit.MegavoltPerMicrosecond);
        public ElectricPotentialChangeRate MegavoltPerMinute => new ElectricPotentialChangeRate(value, ElectricPotentialChangeRateUnit.MegavoltPerMinute);
        public ElectricPotentialChangeRate MegavoltPerSecond => new ElectricPotentialChangeRate(value, ElectricPotentialChangeRateUnit.MegavoltPerSecond);
        public ElectricPotentialChangeRate MicrovoltPerHour => new ElectricPotentialChangeRate(value, ElectricPotentialChangeRateUnit.MicrovoltPerHour);
        public ElectricPotentialChangeRate MicrovoltPerMicrosecond => new ElectricPotentialChangeRate(value, ElectricPotentialChangeRateUnit.MicrovoltPerMicrosecond);
        public ElectricPotentialChangeRate MicrovoltPerMinute => new ElectricPotentialChangeRate(value, ElectricPotentialChangeRateUnit.MicrovoltPerMinute);
        public ElectricPotentialChangeRate MicrovoltPerSecond => new ElectricPotentialChangeRate(value, ElectricPotentialChangeRateUnit.MicrovoltPerSecond);
        public ElectricPotentialChangeRate MillivoltPerHour => new ElectricPotentialChangeRate(value, ElectricPotentialChangeRateUnit.MillivoltPerHour);
        public ElectricPotentialChangeRate MillivoltPerMicrosecond => new ElectricPotentialChangeRate(value, ElectricPotentialChangeRateUnit.MillivoltPerMicrosecond);
        public ElectricPotentialChangeRate MillivoltPerMinute => new ElectricPotentialChangeRate(value, ElectricPotentialChangeRateUnit.MillivoltPerMinute);
        public ElectricPotentialChangeRate MillivoltPerSecond => new ElectricPotentialChangeRate(value, ElectricPotentialChangeRateUnit.MillivoltPerSecond);
        public ElectricPotentialChangeRate VoltPerHour => new ElectricPotentialChangeRate(value, ElectricPotentialChangeRateUnit.VoltPerHour);
        public ElectricPotentialChangeRate VoltPerMicrosecond => new ElectricPotentialChangeRate(value, ElectricPotentialChangeRateUnit.VoltPerMicrosecond);
        public ElectricPotentialChangeRate VoltPerMinute => new ElectricPotentialChangeRate(value, ElectricPotentialChangeRateUnit.VoltPerMinute);
        public ElectricPotentialChangeRate VoltPerSecond => new ElectricPotentialChangeRate(value, ElectricPotentialChangeRateUnit.VoltPerSecond);
    }

    // decimal receiver (convert as needed)
    extension(decimal value)
    {
        public ElectricPotentialChangeRate KilovoltPerHour => new ElectricPotentialChangeRate((double)value, ElectricPotentialChangeRateUnit.KilovoltPerHour);
        public ElectricPotentialChangeRate KilovoltPerMicrosecond => new ElectricPotentialChangeRate((double)value, ElectricPotentialChangeRateUnit.KilovoltPerMicrosecond);
        public ElectricPotentialChangeRate KilovoltPerMinute => new ElectricPotentialChangeRate((double)value, ElectricPotentialChangeRateUnit.KilovoltPerMinute);
        public ElectricPotentialChangeRate KilovoltPerSecond => new ElectricPotentialChangeRate((double)value, ElectricPotentialChangeRateUnit.KilovoltPerSecond);
        public ElectricPotentialChangeRate MegavoltPerHour => new ElectricPotentialChangeRate((double)value, ElectricPotentialChangeRateUnit.MegavoltPerHour);
        public ElectricPotentialChangeRate MegavoltPerMicrosecond => new ElectricPotentialChangeRate((double)value, ElectricPotentialChangeRateUnit.MegavoltPerMicrosecond);
        public ElectricPotentialChangeRate MegavoltPerMinute => new ElectricPotentialChangeRate((double)value, ElectricPotentialChangeRateUnit.MegavoltPerMinute);
        public ElectricPotentialChangeRate MegavoltPerSecond => new ElectricPotentialChangeRate((double)value, ElectricPotentialChangeRateUnit.MegavoltPerSecond);
        public ElectricPotentialChangeRate MicrovoltPerHour => new ElectricPotentialChangeRate((double)value, ElectricPotentialChangeRateUnit.MicrovoltPerHour);
        public ElectricPotentialChangeRate MicrovoltPerMicrosecond => new ElectricPotentialChangeRate((double)value, ElectricPotentialChangeRateUnit.MicrovoltPerMicrosecond);
        public ElectricPotentialChangeRate MicrovoltPerMinute => new ElectricPotentialChangeRate((double)value, ElectricPotentialChangeRateUnit.MicrovoltPerMinute);
        public ElectricPotentialChangeRate MicrovoltPerSecond => new ElectricPotentialChangeRate((double)value, ElectricPotentialChangeRateUnit.MicrovoltPerSecond);
        public ElectricPotentialChangeRate MillivoltPerHour => new ElectricPotentialChangeRate((double)value, ElectricPotentialChangeRateUnit.MillivoltPerHour);
        public ElectricPotentialChangeRate MillivoltPerMicrosecond => new ElectricPotentialChangeRate((double)value, ElectricPotentialChangeRateUnit.MillivoltPerMicrosecond);
        public ElectricPotentialChangeRate MillivoltPerMinute => new ElectricPotentialChangeRate((double)value, ElectricPotentialChangeRateUnit.MillivoltPerMinute);
        public ElectricPotentialChangeRate MillivoltPerSecond => new ElectricPotentialChangeRate((double)value, ElectricPotentialChangeRateUnit.MillivoltPerSecond);
        public ElectricPotentialChangeRate VoltPerHour => new ElectricPotentialChangeRate((double)value, ElectricPotentialChangeRateUnit.VoltPerHour);
        public ElectricPotentialChangeRate VoltPerMicrosecond => new ElectricPotentialChangeRate((double)value, ElectricPotentialChangeRateUnit.VoltPerMicrosecond);
        public ElectricPotentialChangeRate VoltPerMinute => new ElectricPotentialChangeRate((double)value, ElectricPotentialChangeRateUnit.VoltPerMinute);
        public ElectricPotentialChangeRate VoltPerSecond => new ElectricPotentialChangeRate((double)value, ElectricPotentialChangeRateUnit.VoltPerSecond);
    }
}