using EngineeringUnits;
using EngineeringUnits.Units;

namespace EngineeringUnits.NumberExtensions.NumberToElectricCurrentGradient;

// <auto-generated/>
// This file is auto-generated; changes will be overwritten.
public static class NumberToElectricCurrentGradientExtensions
{
    // double receiver
    extension(double value)
    {
        public ElectricCurrentGradient AmperePerMicrosecond => new ElectricCurrentGradient(value, ElectricCurrentGradientUnit.AmperePerMicrosecond);
        public ElectricCurrentGradient AmperePerMillisecond => new ElectricCurrentGradient(value, ElectricCurrentGradientUnit.AmperePerMillisecond);
        public ElectricCurrentGradient AmperePerNanosecond => new ElectricCurrentGradient(value, ElectricCurrentGradientUnit.AmperePerNanosecond);
        public ElectricCurrentGradient AmperePerSecond => new ElectricCurrentGradient(value, ElectricCurrentGradientUnit.AmperePerSecond);
    }

    // int receiver
    extension(int value)
    {
        public ElectricCurrentGradient AmperePerMicrosecond => new ElectricCurrentGradient(value, ElectricCurrentGradientUnit.AmperePerMicrosecond);
        public ElectricCurrentGradient AmperePerMillisecond => new ElectricCurrentGradient(value, ElectricCurrentGradientUnit.AmperePerMillisecond);
        public ElectricCurrentGradient AmperePerNanosecond => new ElectricCurrentGradient(value, ElectricCurrentGradientUnit.AmperePerNanosecond);
        public ElectricCurrentGradient AmperePerSecond => new ElectricCurrentGradient(value, ElectricCurrentGradientUnit.AmperePerSecond);
    }

    // decimal receiver (convert as needed)
    extension(decimal value)
    {
        public ElectricCurrentGradient AmperePerMicrosecond => new ElectricCurrentGradient((double)value, ElectricCurrentGradientUnit.AmperePerMicrosecond);
        public ElectricCurrentGradient AmperePerMillisecond => new ElectricCurrentGradient((double)value, ElectricCurrentGradientUnit.AmperePerMillisecond);
        public ElectricCurrentGradient AmperePerNanosecond => new ElectricCurrentGradient((double)value, ElectricCurrentGradientUnit.AmperePerNanosecond);
        public ElectricCurrentGradient AmperePerSecond => new ElectricCurrentGradient((double)value, ElectricCurrentGradientUnit.AmperePerSecond);
    }
}