using EngineeringUnits;
using EngineeringUnits.Units;

namespace EngineeringUnits.NumberExtensions.NumberToLuminousIntensity;

// <auto-generated/>
// This file is auto-generated; changes will be overwritten.
public static class NumberToLuminousIntensityExtensions
{
    // double receiver
    extension(double value)
    {
        public LuminousIntensity Candela => new LuminousIntensity(value, LuminousIntensityUnit.Candela);
    }

    // int receiver
    extension(int value)
    {
        public LuminousIntensity Candela => new LuminousIntensity(value, LuminousIntensityUnit.Candela);
    }

    // decimal receiver (convert as needed)
    extension(decimal value)
    {
        public LuminousIntensity Candela => new LuminousIntensity((double)value, LuminousIntensityUnit.Candela);
    }
}