using EngineeringUnits;
using EngineeringUnits.Units;

namespace EngineeringUnits.NumberExtensions.NumberToAcceleration;

// <auto-generated/>
// This file is auto-generated; changes will be overwritten.
public static class NumberToAccelerationExtensions
{
    // double receiver
    extension(double value)
    {
        public Acceleration CentimeterPerSecondSquared => new Acceleration(value, AccelerationUnit.CentimeterPerSecondSquared);
        public Acceleration DecimeterPerSecondSquared => new Acceleration(value, AccelerationUnit.DecimeterPerSecondSquared);
        public Acceleration FootPerSecondSquared => new Acceleration(value, AccelerationUnit.FootPerSecondSquared);
        public Acceleration InchPerSecondSquared => new Acceleration(value, AccelerationUnit.InchPerSecondSquared);
        public Acceleration KilometerPerSecondSquared => new Acceleration(value, AccelerationUnit.KilometerPerSecondSquared);
        public Acceleration KnotPerHour => new Acceleration(value, AccelerationUnit.KnotPerHour);
        public Acceleration KnotPerMinute => new Acceleration(value, AccelerationUnit.KnotPerMinute);
        public Acceleration KnotPerSecond => new Acceleration(value, AccelerationUnit.KnotPerSecond);
        public Acceleration MeterPerSecondSquared => new Acceleration(value, AccelerationUnit.MeterPerSecondSquared);
        public Acceleration MicrometerPerSecondSquared => new Acceleration(value, AccelerationUnit.MicrometerPerSecondSquared);
        public Acceleration MillimeterPerSecondSquared => new Acceleration(value, AccelerationUnit.MillimeterPerSecondSquared);
        public Acceleration MillistandardGravity => new Acceleration(value, AccelerationUnit.MillistandardGravity);
        public Acceleration NanometerPerSecondSquared => new Acceleration(value, AccelerationUnit.NanometerPerSecondSquared);
        public Acceleration StandardGravity => new Acceleration(value, AccelerationUnit.StandardGravity);
    }

    // int receiver
    extension(int value)
    {
        public Acceleration CentimeterPerSecondSquared => new Acceleration(value, AccelerationUnit.CentimeterPerSecondSquared);
        public Acceleration DecimeterPerSecondSquared => new Acceleration(value, AccelerationUnit.DecimeterPerSecondSquared);
        public Acceleration FootPerSecondSquared => new Acceleration(value, AccelerationUnit.FootPerSecondSquared);
        public Acceleration InchPerSecondSquared => new Acceleration(value, AccelerationUnit.InchPerSecondSquared);
        public Acceleration KilometerPerSecondSquared => new Acceleration(value, AccelerationUnit.KilometerPerSecondSquared);
        public Acceleration KnotPerHour => new Acceleration(value, AccelerationUnit.KnotPerHour);
        public Acceleration KnotPerMinute => new Acceleration(value, AccelerationUnit.KnotPerMinute);
        public Acceleration KnotPerSecond => new Acceleration(value, AccelerationUnit.KnotPerSecond);
        public Acceleration MeterPerSecondSquared => new Acceleration(value, AccelerationUnit.MeterPerSecondSquared);
        public Acceleration MicrometerPerSecondSquared => new Acceleration(value, AccelerationUnit.MicrometerPerSecondSquared);
        public Acceleration MillimeterPerSecondSquared => new Acceleration(value, AccelerationUnit.MillimeterPerSecondSquared);
        public Acceleration MillistandardGravity => new Acceleration(value, AccelerationUnit.MillistandardGravity);
        public Acceleration NanometerPerSecondSquared => new Acceleration(value, AccelerationUnit.NanometerPerSecondSquared);
        public Acceleration StandardGravity => new Acceleration(value, AccelerationUnit.StandardGravity);
    }

    // decimal receiver (convert as needed)
    extension(decimal value)
    {
        public Acceleration CentimeterPerSecondSquared => new Acceleration((double)value, AccelerationUnit.CentimeterPerSecondSquared);
        public Acceleration DecimeterPerSecondSquared => new Acceleration((double)value, AccelerationUnit.DecimeterPerSecondSquared);
        public Acceleration FootPerSecondSquared => new Acceleration((double)value, AccelerationUnit.FootPerSecondSquared);
        public Acceleration InchPerSecondSquared => new Acceleration((double)value, AccelerationUnit.InchPerSecondSquared);
        public Acceleration KilometerPerSecondSquared => new Acceleration((double)value, AccelerationUnit.KilometerPerSecondSquared);
        public Acceleration KnotPerHour => new Acceleration((double)value, AccelerationUnit.KnotPerHour);
        public Acceleration KnotPerMinute => new Acceleration((double)value, AccelerationUnit.KnotPerMinute);
        public Acceleration KnotPerSecond => new Acceleration((double)value, AccelerationUnit.KnotPerSecond);
        public Acceleration MeterPerSecondSquared => new Acceleration((double)value, AccelerationUnit.MeterPerSecondSquared);
        public Acceleration MicrometerPerSecondSquared => new Acceleration((double)value, AccelerationUnit.MicrometerPerSecondSquared);
        public Acceleration MillimeterPerSecondSquared => new Acceleration((double)value, AccelerationUnit.MillimeterPerSecondSquared);
        public Acceleration MillistandardGravity => new Acceleration((double)value, AccelerationUnit.MillistandardGravity);
        public Acceleration NanometerPerSecondSquared => new Acceleration((double)value, AccelerationUnit.NanometerPerSecondSquared);
        public Acceleration StandardGravity => new Acceleration((double)value, AccelerationUnit.StandardGravity);
    }
}