using EngineeringUnits;
using EngineeringUnits.Units;

namespace EngineeringUnits.NumberExtensions.NumberToBrakeSpecificFuelConsumption;

// <auto-generated/>
// This file is auto-generated; changes will be overwritten.
public static class NumberToBrakeSpecificFuelConsumptionExtensions
{
    // double receiver
    extension(double value)
    {
        public BrakeSpecificFuelConsumption GramPerKiloWattHour => new BrakeSpecificFuelConsumption(value, BrakeSpecificFuelConsumptionUnit.GramPerKiloWattHour);
        public BrakeSpecificFuelConsumption KilogramPerJoule => new BrakeSpecificFuelConsumption(value, BrakeSpecificFuelConsumptionUnit.KilogramPerJoule);
        public BrakeSpecificFuelConsumption PoundPerMechanicalHorsepowerHour => new BrakeSpecificFuelConsumption(value, BrakeSpecificFuelConsumptionUnit.PoundPerMechanicalHorsepowerHour);
    }

    // int receiver
    extension(int value)
    {
        public BrakeSpecificFuelConsumption GramPerKiloWattHour => new BrakeSpecificFuelConsumption(value, BrakeSpecificFuelConsumptionUnit.GramPerKiloWattHour);
        public BrakeSpecificFuelConsumption KilogramPerJoule => new BrakeSpecificFuelConsumption(value, BrakeSpecificFuelConsumptionUnit.KilogramPerJoule);
        public BrakeSpecificFuelConsumption PoundPerMechanicalHorsepowerHour => new BrakeSpecificFuelConsumption(value, BrakeSpecificFuelConsumptionUnit.PoundPerMechanicalHorsepowerHour);
    }

    // decimal receiver (convert as needed)
    extension(decimal value)
    {
        public BrakeSpecificFuelConsumption GramPerKiloWattHour => new BrakeSpecificFuelConsumption((double)value, BrakeSpecificFuelConsumptionUnit.GramPerKiloWattHour);
        public BrakeSpecificFuelConsumption KilogramPerJoule => new BrakeSpecificFuelConsumption((double)value, BrakeSpecificFuelConsumptionUnit.KilogramPerJoule);
        public BrakeSpecificFuelConsumption PoundPerMechanicalHorsepowerHour => new BrakeSpecificFuelConsumption((double)value, BrakeSpecificFuelConsumptionUnit.PoundPerMechanicalHorsepowerHour);
    }
}