using EngineeringUnits;
using EngineeringUnits.Units;

namespace EngineeringUnits.NumberExtensions.NumberToMass;

// <auto-generated/>
// This file is auto-generated; changes will be overwritten.
public static class NumberToMassExtensions
{
    // double receiver
    extension(double value)
    {
        public Mass Centigram => new Mass(value, MassUnit.Centigram);
        public Mass Decagram => new Mass(value, MassUnit.Decagram);
        public Mass Decigram => new Mass(value, MassUnit.Decigram);
        public Mass EarthMass => new Mass(value, MassUnit.EarthMass);
        public Mass Grain => new Mass(value, MassUnit.Grain);
        public Mass Gram => new Mass(value, MassUnit.Gram);
        public Mass Hectogram => new Mass(value, MassUnit.Hectogram);
        public Mass Kilogram => new Mass(value, MassUnit.Kilogram);
        public Mass Kilopound => new Mass(value, MassUnit.Kilopound);
        public Mass Kilotonne => new Mass(value, MassUnit.Kilotonne);
        public Mass LongHundredweight => new Mass(value, MassUnit.LongHundredweight);
        public Mass LongTon => new Mass(value, MassUnit.LongTon);
        public Mass Megapound => new Mass(value, MassUnit.Megapound);
        public Mass Megatonne => new Mass(value, MassUnit.Megatonne);
        public Mass Microgram => new Mass(value, MassUnit.Microgram);
        public Mass Milligram => new Mass(value, MassUnit.Milligram);
        public Mass Nanogram => new Mass(value, MassUnit.Nanogram);
        public Mass Ounce => new Mass(value, MassUnit.Ounce);
        public Mass Picogram => new Mass(value, MassUnit.Picogram);
        public Mass Pound => new Mass(value, MassUnit.Pound);
        public Mass ShortHundredweight => new Mass(value, MassUnit.ShortHundredweight);
        public Mass ShortTon => new Mass(value, MassUnit.ShortTon);
        public Mass Slug => new Mass(value, MassUnit.Slug);
        public Mass Stone => new Mass(value, MassUnit.Stone);
        public Mass Tonne => new Mass(value, MassUnit.Tonne);
    }

    // int receiver
    extension(int value)
    {
        public Mass Centigram => new Mass(value, MassUnit.Centigram);
        public Mass Decagram => new Mass(value, MassUnit.Decagram);
        public Mass Decigram => new Mass(value, MassUnit.Decigram);
        public Mass EarthMass => new Mass(value, MassUnit.EarthMass);
        public Mass Grain => new Mass(value, MassUnit.Grain);
        public Mass Gram => new Mass(value, MassUnit.Gram);
        public Mass Hectogram => new Mass(value, MassUnit.Hectogram);
        public Mass Kilogram => new Mass(value, MassUnit.Kilogram);
        public Mass Kilopound => new Mass(value, MassUnit.Kilopound);
        public Mass Kilotonne => new Mass(value, MassUnit.Kilotonne);
        public Mass LongHundredweight => new Mass(value, MassUnit.LongHundredweight);
        public Mass LongTon => new Mass(value, MassUnit.LongTon);
        public Mass Megapound => new Mass(value, MassUnit.Megapound);
        public Mass Megatonne => new Mass(value, MassUnit.Megatonne);
        public Mass Microgram => new Mass(value, MassUnit.Microgram);
        public Mass Milligram => new Mass(value, MassUnit.Milligram);
        public Mass Nanogram => new Mass(value, MassUnit.Nanogram);
        public Mass Ounce => new Mass(value, MassUnit.Ounce);
        public Mass Picogram => new Mass(value, MassUnit.Picogram);
        public Mass Pound => new Mass(value, MassUnit.Pound);
        public Mass ShortHundredweight => new Mass(value, MassUnit.ShortHundredweight);
        public Mass ShortTon => new Mass(value, MassUnit.ShortTon);
        public Mass Slug => new Mass(value, MassUnit.Slug);
        public Mass Stone => new Mass(value, MassUnit.Stone);
        public Mass Tonne => new Mass(value, MassUnit.Tonne);
    }

    // decimal receiver (convert as needed)
    extension(decimal value)
    {
        public Mass Centigram => new Mass((double)value, MassUnit.Centigram);
        public Mass Decagram => new Mass((double)value, MassUnit.Decagram);
        public Mass Decigram => new Mass((double)value, MassUnit.Decigram);
        public Mass EarthMass => new Mass((double)value, MassUnit.EarthMass);
        public Mass Grain => new Mass((double)value, MassUnit.Grain);
        public Mass Gram => new Mass((double)value, MassUnit.Gram);
        public Mass Hectogram => new Mass((double)value, MassUnit.Hectogram);
        public Mass Kilogram => new Mass((double)value, MassUnit.Kilogram);
        public Mass Kilopound => new Mass((double)value, MassUnit.Kilopound);
        public Mass Kilotonne => new Mass((double)value, MassUnit.Kilotonne);
        public Mass LongHundredweight => new Mass((double)value, MassUnit.LongHundredweight);
        public Mass LongTon => new Mass((double)value, MassUnit.LongTon);
        public Mass Megapound => new Mass((double)value, MassUnit.Megapound);
        public Mass Megatonne => new Mass((double)value, MassUnit.Megatonne);
        public Mass Microgram => new Mass((double)value, MassUnit.Microgram);
        public Mass Milligram => new Mass((double)value, MassUnit.Milligram);
        public Mass Nanogram => new Mass((double)value, MassUnit.Nanogram);
        public Mass Ounce => new Mass((double)value, MassUnit.Ounce);
        public Mass Picogram => new Mass((double)value, MassUnit.Picogram);
        public Mass Pound => new Mass((double)value, MassUnit.Pound);
        public Mass ShortHundredweight => new Mass((double)value, MassUnit.ShortHundredweight);
        public Mass ShortTon => new Mass((double)value, MassUnit.ShortTon);
        public Mass Slug => new Mass((double)value, MassUnit.Slug);
        public Mass Stone => new Mass((double)value, MassUnit.Stone);
        public Mass Tonne => new Mass((double)value, MassUnit.Tonne);
    }
}