using EngineeringUnits;
using EngineeringUnits.Units;

namespace EngineeringUnits.NumberExtensions.NumberToLinearPowerDensity;

// <auto-generated/>
// This file is auto-generated; changes will be overwritten.
public static class NumberToLinearPowerDensityExtensions
{
    // double receiver
    extension(double value)
    {
        public LinearPowerDensity GigawattPerCentimeter => new LinearPowerDensity(value, LinearPowerDensityUnit.GigawattPerCentimeter);
        public LinearPowerDensity GigawattPerFoot => new LinearPowerDensity(value, LinearPowerDensityUnit.GigawattPerFoot);
        public LinearPowerDensity GigawattPerInch => new LinearPowerDensity(value, LinearPowerDensityUnit.GigawattPerInch);
        public LinearPowerDensity GigawattPerMeter => new LinearPowerDensity(value, LinearPowerDensityUnit.GigawattPerMeter);
        public LinearPowerDensity GigawattPerMillimeter => new LinearPowerDensity(value, LinearPowerDensityUnit.GigawattPerMillimeter);
        public LinearPowerDensity KilowattPerCentimeter => new LinearPowerDensity(value, LinearPowerDensityUnit.KilowattPerCentimeter);
        public LinearPowerDensity KilowattPerFoot => new LinearPowerDensity(value, LinearPowerDensityUnit.KilowattPerFoot);
        public LinearPowerDensity KilowattPerInch => new LinearPowerDensity(value, LinearPowerDensityUnit.KilowattPerInch);
        public LinearPowerDensity KilowattPerMeter => new LinearPowerDensity(value, LinearPowerDensityUnit.KilowattPerMeter);
        public LinearPowerDensity KilowattPerMillimeter => new LinearPowerDensity(value, LinearPowerDensityUnit.KilowattPerMillimeter);
        public LinearPowerDensity MegawattPerCentimeter => new LinearPowerDensity(value, LinearPowerDensityUnit.MegawattPerCentimeter);
        public LinearPowerDensity MegawattPerFoot => new LinearPowerDensity(value, LinearPowerDensityUnit.MegawattPerFoot);
        public LinearPowerDensity MegawattPerInch => new LinearPowerDensity(value, LinearPowerDensityUnit.MegawattPerInch);
        public LinearPowerDensity MegawattPerMeter => new LinearPowerDensity(value, LinearPowerDensityUnit.MegawattPerMeter);
        public LinearPowerDensity MegawattPerMillimeter => new LinearPowerDensity(value, LinearPowerDensityUnit.MegawattPerMillimeter);
        public LinearPowerDensity MilliwattPerCentimeter => new LinearPowerDensity(value, LinearPowerDensityUnit.MilliwattPerCentimeter);
        public LinearPowerDensity MilliwattPerFoot => new LinearPowerDensity(value, LinearPowerDensityUnit.MilliwattPerFoot);
        public LinearPowerDensity MilliwattPerInch => new LinearPowerDensity(value, LinearPowerDensityUnit.MilliwattPerInch);
        public LinearPowerDensity MilliwattPerMeter => new LinearPowerDensity(value, LinearPowerDensityUnit.MilliwattPerMeter);
        public LinearPowerDensity MilliwattPerMillimeter => new LinearPowerDensity(value, LinearPowerDensityUnit.MilliwattPerMillimeter);
        public LinearPowerDensity WattPerCentimeter => new LinearPowerDensity(value, LinearPowerDensityUnit.WattPerCentimeter);
        public LinearPowerDensity WattPerFoot => new LinearPowerDensity(value, LinearPowerDensityUnit.WattPerFoot);
        public LinearPowerDensity WattPerInch => new LinearPowerDensity(value, LinearPowerDensityUnit.WattPerInch);
        public LinearPowerDensity WattPerMeter => new LinearPowerDensity(value, LinearPowerDensityUnit.WattPerMeter);
        public LinearPowerDensity WattPerMillimeter => new LinearPowerDensity(value, LinearPowerDensityUnit.WattPerMillimeter);
    }

    // int receiver
    extension(int value)
    {
        public LinearPowerDensity GigawattPerCentimeter => new LinearPowerDensity(value, LinearPowerDensityUnit.GigawattPerCentimeter);
        public LinearPowerDensity GigawattPerFoot => new LinearPowerDensity(value, LinearPowerDensityUnit.GigawattPerFoot);
        public LinearPowerDensity GigawattPerInch => new LinearPowerDensity(value, LinearPowerDensityUnit.GigawattPerInch);
        public LinearPowerDensity GigawattPerMeter => new LinearPowerDensity(value, LinearPowerDensityUnit.GigawattPerMeter);
        public LinearPowerDensity GigawattPerMillimeter => new LinearPowerDensity(value, LinearPowerDensityUnit.GigawattPerMillimeter);
        public LinearPowerDensity KilowattPerCentimeter => new LinearPowerDensity(value, LinearPowerDensityUnit.KilowattPerCentimeter);
        public LinearPowerDensity KilowattPerFoot => new LinearPowerDensity(value, LinearPowerDensityUnit.KilowattPerFoot);
        public LinearPowerDensity KilowattPerInch => new LinearPowerDensity(value, LinearPowerDensityUnit.KilowattPerInch);
        public LinearPowerDensity KilowattPerMeter => new LinearPowerDensity(value, LinearPowerDensityUnit.KilowattPerMeter);
        public LinearPowerDensity KilowattPerMillimeter => new LinearPowerDensity(value, LinearPowerDensityUnit.KilowattPerMillimeter);
        public LinearPowerDensity MegawattPerCentimeter => new LinearPowerDensity(value, LinearPowerDensityUnit.MegawattPerCentimeter);
        public LinearPowerDensity MegawattPerFoot => new LinearPowerDensity(value, LinearPowerDensityUnit.MegawattPerFoot);
        public LinearPowerDensity MegawattPerInch => new LinearPowerDensity(value, LinearPowerDensityUnit.MegawattPerInch);
        public LinearPowerDensity MegawattPerMeter => new LinearPowerDensity(value, LinearPowerDensityUnit.MegawattPerMeter);
        public LinearPowerDensity MegawattPerMillimeter => new LinearPowerDensity(value, LinearPowerDensityUnit.MegawattPerMillimeter);
        public LinearPowerDensity MilliwattPerCentimeter => new LinearPowerDensity(value, LinearPowerDensityUnit.MilliwattPerCentimeter);
        public LinearPowerDensity MilliwattPerFoot => new LinearPowerDensity(value, LinearPowerDensityUnit.MilliwattPerFoot);
        public LinearPowerDensity MilliwattPerInch => new LinearPowerDensity(value, LinearPowerDensityUnit.MilliwattPerInch);
        public LinearPowerDensity MilliwattPerMeter => new LinearPowerDensity(value, LinearPowerDensityUnit.MilliwattPerMeter);
        public LinearPowerDensity MilliwattPerMillimeter => new LinearPowerDensity(value, LinearPowerDensityUnit.MilliwattPerMillimeter);
        public LinearPowerDensity WattPerCentimeter => new LinearPowerDensity(value, LinearPowerDensityUnit.WattPerCentimeter);
        public LinearPowerDensity WattPerFoot => new LinearPowerDensity(value, LinearPowerDensityUnit.WattPerFoot);
        public LinearPowerDensity WattPerInch => new LinearPowerDensity(value, LinearPowerDensityUnit.WattPerInch);
        public LinearPowerDensity WattPerMeter => new LinearPowerDensity(value, LinearPowerDensityUnit.WattPerMeter);
        public LinearPowerDensity WattPerMillimeter => new LinearPowerDensity(value, LinearPowerDensityUnit.WattPerMillimeter);
    }

    // decimal receiver (convert as needed)
    extension(decimal value)
    {
        public LinearPowerDensity GigawattPerCentimeter => new LinearPowerDensity((double)value, LinearPowerDensityUnit.GigawattPerCentimeter);
        public LinearPowerDensity GigawattPerFoot => new LinearPowerDensity((double)value, LinearPowerDensityUnit.GigawattPerFoot);
        public LinearPowerDensity GigawattPerInch => new LinearPowerDensity((double)value, LinearPowerDensityUnit.GigawattPerInch);
        public LinearPowerDensity GigawattPerMeter => new LinearPowerDensity((double)value, LinearPowerDensityUnit.GigawattPerMeter);
        public LinearPowerDensity GigawattPerMillimeter => new LinearPowerDensity((double)value, LinearPowerDensityUnit.GigawattPerMillimeter);
        public LinearPowerDensity KilowattPerCentimeter => new LinearPowerDensity((double)value, LinearPowerDensityUnit.KilowattPerCentimeter);
        public LinearPowerDensity KilowattPerFoot => new LinearPowerDensity((double)value, LinearPowerDensityUnit.KilowattPerFoot);
        public LinearPowerDensity KilowattPerInch => new LinearPowerDensity((double)value, LinearPowerDensityUnit.KilowattPerInch);
        public LinearPowerDensity KilowattPerMeter => new LinearPowerDensity((double)value, LinearPowerDensityUnit.KilowattPerMeter);
        public LinearPowerDensity KilowattPerMillimeter => new LinearPowerDensity((double)value, LinearPowerDensityUnit.KilowattPerMillimeter);
        public LinearPowerDensity MegawattPerCentimeter => new LinearPowerDensity((double)value, LinearPowerDensityUnit.MegawattPerCentimeter);
        public LinearPowerDensity MegawattPerFoot => new LinearPowerDensity((double)value, LinearPowerDensityUnit.MegawattPerFoot);
        public LinearPowerDensity MegawattPerInch => new LinearPowerDensity((double)value, LinearPowerDensityUnit.MegawattPerInch);
        public LinearPowerDensity MegawattPerMeter => new LinearPowerDensity((double)value, LinearPowerDensityUnit.MegawattPerMeter);
        public LinearPowerDensity MegawattPerMillimeter => new LinearPowerDensity((double)value, LinearPowerDensityUnit.MegawattPerMillimeter);
        public LinearPowerDensity MilliwattPerCentimeter => new LinearPowerDensity((double)value, LinearPowerDensityUnit.MilliwattPerCentimeter);
        public LinearPowerDensity MilliwattPerFoot => new LinearPowerDensity((double)value, LinearPowerDensityUnit.MilliwattPerFoot);
        public LinearPowerDensity MilliwattPerInch => new LinearPowerDensity((double)value, LinearPowerDensityUnit.MilliwattPerInch);
        public LinearPowerDensity MilliwattPerMeter => new LinearPowerDensity((double)value, LinearPowerDensityUnit.MilliwattPerMeter);
        public LinearPowerDensity MilliwattPerMillimeter => new LinearPowerDensity((double)value, LinearPowerDensityUnit.MilliwattPerMillimeter);
        public LinearPowerDensity WattPerCentimeter => new LinearPowerDensity((double)value, LinearPowerDensityUnit.WattPerCentimeter);
        public LinearPowerDensity WattPerFoot => new LinearPowerDensity((double)value, LinearPowerDensityUnit.WattPerFoot);
        public LinearPowerDensity WattPerInch => new LinearPowerDensity((double)value, LinearPowerDensityUnit.WattPerInch);
        public LinearPowerDensity WattPerMeter => new LinearPowerDensity((double)value, LinearPowerDensityUnit.WattPerMeter);
        public LinearPowerDensity WattPerMillimeter => new LinearPowerDensity((double)value, LinearPowerDensityUnit.WattPerMillimeter);
    }
}