using EngineeringUnits;
using EngineeringUnits.Units;

namespace EngineeringUnits.NumberExtensions.NumberToForce;

// <auto-generated/>
// This file is auto-generated; changes will be overwritten.
public static class NumberToForceExtensions
{
    // double receiver
    extension(double value)
    {
        public Force Decanewton => new Force(value, ForceUnit.Decanewton);
        public Force Dyn => new Force(value, ForceUnit.Dyn);
        public Force KiloPond => new Force(value, ForceUnit.KiloPond);
        public Force KilogramForce => new Force(value, ForceUnit.KilogramForce);
        public Force Kilonewton => new Force(value, ForceUnit.Kilonewton);
        public Force KilopoundForce => new Force(value, ForceUnit.KilopoundForce);
        public Force Meganewton => new Force(value, ForceUnit.Meganewton);
        public Force MegapoundForce => new Force(value, ForceUnit.MegapoundForce);
        public Force Micronewton => new Force(value, ForceUnit.Micronewton);
        public Force Millinewton => new Force(value, ForceUnit.Millinewton);
        public Force Newton => new Force(value, ForceUnit.Newton);
        public Force OunceForce => new Force(value, ForceUnit.OunceForce);
        public Force PoundForce => new Force(value, ForceUnit.PoundForce);
        public Force Poundal => new Force(value, ForceUnit.Poundal);
        public Force ShortTonForce => new Force(value, ForceUnit.ShortTonForce);
        public Force TonneForce => new Force(value, ForceUnit.TonneForce);
    }

    // int receiver
    extension(int value)
    {
        public Force Decanewton => new Force(value, ForceUnit.Decanewton);
        public Force Dyn => new Force(value, ForceUnit.Dyn);
        public Force KiloPond => new Force(value, ForceUnit.KiloPond);
        public Force KilogramForce => new Force(value, ForceUnit.KilogramForce);
        public Force Kilonewton => new Force(value, ForceUnit.Kilonewton);
        public Force KilopoundForce => new Force(value, ForceUnit.KilopoundForce);
        public Force Meganewton => new Force(value, ForceUnit.Meganewton);
        public Force MegapoundForce => new Force(value, ForceUnit.MegapoundForce);
        public Force Micronewton => new Force(value, ForceUnit.Micronewton);
        public Force Millinewton => new Force(value, ForceUnit.Millinewton);
        public Force Newton => new Force(value, ForceUnit.Newton);
        public Force OunceForce => new Force(value, ForceUnit.OunceForce);
        public Force PoundForce => new Force(value, ForceUnit.PoundForce);
        public Force Poundal => new Force(value, ForceUnit.Poundal);
        public Force ShortTonForce => new Force(value, ForceUnit.ShortTonForce);
        public Force TonneForce => new Force(value, ForceUnit.TonneForce);
    }

    // decimal receiver (convert as needed)
    extension(decimal value)
    {
        public Force Decanewton => new Force((double)value, ForceUnit.Decanewton);
        public Force Dyn => new Force((double)value, ForceUnit.Dyn);
        public Force KiloPond => new Force((double)value, ForceUnit.KiloPond);
        public Force KilogramForce => new Force((double)value, ForceUnit.KilogramForce);
        public Force Kilonewton => new Force((double)value, ForceUnit.Kilonewton);
        public Force KilopoundForce => new Force((double)value, ForceUnit.KilopoundForce);
        public Force Meganewton => new Force((double)value, ForceUnit.Meganewton);
        public Force MegapoundForce => new Force((double)value, ForceUnit.MegapoundForce);
        public Force Micronewton => new Force((double)value, ForceUnit.Micronewton);
        public Force Millinewton => new Force((double)value, ForceUnit.Millinewton);
        public Force Newton => new Force((double)value, ForceUnit.Newton);
        public Force OunceForce => new Force((double)value, ForceUnit.OunceForce);
        public Force PoundForce => new Force((double)value, ForceUnit.PoundForce);
        public Force Poundal => new Force((double)value, ForceUnit.Poundal);
        public Force ShortTonForce => new Force((double)value, ForceUnit.ShortTonForce);
        public Force TonneForce => new Force((double)value, ForceUnit.TonneForce);
    }
}