using EngineeringUnits;
using EngineeringUnits.Units;

namespace EngineeringUnits.NumberExtensions.NumberToEntropy;

// <auto-generated/>
// This file is auto-generated; changes will be overwritten.
public static class NumberToEntropyExtensions
{
    // double receiver
    extension(double value)
    {
        public Entropy CaloriePerKelvin => new Entropy(value, EntropyUnit.CaloriePerKelvin);
        public Entropy JoulePerDegreeCelsius => new Entropy(value, EntropyUnit.JoulePerDegreeCelsius);
        public Entropy JoulePerKelvin => new Entropy(value, EntropyUnit.JoulePerKelvin);
        public Entropy KilocaloriePerKelvin => new Entropy(value, EntropyUnit.KilocaloriePerKelvin);
        public Entropy KilojoulePerDegreeCelsius => new Entropy(value, EntropyUnit.KilojoulePerDegreeCelsius);
        public Entropy KilojoulePerKelvin => new Entropy(value, EntropyUnit.KilojoulePerKelvin);
        public Entropy MegajoulePerKelvin => new Entropy(value, EntropyUnit.MegajoulePerKelvin);
    }

    // int receiver
    extension(int value)
    {
        public Entropy CaloriePerKelvin => new Entropy(value, EntropyUnit.CaloriePerKelvin);
        public Entropy JoulePerDegreeCelsius => new Entropy(value, EntropyUnit.JoulePerDegreeCelsius);
        public Entropy JoulePerKelvin => new Entropy(value, EntropyUnit.JoulePerKelvin);
        public Entropy KilocaloriePerKelvin => new Entropy(value, EntropyUnit.KilocaloriePerKelvin);
        public Entropy KilojoulePerDegreeCelsius => new Entropy(value, EntropyUnit.KilojoulePerDegreeCelsius);
        public Entropy KilojoulePerKelvin => new Entropy(value, EntropyUnit.KilojoulePerKelvin);
        public Entropy MegajoulePerKelvin => new Entropy(value, EntropyUnit.MegajoulePerKelvin);
    }

    // decimal receiver (convert as needed)
    extension(decimal value)
    {
        public Entropy CaloriePerKelvin => new Entropy((double)value, EntropyUnit.CaloriePerKelvin);
        public Entropy JoulePerDegreeCelsius => new Entropy((double)value, EntropyUnit.JoulePerDegreeCelsius);
        public Entropy JoulePerKelvin => new Entropy((double)value, EntropyUnit.JoulePerKelvin);
        public Entropy KilocaloriePerKelvin => new Entropy((double)value, EntropyUnit.KilocaloriePerKelvin);
        public Entropy KilojoulePerDegreeCelsius => new Entropy((double)value, EntropyUnit.KilojoulePerDegreeCelsius);
        public Entropy KilojoulePerKelvin => new Entropy((double)value, EntropyUnit.KilojoulePerKelvin);
        public Entropy MegajoulePerKelvin => new Entropy((double)value, EntropyUnit.MegajoulePerKelvin);
    }
}