using EngineeringUnits;
using EngineeringUnits.Units;

namespace EngineeringUnits.NumberExtensions.NumberToLuminousFlux;

// <auto-generated/>
// This file is auto-generated; changes will be overwritten.
public static class NumberToLuminousFluxExtensions
{
    // double receiver
    extension(double value)
    {
        public LuminousFlux Lumen => new LuminousFlux(value, LuminousFluxUnit.Lumen);
    }

    // int receiver
    extension(int value)
    {
        public LuminousFlux Lumen => new LuminousFlux(value, LuminousFluxUnit.Lumen);
    }

    // decimal receiver (convert as needed)
    extension(decimal value)
    {
        public LuminousFlux Lumen => new LuminousFlux((double)value, LuminousFluxUnit.Lumen);
    }
}