using EngineeringUnits;
using EngineeringUnits.Units;

namespace EngineeringUnits.NumberExtensions.NumberToPipeSize;

// <auto-generated/>
// This file is auto-generated; changes will be overwritten.
public static class NumberToPipeSizeExtensions
{
    // double receiver
    extension(double value)
    {
        public PipeSize DN => new PipeSize(value, PipeSizeUnit.DN);
    }

    // int receiver
    extension(int value)
    {
        public PipeSize DN => new PipeSize(value, PipeSizeUnit.DN);
    }

    // decimal receiver (convert as needed)
    extension(decimal value)
    {
        public PipeSize DN => new PipeSize((double)value, PipeSizeUnit.DN);
    }
}