using EngineeringUnits;
using EngineeringUnits.Units;

namespace EngineeringUnits.NumberExtensions.NumberToDuration;

// <auto-generated/>
// This file is auto-generated; changes will be overwritten.
public static class NumberToDurationExtensions
{
    // double receiver
    extension(double value)
    {
        public Duration Day => new Duration(value, DurationUnit.Day);
        public Duration Hour => new Duration(value, DurationUnit.Hour);
        public Duration Microsecond => new Duration(value, DurationUnit.Microsecond);
        public Duration Millisecond => new Duration(value, DurationUnit.Millisecond);
        public Duration Minute => new Duration(value, DurationUnit.Minute);
        public Duration Month30 => new Duration(value, DurationUnit.Month30);
        public Duration Nanosecond => new Duration(value, DurationUnit.Nanosecond);
        public Duration Second => new Duration(value, DurationUnit.Second);
        public Duration Week => new Duration(value, DurationUnit.Week);
        public Duration Year365 => new Duration(value, DurationUnit.Year365);
    }

    // int receiver
    extension(int value)
    {
        public Duration Day => new Duration(value, DurationUnit.Day);
        public Duration Hour => new Duration(value, DurationUnit.Hour);
        public Duration Microsecond => new Duration(value, DurationUnit.Microsecond);
        public Duration Millisecond => new Duration(value, DurationUnit.Millisecond);
        public Duration Minute => new Duration(value, DurationUnit.Minute);
        public Duration Month30 => new Duration(value, DurationUnit.Month30);
        public Duration Nanosecond => new Duration(value, DurationUnit.Nanosecond);
        public Duration Second => new Duration(value, DurationUnit.Second);
        public Duration Week => new Duration(value, DurationUnit.Week);
        public Duration Year365 => new Duration(value, DurationUnit.Year365);
    }

    // decimal receiver (convert as needed)
    extension(decimal value)
    {
        public Duration Day => new Duration((double)value, DurationUnit.Day);
        public Duration Hour => new Duration((double)value, DurationUnit.Hour);
        public Duration Microsecond => new Duration((double)value, DurationUnit.Microsecond);
        public Duration Millisecond => new Duration((double)value, DurationUnit.Millisecond);
        public Duration Minute => new Duration((double)value, DurationUnit.Minute);
        public Duration Month30 => new Duration((double)value, DurationUnit.Month30);
        public Duration Nanosecond => new Duration((double)value, DurationUnit.Nanosecond);
        public Duration Second => new Duration((double)value, DurationUnit.Second);
        public Duration Week => new Duration((double)value, DurationUnit.Week);
        public Duration Year365 => new Duration((double)value, DurationUnit.Year365);
    }
}