using EngineeringUnits;
using EngineeringUnits.Units;

namespace EngineeringUnits.NumberExtensions.NumberToPressureChangeRate;

// <auto-generated/>
// This file is auto-generated; changes will be overwritten.
public static class NumberToPressureChangeRateExtensions
{
    // double receiver
    extension(double value)
    {
        public PressureChangeRate AtmospherePerSecond => new PressureChangeRate(value, PressureChangeRateUnit.AtmospherePerSecond);
        public PressureChangeRate KilopascalPerMinute => new PressureChangeRate(value, PressureChangeRateUnit.KilopascalPerMinute);
        public PressureChangeRate KilopascalPerSecond => new PressureChangeRate(value, PressureChangeRateUnit.KilopascalPerSecond);
        public PressureChangeRate KilopoundForcePerSquareInchPerMinute => new PressureChangeRate(value, PressureChangeRateUnit.KilopoundForcePerSquareInchPerMinute);
        public PressureChangeRate KilopoundForcePerSquareInchPerSecond => new PressureChangeRate(value, PressureChangeRateUnit.KilopoundForcePerSquareInchPerSecond);
        public PressureChangeRate MegapascalPerMinute => new PressureChangeRate(value, PressureChangeRateUnit.MegapascalPerMinute);
        public PressureChangeRate MegapascalPerSecond => new PressureChangeRate(value, PressureChangeRateUnit.MegapascalPerSecond);
        public PressureChangeRate MegapoundForcePerSquareInchPerMinute => new PressureChangeRate(value, PressureChangeRateUnit.MegapoundForcePerSquareInchPerMinute);
        public PressureChangeRate MegapoundForcePerSquareInchPerSecond => new PressureChangeRate(value, PressureChangeRateUnit.MegapoundForcePerSquareInchPerSecond);
        public PressureChangeRate PascalPerMinute => new PressureChangeRate(value, PressureChangeRateUnit.PascalPerMinute);
        public PressureChangeRate PascalPerSecond => new PressureChangeRate(value, PressureChangeRateUnit.PascalPerSecond);
        public PressureChangeRate PoundForcePerSquareInchPerMinute => new PressureChangeRate(value, PressureChangeRateUnit.PoundForcePerSquareInchPerMinute);
        public PressureChangeRate PoundForcePerSquareInchPerSecond => new PressureChangeRate(value, PressureChangeRateUnit.PoundForcePerSquareInchPerSecond);
    }

    // int receiver
    extension(int value)
    {
        public PressureChangeRate AtmospherePerSecond => new PressureChangeRate(value, PressureChangeRateUnit.AtmospherePerSecond);
        public PressureChangeRate KilopascalPerMinute => new PressureChangeRate(value, PressureChangeRateUnit.KilopascalPerMinute);
        public PressureChangeRate KilopascalPerSecond => new PressureChangeRate(value, PressureChangeRateUnit.KilopascalPerSecond);
        public PressureChangeRate KilopoundForcePerSquareInchPerMinute => new PressureChangeRate(value, PressureChangeRateUnit.KilopoundForcePerSquareInchPerMinute);
        public PressureChangeRate KilopoundForcePerSquareInchPerSecond => new PressureChangeRate(value, PressureChangeRateUnit.KilopoundForcePerSquareInchPerSecond);
        public PressureChangeRate MegapascalPerMinute => new PressureChangeRate(value, PressureChangeRateUnit.MegapascalPerMinute);
        public PressureChangeRate MegapascalPerSecond => new PressureChangeRate(value, PressureChangeRateUnit.MegapascalPerSecond);
        public PressureChangeRate MegapoundForcePerSquareInchPerMinute => new PressureChangeRate(value, PressureChangeRateUnit.MegapoundForcePerSquareInchPerMinute);
        public PressureChangeRate MegapoundForcePerSquareInchPerSecond => new PressureChangeRate(value, PressureChangeRateUnit.MegapoundForcePerSquareInchPerSecond);
        public PressureChangeRate PascalPerMinute => new PressureChangeRate(value, PressureChangeRateUnit.PascalPerMinute);
        public PressureChangeRate PascalPerSecond => new PressureChangeRate(value, PressureChangeRateUnit.PascalPerSecond);
        public PressureChangeRate PoundForcePerSquareInchPerMinute => new PressureChangeRate(value, PressureChangeRateUnit.PoundForcePerSquareInchPerMinute);
        public PressureChangeRate PoundForcePerSquareInchPerSecond => new PressureChangeRate(value, PressureChangeRateUnit.PoundForcePerSquareInchPerSecond);
    }

    // decimal receiver (convert as needed)
    extension(decimal value)
    {
        public PressureChangeRate AtmospherePerSecond => new PressureChangeRate((double)value, PressureChangeRateUnit.AtmospherePerSecond);
        public PressureChangeRate KilopascalPerMinute => new PressureChangeRate((double)value, PressureChangeRateUnit.KilopascalPerMinute);
        public PressureChangeRate KilopascalPerSecond => new PressureChangeRate((double)value, PressureChangeRateUnit.KilopascalPerSecond);
        public PressureChangeRate KilopoundForcePerSquareInchPerMinute => new PressureChangeRate((double)value, PressureChangeRateUnit.KilopoundForcePerSquareInchPerMinute);
        public PressureChangeRate KilopoundForcePerSquareInchPerSecond => new PressureChangeRate((double)value, PressureChangeRateUnit.KilopoundForcePerSquareInchPerSecond);
        public PressureChangeRate MegapascalPerMinute => new PressureChangeRate((double)value, PressureChangeRateUnit.MegapascalPerMinute);
        public PressureChangeRate MegapascalPerSecond => new PressureChangeRate((double)value, PressureChangeRateUnit.MegapascalPerSecond);
        public PressureChangeRate MegapoundForcePerSquareInchPerMinute => new PressureChangeRate((double)value, PressureChangeRateUnit.MegapoundForcePerSquareInchPerMinute);
        public PressureChangeRate MegapoundForcePerSquareInchPerSecond => new PressureChangeRate((double)value, PressureChangeRateUnit.MegapoundForcePerSquareInchPerSecond);
        public PressureChangeRate PascalPerMinute => new PressureChangeRate((double)value, PressureChangeRateUnit.PascalPerMinute);
        public PressureChangeRate PascalPerSecond => new PressureChangeRate((double)value, PressureChangeRateUnit.PascalPerSecond);
        public PressureChangeRate PoundForcePerSquareInchPerMinute => new PressureChangeRate((double)value, PressureChangeRateUnit.PoundForcePerSquareInchPerMinute);
        public PressureChangeRate PoundForcePerSquareInchPerSecond => new PressureChangeRate((double)value, PressureChangeRateUnit.PoundForcePerSquareInchPerSecond);
    }
}