using EngineeringUnits;
using EngineeringUnits.Units;

namespace EngineeringUnits.NumberExtensions.NumberToThermalResistance;

// <auto-generated/>
// This file is auto-generated; changes will be overwritten.
public static class NumberToThermalResistanceExtensions
{
    // double receiver
    extension(double value)
    {
        public ThermalResistance HourSquareFeetDegreeFahrenheitPerBtu => new ThermalResistance(value, ThermalResistanceUnit.HourSquareFeetDegreeFahrenheitPerBtu);
        public ThermalResistance SquareCentimeterHourDegreeCelsiusPerKilocalorie => new ThermalResistance(value, ThermalResistanceUnit.SquareCentimeterHourDegreeCelsiusPerKilocalorie);
        public ThermalResistance SquareCentimeterKelvinPerWatt => new ThermalResistance(value, ThermalResistanceUnit.SquareCentimeterKelvinPerWatt);
        public ThermalResistance SquareMeterDegreeCelsiusPerWatt => new ThermalResistance(value, ThermalResistanceUnit.SquareMeterDegreeCelsiusPerWatt);
        public ThermalResistance SquareMeterKelvinPerKilowatt => new ThermalResistance(value, ThermalResistanceUnit.SquareMeterKelvinPerKilowatt);
    }

    // int receiver
    extension(int value)
    {
        public ThermalResistance HourSquareFeetDegreeFahrenheitPerBtu => new ThermalResistance(value, ThermalResistanceUnit.HourSquareFeetDegreeFahrenheitPerBtu);
        public ThermalResistance SquareCentimeterHourDegreeCelsiusPerKilocalorie => new ThermalResistance(value, ThermalResistanceUnit.SquareCentimeterHourDegreeCelsiusPerKilocalorie);
        public ThermalResistance SquareCentimeterKelvinPerWatt => new ThermalResistance(value, ThermalResistanceUnit.SquareCentimeterKelvinPerWatt);
        public ThermalResistance SquareMeterDegreeCelsiusPerWatt => new ThermalResistance(value, ThermalResistanceUnit.SquareMeterDegreeCelsiusPerWatt);
        public ThermalResistance SquareMeterKelvinPerKilowatt => new ThermalResistance(value, ThermalResistanceUnit.SquareMeterKelvinPerKilowatt);
    }

    // decimal receiver (convert as needed)
    extension(decimal value)
    {
        public ThermalResistance HourSquareFeetDegreeFahrenheitPerBtu => new ThermalResistance((double)value, ThermalResistanceUnit.HourSquareFeetDegreeFahrenheitPerBtu);
        public ThermalResistance SquareCentimeterHourDegreeCelsiusPerKilocalorie => new ThermalResistance((double)value, ThermalResistanceUnit.SquareCentimeterHourDegreeCelsiusPerKilocalorie);
        public ThermalResistance SquareCentimeterKelvinPerWatt => new ThermalResistance((double)value, ThermalResistanceUnit.SquareCentimeterKelvinPerWatt);
        public ThermalResistance SquareMeterDegreeCelsiusPerWatt => new ThermalResistance((double)value, ThermalResistanceUnit.SquareMeterDegreeCelsiusPerWatt);
        public ThermalResistance SquareMeterKelvinPerKilowatt => new ThermalResistance((double)value, ThermalResistanceUnit.SquareMeterKelvinPerKilowatt);
    }
}