using EngineeringUnits;
using EngineeringUnits.Units;

namespace EngineeringUnits.NumberExtensions.NumberToVolumePerLength;

// <auto-generated/>
// This file is auto-generated; changes will be overwritten.
public static class NumberToVolumePerLengthExtensions
{
    // double receiver
    extension(double value)
    {
        public VolumePerLength CubicMeterPerMeter => new VolumePerLength(value, VolumePerLengthUnit.CubicMeterPerMeter);
        public VolumePerLength CubicYardPerFoot => new VolumePerLength(value, VolumePerLengthUnit.CubicYardPerFoot);
        public VolumePerLength CubicYardPerUsSurveyFoot => new VolumePerLength(value, VolumePerLengthUnit.CubicYardPerUsSurveyFoot);
        public VolumePerLength LiterPerKilometer => new VolumePerLength(value, VolumePerLengthUnit.LiterPerKilometer);
        public VolumePerLength LiterPerMeter => new VolumePerLength(value, VolumePerLengthUnit.LiterPerMeter);
        public VolumePerLength LiterPerMillimeter => new VolumePerLength(value, VolumePerLengthUnit.LiterPerMillimeter);
        public VolumePerLength OilBarrelPerFoot => new VolumePerLength(value, VolumePerLengthUnit.OilBarrelPerFoot);
    }

    // int receiver
    extension(int value)
    {
        public VolumePerLength CubicMeterPerMeter => new VolumePerLength(value, VolumePerLengthUnit.CubicMeterPerMeter);
        public VolumePerLength CubicYardPerFoot => new VolumePerLength(value, VolumePerLengthUnit.CubicYardPerFoot);
        public VolumePerLength CubicYardPerUsSurveyFoot => new VolumePerLength(value, VolumePerLengthUnit.CubicYardPerUsSurveyFoot);
        public VolumePerLength LiterPerKilometer => new VolumePerLength(value, VolumePerLengthUnit.LiterPerKilometer);
        public VolumePerLength LiterPerMeter => new VolumePerLength(value, VolumePerLengthUnit.LiterPerMeter);
        public VolumePerLength LiterPerMillimeter => new VolumePerLength(value, VolumePerLengthUnit.LiterPerMillimeter);
        public VolumePerLength OilBarrelPerFoot => new VolumePerLength(value, VolumePerLengthUnit.OilBarrelPerFoot);
    }

    // decimal receiver (convert as needed)
    extension(decimal value)
    {
        public VolumePerLength CubicMeterPerMeter => new VolumePerLength((double)value, VolumePerLengthUnit.CubicMeterPerMeter);
        public VolumePerLength CubicYardPerFoot => new VolumePerLength((double)value, VolumePerLengthUnit.CubicYardPerFoot);
        public VolumePerLength CubicYardPerUsSurveyFoot => new VolumePerLength((double)value, VolumePerLengthUnit.CubicYardPerUsSurveyFoot);
        public VolumePerLength LiterPerKilometer => new VolumePerLength((double)value, VolumePerLengthUnit.LiterPerKilometer);
        public VolumePerLength LiterPerMeter => new VolumePerLength((double)value, VolumePerLengthUnit.LiterPerMeter);
        public VolumePerLength LiterPerMillimeter => new VolumePerLength((double)value, VolumePerLengthUnit.LiterPerMillimeter);
        public VolumePerLength OilBarrelPerFoot => new VolumePerLength((double)value, VolumePerLengthUnit.OilBarrelPerFoot);
    }
}