using EngineeringUnits;
using EngineeringUnits.Units;

namespace EngineeringUnits.NumberExtensions.NumberToMolarMass;

// <auto-generated/>
// This file is auto-generated; changes will be overwritten.
public static class NumberToMolarMassExtensions
{
    // double receiver
    extension(double value)
    {
        public MolarMass CentigramPerMole => new MolarMass(value, MolarMassUnit.CentigramPerMole);
        public MolarMass DecagramPerMole => new MolarMass(value, MolarMassUnit.DecagramPerMole);
        public MolarMass DecigramPerMole => new MolarMass(value, MolarMassUnit.DecigramPerMole);
        public MolarMass GramPerMole => new MolarMass(value, MolarMassUnit.GramPerMole);
        public MolarMass HectogramPerMole => new MolarMass(value, MolarMassUnit.HectogramPerMole);
        public MolarMass KilogramPerMole => new MolarMass(value, MolarMassUnit.KilogramPerMole);
        public MolarMass KilopoundPerMole => new MolarMass(value, MolarMassUnit.KilopoundPerMole);
        public MolarMass MegapoundPerMole => new MolarMass(value, MolarMassUnit.MegapoundPerMole);
        public MolarMass MicrogramPerMole => new MolarMass(value, MolarMassUnit.MicrogramPerMole);
        public MolarMass MilligramPerMole => new MolarMass(value, MolarMassUnit.MilligramPerMole);
        public MolarMass NanogramPerMole => new MolarMass(value, MolarMassUnit.NanogramPerMole);
        public MolarMass PoundPerMole => new MolarMass(value, MolarMassUnit.PoundPerMole);
    }

    // int receiver
    extension(int value)
    {
        public MolarMass CentigramPerMole => new MolarMass(value, MolarMassUnit.CentigramPerMole);
        public MolarMass DecagramPerMole => new MolarMass(value, MolarMassUnit.DecagramPerMole);
        public MolarMass DecigramPerMole => new MolarMass(value, MolarMassUnit.DecigramPerMole);
        public MolarMass GramPerMole => new MolarMass(value, MolarMassUnit.GramPerMole);
        public MolarMass HectogramPerMole => new MolarMass(value, MolarMassUnit.HectogramPerMole);
        public MolarMass KilogramPerMole => new MolarMass(value, MolarMassUnit.KilogramPerMole);
        public MolarMass KilopoundPerMole => new MolarMass(value, MolarMassUnit.KilopoundPerMole);
        public MolarMass MegapoundPerMole => new MolarMass(value, MolarMassUnit.MegapoundPerMole);
        public MolarMass MicrogramPerMole => new MolarMass(value, MolarMassUnit.MicrogramPerMole);
        public MolarMass MilligramPerMole => new MolarMass(value, MolarMassUnit.MilligramPerMole);
        public MolarMass NanogramPerMole => new MolarMass(value, MolarMassUnit.NanogramPerMole);
        public MolarMass PoundPerMole => new MolarMass(value, MolarMassUnit.PoundPerMole);
    }

    // decimal receiver (convert as needed)
    extension(decimal value)
    {
        public MolarMass CentigramPerMole => new MolarMass((double)value, MolarMassUnit.CentigramPerMole);
        public MolarMass DecagramPerMole => new MolarMass((double)value, MolarMassUnit.DecagramPerMole);
        public MolarMass DecigramPerMole => new MolarMass((double)value, MolarMassUnit.DecigramPerMole);
        public MolarMass GramPerMole => new MolarMass((double)value, MolarMassUnit.GramPerMole);
        public MolarMass HectogramPerMole => new MolarMass((double)value, MolarMassUnit.HectogramPerMole);
        public MolarMass KilogramPerMole => new MolarMass((double)value, MolarMassUnit.KilogramPerMole);
        public MolarMass KilopoundPerMole => new MolarMass((double)value, MolarMassUnit.KilopoundPerMole);
        public MolarMass MegapoundPerMole => new MolarMass((double)value, MolarMassUnit.MegapoundPerMole);
        public MolarMass MicrogramPerMole => new MolarMass((double)value, MolarMassUnit.MicrogramPerMole);
        public MolarMass MilligramPerMole => new MolarMass((double)value, MolarMassUnit.MilligramPerMole);
        public MolarMass NanogramPerMole => new MolarMass((double)value, MolarMassUnit.NanogramPerMole);
        public MolarMass PoundPerMole => new MolarMass((double)value, MolarMassUnit.PoundPerMole);
    }
}