using EngineeringUnits;
using EngineeringUnits.Units;

namespace EngineeringUnits.NumberExtensions.NumberToIrradiation;

// <auto-generated/>
// This file is auto-generated; changes will be overwritten.
public static class NumberToIrradiationExtensions
{
    // double receiver
    extension(double value)
    {
        public Irradiation JoulePerSquareCentimeter => new Irradiation(value, IrradiationUnit.JoulePerSquareCentimeter);
        public Irradiation JoulePerSquareMeter => new Irradiation(value, IrradiationUnit.JoulePerSquareMeter);
        public Irradiation JoulePerSquareMillimeter => new Irradiation(value, IrradiationUnit.JoulePerSquareMillimeter);
        public Irradiation KilojoulePerSquareMeter => new Irradiation(value, IrradiationUnit.KilojoulePerSquareMeter);
        public Irradiation KilowattHourPerSquareMeter => new Irradiation(value, IrradiationUnit.KilowattHourPerSquareMeter);
        public Irradiation MillijoulePerSquareCentimeter => new Irradiation(value, IrradiationUnit.MillijoulePerSquareCentimeter);
        public Irradiation WattHourPerSquareMeter => new Irradiation(value, IrradiationUnit.WattHourPerSquareMeter);
    }

    // int receiver
    extension(int value)
    {
        public Irradiation JoulePerSquareCentimeter => new Irradiation(value, IrradiationUnit.JoulePerSquareCentimeter);
        public Irradiation JoulePerSquareMeter => new Irradiation(value, IrradiationUnit.JoulePerSquareMeter);
        public Irradiation JoulePerSquareMillimeter => new Irradiation(value, IrradiationUnit.JoulePerSquareMillimeter);
        public Irradiation KilojoulePerSquareMeter => new Irradiation(value, IrradiationUnit.KilojoulePerSquareMeter);
        public Irradiation KilowattHourPerSquareMeter => new Irradiation(value, IrradiationUnit.KilowattHourPerSquareMeter);
        public Irradiation MillijoulePerSquareCentimeter => new Irradiation(value, IrradiationUnit.MillijoulePerSquareCentimeter);
        public Irradiation WattHourPerSquareMeter => new Irradiation(value, IrradiationUnit.WattHourPerSquareMeter);
    }

    // decimal receiver (convert as needed)
    extension(decimal value)
    {
        public Irradiation JoulePerSquareCentimeter => new Irradiation((double)value, IrradiationUnit.JoulePerSquareCentimeter);
        public Irradiation JoulePerSquareMeter => new Irradiation((double)value, IrradiationUnit.JoulePerSquareMeter);
        public Irradiation JoulePerSquareMillimeter => new Irradiation((double)value, IrradiationUnit.JoulePerSquareMillimeter);
        public Irradiation KilojoulePerSquareMeter => new Irradiation((double)value, IrradiationUnit.KilojoulePerSquareMeter);
        public Irradiation KilowattHourPerSquareMeter => new Irradiation((double)value, IrradiationUnit.KilowattHourPerSquareMeter);
        public Irradiation MillijoulePerSquareCentimeter => new Irradiation((double)value, IrradiationUnit.MillijoulePerSquareCentimeter);
        public Irradiation WattHourPerSquareMeter => new Irradiation((double)value, IrradiationUnit.WattHourPerSquareMeter);
    }
}