using EngineeringUnits;
using EngineeringUnits.Units;

namespace EngineeringUnits.NumberExtensions.NumberToSnap;

// <auto-generated/>
// This file is auto-generated; changes will be overwritten.
public static class NumberToSnapExtensions
{
    // double receiver
    extension(double value)
    {
        public Snap CentimeterPerSecond4 => new Snap(value, SnapUnit.CentimeterPerSecond4);
        public Snap DecimeterPerSecond4 => new Snap(value, SnapUnit.DecimeterPerSecond4);
        public Snap KilometerPerSecond4 => new Snap(value, SnapUnit.KilometerPerSecond4);
        public Snap MeterPerSecond4 => new Snap(value, SnapUnit.MeterPerSecond4);
        public Snap MicrometerPerSecond4 => new Snap(value, SnapUnit.MicrometerPerSecond4);
        public Snap MillimeterPerSecond4 => new Snap(value, SnapUnit.MillimeterPerSecond4);
        public Snap NanometerPerSecond4 => new Snap(value, SnapUnit.NanometerPerSecond4);
    }

    // int receiver
    extension(int value)
    {
        public Snap CentimeterPerSecond4 => new Snap(value, SnapUnit.CentimeterPerSecond4);
        public Snap DecimeterPerSecond4 => new Snap(value, SnapUnit.DecimeterPerSecond4);
        public Snap KilometerPerSecond4 => new Snap(value, SnapUnit.KilometerPerSecond4);
        public Snap MeterPerSecond4 => new Snap(value, SnapUnit.MeterPerSecond4);
        public Snap MicrometerPerSecond4 => new Snap(value, SnapUnit.MicrometerPerSecond4);
        public Snap MillimeterPerSecond4 => new Snap(value, SnapUnit.MillimeterPerSecond4);
        public Snap NanometerPerSecond4 => new Snap(value, SnapUnit.NanometerPerSecond4);
    }

    // decimal receiver (convert as needed)
    extension(decimal value)
    {
        public Snap CentimeterPerSecond4 => new Snap((double)value, SnapUnit.CentimeterPerSecond4);
        public Snap DecimeterPerSecond4 => new Snap((double)value, SnapUnit.DecimeterPerSecond4);
        public Snap KilometerPerSecond4 => new Snap((double)value, SnapUnit.KilometerPerSecond4);
        public Snap MeterPerSecond4 => new Snap((double)value, SnapUnit.MeterPerSecond4);
        public Snap MicrometerPerSecond4 => new Snap((double)value, SnapUnit.MicrometerPerSecond4);
        public Snap MillimeterPerSecond4 => new Snap((double)value, SnapUnit.MillimeterPerSecond4);
        public Snap NanometerPerSecond4 => new Snap((double)value, SnapUnit.NanometerPerSecond4);
    }
}