using EngineeringUnits;
using EngineeringUnits.Units;

namespace EngineeringUnits.NumberExtensions.NumberToTemperatureChangeRate;

// <auto-generated/>
// This file is auto-generated; changes will be overwritten.
public static class NumberToTemperatureChangeRateExtensions
{
    // double receiver
    extension(double value)
    {
        public TemperatureChangeRate CentidegreeCelsiusPerSecond => new TemperatureChangeRate(value, TemperatureChangeRateUnit.CentidegreeCelsiusPerSecond);
        public TemperatureChangeRate DecadegreeCelsiusPerSecond => new TemperatureChangeRate(value, TemperatureChangeRateUnit.DecadegreeCelsiusPerSecond);
        public TemperatureChangeRate DecidegreeCelsiusPerSecond => new TemperatureChangeRate(value, TemperatureChangeRateUnit.DecidegreeCelsiusPerSecond);
        public TemperatureChangeRate DegreeCelsiusPerMinute => new TemperatureChangeRate(value, TemperatureChangeRateUnit.DegreeCelsiusPerMinute);
        public TemperatureChangeRate DegreeCelsiusPerSecond => new TemperatureChangeRate(value, TemperatureChangeRateUnit.DegreeCelsiusPerSecond);
        public TemperatureChangeRate HectodegreeCelsiusPerSecond => new TemperatureChangeRate(value, TemperatureChangeRateUnit.HectodegreeCelsiusPerSecond);
        public TemperatureChangeRate KilodegreeCelsiusPerSecond => new TemperatureChangeRate(value, TemperatureChangeRateUnit.KilodegreeCelsiusPerSecond);
        public TemperatureChangeRate MicrodegreeCelsiusPerSecond => new TemperatureChangeRate(value, TemperatureChangeRateUnit.MicrodegreeCelsiusPerSecond);
        public TemperatureChangeRate MillidegreeCelsiusPerSecond => new TemperatureChangeRate(value, TemperatureChangeRateUnit.MillidegreeCelsiusPerSecond);
        public TemperatureChangeRate NanodegreeCelsiusPerSecond => new TemperatureChangeRate(value, TemperatureChangeRateUnit.NanodegreeCelsiusPerSecond);
    }

    // int receiver
    extension(int value)
    {
        public TemperatureChangeRate CentidegreeCelsiusPerSecond => new TemperatureChangeRate(value, TemperatureChangeRateUnit.CentidegreeCelsiusPerSecond);
        public TemperatureChangeRate DecadegreeCelsiusPerSecond => new TemperatureChangeRate(value, TemperatureChangeRateUnit.DecadegreeCelsiusPerSecond);
        public TemperatureChangeRate DecidegreeCelsiusPerSecond => new TemperatureChangeRate(value, TemperatureChangeRateUnit.DecidegreeCelsiusPerSecond);
        public TemperatureChangeRate DegreeCelsiusPerMinute => new TemperatureChangeRate(value, TemperatureChangeRateUnit.DegreeCelsiusPerMinute);
        public TemperatureChangeRate DegreeCelsiusPerSecond => new TemperatureChangeRate(value, TemperatureChangeRateUnit.DegreeCelsiusPerSecond);
        public TemperatureChangeRate HectodegreeCelsiusPerSecond => new TemperatureChangeRate(value, TemperatureChangeRateUnit.HectodegreeCelsiusPerSecond);
        public TemperatureChangeRate KilodegreeCelsiusPerSecond => new TemperatureChangeRate(value, TemperatureChangeRateUnit.KilodegreeCelsiusPerSecond);
        public TemperatureChangeRate MicrodegreeCelsiusPerSecond => new TemperatureChangeRate(value, TemperatureChangeRateUnit.MicrodegreeCelsiusPerSecond);
        public TemperatureChangeRate MillidegreeCelsiusPerSecond => new TemperatureChangeRate(value, TemperatureChangeRateUnit.MillidegreeCelsiusPerSecond);
        public TemperatureChangeRate NanodegreeCelsiusPerSecond => new TemperatureChangeRate(value, TemperatureChangeRateUnit.NanodegreeCelsiusPerSecond);
    }

    // decimal receiver (convert as needed)
    extension(decimal value)
    {
        public TemperatureChangeRate CentidegreeCelsiusPerSecond => new TemperatureChangeRate((double)value, TemperatureChangeRateUnit.CentidegreeCelsiusPerSecond);
        public TemperatureChangeRate DecadegreeCelsiusPerSecond => new TemperatureChangeRate((double)value, TemperatureChangeRateUnit.DecadegreeCelsiusPerSecond);
        public TemperatureChangeRate DecidegreeCelsiusPerSecond => new TemperatureChangeRate((double)value, TemperatureChangeRateUnit.DecidegreeCelsiusPerSecond);
        public TemperatureChangeRate DegreeCelsiusPerMinute => new TemperatureChangeRate((double)value, TemperatureChangeRateUnit.DegreeCelsiusPerMinute);
        public TemperatureChangeRate DegreeCelsiusPerSecond => new TemperatureChangeRate((double)value, TemperatureChangeRateUnit.DegreeCelsiusPerSecond);
        public TemperatureChangeRate HectodegreeCelsiusPerSecond => new TemperatureChangeRate((double)value, TemperatureChangeRateUnit.HectodegreeCelsiusPerSecond);
        public TemperatureChangeRate KilodegreeCelsiusPerSecond => new TemperatureChangeRate((double)value, TemperatureChangeRateUnit.KilodegreeCelsiusPerSecond);
        public TemperatureChangeRate MicrodegreeCelsiusPerSecond => new TemperatureChangeRate((double)value, TemperatureChangeRateUnit.MicrodegreeCelsiusPerSecond);
        public TemperatureChangeRate MillidegreeCelsiusPerSecond => new TemperatureChangeRate((double)value, TemperatureChangeRateUnit.MillidegreeCelsiusPerSecond);
        public TemperatureChangeRate NanodegreeCelsiusPerSecond => new TemperatureChangeRate((double)value, TemperatureChangeRateUnit.NanodegreeCelsiusPerSecond);
    }
}