using EngineeringUnits;
using EngineeringUnits.Units;

namespace EngineeringUnits.NumberExtensions.NumberToVolumeFlow;

// <auto-generated/>
// This file is auto-generated; changes will be overwritten.
public static class NumberToVolumeFlowExtensions
{
    // double receiver
    extension(double value)
    {
        public VolumeFlow AcreFootPerDay => new VolumeFlow(value, VolumeFlowUnit.AcreFootPerDay);
        public VolumeFlow AcreFootPerHour => new VolumeFlow(value, VolumeFlowUnit.AcreFootPerHour);
        public VolumeFlow AcreFootPerMinute => new VolumeFlow(value, VolumeFlowUnit.AcreFootPerMinute);
        public VolumeFlow AcreFootPerSecond => new VolumeFlow(value, VolumeFlowUnit.AcreFootPerSecond);
        public VolumeFlow CentiliterPerDay => new VolumeFlow(value, VolumeFlowUnit.CentiliterPerDay);
        public VolumeFlow CentiliterPerMinute => new VolumeFlow(value, VolumeFlowUnit.CentiliterPerMinute);
        public VolumeFlow CentiliterPerSecond => new VolumeFlow(value, VolumeFlowUnit.CentiliterPerSecond);
        public VolumeFlow CubicCentimeterPerMinute => new VolumeFlow(value, VolumeFlowUnit.CubicCentimeterPerMinute);
        public VolumeFlow CubicDecimeterPerMinute => new VolumeFlow(value, VolumeFlowUnit.CubicDecimeterPerMinute);
        public VolumeFlow CubicFootPerHour => new VolumeFlow(value, VolumeFlowUnit.CubicFootPerHour);
        public VolumeFlow CubicFootPerMinute => new VolumeFlow(value, VolumeFlowUnit.CubicFootPerMinute);
        public VolumeFlow CubicFootPerSecond => new VolumeFlow(value, VolumeFlowUnit.CubicFootPerSecond);
        public VolumeFlow CubicMeterPerDay => new VolumeFlow(value, VolumeFlowUnit.CubicMeterPerDay);
        public VolumeFlow CubicMeterPerHour => new VolumeFlow(value, VolumeFlowUnit.CubicMeterPerHour);
        public VolumeFlow CubicMeterPerMinute => new VolumeFlow(value, VolumeFlowUnit.CubicMeterPerMinute);
        public VolumeFlow CubicMeterPerSecond => new VolumeFlow(value, VolumeFlowUnit.CubicMeterPerSecond);
        public VolumeFlow CubicMillimeterPerSecond => new VolumeFlow(value, VolumeFlowUnit.CubicMillimeterPerSecond);
        public VolumeFlow CubicYardPerDay => new VolumeFlow(value, VolumeFlowUnit.CubicYardPerDay);
        public VolumeFlow CubicYardPerHour => new VolumeFlow(value, VolumeFlowUnit.CubicYardPerHour);
        public VolumeFlow CubicYardPerMinute => new VolumeFlow(value, VolumeFlowUnit.CubicYardPerMinute);
        public VolumeFlow CubicYardPerSecond => new VolumeFlow(value, VolumeFlowUnit.CubicYardPerSecond);
        public VolumeFlow DeciliterPerDay => new VolumeFlow(value, VolumeFlowUnit.DeciliterPerDay);
        public VolumeFlow DeciliterPerMinute => new VolumeFlow(value, VolumeFlowUnit.DeciliterPerMinute);
        public VolumeFlow DeciliterPerSecond => new VolumeFlow(value, VolumeFlowUnit.DeciliterPerSecond);
        public VolumeFlow KiloliterPerDay => new VolumeFlow(value, VolumeFlowUnit.KiloliterPerDay);
        public VolumeFlow KiloliterPerMinute => new VolumeFlow(value, VolumeFlowUnit.KiloliterPerMinute);
        public VolumeFlow KiloliterPerSecond => new VolumeFlow(value, VolumeFlowUnit.KiloliterPerSecond);
        public VolumeFlow KilousGallonPerMinute => new VolumeFlow(value, VolumeFlowUnit.KilousGallonPerMinute);
        public VolumeFlow LiterPerDay => new VolumeFlow(value, VolumeFlowUnit.LiterPerDay);
        public VolumeFlow LiterPerHour => new VolumeFlow(value, VolumeFlowUnit.LiterPerHour);
        public VolumeFlow LiterPerMinute => new VolumeFlow(value, VolumeFlowUnit.LiterPerMinute);
        public VolumeFlow LiterPerSecond => new VolumeFlow(value, VolumeFlowUnit.LiterPerSecond);
        public VolumeFlow MegaliterPerDay => new VolumeFlow(value, VolumeFlowUnit.MegaliterPerDay);
        public VolumeFlow MegaukGallonPerSecond => new VolumeFlow(value, VolumeFlowUnit.MegaukGallonPerSecond);
        public VolumeFlow MicroliterPerDay => new VolumeFlow(value, VolumeFlowUnit.MicroliterPerDay);
        public VolumeFlow MicroliterPerMinute => new VolumeFlow(value, VolumeFlowUnit.MicroliterPerMinute);
        public VolumeFlow MicroliterPerSecond => new VolumeFlow(value, VolumeFlowUnit.MicroliterPerSecond);
        public VolumeFlow MilliliterPerDay => new VolumeFlow(value, VolumeFlowUnit.MilliliterPerDay);
        public VolumeFlow MilliliterPerMinute => new VolumeFlow(value, VolumeFlowUnit.MilliliterPerMinute);
        public VolumeFlow MilliliterPerSecond => new VolumeFlow(value, VolumeFlowUnit.MilliliterPerSecond);
        public VolumeFlow MillionUsGallonsPerDay => new VolumeFlow(value, VolumeFlowUnit.MillionUsGallonsPerDay);
        public VolumeFlow NanoliterPerDay => new VolumeFlow(value, VolumeFlowUnit.NanoliterPerDay);
        public VolumeFlow NanoliterPerMinute => new VolumeFlow(value, VolumeFlowUnit.NanoliterPerMinute);
        public VolumeFlow NanoliterPerSecond => new VolumeFlow(value, VolumeFlowUnit.NanoliterPerSecond);
        public VolumeFlow OilBarrelPerDay => new VolumeFlow(value, VolumeFlowUnit.OilBarrelPerDay);
        public VolumeFlow OilBarrelPerHour => new VolumeFlow(value, VolumeFlowUnit.OilBarrelPerHour);
        public VolumeFlow OilBarrelPerMinute => new VolumeFlow(value, VolumeFlowUnit.OilBarrelPerMinute);
        public VolumeFlow OilBarrelPerSecond => new VolumeFlow(value, VolumeFlowUnit.OilBarrelPerSecond);
        public VolumeFlow UkGallonPerDay => new VolumeFlow(value, VolumeFlowUnit.UkGallonPerDay);
        public VolumeFlow UkGallonPerHour => new VolumeFlow(value, VolumeFlowUnit.UkGallonPerHour);
        public VolumeFlow UkGallonPerMinute => new VolumeFlow(value, VolumeFlowUnit.UkGallonPerMinute);
        public VolumeFlow UkGallonPerSecond => new VolumeFlow(value, VolumeFlowUnit.UkGallonPerSecond);
        public VolumeFlow UsGallonPerDay => new VolumeFlow(value, VolumeFlowUnit.UsGallonPerDay);
        public VolumeFlow UsGallonPerHour => new VolumeFlow(value, VolumeFlowUnit.UsGallonPerHour);
        public VolumeFlow UsGallonPerMinute => new VolumeFlow(value, VolumeFlowUnit.UsGallonPerMinute);
        public VolumeFlow UsGallonPerSecond => new VolumeFlow(value, VolumeFlowUnit.UsGallonPerSecond);
    }

    // int receiver
    extension(int value)
    {
        public VolumeFlow AcreFootPerDay => new VolumeFlow(value, VolumeFlowUnit.AcreFootPerDay);
        public VolumeFlow AcreFootPerHour => new VolumeFlow(value, VolumeFlowUnit.AcreFootPerHour);
        public VolumeFlow AcreFootPerMinute => new VolumeFlow(value, VolumeFlowUnit.AcreFootPerMinute);
        public VolumeFlow AcreFootPerSecond => new VolumeFlow(value, VolumeFlowUnit.AcreFootPerSecond);
        public VolumeFlow CentiliterPerDay => new VolumeFlow(value, VolumeFlowUnit.CentiliterPerDay);
        public VolumeFlow CentiliterPerMinute => new VolumeFlow(value, VolumeFlowUnit.CentiliterPerMinute);
        public VolumeFlow CentiliterPerSecond => new VolumeFlow(value, VolumeFlowUnit.CentiliterPerSecond);
        public VolumeFlow CubicCentimeterPerMinute => new VolumeFlow(value, VolumeFlowUnit.CubicCentimeterPerMinute);
        public VolumeFlow CubicDecimeterPerMinute => new VolumeFlow(value, VolumeFlowUnit.CubicDecimeterPerMinute);
        public VolumeFlow CubicFootPerHour => new VolumeFlow(value, VolumeFlowUnit.CubicFootPerHour);
        public VolumeFlow CubicFootPerMinute => new VolumeFlow(value, VolumeFlowUnit.CubicFootPerMinute);
        public VolumeFlow CubicFootPerSecond => new VolumeFlow(value, VolumeFlowUnit.CubicFootPerSecond);
        public VolumeFlow CubicMeterPerDay => new VolumeFlow(value, VolumeFlowUnit.CubicMeterPerDay);
        public VolumeFlow CubicMeterPerHour => new VolumeFlow(value, VolumeFlowUnit.CubicMeterPerHour);
        public VolumeFlow CubicMeterPerMinute => new VolumeFlow(value, VolumeFlowUnit.CubicMeterPerMinute);
        public VolumeFlow CubicMeterPerSecond => new VolumeFlow(value, VolumeFlowUnit.CubicMeterPerSecond);
        public VolumeFlow CubicMillimeterPerSecond => new VolumeFlow(value, VolumeFlowUnit.CubicMillimeterPerSecond);
        public VolumeFlow CubicYardPerDay => new VolumeFlow(value, VolumeFlowUnit.CubicYardPerDay);
        public VolumeFlow CubicYardPerHour => new VolumeFlow(value, VolumeFlowUnit.CubicYardPerHour);
        public VolumeFlow CubicYardPerMinute => new VolumeFlow(value, VolumeFlowUnit.CubicYardPerMinute);
        public VolumeFlow CubicYardPerSecond => new VolumeFlow(value, VolumeFlowUnit.CubicYardPerSecond);
        public VolumeFlow DeciliterPerDay => new VolumeFlow(value, VolumeFlowUnit.DeciliterPerDay);
        public VolumeFlow DeciliterPerMinute => new VolumeFlow(value, VolumeFlowUnit.DeciliterPerMinute);
        public VolumeFlow DeciliterPerSecond => new VolumeFlow(value, VolumeFlowUnit.DeciliterPerSecond);
        public VolumeFlow KiloliterPerDay => new VolumeFlow(value, VolumeFlowUnit.KiloliterPerDay);
        public VolumeFlow KiloliterPerMinute => new VolumeFlow(value, VolumeFlowUnit.KiloliterPerMinute);
        public VolumeFlow KiloliterPerSecond => new VolumeFlow(value, VolumeFlowUnit.KiloliterPerSecond);
        public VolumeFlow KilousGallonPerMinute => new VolumeFlow(value, VolumeFlowUnit.KilousGallonPerMinute);
        public VolumeFlow LiterPerDay => new VolumeFlow(value, VolumeFlowUnit.LiterPerDay);
        public VolumeFlow LiterPerHour => new VolumeFlow(value, VolumeFlowUnit.LiterPerHour);
        public VolumeFlow LiterPerMinute => new VolumeFlow(value, VolumeFlowUnit.LiterPerMinute);
        public VolumeFlow LiterPerSecond => new VolumeFlow(value, VolumeFlowUnit.LiterPerSecond);
        public VolumeFlow MegaliterPerDay => new VolumeFlow(value, VolumeFlowUnit.MegaliterPerDay);
        public VolumeFlow MegaukGallonPerSecond => new VolumeFlow(value, VolumeFlowUnit.MegaukGallonPerSecond);
        public VolumeFlow MicroliterPerDay => new VolumeFlow(value, VolumeFlowUnit.MicroliterPerDay);
        public VolumeFlow MicroliterPerMinute => new VolumeFlow(value, VolumeFlowUnit.MicroliterPerMinute);
        public VolumeFlow MicroliterPerSecond => new VolumeFlow(value, VolumeFlowUnit.MicroliterPerSecond);
        public VolumeFlow MilliliterPerDay => new VolumeFlow(value, VolumeFlowUnit.MilliliterPerDay);
        public VolumeFlow MilliliterPerMinute => new VolumeFlow(value, VolumeFlowUnit.MilliliterPerMinute);
        public VolumeFlow MilliliterPerSecond => new VolumeFlow(value, VolumeFlowUnit.MilliliterPerSecond);
        public VolumeFlow MillionUsGallonsPerDay => new VolumeFlow(value, VolumeFlowUnit.MillionUsGallonsPerDay);
        public VolumeFlow NanoliterPerDay => new VolumeFlow(value, VolumeFlowUnit.NanoliterPerDay);
        public VolumeFlow NanoliterPerMinute => new VolumeFlow(value, VolumeFlowUnit.NanoliterPerMinute);
        public VolumeFlow NanoliterPerSecond => new VolumeFlow(value, VolumeFlowUnit.NanoliterPerSecond);
        public VolumeFlow OilBarrelPerDay => new VolumeFlow(value, VolumeFlowUnit.OilBarrelPerDay);
        public VolumeFlow OilBarrelPerHour => new VolumeFlow(value, VolumeFlowUnit.OilBarrelPerHour);
        public VolumeFlow OilBarrelPerMinute => new VolumeFlow(value, VolumeFlowUnit.OilBarrelPerMinute);
        public VolumeFlow OilBarrelPerSecond => new VolumeFlow(value, VolumeFlowUnit.OilBarrelPerSecond);
        public VolumeFlow UkGallonPerDay => new VolumeFlow(value, VolumeFlowUnit.UkGallonPerDay);
        public VolumeFlow UkGallonPerHour => new VolumeFlow(value, VolumeFlowUnit.UkGallonPerHour);
        public VolumeFlow UkGallonPerMinute => new VolumeFlow(value, VolumeFlowUnit.UkGallonPerMinute);
        public VolumeFlow UkGallonPerSecond => new VolumeFlow(value, VolumeFlowUnit.UkGallonPerSecond);
        public VolumeFlow UsGallonPerDay => new VolumeFlow(value, VolumeFlowUnit.UsGallonPerDay);
        public VolumeFlow UsGallonPerHour => new VolumeFlow(value, VolumeFlowUnit.UsGallonPerHour);
        public VolumeFlow UsGallonPerMinute => new VolumeFlow(value, VolumeFlowUnit.UsGallonPerMinute);
        public VolumeFlow UsGallonPerSecond => new VolumeFlow(value, VolumeFlowUnit.UsGallonPerSecond);
    }

    // decimal receiver (convert as needed)
    extension(decimal value)
    {
        public VolumeFlow AcreFootPerDay => new VolumeFlow((double)value, VolumeFlowUnit.AcreFootPerDay);
        public VolumeFlow AcreFootPerHour => new VolumeFlow((double)value, VolumeFlowUnit.AcreFootPerHour);
        public VolumeFlow AcreFootPerMinute => new VolumeFlow((double)value, VolumeFlowUnit.AcreFootPerMinute);
        public VolumeFlow AcreFootPerSecond => new VolumeFlow((double)value, VolumeFlowUnit.AcreFootPerSecond);
        public VolumeFlow CentiliterPerDay => new VolumeFlow((double)value, VolumeFlowUnit.CentiliterPerDay);
        public VolumeFlow CentiliterPerMinute => new VolumeFlow((double)value, VolumeFlowUnit.CentiliterPerMinute);
        public VolumeFlow CentiliterPerSecond => new VolumeFlow((double)value, VolumeFlowUnit.CentiliterPerSecond);
        public VolumeFlow CubicCentimeterPerMinute => new VolumeFlow((double)value, VolumeFlowUnit.CubicCentimeterPerMinute);
        public VolumeFlow CubicDecimeterPerMinute => new VolumeFlow((double)value, VolumeFlowUnit.CubicDecimeterPerMinute);
        public VolumeFlow CubicFootPerHour => new VolumeFlow((double)value, VolumeFlowUnit.CubicFootPerHour);
        public VolumeFlow CubicFootPerMinute => new VolumeFlow((double)value, VolumeFlowUnit.CubicFootPerMinute);
        public VolumeFlow CubicFootPerSecond => new VolumeFlow((double)value, VolumeFlowUnit.CubicFootPerSecond);
        public VolumeFlow CubicMeterPerDay => new VolumeFlow((double)value, VolumeFlowUnit.CubicMeterPerDay);
        public VolumeFlow CubicMeterPerHour => new VolumeFlow((double)value, VolumeFlowUnit.CubicMeterPerHour);
        public VolumeFlow CubicMeterPerMinute => new VolumeFlow((double)value, VolumeFlowUnit.CubicMeterPerMinute);
        public VolumeFlow CubicMeterPerSecond => new VolumeFlow((double)value, VolumeFlowUnit.CubicMeterPerSecond);
        public VolumeFlow CubicMillimeterPerSecond => new VolumeFlow((double)value, VolumeFlowUnit.CubicMillimeterPerSecond);
        public VolumeFlow CubicYardPerDay => new VolumeFlow((double)value, VolumeFlowUnit.CubicYardPerDay);
        public VolumeFlow CubicYardPerHour => new VolumeFlow((double)value, VolumeFlowUnit.CubicYardPerHour);
        public VolumeFlow CubicYardPerMinute => new VolumeFlow((double)value, VolumeFlowUnit.CubicYardPerMinute);
        public VolumeFlow CubicYardPerSecond => new VolumeFlow((double)value, VolumeFlowUnit.CubicYardPerSecond);
        public VolumeFlow DeciliterPerDay => new VolumeFlow((double)value, VolumeFlowUnit.DeciliterPerDay);
        public VolumeFlow DeciliterPerMinute => new VolumeFlow((double)value, VolumeFlowUnit.DeciliterPerMinute);
        public VolumeFlow DeciliterPerSecond => new VolumeFlow((double)value, VolumeFlowUnit.DeciliterPerSecond);
        public VolumeFlow KiloliterPerDay => new VolumeFlow((double)value, VolumeFlowUnit.KiloliterPerDay);
        public VolumeFlow KiloliterPerMinute => new VolumeFlow((double)value, VolumeFlowUnit.KiloliterPerMinute);
        public VolumeFlow KiloliterPerSecond => new VolumeFlow((double)value, VolumeFlowUnit.KiloliterPerSecond);
        public VolumeFlow KilousGallonPerMinute => new VolumeFlow((double)value, VolumeFlowUnit.KilousGallonPerMinute);
        public VolumeFlow LiterPerDay => new VolumeFlow((double)value, VolumeFlowUnit.LiterPerDay);
        public VolumeFlow LiterPerHour => new VolumeFlow((double)value, VolumeFlowUnit.LiterPerHour);
        public VolumeFlow LiterPerMinute => new VolumeFlow((double)value, VolumeFlowUnit.LiterPerMinute);
        public VolumeFlow LiterPerSecond => new VolumeFlow((double)value, VolumeFlowUnit.LiterPerSecond);
        public VolumeFlow MegaliterPerDay => new VolumeFlow((double)value, VolumeFlowUnit.MegaliterPerDay);
        public VolumeFlow MegaukGallonPerSecond => new VolumeFlow((double)value, VolumeFlowUnit.MegaukGallonPerSecond);
        public VolumeFlow MicroliterPerDay => new VolumeFlow((double)value, VolumeFlowUnit.MicroliterPerDay);
        public VolumeFlow MicroliterPerMinute => new VolumeFlow((double)value, VolumeFlowUnit.MicroliterPerMinute);
        public VolumeFlow MicroliterPerSecond => new VolumeFlow((double)value, VolumeFlowUnit.MicroliterPerSecond);
        public VolumeFlow MilliliterPerDay => new VolumeFlow((double)value, VolumeFlowUnit.MilliliterPerDay);
        public VolumeFlow MilliliterPerMinute => new VolumeFlow((double)value, VolumeFlowUnit.MilliliterPerMinute);
        public VolumeFlow MilliliterPerSecond => new VolumeFlow((double)value, VolumeFlowUnit.MilliliterPerSecond);
        public VolumeFlow MillionUsGallonsPerDay => new VolumeFlow((double)value, VolumeFlowUnit.MillionUsGallonsPerDay);
        public VolumeFlow NanoliterPerDay => new VolumeFlow((double)value, VolumeFlowUnit.NanoliterPerDay);
        public VolumeFlow NanoliterPerMinute => new VolumeFlow((double)value, VolumeFlowUnit.NanoliterPerMinute);
        public VolumeFlow NanoliterPerSecond => new VolumeFlow((double)value, VolumeFlowUnit.NanoliterPerSecond);
        public VolumeFlow OilBarrelPerDay => new VolumeFlow((double)value, VolumeFlowUnit.OilBarrelPerDay);
        public VolumeFlow OilBarrelPerHour => new VolumeFlow((double)value, VolumeFlowUnit.OilBarrelPerHour);
        public VolumeFlow OilBarrelPerMinute => new VolumeFlow((double)value, VolumeFlowUnit.OilBarrelPerMinute);
        public VolumeFlow OilBarrelPerSecond => new VolumeFlow((double)value, VolumeFlowUnit.OilBarrelPerSecond);
        public VolumeFlow UkGallonPerDay => new VolumeFlow((double)value, VolumeFlowUnit.UkGallonPerDay);
        public VolumeFlow UkGallonPerHour => new VolumeFlow((double)value, VolumeFlowUnit.UkGallonPerHour);
        public VolumeFlow UkGallonPerMinute => new VolumeFlow((double)value, VolumeFlowUnit.UkGallonPerMinute);
        public VolumeFlow UkGallonPerSecond => new VolumeFlow((double)value, VolumeFlowUnit.UkGallonPerSecond);
        public VolumeFlow UsGallonPerDay => new VolumeFlow((double)value, VolumeFlowUnit.UsGallonPerDay);
        public VolumeFlow UsGallonPerHour => new VolumeFlow((double)value, VolumeFlowUnit.UsGallonPerHour);
        public VolumeFlow UsGallonPerMinute => new VolumeFlow((double)value, VolumeFlowUnit.UsGallonPerMinute);
        public VolumeFlow UsGallonPerSecond => new VolumeFlow((double)value, VolumeFlowUnit.UsGallonPerSecond);
    }
}