using EngineeringUnits;
using EngineeringUnits.Units;

namespace EngineeringUnits.NumberExtensions.NumberToMassFlux;

// <auto-generated/>
// This file is auto-generated; changes will be overwritten.
public static class NumberToMassFluxExtensions
{
    // double receiver
    extension(double value)
    {
        public MassFlux GramPerHourPerSquareCentimeter => new MassFlux(value, MassFluxUnit.GramPerHourPerSquareCentimeter);
        public MassFlux GramPerHourPerSquareMeter => new MassFlux(value, MassFluxUnit.GramPerHourPerSquareMeter);
        public MassFlux GramPerHourPerSquareMillimeter => new MassFlux(value, MassFluxUnit.GramPerHourPerSquareMillimeter);
        public MassFlux GramPerSecondPerSquareCentimeter => new MassFlux(value, MassFluxUnit.GramPerSecondPerSquareCentimeter);
        public MassFlux GramPerSecondPerSquareMeter => new MassFlux(value, MassFluxUnit.GramPerSecondPerSquareMeter);
        public MassFlux GramPerSecondPerSquareMillimeter => new MassFlux(value, MassFluxUnit.GramPerSecondPerSquareMillimeter);
        public MassFlux KilogramPerHourPerSquareCentimeter => new MassFlux(value, MassFluxUnit.KilogramPerHourPerSquareCentimeter);
        public MassFlux KilogramPerHourPerSquareMeter => new MassFlux(value, MassFluxUnit.KilogramPerHourPerSquareMeter);
        public MassFlux KilogramPerHourPerSquareMillimeter => new MassFlux(value, MassFluxUnit.KilogramPerHourPerSquareMillimeter);
        public MassFlux KilogramPerSecondPerSquareCentimeter => new MassFlux(value, MassFluxUnit.KilogramPerSecondPerSquareCentimeter);
        public MassFlux KilogramPerSecondPerSquareMeter => new MassFlux(value, MassFluxUnit.KilogramPerSecondPerSquareMeter);
        public MassFlux KilogramPerSecondPerSquareMillimeter => new MassFlux(value, MassFluxUnit.KilogramPerSecondPerSquareMillimeter);
    }

    // int receiver
    extension(int value)
    {
        public MassFlux GramPerHourPerSquareCentimeter => new MassFlux(value, MassFluxUnit.GramPerHourPerSquareCentimeter);
        public MassFlux GramPerHourPerSquareMeter => new MassFlux(value, MassFluxUnit.GramPerHourPerSquareMeter);
        public MassFlux GramPerHourPerSquareMillimeter => new MassFlux(value, MassFluxUnit.GramPerHourPerSquareMillimeter);
        public MassFlux GramPerSecondPerSquareCentimeter => new MassFlux(value, MassFluxUnit.GramPerSecondPerSquareCentimeter);
        public MassFlux GramPerSecondPerSquareMeter => new MassFlux(value, MassFluxUnit.GramPerSecondPerSquareMeter);
        public MassFlux GramPerSecondPerSquareMillimeter => new MassFlux(value, MassFluxUnit.GramPerSecondPerSquareMillimeter);
        public MassFlux KilogramPerHourPerSquareCentimeter => new MassFlux(value, MassFluxUnit.KilogramPerHourPerSquareCentimeter);
        public MassFlux KilogramPerHourPerSquareMeter => new MassFlux(value, MassFluxUnit.KilogramPerHourPerSquareMeter);
        public MassFlux KilogramPerHourPerSquareMillimeter => new MassFlux(value, MassFluxUnit.KilogramPerHourPerSquareMillimeter);
        public MassFlux KilogramPerSecondPerSquareCentimeter => new MassFlux(value, MassFluxUnit.KilogramPerSecondPerSquareCentimeter);
        public MassFlux KilogramPerSecondPerSquareMeter => new MassFlux(value, MassFluxUnit.KilogramPerSecondPerSquareMeter);
        public MassFlux KilogramPerSecondPerSquareMillimeter => new MassFlux(value, MassFluxUnit.KilogramPerSecondPerSquareMillimeter);
    }

    // decimal receiver (convert as needed)
    extension(decimal value)
    {
        public MassFlux GramPerHourPerSquareCentimeter => new MassFlux((double)value, MassFluxUnit.GramPerHourPerSquareCentimeter);
        public MassFlux GramPerHourPerSquareMeter => new MassFlux((double)value, MassFluxUnit.GramPerHourPerSquareMeter);
        public MassFlux GramPerHourPerSquareMillimeter => new MassFlux((double)value, MassFluxUnit.GramPerHourPerSquareMillimeter);
        public MassFlux GramPerSecondPerSquareCentimeter => new MassFlux((double)value, MassFluxUnit.GramPerSecondPerSquareCentimeter);
        public MassFlux GramPerSecondPerSquareMeter => new MassFlux((double)value, MassFluxUnit.GramPerSecondPerSquareMeter);
        public MassFlux GramPerSecondPerSquareMillimeter => new MassFlux((double)value, MassFluxUnit.GramPerSecondPerSquareMillimeter);
        public MassFlux KilogramPerHourPerSquareCentimeter => new MassFlux((double)value, MassFluxUnit.KilogramPerHourPerSquareCentimeter);
        public MassFlux KilogramPerHourPerSquareMeter => new MassFlux((double)value, MassFluxUnit.KilogramPerHourPerSquareMeter);
        public MassFlux KilogramPerHourPerSquareMillimeter => new MassFlux((double)value, MassFluxUnit.KilogramPerHourPerSquareMillimeter);
        public MassFlux KilogramPerSecondPerSquareCentimeter => new MassFlux((double)value, MassFluxUnit.KilogramPerSecondPerSquareCentimeter);
        public MassFlux KilogramPerSecondPerSquareMeter => new MassFlux((double)value, MassFluxUnit.KilogramPerSecondPerSquareMeter);
        public MassFlux KilogramPerSecondPerSquareMillimeter => new MassFlux((double)value, MassFluxUnit.KilogramPerSecondPerSquareMillimeter);
    }
}