using EngineeringUnits;
using EngineeringUnits.Units;

namespace EngineeringUnits.NumberExtensions.NumberToReactiveEnergy;

// <auto-generated/>
// This file is auto-generated; changes will be overwritten.
public static class NumberToReactiveEnergyExtensions
{
    // double receiver
    extension(double value)
    {
        public ReactiveEnergy KilovoltampereReactiveHour => new ReactiveEnergy(value, ReactiveEnergyUnit.KilovoltampereReactiveHour);
        public ReactiveEnergy MegavoltampereReactiveHour => new ReactiveEnergy(value, ReactiveEnergyUnit.MegavoltampereReactiveHour);
        public ReactiveEnergy VoltampereReactiveHour => new ReactiveEnergy(value, ReactiveEnergyUnit.VoltampereReactiveHour);
    }

    // int receiver
    extension(int value)
    {
        public ReactiveEnergy KilovoltampereReactiveHour => new ReactiveEnergy(value, ReactiveEnergyUnit.KilovoltampereReactiveHour);
        public ReactiveEnergy MegavoltampereReactiveHour => new ReactiveEnergy(value, ReactiveEnergyUnit.MegavoltampereReactiveHour);
        public ReactiveEnergy VoltampereReactiveHour => new ReactiveEnergy(value, ReactiveEnergyUnit.VoltampereReactiveHour);
    }

    // decimal receiver (convert as needed)
    extension(decimal value)
    {
        public ReactiveEnergy KilovoltampereReactiveHour => new ReactiveEnergy((double)value, ReactiveEnergyUnit.KilovoltampereReactiveHour);
        public ReactiveEnergy MegavoltampereReactiveHour => new ReactiveEnergy((double)value, ReactiveEnergyUnit.MegavoltampereReactiveHour);
        public ReactiveEnergy VoltampereReactiveHour => new ReactiveEnergy((double)value, ReactiveEnergyUnit.VoltampereReactiveHour);
    }
}