using EngineeringUnits;
using EngineeringUnits.Units;

namespace EngineeringUnits.NumberExtensions.NumberToMolarFlow;

// <auto-generated/>
// This file is auto-generated; changes will be overwritten.
public static class NumberToMolarFlowExtensions
{
    // double receiver
    extension(double value)
    {
        public MolarFlow MolePerSecond => new MolarFlow(value, MolarFlowUnit.MolePerSecond);
    }

    // int receiver
    extension(int value)
    {
        public MolarFlow MolePerSecond => new MolarFlow(value, MolarFlowUnit.MolePerSecond);
    }

    // decimal receiver (convert as needed)
    extension(decimal value)
    {
        public MolarFlow MolePerSecond => new MolarFlow((double)value, MolarFlowUnit.MolePerSecond);
    }
}