using EngineeringUnits;
using EngineeringUnits.Units;

namespace EngineeringUnits.NumberExtensions.NumberToMolarEntropy;

// <auto-generated/>
// This file is auto-generated; changes will be overwritten.
public static class NumberToMolarEntropyExtensions
{
    // double receiver
    extension(double value)
    {
        public MolarEntropy JoulePerMoleKelvin => new MolarEntropy(value, MolarEntropyUnit.JoulePerMoleKelvin);
        public MolarEntropy KilojoulePerMoleKelvin => new MolarEntropy(value, MolarEntropyUnit.KilojoulePerMoleKelvin);
        public MolarEntropy MegajoulePerMoleKelvin => new MolarEntropy(value, MolarEntropyUnit.MegajoulePerMoleKelvin);
    }

    // int receiver
    extension(int value)
    {
        public MolarEntropy JoulePerMoleKelvin => new MolarEntropy(value, MolarEntropyUnit.JoulePerMoleKelvin);
        public MolarEntropy KilojoulePerMoleKelvin => new MolarEntropy(value, MolarEntropyUnit.KilojoulePerMoleKelvin);
        public MolarEntropy MegajoulePerMoleKelvin => new MolarEntropy(value, MolarEntropyUnit.MegajoulePerMoleKelvin);
    }

    // decimal receiver (convert as needed)
    extension(decimal value)
    {
        public MolarEntropy JoulePerMoleKelvin => new MolarEntropy((double)value, MolarEntropyUnit.JoulePerMoleKelvin);
        public MolarEntropy KilojoulePerMoleKelvin => new MolarEntropy((double)value, MolarEntropyUnit.KilojoulePerMoleKelvin);
        public MolarEntropy MegajoulePerMoleKelvin => new MolarEntropy((double)value, MolarEntropyUnit.MegajoulePerMoleKelvin);
    }
}