using EngineeringUnits;
using EngineeringUnits.Units;

namespace EngineeringUnits.NumberExtensions.NumberToElectricCharge;

// <auto-generated/>
// This file is auto-generated; changes will be overwritten.
public static class NumberToElectricChargeExtensions
{
    // double receiver
    extension(double value)
    {
        public ElectricCharge AmpereHour => new ElectricCharge(value, ElectricChargeUnit.AmpereHour);
        public ElectricCharge Coulomb => new ElectricCharge(value, ElectricChargeUnit.Coulomb);
        public ElectricCharge Gigacoulomb => new ElectricCharge(value, ElectricChargeUnit.Gigacoulomb);
        public ElectricCharge KiloampereHour => new ElectricCharge(value, ElectricChargeUnit.KiloampereHour);
        public ElectricCharge Kilocoulomb => new ElectricCharge(value, ElectricChargeUnit.Kilocoulomb);
        public ElectricCharge MegaampereHour => new ElectricCharge(value, ElectricChargeUnit.MegaampereHour);
        public ElectricCharge Megacoulomb => new ElectricCharge(value, ElectricChargeUnit.Megacoulomb);
        public ElectricCharge Microcoulomb => new ElectricCharge(value, ElectricChargeUnit.Microcoulomb);
        public ElectricCharge MilliampereHour => new ElectricCharge(value, ElectricChargeUnit.MilliampereHour);
        public ElectricCharge Millicoulomb => new ElectricCharge(value, ElectricChargeUnit.Millicoulomb);
        public ElectricCharge Nanocoulomb => new ElectricCharge(value, ElectricChargeUnit.Nanocoulomb);
        public ElectricCharge Picocoulomb => new ElectricCharge(value, ElectricChargeUnit.Picocoulomb);
        public ElectricCharge Teracoulomb => new ElectricCharge(value, ElectricChargeUnit.Teracoulomb);
    }

    // int receiver
    extension(int value)
    {
        public ElectricCharge AmpereHour => new ElectricCharge(value, ElectricChargeUnit.AmpereHour);
        public ElectricCharge Coulomb => new ElectricCharge(value, ElectricChargeUnit.Coulomb);
        public ElectricCharge Gigacoulomb => new ElectricCharge(value, ElectricChargeUnit.Gigacoulomb);
        public ElectricCharge KiloampereHour => new ElectricCharge(value, ElectricChargeUnit.KiloampereHour);
        public ElectricCharge Kilocoulomb => new ElectricCharge(value, ElectricChargeUnit.Kilocoulomb);
        public ElectricCharge MegaampereHour => new ElectricCharge(value, ElectricChargeUnit.MegaampereHour);
        public ElectricCharge Megacoulomb => new ElectricCharge(value, ElectricChargeUnit.Megacoulomb);
        public ElectricCharge Microcoulomb => new ElectricCharge(value, ElectricChargeUnit.Microcoulomb);
        public ElectricCharge MilliampereHour => new ElectricCharge(value, ElectricChargeUnit.MilliampereHour);
        public ElectricCharge Millicoulomb => new ElectricCharge(value, ElectricChargeUnit.Millicoulomb);
        public ElectricCharge Nanocoulomb => new ElectricCharge(value, ElectricChargeUnit.Nanocoulomb);
        public ElectricCharge Picocoulomb => new ElectricCharge(value, ElectricChargeUnit.Picocoulomb);
        public ElectricCharge Teracoulomb => new ElectricCharge(value, ElectricChargeUnit.Teracoulomb);
    }

    // decimal receiver (convert as needed)
    extension(decimal value)
    {
        public ElectricCharge AmpereHour => new ElectricCharge((double)value, ElectricChargeUnit.AmpereHour);
        public ElectricCharge Coulomb => new ElectricCharge((double)value, ElectricChargeUnit.Coulomb);
        public ElectricCharge Gigacoulomb => new ElectricCharge((double)value, ElectricChargeUnit.Gigacoulomb);
        public ElectricCharge KiloampereHour => new ElectricCharge((double)value, ElectricChargeUnit.KiloampereHour);
        public ElectricCharge Kilocoulomb => new ElectricCharge((double)value, ElectricChargeUnit.Kilocoulomb);
        public ElectricCharge MegaampereHour => new ElectricCharge((double)value, ElectricChargeUnit.MegaampereHour);
        public ElectricCharge Megacoulomb => new ElectricCharge((double)value, ElectricChargeUnit.Megacoulomb);
        public ElectricCharge Microcoulomb => new ElectricCharge((double)value, ElectricChargeUnit.Microcoulomb);
        public ElectricCharge MilliampereHour => new ElectricCharge((double)value, ElectricChargeUnit.MilliampereHour);
        public ElectricCharge Millicoulomb => new ElectricCharge((double)value, ElectricChargeUnit.Millicoulomb);
        public ElectricCharge Nanocoulomb => new ElectricCharge((double)value, ElectricChargeUnit.Nanocoulomb);
        public ElectricCharge Picocoulomb => new ElectricCharge((double)value, ElectricChargeUnit.Picocoulomb);
        public ElectricCharge Teracoulomb => new ElectricCharge((double)value, ElectricChargeUnit.Teracoulomb);
    }
}