using EngineeringUnits;
using EngineeringUnits.Units;

namespace EngineeringUnits.NumberExtensions.NumberToLinearDensity;

// <auto-generated/>
// This file is auto-generated; changes will be overwritten.
public static class NumberToLinearDensityExtensions
{
    // double receiver
    extension(double value)
    {
        public LinearDensity GramPerCentimeter => new LinearDensity(value, LinearDensityUnit.GramPerCentimeter);
        public LinearDensity GramPerMeter => new LinearDensity(value, LinearDensityUnit.GramPerMeter);
        public LinearDensity GramPerMillimeter => new LinearDensity(value, LinearDensityUnit.GramPerMillimeter);
        public LinearDensity KilogramPerCentimeter => new LinearDensity(value, LinearDensityUnit.KilogramPerCentimeter);
        public LinearDensity KilogramPerMeter => new LinearDensity(value, LinearDensityUnit.KilogramPerMeter);
        public LinearDensity KilogramPerMillimeter => new LinearDensity(value, LinearDensityUnit.KilogramPerMillimeter);
        public LinearDensity MicrogramPerCentimeter => new LinearDensity(value, LinearDensityUnit.MicrogramPerCentimeter);
        public LinearDensity MicrogramPerMeter => new LinearDensity(value, LinearDensityUnit.MicrogramPerMeter);
        public LinearDensity MicrogramPerMillimeter => new LinearDensity(value, LinearDensityUnit.MicrogramPerMillimeter);
        public LinearDensity MilligramPerCentimeter => new LinearDensity(value, LinearDensityUnit.MilligramPerCentimeter);
        public LinearDensity MilligramPerMeter => new LinearDensity(value, LinearDensityUnit.MilligramPerMeter);
        public LinearDensity MilligramPerMillimeter => new LinearDensity(value, LinearDensityUnit.MilligramPerMillimeter);
        public LinearDensity PoundPerFoot => new LinearDensity(value, LinearDensityUnit.PoundPerFoot);
        public LinearDensity PoundPerInch => new LinearDensity(value, LinearDensityUnit.PoundPerInch);
    }

    // int receiver
    extension(int value)
    {
        public LinearDensity GramPerCentimeter => new LinearDensity(value, LinearDensityUnit.GramPerCentimeter);
        public LinearDensity GramPerMeter => new LinearDensity(value, LinearDensityUnit.GramPerMeter);
        public LinearDensity GramPerMillimeter => new LinearDensity(value, LinearDensityUnit.GramPerMillimeter);
        public LinearDensity KilogramPerCentimeter => new LinearDensity(value, LinearDensityUnit.KilogramPerCentimeter);
        public LinearDensity KilogramPerMeter => new LinearDensity(value, LinearDensityUnit.KilogramPerMeter);
        public LinearDensity KilogramPerMillimeter => new LinearDensity(value, LinearDensityUnit.KilogramPerMillimeter);
        public LinearDensity MicrogramPerCentimeter => new LinearDensity(value, LinearDensityUnit.MicrogramPerCentimeter);
        public LinearDensity MicrogramPerMeter => new LinearDensity(value, LinearDensityUnit.MicrogramPerMeter);
        public LinearDensity MicrogramPerMillimeter => new LinearDensity(value, LinearDensityUnit.MicrogramPerMillimeter);
        public LinearDensity MilligramPerCentimeter => new LinearDensity(value, LinearDensityUnit.MilligramPerCentimeter);
        public LinearDensity MilligramPerMeter => new LinearDensity(value, LinearDensityUnit.MilligramPerMeter);
        public LinearDensity MilligramPerMillimeter => new LinearDensity(value, LinearDensityUnit.MilligramPerMillimeter);
        public LinearDensity PoundPerFoot => new LinearDensity(value, LinearDensityUnit.PoundPerFoot);
        public LinearDensity PoundPerInch => new LinearDensity(value, LinearDensityUnit.PoundPerInch);
    }

    // decimal receiver (convert as needed)
    extension(decimal value)
    {
        public LinearDensity GramPerCentimeter => new LinearDensity((double)value, LinearDensityUnit.GramPerCentimeter);
        public LinearDensity GramPerMeter => new LinearDensity((double)value, LinearDensityUnit.GramPerMeter);
        public LinearDensity GramPerMillimeter => new LinearDensity((double)value, LinearDensityUnit.GramPerMillimeter);
        public LinearDensity KilogramPerCentimeter => new LinearDensity((double)value, LinearDensityUnit.KilogramPerCentimeter);
        public LinearDensity KilogramPerMeter => new LinearDensity((double)value, LinearDensityUnit.KilogramPerMeter);
        public LinearDensity KilogramPerMillimeter => new LinearDensity((double)value, LinearDensityUnit.KilogramPerMillimeter);
        public LinearDensity MicrogramPerCentimeter => new LinearDensity((double)value, LinearDensityUnit.MicrogramPerCentimeter);
        public LinearDensity MicrogramPerMeter => new LinearDensity((double)value, LinearDensityUnit.MicrogramPerMeter);
        public LinearDensity MicrogramPerMillimeter => new LinearDensity((double)value, LinearDensityUnit.MicrogramPerMillimeter);
        public LinearDensity MilligramPerCentimeter => new LinearDensity((double)value, LinearDensityUnit.MilligramPerCentimeter);
        public LinearDensity MilligramPerMeter => new LinearDensity((double)value, LinearDensityUnit.MilligramPerMeter);
        public LinearDensity MilligramPerMillimeter => new LinearDensity((double)value, LinearDensityUnit.MilligramPerMillimeter);
        public LinearDensity PoundPerFoot => new LinearDensity((double)value, LinearDensityUnit.PoundPerFoot);
        public LinearDensity PoundPerInch => new LinearDensity((double)value, LinearDensityUnit.PoundPerInch);
    }
}