using EngineeringUnits;
using EngineeringUnits.Units;

namespace EngineeringUnits.NumberExtensions.NumberToMassCost;

// <auto-generated/>
// This file is auto-generated; changes will be overwritten.
public static class NumberToMassCostExtensions
{
    // double receiver
    extension(double value)
    {
        public MassCost EuroPerKilogram => new MassCost(value, MassCostUnit.EuroPerKilogram);
        public MassCost MillionUSDollarPerTonne => new MassCost(value, MassCostUnit.MillionUSDollarPerTonne);
        public MassCost USDollarPerKilogram => new MassCost(value, MassCostUnit.USDollarPerKilogram);
        public MassCost USDollarPerTonne => new MassCost(value, MassCostUnit.USDollarPerTonne);
    }

    // int receiver
    extension(int value)
    {
        public MassCost EuroPerKilogram => new MassCost(value, MassCostUnit.EuroPerKilogram);
        public MassCost MillionUSDollarPerTonne => new MassCost(value, MassCostUnit.MillionUSDollarPerTonne);
        public MassCost USDollarPerKilogram => new MassCost(value, MassCostUnit.USDollarPerKilogram);
        public MassCost USDollarPerTonne => new MassCost(value, MassCostUnit.USDollarPerTonne);
    }

    // decimal receiver (convert as needed)
    extension(decimal value)
    {
        public MassCost EuroPerKilogram => new MassCost((double)value, MassCostUnit.EuroPerKilogram);
        public MassCost MillionUSDollarPerTonne => new MassCost((double)value, MassCostUnit.MillionUSDollarPerTonne);
        public MassCost USDollarPerKilogram => new MassCost((double)value, MassCostUnit.USDollarPerKilogram);
        public MassCost USDollarPerTonne => new MassCost((double)value, MassCostUnit.USDollarPerTonne);
    }
}