using EngineeringUnits;
using EngineeringUnits.Units;

namespace EngineeringUnits.NumberExtensions.NumberToBitRate;

// <auto-generated/>
// This file is auto-generated; changes will be overwritten.
public static class NumberToBitRateExtensions
{
    // double receiver
    extension(double value)
    {
        public BitRate BitPerSecond => new BitRate(value, BitRateUnit.BitPerSecond);
        public BitRate BytePerSecond => new BitRate(value, BitRateUnit.BytePerSecond);
        public BitRate ExabitPerSecond => new BitRate(value, BitRateUnit.ExabitPerSecond);
        public BitRate ExabytePerSecond => new BitRate(value, BitRateUnit.ExabytePerSecond);
        public BitRate ExbibitPerSecond => new BitRate(value, BitRateUnit.ExbibitPerSecond);
        public BitRate ExbibytePerSecond => new BitRate(value, BitRateUnit.ExbibytePerSecond);
        public BitRate GibibitPerSecond => new BitRate(value, BitRateUnit.GibibitPerSecond);
        public BitRate GibibytePerSecond => new BitRate(value, BitRateUnit.GibibytePerSecond);
        public BitRate GigabitPerSecond => new BitRate(value, BitRateUnit.GigabitPerSecond);
        public BitRate GigabytePerSecond => new BitRate(value, BitRateUnit.GigabytePerSecond);
        public BitRate KibibitPerSecond => new BitRate(value, BitRateUnit.KibibitPerSecond);
        public BitRate KibibytePerSecond => new BitRate(value, BitRateUnit.KibibytePerSecond);
        public BitRate KilobitPerSecond => new BitRate(value, BitRateUnit.KilobitPerSecond);
        public BitRate KilobytePerSecond => new BitRate(value, BitRateUnit.KilobytePerSecond);
        public BitRate MebibitPerSecond => new BitRate(value, BitRateUnit.MebibitPerSecond);
        public BitRate MebibytePerSecond => new BitRate(value, BitRateUnit.MebibytePerSecond);
        public BitRate MegabitPerSecond => new BitRate(value, BitRateUnit.MegabitPerSecond);
        public BitRate MegabytePerSecond => new BitRate(value, BitRateUnit.MegabytePerSecond);
        public BitRate PebibitPerSecond => new BitRate(value, BitRateUnit.PebibitPerSecond);
        public BitRate PebibytePerSecond => new BitRate(value, BitRateUnit.PebibytePerSecond);
        public BitRate PetabitPerSecond => new BitRate(value, BitRateUnit.PetabitPerSecond);
        public BitRate PetabytePerSecond => new BitRate(value, BitRateUnit.PetabytePerSecond);
        public BitRate TebibitPerSecond => new BitRate(value, BitRateUnit.TebibitPerSecond);
        public BitRate TebibytePerSecond => new BitRate(value, BitRateUnit.TebibytePerSecond);
        public BitRate TerabitPerSecond => new BitRate(value, BitRateUnit.TerabitPerSecond);
        public BitRate TerabytePerSecond => new BitRate(value, BitRateUnit.TerabytePerSecond);
    }

    // int receiver
    extension(int value)
    {
        public BitRate BitPerSecond => new BitRate(value, BitRateUnit.BitPerSecond);
        public BitRate BytePerSecond => new BitRate(value, BitRateUnit.BytePerSecond);
        public BitRate ExabitPerSecond => new BitRate(value, BitRateUnit.ExabitPerSecond);
        public BitRate ExabytePerSecond => new BitRate(value, BitRateUnit.ExabytePerSecond);
        public BitRate ExbibitPerSecond => new BitRate(value, BitRateUnit.ExbibitPerSecond);
        public BitRate ExbibytePerSecond => new BitRate(value, BitRateUnit.ExbibytePerSecond);
        public BitRate GibibitPerSecond => new BitRate(value, BitRateUnit.GibibitPerSecond);
        public BitRate GibibytePerSecond => new BitRate(value, BitRateUnit.GibibytePerSecond);
        public BitRate GigabitPerSecond => new BitRate(value, BitRateUnit.GigabitPerSecond);
        public BitRate GigabytePerSecond => new BitRate(value, BitRateUnit.GigabytePerSecond);
        public BitRate KibibitPerSecond => new BitRate(value, BitRateUnit.KibibitPerSecond);
        public BitRate KibibytePerSecond => new BitRate(value, BitRateUnit.KibibytePerSecond);
        public BitRate KilobitPerSecond => new BitRate(value, BitRateUnit.KilobitPerSecond);
        public BitRate KilobytePerSecond => new BitRate(value, BitRateUnit.KilobytePerSecond);
        public BitRate MebibitPerSecond => new BitRate(value, BitRateUnit.MebibitPerSecond);
        public BitRate MebibytePerSecond => new BitRate(value, BitRateUnit.MebibytePerSecond);
        public BitRate MegabitPerSecond => new BitRate(value, BitRateUnit.MegabitPerSecond);
        public BitRate MegabytePerSecond => new BitRate(value, BitRateUnit.MegabytePerSecond);
        public BitRate PebibitPerSecond => new BitRate(value, BitRateUnit.PebibitPerSecond);
        public BitRate PebibytePerSecond => new BitRate(value, BitRateUnit.PebibytePerSecond);
        public BitRate PetabitPerSecond => new BitRate(value, BitRateUnit.PetabitPerSecond);
        public BitRate PetabytePerSecond => new BitRate(value, BitRateUnit.PetabytePerSecond);
        public BitRate TebibitPerSecond => new BitRate(value, BitRateUnit.TebibitPerSecond);
        public BitRate TebibytePerSecond => new BitRate(value, BitRateUnit.TebibytePerSecond);
        public BitRate TerabitPerSecond => new BitRate(value, BitRateUnit.TerabitPerSecond);
        public BitRate TerabytePerSecond => new BitRate(value, BitRateUnit.TerabytePerSecond);
    }

    // decimal receiver (convert as needed)
    extension(decimal value)
    {
        public BitRate BitPerSecond => new BitRate((double)value, BitRateUnit.BitPerSecond);
        public BitRate BytePerSecond => new BitRate((double)value, BitRateUnit.BytePerSecond);
        public BitRate ExabitPerSecond => new BitRate((double)value, BitRateUnit.ExabitPerSecond);
        public BitRate ExabytePerSecond => new BitRate((double)value, BitRateUnit.ExabytePerSecond);
        public BitRate ExbibitPerSecond => new BitRate((double)value, BitRateUnit.ExbibitPerSecond);
        public BitRate ExbibytePerSecond => new BitRate((double)value, BitRateUnit.ExbibytePerSecond);
        public BitRate GibibitPerSecond => new BitRate((double)value, BitRateUnit.GibibitPerSecond);
        public BitRate GibibytePerSecond => new BitRate((double)value, BitRateUnit.GibibytePerSecond);
        public BitRate GigabitPerSecond => new BitRate((double)value, BitRateUnit.GigabitPerSecond);
        public BitRate GigabytePerSecond => new BitRate((double)value, BitRateUnit.GigabytePerSecond);
        public BitRate KibibitPerSecond => new BitRate((double)value, BitRateUnit.KibibitPerSecond);
        public BitRate KibibytePerSecond => new BitRate((double)value, BitRateUnit.KibibytePerSecond);
        public BitRate KilobitPerSecond => new BitRate((double)value, BitRateUnit.KilobitPerSecond);
        public BitRate KilobytePerSecond => new BitRate((double)value, BitRateUnit.KilobytePerSecond);
        public BitRate MebibitPerSecond => new BitRate((double)value, BitRateUnit.MebibitPerSecond);
        public BitRate MebibytePerSecond => new BitRate((double)value, BitRateUnit.MebibytePerSecond);
        public BitRate MegabitPerSecond => new BitRate((double)value, BitRateUnit.MegabitPerSecond);
        public BitRate MegabytePerSecond => new BitRate((double)value, BitRateUnit.MegabytePerSecond);
        public BitRate PebibitPerSecond => new BitRate((double)value, BitRateUnit.PebibitPerSecond);
        public BitRate PebibytePerSecond => new BitRate((double)value, BitRateUnit.PebibytePerSecond);
        public BitRate PetabitPerSecond => new BitRate((double)value, BitRateUnit.PetabitPerSecond);
        public BitRate PetabytePerSecond => new BitRate((double)value, BitRateUnit.PetabytePerSecond);
        public BitRate TebibitPerSecond => new BitRate((double)value, BitRateUnit.TebibitPerSecond);
        public BitRate TebibytePerSecond => new BitRate((double)value, BitRateUnit.TebibytePerSecond);
        public BitRate TerabitPerSecond => new BitRate((double)value, BitRateUnit.TerabitPerSecond);
        public BitRate TerabytePerSecond => new BitRate((double)value, BitRateUnit.TerabytePerSecond);
    }
}