using EngineeringUnits;
using EngineeringUnits.Units;

namespace EngineeringUnits.NumberExtensions.NumberToIlluminance;

// <auto-generated/>
// This file is auto-generated; changes will be overwritten.
public static class NumberToIlluminanceExtensions
{
    // double receiver
    extension(double value)
    {
        public Illuminance Kilolux => new Illuminance(value, IlluminanceUnit.Kilolux);
        public Illuminance Lux => new Illuminance(value, IlluminanceUnit.Lux);
        public Illuminance Megalux => new Illuminance(value, IlluminanceUnit.Megalux);
        public Illuminance Millilux => new Illuminance(value, IlluminanceUnit.Millilux);
    }

    // int receiver
    extension(int value)
    {
        public Illuminance Kilolux => new Illuminance(value, IlluminanceUnit.Kilolux);
        public Illuminance Lux => new Illuminance(value, IlluminanceUnit.Lux);
        public Illuminance Megalux => new Illuminance(value, IlluminanceUnit.Megalux);
        public Illuminance Millilux => new Illuminance(value, IlluminanceUnit.Millilux);
    }

    // decimal receiver (convert as needed)
    extension(decimal value)
    {
        public Illuminance Kilolux => new Illuminance((double)value, IlluminanceUnit.Kilolux);
        public Illuminance Lux => new Illuminance((double)value, IlluminanceUnit.Lux);
        public Illuminance Megalux => new Illuminance((double)value, IlluminanceUnit.Megalux);
        public Illuminance Millilux => new Illuminance((double)value, IlluminanceUnit.Millilux);
    }
}