using EngineeringUnits;
using EngineeringUnits.Units;

namespace EngineeringUnits.NumberExtensions.NumberToLength;

// <auto-generated/>
// This file is auto-generated; changes will be overwritten.
public static class NumberToLengthExtensions
{
    // double receiver
    extension(double value)
    {
        public Length AstronomicalUnit => new Length(value, LengthUnit.AstronomicalUnit);
        public Length Centimeter => new Length(value, LengthUnit.Centimeter);
        public Length Chain => new Length(value, LengthUnit.Chain);
        public Length Decimeter => new Length(value, LengthUnit.Decimeter);
        public Length DtpPica => new Length(value, LengthUnit.DtpPica);
        public Length DtpPoint => new Length(value, LengthUnit.DtpPoint);
        public Length Fathom => new Length(value, LengthUnit.Fathom);
        public Length Foot => new Length(value, LengthUnit.Foot);
        public Length Hand => new Length(value, LengthUnit.Hand);
        public Length Hectometer => new Length(value, LengthUnit.Hectometer);
        public Length Inch => new Length(value, LengthUnit.Inch);
        public Length KilolightYear => new Length(value, LengthUnit.KilolightYear);
        public Length Kilometer => new Length(value, LengthUnit.Kilometer);
        public Length Kiloparsec => new Length(value, LengthUnit.Kiloparsec);
        public Length LightYear => new Length(value, LengthUnit.LightYear);
        public Length MegalightYear => new Length(value, LengthUnit.MegalightYear);
        public Length Megaparsec => new Length(value, LengthUnit.Megaparsec);
        public Length Meter => new Length(value, LengthUnit.Meter);
        public Length Microinch => new Length(value, LengthUnit.Microinch);
        public Length Micrometer => new Length(value, LengthUnit.Micrometer);
        public Length Mil => new Length(value, LengthUnit.Mil);
        public Length Mile => new Length(value, LengthUnit.Mile);
        public Length Millimeter => new Length(value, LengthUnit.Millimeter);
        public Length Nanometer => new Length(value, LengthUnit.Nanometer);
        public Length NauticalMile => new Length(value, LengthUnit.NauticalMile);
        public Length Parsec => new Length(value, LengthUnit.Parsec);
        public Length Shackle => new Length(value, LengthUnit.Shackle);
        public Length SolarRadius => new Length(value, LengthUnit.SolarRadius);
        public Length Twip => new Length(value, LengthUnit.Twip);
        public Length UsSurveyFoot => new Length(value, LengthUnit.UsSurveyFoot);
        public Length Yard => new Length(value, LengthUnit.Yard);
    }

    // int receiver
    extension(int value)
    {
        public Length AstronomicalUnit => new Length(value, LengthUnit.AstronomicalUnit);
        public Length Centimeter => new Length(value, LengthUnit.Centimeter);
        public Length Chain => new Length(value, LengthUnit.Chain);
        public Length Decimeter => new Length(value, LengthUnit.Decimeter);
        public Length DtpPica => new Length(value, LengthUnit.DtpPica);
        public Length DtpPoint => new Length(value, LengthUnit.DtpPoint);
        public Length Fathom => new Length(value, LengthUnit.Fathom);
        public Length Foot => new Length(value, LengthUnit.Foot);
        public Length Hand => new Length(value, LengthUnit.Hand);
        public Length Hectometer => new Length(value, LengthUnit.Hectometer);
        public Length Inch => new Length(value, LengthUnit.Inch);
        public Length KilolightYear => new Length(value, LengthUnit.KilolightYear);
        public Length Kilometer => new Length(value, LengthUnit.Kilometer);
        public Length Kiloparsec => new Length(value, LengthUnit.Kiloparsec);
        public Length LightYear => new Length(value, LengthUnit.LightYear);
        public Length MegalightYear => new Length(value, LengthUnit.MegalightYear);
        public Length Megaparsec => new Length(value, LengthUnit.Megaparsec);
        public Length Meter => new Length(value, LengthUnit.Meter);
        public Length Microinch => new Length(value, LengthUnit.Microinch);
        public Length Micrometer => new Length(value, LengthUnit.Micrometer);
        public Length Mil => new Length(value, LengthUnit.Mil);
        public Length Mile => new Length(value, LengthUnit.Mile);
        public Length Millimeter => new Length(value, LengthUnit.Millimeter);
        public Length Nanometer => new Length(value, LengthUnit.Nanometer);
        public Length NauticalMile => new Length(value, LengthUnit.NauticalMile);
        public Length Parsec => new Length(value, LengthUnit.Parsec);
        public Length Shackle => new Length(value, LengthUnit.Shackle);
        public Length SolarRadius => new Length(value, LengthUnit.SolarRadius);
        public Length Twip => new Length(value, LengthUnit.Twip);
        public Length UsSurveyFoot => new Length(value, LengthUnit.UsSurveyFoot);
        public Length Yard => new Length(value, LengthUnit.Yard);
    }

    // decimal receiver (convert as needed)
    extension(decimal value)
    {
        public Length AstronomicalUnit => new Length((double)value, LengthUnit.AstronomicalUnit);
        public Length Centimeter => new Length((double)value, LengthUnit.Centimeter);
        public Length Chain => new Length((double)value, LengthUnit.Chain);
        public Length Decimeter => new Length((double)value, LengthUnit.Decimeter);
        public Length DtpPica => new Length((double)value, LengthUnit.DtpPica);
        public Length DtpPoint => new Length((double)value, LengthUnit.DtpPoint);
        public Length Fathom => new Length((double)value, LengthUnit.Fathom);
        public Length Foot => new Length((double)value, LengthUnit.Foot);
        public Length Hand => new Length((double)value, LengthUnit.Hand);
        public Length Hectometer => new Length((double)value, LengthUnit.Hectometer);
        public Length Inch => new Length((double)value, LengthUnit.Inch);
        public Length KilolightYear => new Length((double)value, LengthUnit.KilolightYear);
        public Length Kilometer => new Length((double)value, LengthUnit.Kilometer);
        public Length Kiloparsec => new Length((double)value, LengthUnit.Kiloparsec);
        public Length LightYear => new Length((double)value, LengthUnit.LightYear);
        public Length MegalightYear => new Length((double)value, LengthUnit.MegalightYear);
        public Length Megaparsec => new Length((double)value, LengthUnit.Megaparsec);
        public Length Meter => new Length((double)value, LengthUnit.Meter);
        public Length Microinch => new Length((double)value, LengthUnit.Microinch);
        public Length Micrometer => new Length((double)value, LengthUnit.Micrometer);
        public Length Mil => new Length((double)value, LengthUnit.Mil);
        public Length Mile => new Length((double)value, LengthUnit.Mile);
        public Length Millimeter => new Length((double)value, LengthUnit.Millimeter);
        public Length Nanometer => new Length((double)value, LengthUnit.Nanometer);
        public Length NauticalMile => new Length((double)value, LengthUnit.NauticalMile);
        public Length Parsec => new Length((double)value, LengthUnit.Parsec);
        public Length Shackle => new Length((double)value, LengthUnit.Shackle);
        public Length SolarRadius => new Length((double)value, LengthUnit.SolarRadius);
        public Length Twip => new Length((double)value, LengthUnit.Twip);
        public Length UsSurveyFoot => new Length((double)value, LengthUnit.UsSurveyFoot);
        public Length Yard => new Length((double)value, LengthUnit.Yard);
    }
}