using EngineeringUnits;
using EngineeringUnits.Units;

namespace EngineeringUnits.NumberExtensions.NumberToJerk;

// <auto-generated/>
// This file is auto-generated; changes will be overwritten.
public static class NumberToJerkExtensions
{
    // double receiver
    extension(double value)
    {
        public Jerk CentimeterPerSecondCubed => new Jerk(value, JerkUnit.CentimeterPerSecondCubed);
        public Jerk DecimeterPerSecondCubed => new Jerk(value, JerkUnit.DecimeterPerSecondCubed);
        public Jerk KilometerPerSecondCubed => new Jerk(value, JerkUnit.KilometerPerSecondCubed);
        public Jerk MeterPerSecondCubed => new Jerk(value, JerkUnit.MeterPerSecondCubed);
        public Jerk MicrometerPerSecondCubed => new Jerk(value, JerkUnit.MicrometerPerSecondCubed);
        public Jerk MillimeterPerSecondCubed => new Jerk(value, JerkUnit.MillimeterPerSecondCubed);
        public Jerk NanometerPerSecondCubed => new Jerk(value, JerkUnit.NanometerPerSecondCubed);
    }

    // int receiver
    extension(int value)
    {
        public Jerk CentimeterPerSecondCubed => new Jerk(value, JerkUnit.CentimeterPerSecondCubed);
        public Jerk DecimeterPerSecondCubed => new Jerk(value, JerkUnit.DecimeterPerSecondCubed);
        public Jerk KilometerPerSecondCubed => new Jerk(value, JerkUnit.KilometerPerSecondCubed);
        public Jerk MeterPerSecondCubed => new Jerk(value, JerkUnit.MeterPerSecondCubed);
        public Jerk MicrometerPerSecondCubed => new Jerk(value, JerkUnit.MicrometerPerSecondCubed);
        public Jerk MillimeterPerSecondCubed => new Jerk(value, JerkUnit.MillimeterPerSecondCubed);
        public Jerk NanometerPerSecondCubed => new Jerk(value, JerkUnit.NanometerPerSecondCubed);
    }

    // decimal receiver (convert as needed)
    extension(decimal value)
    {
        public Jerk CentimeterPerSecondCubed => new Jerk((double)value, JerkUnit.CentimeterPerSecondCubed);
        public Jerk DecimeterPerSecondCubed => new Jerk((double)value, JerkUnit.DecimeterPerSecondCubed);
        public Jerk KilometerPerSecondCubed => new Jerk((double)value, JerkUnit.KilometerPerSecondCubed);
        public Jerk MeterPerSecondCubed => new Jerk((double)value, JerkUnit.MeterPerSecondCubed);
        public Jerk MicrometerPerSecondCubed => new Jerk((double)value, JerkUnit.MicrometerPerSecondCubed);
        public Jerk MillimeterPerSecondCubed => new Jerk((double)value, JerkUnit.MillimeterPerSecondCubed);
        public Jerk NanometerPerSecondCubed => new Jerk((double)value, JerkUnit.NanometerPerSecondCubed);
    }
}