using EngineeringUnits;
using EngineeringUnits.Units;

namespace EngineeringUnits.NumberExtensions.NumberToElectricField;

// <auto-generated/>
// This file is auto-generated; changes will be overwritten.
public static class NumberToElectricFieldExtensions
{
    // double receiver
    extension(double value)
    {
        public ElectricField VoltPerMeter => new ElectricField(value, ElectricFieldUnit.VoltPerMeter);
    }

    // int receiver
    extension(int value)
    {
        public ElectricField VoltPerMeter => new ElectricField(value, ElectricFieldUnit.VoltPerMeter);
    }

    // decimal receiver (convert as needed)
    extension(decimal value)
    {
        public ElectricField VoltPerMeter => new ElectricField((double)value, ElectricFieldUnit.VoltPerMeter);
    }
}