using EngineeringUnits;
using EngineeringUnits.Units;

namespace EngineeringUnits.NumberExtensions.NumberToSpeed;

// <auto-generated/>
// This file is auto-generated; changes will be overwritten.
public static class NumberToSpeedExtensions
{
    // double receiver
    extension(double value)
    {
        public Speed CentimeterPerHour => new Speed(value, SpeedUnit.CentimeterPerHour);
        public Speed CentimeterPerMinute => new Speed(value, SpeedUnit.CentimeterPerMinute);
        public Speed CentimeterPerSecond => new Speed(value, SpeedUnit.CentimeterPerSecond);
        public Speed DecimeterPerMinute => new Speed(value, SpeedUnit.DecimeterPerMinute);
        public Speed DecimeterPerSecond => new Speed(value, SpeedUnit.DecimeterPerSecond);
        public Speed FootPerHour => new Speed(value, SpeedUnit.FootPerHour);
        public Speed FootPerMinute => new Speed(value, SpeedUnit.FootPerMinute);
        public Speed FootPerSecond => new Speed(value, SpeedUnit.FootPerSecond);
        public Speed InchPerHour => new Speed(value, SpeedUnit.InchPerHour);
        public Speed InchPerMinute => new Speed(value, SpeedUnit.InchPerMinute);
        public Speed InchPerSecond => new Speed(value, SpeedUnit.InchPerSecond);
        public Speed KilometerPerHour => new Speed(value, SpeedUnit.KilometerPerHour);
        public Speed KilometerPerMinute => new Speed(value, SpeedUnit.KilometerPerMinute);
        public Speed KilometerPerSecond => new Speed(value, SpeedUnit.KilometerPerSecond);
        public Speed KilometerPerhour => new Speed(value, SpeedUnit.KilometerPerhour);
        public Speed Knot => new Speed(value, SpeedUnit.Knot);
        public Speed MeterPerHour => new Speed(value, SpeedUnit.MeterPerHour);
        public Speed MeterPerMinute => new Speed(value, SpeedUnit.MeterPerMinute);
        public Speed MeterPerSecond => new Speed(value, SpeedUnit.MeterPerSecond);
        public Speed MicrometerPerMinute => new Speed(value, SpeedUnit.MicrometerPerMinute);
        public Speed MicrometerPerSecond => new Speed(value, SpeedUnit.MicrometerPerSecond);
        public Speed MilePerHour => new Speed(value, SpeedUnit.MilePerHour);
        public Speed MilePerSecond => new Speed(value, SpeedUnit.MilePerSecond);
        public Speed MillimeterPerHour => new Speed(value, SpeedUnit.MillimeterPerHour);
        public Speed MillimeterPerMinute => new Speed(value, SpeedUnit.MillimeterPerMinute);
        public Speed MillimeterPerSecond => new Speed(value, SpeedUnit.MillimeterPerSecond);
        public Speed NanometerPerMinute => new Speed(value, SpeedUnit.NanometerPerMinute);
        public Speed NanometerPerSecond => new Speed(value, SpeedUnit.NanometerPerSecond);
        public Speed UsSurveyFootPerHour => new Speed(value, SpeedUnit.UsSurveyFootPerHour);
        public Speed UsSurveyFootPerMinute => new Speed(value, SpeedUnit.UsSurveyFootPerMinute);
        public Speed UsSurveyFootPerSecond => new Speed(value, SpeedUnit.UsSurveyFootPerSecond);
        public Speed YardPerHour => new Speed(value, SpeedUnit.YardPerHour);
        public Speed YardPerMinute => new Speed(value, SpeedUnit.YardPerMinute);
        public Speed YardPerSecond => new Speed(value, SpeedUnit.YardPerSecond);
    }

    // int receiver
    extension(int value)
    {
        public Speed CentimeterPerHour => new Speed(value, SpeedUnit.CentimeterPerHour);
        public Speed CentimeterPerMinute => new Speed(value, SpeedUnit.CentimeterPerMinute);
        public Speed CentimeterPerSecond => new Speed(value, SpeedUnit.CentimeterPerSecond);
        public Speed DecimeterPerMinute => new Speed(value, SpeedUnit.DecimeterPerMinute);
        public Speed DecimeterPerSecond => new Speed(value, SpeedUnit.DecimeterPerSecond);
        public Speed FootPerHour => new Speed(value, SpeedUnit.FootPerHour);
        public Speed FootPerMinute => new Speed(value, SpeedUnit.FootPerMinute);
        public Speed FootPerSecond => new Speed(value, SpeedUnit.FootPerSecond);
        public Speed InchPerHour => new Speed(value, SpeedUnit.InchPerHour);
        public Speed InchPerMinute => new Speed(value, SpeedUnit.InchPerMinute);
        public Speed InchPerSecond => new Speed(value, SpeedUnit.InchPerSecond);
        public Speed KilometerPerHour => new Speed(value, SpeedUnit.KilometerPerHour);
        public Speed KilometerPerMinute => new Speed(value, SpeedUnit.KilometerPerMinute);
        public Speed KilometerPerSecond => new Speed(value, SpeedUnit.KilometerPerSecond);
        public Speed KilometerPerhour => new Speed(value, SpeedUnit.KilometerPerhour);
        public Speed Knot => new Speed(value, SpeedUnit.Knot);
        public Speed MeterPerHour => new Speed(value, SpeedUnit.MeterPerHour);
        public Speed MeterPerMinute => new Speed(value, SpeedUnit.MeterPerMinute);
        public Speed MeterPerSecond => new Speed(value, SpeedUnit.MeterPerSecond);
        public Speed MicrometerPerMinute => new Speed(value, SpeedUnit.MicrometerPerMinute);
        public Speed MicrometerPerSecond => new Speed(value, SpeedUnit.MicrometerPerSecond);
        public Speed MilePerHour => new Speed(value, SpeedUnit.MilePerHour);
        public Speed MilePerSecond => new Speed(value, SpeedUnit.MilePerSecond);
        public Speed MillimeterPerHour => new Speed(value, SpeedUnit.MillimeterPerHour);
        public Speed MillimeterPerMinute => new Speed(value, SpeedUnit.MillimeterPerMinute);
        public Speed MillimeterPerSecond => new Speed(value, SpeedUnit.MillimeterPerSecond);
        public Speed NanometerPerMinute => new Speed(value, SpeedUnit.NanometerPerMinute);
        public Speed NanometerPerSecond => new Speed(value, SpeedUnit.NanometerPerSecond);
        public Speed UsSurveyFootPerHour => new Speed(value, SpeedUnit.UsSurveyFootPerHour);
        public Speed UsSurveyFootPerMinute => new Speed(value, SpeedUnit.UsSurveyFootPerMinute);
        public Speed UsSurveyFootPerSecond => new Speed(value, SpeedUnit.UsSurveyFootPerSecond);
        public Speed YardPerHour => new Speed(value, SpeedUnit.YardPerHour);
        public Speed YardPerMinute => new Speed(value, SpeedUnit.YardPerMinute);
        public Speed YardPerSecond => new Speed(value, SpeedUnit.YardPerSecond);
    }

    // decimal receiver (convert as needed)
    extension(decimal value)
    {
        public Speed CentimeterPerHour => new Speed((double)value, SpeedUnit.CentimeterPerHour);
        public Speed CentimeterPerMinute => new Speed((double)value, SpeedUnit.CentimeterPerMinute);
        public Speed CentimeterPerSecond => new Speed((double)value, SpeedUnit.CentimeterPerSecond);
        public Speed DecimeterPerMinute => new Speed((double)value, SpeedUnit.DecimeterPerMinute);
        public Speed DecimeterPerSecond => new Speed((double)value, SpeedUnit.DecimeterPerSecond);
        public Speed FootPerHour => new Speed((double)value, SpeedUnit.FootPerHour);
        public Speed FootPerMinute => new Speed((double)value, SpeedUnit.FootPerMinute);
        public Speed FootPerSecond => new Speed((double)value, SpeedUnit.FootPerSecond);
        public Speed InchPerHour => new Speed((double)value, SpeedUnit.InchPerHour);
        public Speed InchPerMinute => new Speed((double)value, SpeedUnit.InchPerMinute);
        public Speed InchPerSecond => new Speed((double)value, SpeedUnit.InchPerSecond);
        public Speed KilometerPerHour => new Speed((double)value, SpeedUnit.KilometerPerHour);
        public Speed KilometerPerMinute => new Speed((double)value, SpeedUnit.KilometerPerMinute);
        public Speed KilometerPerSecond => new Speed((double)value, SpeedUnit.KilometerPerSecond);
        public Speed KilometerPerhour => new Speed((double)value, SpeedUnit.KilometerPerhour);
        public Speed Knot => new Speed((double)value, SpeedUnit.Knot);
        public Speed MeterPerHour => new Speed((double)value, SpeedUnit.MeterPerHour);
        public Speed MeterPerMinute => new Speed((double)value, SpeedUnit.MeterPerMinute);
        public Speed MeterPerSecond => new Speed((double)value, SpeedUnit.MeterPerSecond);
        public Speed MicrometerPerMinute => new Speed((double)value, SpeedUnit.MicrometerPerMinute);
        public Speed MicrometerPerSecond => new Speed((double)value, SpeedUnit.MicrometerPerSecond);
        public Speed MilePerHour => new Speed((double)value, SpeedUnit.MilePerHour);
        public Speed MilePerSecond => new Speed((double)value, SpeedUnit.MilePerSecond);
        public Speed MillimeterPerHour => new Speed((double)value, SpeedUnit.MillimeterPerHour);
        public Speed MillimeterPerMinute => new Speed((double)value, SpeedUnit.MillimeterPerMinute);
        public Speed MillimeterPerSecond => new Speed((double)value, SpeedUnit.MillimeterPerSecond);
        public Speed NanometerPerMinute => new Speed((double)value, SpeedUnit.NanometerPerMinute);
        public Speed NanometerPerSecond => new Speed((double)value, SpeedUnit.NanometerPerSecond);
        public Speed UsSurveyFootPerHour => new Speed((double)value, SpeedUnit.UsSurveyFootPerHour);
        public Speed UsSurveyFootPerMinute => new Speed((double)value, SpeedUnit.UsSurveyFootPerMinute);
        public Speed UsSurveyFootPerSecond => new Speed((double)value, SpeedUnit.UsSurveyFootPerSecond);
        public Speed YardPerHour => new Speed((double)value, SpeedUnit.YardPerHour);
        public Speed YardPerMinute => new Speed((double)value, SpeedUnit.YardPerMinute);
        public Speed YardPerSecond => new Speed((double)value, SpeedUnit.YardPerSecond);
    }
}