// <auto-generated/>
// Generated by CodeGen.Fast from the EngineeringUnits unit definitions - changes will be overwritten!
#nullable enable
// EngineeringUnits.Fast only targets net10.0
#if NET10_0_OR_GREATER
using System;

// ToFast() is the implicit EngineeringUnits -> EngineeringUnits.Fast conversion, written out
#pragma warning disable EUF0009

// Global namespace on purpose: the methods are found in files that use EngineeringUnits, EngineeringUnits.Fast or
// both, with no extra using. When the move is done, remove EngineeringUnits and the compiler lists every call that's left.

/// <summary>
/// Converts between EngineeringUnits and EngineeringUnits.Fast, for moving a code base over one project at a time.
/// The SI value is copied exactly, in both directions. Fast keeps no display unit, so <c>ToClassic()</c> gives the SI unit.
/// </summary>
public static class FastBridgeExtensions
{
    /// <summary>The same Acceleration as an EngineeringUnits.Fast struct. Null throws: use <c>value?.ToFast()</c> to pass null through.</summary>
    public static global::EngineeringUnits.Fast.Acceleration ToFast(this global::EngineeringUnits.Acceleration value) => (global::EngineeringUnits.Fast.Acceleration?)value ?? throw new ArgumentNullException(nameof(value));

    /// <summary>The same Acceleration as an EngineeringUnits object, in its SI unit.</summary>
    public static global::EngineeringUnits.Acceleration ToClassic(this global::EngineeringUnits.Fast.Acceleration value) => new(value.SI, global::EngineeringUnits.Units.AccelerationUnit.SI);

    /// <summary>The same AmountOfSubstance as an EngineeringUnits.Fast struct. Null throws: use <c>value?.ToFast()</c> to pass null through.</summary>
    public static global::EngineeringUnits.Fast.AmountOfSubstance ToFast(this global::EngineeringUnits.AmountOfSubstance value) => (global::EngineeringUnits.Fast.AmountOfSubstance?)value ?? throw new ArgumentNullException(nameof(value));

    /// <summary>The same AmountOfSubstance as an EngineeringUnits object, in its SI unit.</summary>
    public static global::EngineeringUnits.AmountOfSubstance ToClassic(this global::EngineeringUnits.Fast.AmountOfSubstance value) => new(value.SI, global::EngineeringUnits.Units.AmountOfSubstanceUnit.SI);

    /// <summary>The same Angle as an EngineeringUnits.Fast struct. Null throws: use <c>value?.ToFast()</c> to pass null through.</summary>
    public static global::EngineeringUnits.Fast.Angle ToFast(this global::EngineeringUnits.Angle value) => (global::EngineeringUnits.Fast.Angle?)value ?? throw new ArgumentNullException(nameof(value));

    /// <summary>The same Angle as an EngineeringUnits object, in its SI unit.</summary>
    public static global::EngineeringUnits.Angle ToClassic(this global::EngineeringUnits.Fast.Angle value) => new(value.SI, global::EngineeringUnits.Units.AngleUnit.SI);

    /// <summary>The same ApparentEnergy as an EngineeringUnits.Fast struct. Null throws: use <c>value?.ToFast()</c> to pass null through.</summary>
    public static global::EngineeringUnits.Fast.ApparentEnergy ToFast(this global::EngineeringUnits.ApparentEnergy value) => (global::EngineeringUnits.Fast.ApparentEnergy?)value ?? throw new ArgumentNullException(nameof(value));

    /// <summary>The same ApparentEnergy as an EngineeringUnits object, in its SI unit.</summary>
    public static global::EngineeringUnits.ApparentEnergy ToClassic(this global::EngineeringUnits.Fast.ApparentEnergy value) => new(value.SI, global::EngineeringUnits.Units.ApparentEnergyUnit.SI);

    /// <summary>The same ApparentPower as an EngineeringUnits.Fast struct. Null throws: use <c>value?.ToFast()</c> to pass null through.</summary>
    public static global::EngineeringUnits.Fast.ApparentPower ToFast(this global::EngineeringUnits.ApparentPower value) => (global::EngineeringUnits.Fast.ApparentPower?)value ?? throw new ArgumentNullException(nameof(value));

    /// <summary>The same ApparentPower as an EngineeringUnits object, in its SI unit.</summary>
    public static global::EngineeringUnits.ApparentPower ToClassic(this global::EngineeringUnits.Fast.ApparentPower value) => new(value.SI, global::EngineeringUnits.Units.ApparentPowerUnit.SI);

    /// <summary>The same Area as an EngineeringUnits.Fast struct. Null throws: use <c>value?.ToFast()</c> to pass null through.</summary>
    public static global::EngineeringUnits.Fast.Area ToFast(this global::EngineeringUnits.Area value) => (global::EngineeringUnits.Fast.Area?)value ?? throw new ArgumentNullException(nameof(value));

    /// <summary>The same Area as an EngineeringUnits object, in its SI unit.</summary>
    public static global::EngineeringUnits.Area ToClassic(this global::EngineeringUnits.Fast.Area value) => new(value.SI, global::EngineeringUnits.Units.AreaUnit.SI);

    /// <summary>The same AreaCost as an EngineeringUnits.Fast struct. Null throws: use <c>value?.ToFast()</c> to pass null through.</summary>
    public static global::EngineeringUnits.Fast.AreaCost ToFast(this global::EngineeringUnits.AreaCost value) => (global::EngineeringUnits.Fast.AreaCost?)value ?? throw new ArgumentNullException(nameof(value));

    /// <summary>The same AreaCost as an EngineeringUnits object, in its SI unit.</summary>
    public static global::EngineeringUnits.AreaCost ToClassic(this global::EngineeringUnits.Fast.AreaCost value) => new(value.SI, global::EngineeringUnits.Units.AreaCostUnit.SI);

    /// <summary>The same AreaDensity as an EngineeringUnits.Fast struct. Null throws: use <c>value?.ToFast()</c> to pass null through.</summary>
    public static global::EngineeringUnits.Fast.AreaDensity ToFast(this global::EngineeringUnits.AreaDensity value) => (global::EngineeringUnits.Fast.AreaDensity?)value ?? throw new ArgumentNullException(nameof(value));

    /// <summary>The same AreaDensity as an EngineeringUnits object, in its SI unit.</summary>
    public static global::EngineeringUnits.AreaDensity ToClassic(this global::EngineeringUnits.Fast.AreaDensity value) => new(value.SI, global::EngineeringUnits.Units.AreaDensityUnit.SI);

    /// <summary>The same AreaMomentOfInertia as an EngineeringUnits.Fast struct. Null throws: use <c>value?.ToFast()</c> to pass null through.</summary>
    public static global::EngineeringUnits.Fast.AreaMomentOfInertia ToFast(this global::EngineeringUnits.AreaMomentOfInertia value) => (global::EngineeringUnits.Fast.AreaMomentOfInertia?)value ?? throw new ArgumentNullException(nameof(value));

    /// <summary>The same AreaMomentOfInertia as an EngineeringUnits object, in its SI unit.</summary>
    public static global::EngineeringUnits.AreaMomentOfInertia ToClassic(this global::EngineeringUnits.Fast.AreaMomentOfInertia value) => new(value.SI, global::EngineeringUnits.Units.AreaMomentOfInertiaUnit.SI);

    /// <summary>The same BitRate as an EngineeringUnits.Fast struct. Null throws: use <c>value?.ToFast()</c> to pass null through.</summary>
    public static global::EngineeringUnits.Fast.BitRate ToFast(this global::EngineeringUnits.BitRate value) => (global::EngineeringUnits.Fast.BitRate?)value ?? throw new ArgumentNullException(nameof(value));

    /// <summary>The same BitRate as an EngineeringUnits object, in its SI unit.</summary>
    public static global::EngineeringUnits.BitRate ToClassic(this global::EngineeringUnits.Fast.BitRate value) => new(value.SI, global::EngineeringUnits.Units.BitRateUnit.SI);

    /// <summary>The same BrakeSpecificFuelConsumption as an EngineeringUnits.Fast struct. Null throws: use <c>value?.ToFast()</c> to pass null through.</summary>
    public static global::EngineeringUnits.Fast.BrakeSpecificFuelConsumption ToFast(this global::EngineeringUnits.BrakeSpecificFuelConsumption value) => (global::EngineeringUnits.Fast.BrakeSpecificFuelConsumption?)value ?? throw new ArgumentNullException(nameof(value));

    /// <summary>The same BrakeSpecificFuelConsumption as an EngineeringUnits object, in its SI unit.</summary>
    public static global::EngineeringUnits.BrakeSpecificFuelConsumption ToClassic(this global::EngineeringUnits.Fast.BrakeSpecificFuelConsumption value) => new(value.SI, global::EngineeringUnits.Units.BrakeSpecificFuelConsumptionUnit.SI);

    /// <summary>The same Capacitance as an EngineeringUnits.Fast struct. Null throws: use <c>value?.ToFast()</c> to pass null through.</summary>
    public static global::EngineeringUnits.Fast.Capacitance ToFast(this global::EngineeringUnits.Capacitance value) => (global::EngineeringUnits.Fast.Capacitance?)value ?? throw new ArgumentNullException(nameof(value));

    /// <summary>The same Capacitance as an EngineeringUnits object, in its SI unit.</summary>
    public static global::EngineeringUnits.Capacitance ToClassic(this global::EngineeringUnits.Fast.Capacitance value) => new(value.SI, global::EngineeringUnits.Units.CapacitanceUnit.SI);

    /// <summary>The same CoefficientOfThermalExpansion as an EngineeringUnits.Fast struct. Null throws: use <c>value?.ToFast()</c> to pass null through.</summary>
    public static global::EngineeringUnits.Fast.CoefficientOfThermalExpansion ToFast(this global::EngineeringUnits.CoefficientOfThermalExpansion value) => (global::EngineeringUnits.Fast.CoefficientOfThermalExpansion?)value ?? throw new ArgumentNullException(nameof(value));

    /// <summary>The same CoefficientOfThermalExpansion as an EngineeringUnits object, in its SI unit.</summary>
    public static global::EngineeringUnits.CoefficientOfThermalExpansion ToClassic(this global::EngineeringUnits.Fast.CoefficientOfThermalExpansion value) => new(value.SI, global::EngineeringUnits.Units.CoefficientOfThermalExpansionUnit.SI);

    /// <summary>The same Cost as an EngineeringUnits.Fast struct. Null throws: use <c>value?.ToFast()</c> to pass null through.</summary>
    public static global::EngineeringUnits.Fast.Cost ToFast(this global::EngineeringUnits.Cost value) => (global::EngineeringUnits.Fast.Cost?)value ?? throw new ArgumentNullException(nameof(value));

    /// <summary>The same Cost as an EngineeringUnits object, in its SI unit.</summary>
    public static global::EngineeringUnits.Cost ToClassic(this global::EngineeringUnits.Fast.Cost value) => new(value.SI, global::EngineeringUnits.Units.CostUnit.SI);

    /// <summary>The same Density as an EngineeringUnits.Fast struct. Null throws: use <c>value?.ToFast()</c> to pass null through.</summary>
    public static global::EngineeringUnits.Fast.Density ToFast(this global::EngineeringUnits.Density value) => (global::EngineeringUnits.Fast.Density?)value ?? throw new ArgumentNullException(nameof(value));

    /// <summary>The same Density as an EngineeringUnits object, in its SI unit.</summary>
    public static global::EngineeringUnits.Density ToClassic(this global::EngineeringUnits.Fast.Density value) => new(value.SI, global::EngineeringUnits.Units.DensityUnit.SI);

    /// <summary>The same Dimensionless as an EngineeringUnits.Fast struct. Null throws: use <c>value?.ToFast()</c> to pass null through.</summary>
    public static global::EngineeringUnits.Fast.Dimensionless ToFast(this global::EngineeringUnits.Dimensionless value) => (global::EngineeringUnits.Fast.Dimensionless?)value ?? throw new ArgumentNullException(nameof(value));

    /// <summary>The same Dimensionless as an EngineeringUnits object, in its SI unit.</summary>
    public static global::EngineeringUnits.Dimensionless ToClassic(this global::EngineeringUnits.Fast.Dimensionless value) => new(value.SI, global::EngineeringUnits.Units.DimensionlessUnit.SI);

    /// <summary>The same Duration as an EngineeringUnits.Fast struct. Null throws: use <c>value?.ToFast()</c> to pass null through.</summary>
    public static global::EngineeringUnits.Fast.Duration ToFast(this global::EngineeringUnits.Duration value) => (global::EngineeringUnits.Fast.Duration?)value ?? throw new ArgumentNullException(nameof(value));

    /// <summary>The same Duration as an EngineeringUnits object, in its SI unit.</summary>
    public static global::EngineeringUnits.Duration ToClassic(this global::EngineeringUnits.Fast.Duration value) => new(value.SI, global::EngineeringUnits.Units.DurationUnit.SI);

    /// <summary>The same DurationCost as an EngineeringUnits.Fast struct. Null throws: use <c>value?.ToFast()</c> to pass null through.</summary>
    public static global::EngineeringUnits.Fast.DurationCost ToFast(this global::EngineeringUnits.DurationCost value) => (global::EngineeringUnits.Fast.DurationCost?)value ?? throw new ArgumentNullException(nameof(value));

    /// <summary>The same DurationCost as an EngineeringUnits object, in its SI unit.</summary>
    public static global::EngineeringUnits.DurationCost ToClassic(this global::EngineeringUnits.Fast.DurationCost value) => new(value.SI, global::EngineeringUnits.Units.DurationCostUnit.SI);

    /// <summary>The same DynamicViscosity as an EngineeringUnits.Fast struct. Null throws: use <c>value?.ToFast()</c> to pass null through.</summary>
    public static global::EngineeringUnits.Fast.DynamicViscosity ToFast(this global::EngineeringUnits.DynamicViscosity value) => (global::EngineeringUnits.Fast.DynamicViscosity?)value ?? throw new ArgumentNullException(nameof(value));

    /// <summary>The same DynamicViscosity as an EngineeringUnits object, in its SI unit.</summary>
    public static global::EngineeringUnits.DynamicViscosity ToClassic(this global::EngineeringUnits.Fast.DynamicViscosity value) => new(value.SI, global::EngineeringUnits.Units.DynamicViscosityUnit.SI);

    /// <summary>The same ElectricCharge as an EngineeringUnits.Fast struct. Null throws: use <c>value?.ToFast()</c> to pass null through.</summary>
    public static global::EngineeringUnits.Fast.ElectricCharge ToFast(this global::EngineeringUnits.ElectricCharge value) => (global::EngineeringUnits.Fast.ElectricCharge?)value ?? throw new ArgumentNullException(nameof(value));

    /// <summary>The same ElectricCharge as an EngineeringUnits object, in its SI unit.</summary>
    public static global::EngineeringUnits.ElectricCharge ToClassic(this global::EngineeringUnits.Fast.ElectricCharge value) => new(value.SI, global::EngineeringUnits.Units.ElectricChargeUnit.SI);

    /// <summary>The same ElectricChargeDensity as an EngineeringUnits.Fast struct. Null throws: use <c>value?.ToFast()</c> to pass null through.</summary>
    public static global::EngineeringUnits.Fast.ElectricChargeDensity ToFast(this global::EngineeringUnits.ElectricChargeDensity value) => (global::EngineeringUnits.Fast.ElectricChargeDensity?)value ?? throw new ArgumentNullException(nameof(value));

    /// <summary>The same ElectricChargeDensity as an EngineeringUnits object, in its SI unit.</summary>
    public static global::EngineeringUnits.ElectricChargeDensity ToClassic(this global::EngineeringUnits.Fast.ElectricChargeDensity value) => new(value.SI, global::EngineeringUnits.Units.ElectricChargeDensityUnit.SI);

    /// <summary>The same ElectricConductivity as an EngineeringUnits.Fast struct. Null throws: use <c>value?.ToFast()</c> to pass null through.</summary>
    public static global::EngineeringUnits.Fast.ElectricConductivity ToFast(this global::EngineeringUnits.ElectricConductivity value) => (global::EngineeringUnits.Fast.ElectricConductivity?)value ?? throw new ArgumentNullException(nameof(value));

    /// <summary>The same ElectricConductivity as an EngineeringUnits object, in its SI unit.</summary>
    public static global::EngineeringUnits.ElectricConductivity ToClassic(this global::EngineeringUnits.Fast.ElectricConductivity value) => new(value.SI, global::EngineeringUnits.Units.ElectricConductivityUnit.SI);

    /// <summary>The same ElectricCurrent as an EngineeringUnits.Fast struct. Null throws: use <c>value?.ToFast()</c> to pass null through.</summary>
    public static global::EngineeringUnits.Fast.ElectricCurrent ToFast(this global::EngineeringUnits.ElectricCurrent value) => (global::EngineeringUnits.Fast.ElectricCurrent?)value ?? throw new ArgumentNullException(nameof(value));

    /// <summary>The same ElectricCurrent as an EngineeringUnits object, in its SI unit.</summary>
    public static global::EngineeringUnits.ElectricCurrent ToClassic(this global::EngineeringUnits.Fast.ElectricCurrent value) => new(value.SI, global::EngineeringUnits.Units.ElectricCurrentUnit.SI);

    /// <summary>The same ElectricCurrentDensity as an EngineeringUnits.Fast struct. Null throws: use <c>value?.ToFast()</c> to pass null through.</summary>
    public static global::EngineeringUnits.Fast.ElectricCurrentDensity ToFast(this global::EngineeringUnits.ElectricCurrentDensity value) => (global::EngineeringUnits.Fast.ElectricCurrentDensity?)value ?? throw new ArgumentNullException(nameof(value));

    /// <summary>The same ElectricCurrentDensity as an EngineeringUnits object, in its SI unit.</summary>
    public static global::EngineeringUnits.ElectricCurrentDensity ToClassic(this global::EngineeringUnits.Fast.ElectricCurrentDensity value) => new(value.SI, global::EngineeringUnits.Units.ElectricCurrentDensityUnit.SI);

    /// <summary>The same ElectricCurrentGradient as an EngineeringUnits.Fast struct. Null throws: use <c>value?.ToFast()</c> to pass null through.</summary>
    public static global::EngineeringUnits.Fast.ElectricCurrentGradient ToFast(this global::EngineeringUnits.ElectricCurrentGradient value) => (global::EngineeringUnits.Fast.ElectricCurrentGradient?)value ?? throw new ArgumentNullException(nameof(value));

    /// <summary>The same ElectricCurrentGradient as an EngineeringUnits object, in its SI unit.</summary>
    public static global::EngineeringUnits.ElectricCurrentGradient ToClassic(this global::EngineeringUnits.Fast.ElectricCurrentGradient value) => new(value.SI, global::EngineeringUnits.Units.ElectricCurrentGradientUnit.SI);

    /// <summary>The same ElectricField as an EngineeringUnits.Fast struct. Null throws: use <c>value?.ToFast()</c> to pass null through.</summary>
    public static global::EngineeringUnits.Fast.ElectricField ToFast(this global::EngineeringUnits.ElectricField value) => (global::EngineeringUnits.Fast.ElectricField?)value ?? throw new ArgumentNullException(nameof(value));

    /// <summary>The same ElectricField as an EngineeringUnits object, in its SI unit.</summary>
    public static global::EngineeringUnits.ElectricField ToClassic(this global::EngineeringUnits.Fast.ElectricField value) => new(value.SI, global::EngineeringUnits.Units.ElectricFieldUnit.SI);

    /// <summary>The same ElectricInductance as an EngineeringUnits.Fast struct. Null throws: use <c>value?.ToFast()</c> to pass null through.</summary>
    public static global::EngineeringUnits.Fast.ElectricInductance ToFast(this global::EngineeringUnits.ElectricInductance value) => (global::EngineeringUnits.Fast.ElectricInductance?)value ?? throw new ArgumentNullException(nameof(value));

    /// <summary>The same ElectricInductance as an EngineeringUnits object, in its SI unit.</summary>
    public static global::EngineeringUnits.ElectricInductance ToClassic(this global::EngineeringUnits.Fast.ElectricInductance value) => new(value.SI, global::EngineeringUnits.Units.ElectricInductanceUnit.SI);

    /// <summary>The same ElectricPotential as an EngineeringUnits.Fast struct. Null throws: use <c>value?.ToFast()</c> to pass null through.</summary>
    public static global::EngineeringUnits.Fast.ElectricPotential ToFast(this global::EngineeringUnits.ElectricPotential value) => (global::EngineeringUnits.Fast.ElectricPotential?)value ?? throw new ArgumentNullException(nameof(value));

    /// <summary>The same ElectricPotential as an EngineeringUnits object, in its SI unit.</summary>
    public static global::EngineeringUnits.ElectricPotential ToClassic(this global::EngineeringUnits.Fast.ElectricPotential value) => new(value.SI, global::EngineeringUnits.Units.ElectricPotentialUnit.SI);

    /// <summary>The same ElectricPotentialChangeRate as an EngineeringUnits.Fast struct. Null throws: use <c>value?.ToFast()</c> to pass null through.</summary>
    public static global::EngineeringUnits.Fast.ElectricPotentialChangeRate ToFast(this global::EngineeringUnits.ElectricPotentialChangeRate value) => (global::EngineeringUnits.Fast.ElectricPotentialChangeRate?)value ?? throw new ArgumentNullException(nameof(value));

    /// <summary>The same ElectricPotentialChangeRate as an EngineeringUnits object, in its SI unit.</summary>
    public static global::EngineeringUnits.ElectricPotentialChangeRate ToClassic(this global::EngineeringUnits.Fast.ElectricPotentialChangeRate value) => new(value.SI, global::EngineeringUnits.Units.ElectricPotentialChangeRateUnit.SI);

    /// <summary>The same ElectricResistance as an EngineeringUnits.Fast struct. Null throws: use <c>value?.ToFast()</c> to pass null through.</summary>
    public static global::EngineeringUnits.Fast.ElectricResistance ToFast(this global::EngineeringUnits.ElectricResistance value) => (global::EngineeringUnits.Fast.ElectricResistance?)value ?? throw new ArgumentNullException(nameof(value));

    /// <summary>The same ElectricResistance as an EngineeringUnits object, in its SI unit.</summary>
    public static global::EngineeringUnits.ElectricResistance ToClassic(this global::EngineeringUnits.Fast.ElectricResistance value) => new(value.SI, global::EngineeringUnits.Units.ElectricResistanceUnit.SI);

    /// <summary>The same ElectricResistivity as an EngineeringUnits.Fast struct. Null throws: use <c>value?.ToFast()</c> to pass null through.</summary>
    public static global::EngineeringUnits.Fast.ElectricResistivity ToFast(this global::EngineeringUnits.ElectricResistivity value) => (global::EngineeringUnits.Fast.ElectricResistivity?)value ?? throw new ArgumentNullException(nameof(value));

    /// <summary>The same ElectricResistivity as an EngineeringUnits object, in its SI unit.</summary>
    public static global::EngineeringUnits.ElectricResistivity ToClassic(this global::EngineeringUnits.Fast.ElectricResistivity value) => new(value.SI, global::EngineeringUnits.Units.ElectricResistivityUnit.SI);

    /// <summary>The same ElectricSurfaceChargeDensity as an EngineeringUnits.Fast struct. Null throws: use <c>value?.ToFast()</c> to pass null through.</summary>
    public static global::EngineeringUnits.Fast.ElectricSurfaceChargeDensity ToFast(this global::EngineeringUnits.ElectricSurfaceChargeDensity value) => (global::EngineeringUnits.Fast.ElectricSurfaceChargeDensity?)value ?? throw new ArgumentNullException(nameof(value));

    /// <summary>The same ElectricSurfaceChargeDensity as an EngineeringUnits object, in its SI unit.</summary>
    public static global::EngineeringUnits.ElectricSurfaceChargeDensity ToClassic(this global::EngineeringUnits.Fast.ElectricSurfaceChargeDensity value) => new(value.SI, global::EngineeringUnits.Units.ElectricSurfaceChargeDensityUnit.SI);

    /// <summary>The same Energy as an EngineeringUnits.Fast struct. Null throws: use <c>value?.ToFast()</c> to pass null through.</summary>
    public static global::EngineeringUnits.Fast.Energy ToFast(this global::EngineeringUnits.Energy value) => (global::EngineeringUnits.Fast.Energy?)value ?? throw new ArgumentNullException(nameof(value));

    /// <summary>The same Energy as an EngineeringUnits object, in its SI unit.</summary>
    public static global::EngineeringUnits.Energy ToClassic(this global::EngineeringUnits.Fast.Energy value) => new(value.SI, global::EngineeringUnits.Units.EnergyUnit.SI);

    /// <summary>The same EnergyCost as an EngineeringUnits.Fast struct. Null throws: use <c>value?.ToFast()</c> to pass null through.</summary>
    public static global::EngineeringUnits.Fast.EnergyCost ToFast(this global::EngineeringUnits.EnergyCost value) => (global::EngineeringUnits.Fast.EnergyCost?)value ?? throw new ArgumentNullException(nameof(value));

    /// <summary>The same EnergyCost as an EngineeringUnits object, in its SI unit.</summary>
    public static global::EngineeringUnits.EnergyCost ToClassic(this global::EngineeringUnits.Fast.EnergyCost value) => new(value.SI, global::EngineeringUnits.Units.EnergyCostUnit.SI);

    /// <summary>The same Enthalpy as an EngineeringUnits.Fast struct. Null throws: use <c>value?.ToFast()</c> to pass null through.</summary>
    public static global::EngineeringUnits.Fast.Enthalpy ToFast(this global::EngineeringUnits.Enthalpy value) => (global::EngineeringUnits.Fast.Enthalpy?)value ?? throw new ArgumentNullException(nameof(value));

    /// <summary>The same Enthalpy as an EngineeringUnits object, in its SI unit.</summary>
    public static global::EngineeringUnits.Enthalpy ToClassic(this global::EngineeringUnits.Fast.Enthalpy value) => new(value.SI, global::EngineeringUnits.Units.EnthalpyUnit.SI);

    /// <summary>The same Entropy as an EngineeringUnits.Fast struct. Null throws: use <c>value?.ToFast()</c> to pass null through.</summary>
    public static global::EngineeringUnits.Fast.Entropy ToFast(this global::EngineeringUnits.Entropy value) => (global::EngineeringUnits.Fast.Entropy?)value ?? throw new ArgumentNullException(nameof(value));

    /// <summary>The same Entropy as an EngineeringUnits object, in its SI unit.</summary>
    public static global::EngineeringUnits.Entropy ToClassic(this global::EngineeringUnits.Fast.Entropy value) => new(value.SI, global::EngineeringUnits.Units.EntropyUnit.SI);

    /// <summary>The same Force as an EngineeringUnits.Fast struct. Null throws: use <c>value?.ToFast()</c> to pass null through.</summary>
    public static global::EngineeringUnits.Fast.Force ToFast(this global::EngineeringUnits.Force value) => (global::EngineeringUnits.Fast.Force?)value ?? throw new ArgumentNullException(nameof(value));

    /// <summary>The same Force as an EngineeringUnits object, in its SI unit.</summary>
    public static global::EngineeringUnits.Force ToClassic(this global::EngineeringUnits.Fast.Force value) => new(value.SI, global::EngineeringUnits.Units.ForceUnit.SI);

    /// <summary>The same ForceChangeRate as an EngineeringUnits.Fast struct. Null throws: use <c>value?.ToFast()</c> to pass null through.</summary>
    public static global::EngineeringUnits.Fast.ForceChangeRate ToFast(this global::EngineeringUnits.ForceChangeRate value) => (global::EngineeringUnits.Fast.ForceChangeRate?)value ?? throw new ArgumentNullException(nameof(value));

    /// <summary>The same ForceChangeRate as an EngineeringUnits object, in its SI unit.</summary>
    public static global::EngineeringUnits.ForceChangeRate ToClassic(this global::EngineeringUnits.Fast.ForceChangeRate value) => new(value.SI, global::EngineeringUnits.Units.ForceChangeRateUnit.SI);

    /// <summary>The same ForceCost as an EngineeringUnits.Fast struct. Null throws: use <c>value?.ToFast()</c> to pass null through.</summary>
    public static global::EngineeringUnits.Fast.ForceCost ToFast(this global::EngineeringUnits.ForceCost value) => (global::EngineeringUnits.Fast.ForceCost?)value ?? throw new ArgumentNullException(nameof(value));

    /// <summary>The same ForceCost as an EngineeringUnits object, in its SI unit.</summary>
    public static global::EngineeringUnits.ForceCost ToClassic(this global::EngineeringUnits.Fast.ForceCost value) => new(value.SI, global::EngineeringUnits.Units.ForceCostUnit.SI);

    /// <summary>The same ForcePerLength as an EngineeringUnits.Fast struct. Null throws: use <c>value?.ToFast()</c> to pass null through.</summary>
    public static global::EngineeringUnits.Fast.ForcePerLength ToFast(this global::EngineeringUnits.ForcePerLength value) => (global::EngineeringUnits.Fast.ForcePerLength?)value ?? throw new ArgumentNullException(nameof(value));

    /// <summary>The same ForcePerLength as an EngineeringUnits object, in its SI unit.</summary>
    public static global::EngineeringUnits.ForcePerLength ToClassic(this global::EngineeringUnits.Fast.ForcePerLength value) => new(value.SI, global::EngineeringUnits.Units.ForcePerLengthUnit.SI);

    /// <summary>The same Frequency as an EngineeringUnits.Fast struct. Null throws: use <c>value?.ToFast()</c> to pass null through.</summary>
    public static global::EngineeringUnits.Fast.Frequency ToFast(this global::EngineeringUnits.Frequency value) => (global::EngineeringUnits.Fast.Frequency?)value ?? throw new ArgumentNullException(nameof(value));

    /// <summary>The same Frequency as an EngineeringUnits object, in its SI unit.</summary>
    public static global::EngineeringUnits.Frequency ToClassic(this global::EngineeringUnits.Fast.Frequency value) => new(value.SI, global::EngineeringUnits.Units.FrequencyUnit.SI);

    /// <summary>The same FuelEfficiency as an EngineeringUnits.Fast struct. Null throws: use <c>value?.ToFast()</c> to pass null through.</summary>
    public static global::EngineeringUnits.Fast.FuelEfficiency ToFast(this global::EngineeringUnits.FuelEfficiency value) => (global::EngineeringUnits.Fast.FuelEfficiency?)value ?? throw new ArgumentNullException(nameof(value));

    /// <summary>The same FuelEfficiency as an EngineeringUnits object, in its SI unit.</summary>
    public static global::EngineeringUnits.FuelEfficiency ToClassic(this global::EngineeringUnits.Fast.FuelEfficiency value) => new(value.SI, global::EngineeringUnits.Units.FuelEfficiencyUnit.SI);

    /// <summary>The same HeatFlux as an EngineeringUnits.Fast struct. Null throws: use <c>value?.ToFast()</c> to pass null through.</summary>
    public static global::EngineeringUnits.Fast.HeatFlux ToFast(this global::EngineeringUnits.HeatFlux value) => (global::EngineeringUnits.Fast.HeatFlux?)value ?? throw new ArgumentNullException(nameof(value));

    /// <summary>The same HeatFlux as an EngineeringUnits object, in its SI unit.</summary>
    public static global::EngineeringUnits.HeatFlux ToClassic(this global::EngineeringUnits.Fast.HeatFlux value) => new(value.SI, global::EngineeringUnits.Units.HeatFluxUnit.SI);

    /// <summary>The same HeatTransferCoefficient as an EngineeringUnits.Fast struct. Null throws: use <c>value?.ToFast()</c> to pass null through.</summary>
    public static global::EngineeringUnits.Fast.HeatTransferCoefficient ToFast(this global::EngineeringUnits.HeatTransferCoefficient value) => (global::EngineeringUnits.Fast.HeatTransferCoefficient?)value ?? throw new ArgumentNullException(nameof(value));

    /// <summary>The same HeatTransferCoefficient as an EngineeringUnits object, in its SI unit.</summary>
    public static global::EngineeringUnits.HeatTransferCoefficient ToClassic(this global::EngineeringUnits.Fast.HeatTransferCoefficient value) => new(value.SI, global::EngineeringUnits.Units.HeatTransferCoefficientUnit.SI);

    /// <summary>The same Illuminance as an EngineeringUnits.Fast struct. Null throws: use <c>value?.ToFast()</c> to pass null through.</summary>
    public static global::EngineeringUnits.Fast.Illuminance ToFast(this global::EngineeringUnits.Illuminance value) => (global::EngineeringUnits.Fast.Illuminance?)value ?? throw new ArgumentNullException(nameof(value));

    /// <summary>The same Illuminance as an EngineeringUnits object, in its SI unit.</summary>
    public static global::EngineeringUnits.Illuminance ToClassic(this global::EngineeringUnits.Fast.Illuminance value) => new(value.SI, global::EngineeringUnits.Units.IlluminanceUnit.SI);

    /// <summary>The same Information as an EngineeringUnits.Fast struct. Null throws: use <c>value?.ToFast()</c> to pass null through.</summary>
    public static global::EngineeringUnits.Fast.Information ToFast(this global::EngineeringUnits.Information value) => (global::EngineeringUnits.Fast.Information?)value ?? throw new ArgumentNullException(nameof(value));

    /// <summary>The same Information as an EngineeringUnits object, in its SI unit.</summary>
    public static global::EngineeringUnits.Information ToClassic(this global::EngineeringUnits.Fast.Information value) => new(value.SI, global::EngineeringUnits.Units.InformationUnit.SI);

    /// <summary>The same Irradiance as an EngineeringUnits.Fast struct. Null throws: use <c>value?.ToFast()</c> to pass null through.</summary>
    public static global::EngineeringUnits.Fast.Irradiance ToFast(this global::EngineeringUnits.Irradiance value) => (global::EngineeringUnits.Fast.Irradiance?)value ?? throw new ArgumentNullException(nameof(value));

    /// <summary>The same Irradiance as an EngineeringUnits object, in its SI unit.</summary>
    public static global::EngineeringUnits.Irradiance ToClassic(this global::EngineeringUnits.Fast.Irradiance value) => new(value.SI, global::EngineeringUnits.Units.IrradianceUnit.SI);

    /// <summary>The same Irradiation as an EngineeringUnits.Fast struct. Null throws: use <c>value?.ToFast()</c> to pass null through.</summary>
    public static global::EngineeringUnits.Fast.Irradiation ToFast(this global::EngineeringUnits.Irradiation value) => (global::EngineeringUnits.Fast.Irradiation?)value ?? throw new ArgumentNullException(nameof(value));

    /// <summary>The same Irradiation as an EngineeringUnits object, in its SI unit.</summary>
    public static global::EngineeringUnits.Irradiation ToClassic(this global::EngineeringUnits.Fast.Irradiation value) => new(value.SI, global::EngineeringUnits.Units.IrradiationUnit.SI);

    /// <summary>The same Jerk as an EngineeringUnits.Fast struct. Null throws: use <c>value?.ToFast()</c> to pass null through.</summary>
    public static global::EngineeringUnits.Fast.Jerk ToFast(this global::EngineeringUnits.Jerk value) => (global::EngineeringUnits.Fast.Jerk?)value ?? throw new ArgumentNullException(nameof(value));

    /// <summary>The same Jerk as an EngineeringUnits object, in its SI unit.</summary>
    public static global::EngineeringUnits.Jerk ToClassic(this global::EngineeringUnits.Fast.Jerk value) => new(value.SI, global::EngineeringUnits.Units.JerkUnit.SI);

    /// <summary>The same KinematicViscosity as an EngineeringUnits.Fast struct. Null throws: use <c>value?.ToFast()</c> to pass null through.</summary>
    public static global::EngineeringUnits.Fast.KinematicViscosity ToFast(this global::EngineeringUnits.KinematicViscosity value) => (global::EngineeringUnits.Fast.KinematicViscosity?)value ?? throw new ArgumentNullException(nameof(value));

    /// <summary>The same KinematicViscosity as an EngineeringUnits object, in its SI unit.</summary>
    public static global::EngineeringUnits.KinematicViscosity ToClassic(this global::EngineeringUnits.Fast.KinematicViscosity value) => new(value.SI, global::EngineeringUnits.Units.KinematicViscosityUnit.SI);

    /// <summary>The same LapseRate as an EngineeringUnits.Fast struct. Null throws: use <c>value?.ToFast()</c> to pass null through.</summary>
    public static global::EngineeringUnits.Fast.LapseRate ToFast(this global::EngineeringUnits.LapseRate value) => (global::EngineeringUnits.Fast.LapseRate?)value ?? throw new ArgumentNullException(nameof(value));

    /// <summary>The same LapseRate as an EngineeringUnits object, in its SI unit.</summary>
    public static global::EngineeringUnits.LapseRate ToClassic(this global::EngineeringUnits.Fast.LapseRate value) => new(value.SI, global::EngineeringUnits.Units.LapseRateUnit.SI);

    /// <summary>The same Length as an EngineeringUnits.Fast struct. Null throws: use <c>value?.ToFast()</c> to pass null through.</summary>
    public static global::EngineeringUnits.Fast.Length ToFast(this global::EngineeringUnits.Length value) => (global::EngineeringUnits.Fast.Length?)value ?? throw new ArgumentNullException(nameof(value));

    /// <summary>The same Length as an EngineeringUnits object, in its SI unit.</summary>
    public static global::EngineeringUnits.Length ToClassic(this global::EngineeringUnits.Fast.Length value) => new(value.SI, global::EngineeringUnits.Units.LengthUnit.SI);

    /// <summary>The same LengthCost as an EngineeringUnits.Fast struct. Null throws: use <c>value?.ToFast()</c> to pass null through.</summary>
    public static global::EngineeringUnits.Fast.LengthCost ToFast(this global::EngineeringUnits.LengthCost value) => (global::EngineeringUnits.Fast.LengthCost?)value ?? throw new ArgumentNullException(nameof(value));

    /// <summary>The same LengthCost as an EngineeringUnits object, in its SI unit.</summary>
    public static global::EngineeringUnits.LengthCost ToClassic(this global::EngineeringUnits.Fast.LengthCost value) => new(value.SI, global::EngineeringUnits.Units.LengthCostUnit.SI);

    /// <summary>The same Level as an EngineeringUnits.Fast struct. Null throws: use <c>value?.ToFast()</c> to pass null through.</summary>
    public static global::EngineeringUnits.Fast.Level ToFast(this global::EngineeringUnits.Level value) => (global::EngineeringUnits.Fast.Level?)value ?? throw new ArgumentNullException(nameof(value));

    /// <summary>The same Level as an EngineeringUnits object, in its SI unit.</summary>
    public static global::EngineeringUnits.Level ToClassic(this global::EngineeringUnits.Fast.Level value) => new(value.SI, global::EngineeringUnits.Units.LevelUnit.SI);

    /// <summary>The same LinearDensity as an EngineeringUnits.Fast struct. Null throws: use <c>value?.ToFast()</c> to pass null through.</summary>
    public static global::EngineeringUnits.Fast.LinearDensity ToFast(this global::EngineeringUnits.LinearDensity value) => (global::EngineeringUnits.Fast.LinearDensity?)value ?? throw new ArgumentNullException(nameof(value));

    /// <summary>The same LinearDensity as an EngineeringUnits object, in its SI unit.</summary>
    public static global::EngineeringUnits.LinearDensity ToClassic(this global::EngineeringUnits.Fast.LinearDensity value) => new(value.SI, global::EngineeringUnits.Units.LinearDensityUnit.SI);

    /// <summary>The same LinearPowerDensity as an EngineeringUnits.Fast struct. Null throws: use <c>value?.ToFast()</c> to pass null through.</summary>
    public static global::EngineeringUnits.Fast.LinearPowerDensity ToFast(this global::EngineeringUnits.LinearPowerDensity value) => (global::EngineeringUnits.Fast.LinearPowerDensity?)value ?? throw new ArgumentNullException(nameof(value));

    /// <summary>The same LinearPowerDensity as an EngineeringUnits object, in its SI unit.</summary>
    public static global::EngineeringUnits.LinearPowerDensity ToClassic(this global::EngineeringUnits.Fast.LinearPowerDensity value) => new(value.SI, global::EngineeringUnits.Units.LinearPowerDensityUnit.SI);

    /// <summary>The same LuminousFlux as an EngineeringUnits.Fast struct. Null throws: use <c>value?.ToFast()</c> to pass null through.</summary>
    public static global::EngineeringUnits.Fast.LuminousFlux ToFast(this global::EngineeringUnits.LuminousFlux value) => (global::EngineeringUnits.Fast.LuminousFlux?)value ?? throw new ArgumentNullException(nameof(value));

    /// <summary>The same LuminousFlux as an EngineeringUnits object, in its SI unit.</summary>
    public static global::EngineeringUnits.LuminousFlux ToClassic(this global::EngineeringUnits.Fast.LuminousFlux value) => new(value.SI, global::EngineeringUnits.Units.LuminousFluxUnit.SI);

    /// <summary>The same LuminousIntensity as an EngineeringUnits.Fast struct. Null throws: use <c>value?.ToFast()</c> to pass null through.</summary>
    public static global::EngineeringUnits.Fast.LuminousIntensity ToFast(this global::EngineeringUnits.LuminousIntensity value) => (global::EngineeringUnits.Fast.LuminousIntensity?)value ?? throw new ArgumentNullException(nameof(value));

    /// <summary>The same LuminousIntensity as an EngineeringUnits object, in its SI unit.</summary>
    public static global::EngineeringUnits.LuminousIntensity ToClassic(this global::EngineeringUnits.Fast.LuminousIntensity value) => new(value.SI, global::EngineeringUnits.Units.LuminousIntensityUnit.SI);

    /// <summary>The same MagneticField as an EngineeringUnits.Fast struct. Null throws: use <c>value?.ToFast()</c> to pass null through.</summary>
    public static global::EngineeringUnits.Fast.MagneticField ToFast(this global::EngineeringUnits.MagneticField value) => (global::EngineeringUnits.Fast.MagneticField?)value ?? throw new ArgumentNullException(nameof(value));

    /// <summary>The same MagneticField as an EngineeringUnits object, in its SI unit.</summary>
    public static global::EngineeringUnits.MagneticField ToClassic(this global::EngineeringUnits.Fast.MagneticField value) => new(value.SI, global::EngineeringUnits.Units.MagneticFieldUnit.SI);

    /// <summary>The same MagneticFlux as an EngineeringUnits.Fast struct. Null throws: use <c>value?.ToFast()</c> to pass null through.</summary>
    public static global::EngineeringUnits.Fast.MagneticFlux ToFast(this global::EngineeringUnits.MagneticFlux value) => (global::EngineeringUnits.Fast.MagneticFlux?)value ?? throw new ArgumentNullException(nameof(value));

    /// <summary>The same MagneticFlux as an EngineeringUnits object, in its SI unit.</summary>
    public static global::EngineeringUnits.MagneticFlux ToClassic(this global::EngineeringUnits.Fast.MagneticFlux value) => new(value.SI, global::EngineeringUnits.Units.MagneticFluxUnit.SI);

    /// <summary>The same Magnetization as an EngineeringUnits.Fast struct. Null throws: use <c>value?.ToFast()</c> to pass null through.</summary>
    public static global::EngineeringUnits.Fast.Magnetization ToFast(this global::EngineeringUnits.Magnetization value) => (global::EngineeringUnits.Fast.Magnetization?)value ?? throw new ArgumentNullException(nameof(value));

    /// <summary>The same Magnetization as an EngineeringUnits object, in its SI unit.</summary>
    public static global::EngineeringUnits.Magnetization ToClassic(this global::EngineeringUnits.Fast.Magnetization value) => new(value.SI, global::EngineeringUnits.Units.MagnetizationUnit.SI);

    /// <summary>The same Mass as an EngineeringUnits.Fast struct. Null throws: use <c>value?.ToFast()</c> to pass null through.</summary>
    public static global::EngineeringUnits.Fast.Mass ToFast(this global::EngineeringUnits.Mass value) => (global::EngineeringUnits.Fast.Mass?)value ?? throw new ArgumentNullException(nameof(value));

    /// <summary>The same Mass as an EngineeringUnits object, in its SI unit.</summary>
    public static global::EngineeringUnits.Mass ToClassic(this global::EngineeringUnits.Fast.Mass value) => new(value.SI, global::EngineeringUnits.Units.MassUnit.SI);

    /// <summary>The same MassCost as an EngineeringUnits.Fast struct. Null throws: use <c>value?.ToFast()</c> to pass null through.</summary>
    public static global::EngineeringUnits.Fast.MassCost ToFast(this global::EngineeringUnits.MassCost value) => (global::EngineeringUnits.Fast.MassCost?)value ?? throw new ArgumentNullException(nameof(value));

    /// <summary>The same MassCost as an EngineeringUnits object, in its SI unit.</summary>
    public static global::EngineeringUnits.MassCost ToClassic(this global::EngineeringUnits.Fast.MassCost value) => new(value.SI, global::EngineeringUnits.Units.MassCostUnit.SI);

    /// <summary>The same MassFlow as an EngineeringUnits.Fast struct. Null throws: use <c>value?.ToFast()</c> to pass null through.</summary>
    public static global::EngineeringUnits.Fast.MassFlow ToFast(this global::EngineeringUnits.MassFlow value) => (global::EngineeringUnits.Fast.MassFlow?)value ?? throw new ArgumentNullException(nameof(value));

    /// <summary>The same MassFlow as an EngineeringUnits object, in its SI unit.</summary>
    public static global::EngineeringUnits.MassFlow ToClassic(this global::EngineeringUnits.Fast.MassFlow value) => new(value.SI, global::EngineeringUnits.Units.MassFlowUnit.SI);

    /// <summary>The same MassFlux as an EngineeringUnits.Fast struct. Null throws: use <c>value?.ToFast()</c> to pass null through.</summary>
    public static global::EngineeringUnits.Fast.MassFlux ToFast(this global::EngineeringUnits.MassFlux value) => (global::EngineeringUnits.Fast.MassFlux?)value ?? throw new ArgumentNullException(nameof(value));

    /// <summary>The same MassFlux as an EngineeringUnits object, in its SI unit.</summary>
    public static global::EngineeringUnits.MassFlux ToClassic(this global::EngineeringUnits.Fast.MassFlux value) => new(value.SI, global::EngineeringUnits.Units.MassFluxUnit.SI);

    /// <summary>The same MassMomentOfInertia as an EngineeringUnits.Fast struct. Null throws: use <c>value?.ToFast()</c> to pass null through.</summary>
    public static global::EngineeringUnits.Fast.MassMomentOfInertia ToFast(this global::EngineeringUnits.MassMomentOfInertia value) => (global::EngineeringUnits.Fast.MassMomentOfInertia?)value ?? throw new ArgumentNullException(nameof(value));

    /// <summary>The same MassMomentOfInertia as an EngineeringUnits object, in its SI unit.</summary>
    public static global::EngineeringUnits.MassMomentOfInertia ToClassic(this global::EngineeringUnits.Fast.MassMomentOfInertia value) => new(value.SI, global::EngineeringUnits.Units.MassMomentOfInertiaUnit.SI);

    /// <summary>The same MolarEnergy as an EngineeringUnits.Fast struct. Null throws: use <c>value?.ToFast()</c> to pass null through.</summary>
    public static global::EngineeringUnits.Fast.MolarEnergy ToFast(this global::EngineeringUnits.MolarEnergy value) => (global::EngineeringUnits.Fast.MolarEnergy?)value ?? throw new ArgumentNullException(nameof(value));

    /// <summary>The same MolarEnergy as an EngineeringUnits object, in its SI unit.</summary>
    public static global::EngineeringUnits.MolarEnergy ToClassic(this global::EngineeringUnits.Fast.MolarEnergy value) => new(value.SI, global::EngineeringUnits.Units.MolarEnergyUnit.SI);

    /// <summary>The same MolarEntropy as an EngineeringUnits.Fast struct. Null throws: use <c>value?.ToFast()</c> to pass null through.</summary>
    public static global::EngineeringUnits.Fast.MolarEntropy ToFast(this global::EngineeringUnits.MolarEntropy value) => (global::EngineeringUnits.Fast.MolarEntropy?)value ?? throw new ArgumentNullException(nameof(value));

    /// <summary>The same MolarEntropy as an EngineeringUnits object, in its SI unit.</summary>
    public static global::EngineeringUnits.MolarEntropy ToClassic(this global::EngineeringUnits.Fast.MolarEntropy value) => new(value.SI, global::EngineeringUnits.Units.MolarEntropyUnit.SI);

    /// <summary>The same MolarFlow as an EngineeringUnits.Fast struct. Null throws: use <c>value?.ToFast()</c> to pass null through.</summary>
    public static global::EngineeringUnits.Fast.MolarFlow ToFast(this global::EngineeringUnits.MolarFlow value) => (global::EngineeringUnits.Fast.MolarFlow?)value ?? throw new ArgumentNullException(nameof(value));

    /// <summary>The same MolarFlow as an EngineeringUnits object, in its SI unit.</summary>
    public static global::EngineeringUnits.MolarFlow ToClassic(this global::EngineeringUnits.Fast.MolarFlow value) => new(value.SI, global::EngineeringUnits.Units.MolarFlowUnit.SI);

    /// <summary>The same MolarMass as an EngineeringUnits.Fast struct. Null throws: use <c>value?.ToFast()</c> to pass null through.</summary>
    public static global::EngineeringUnits.Fast.MolarMass ToFast(this global::EngineeringUnits.MolarMass value) => (global::EngineeringUnits.Fast.MolarMass?)value ?? throw new ArgumentNullException(nameof(value));

    /// <summary>The same MolarMass as an EngineeringUnits object, in its SI unit.</summary>
    public static global::EngineeringUnits.MolarMass ToClassic(this global::EngineeringUnits.Fast.MolarMass value) => new(value.SI, global::EngineeringUnits.Units.MolarMassUnit.SI);

    /// <summary>The same Molarity as an EngineeringUnits.Fast struct. Null throws: use <c>value?.ToFast()</c> to pass null through.</summary>
    public static global::EngineeringUnits.Fast.Molarity ToFast(this global::EngineeringUnits.Molarity value) => (global::EngineeringUnits.Fast.Molarity?)value ?? throw new ArgumentNullException(nameof(value));

    /// <summary>The same Molarity as an EngineeringUnits object, in its SI unit.</summary>
    public static global::EngineeringUnits.Molarity ToClassic(this global::EngineeringUnits.Fast.Molarity value) => new(value.SI, global::EngineeringUnits.Units.MolarityUnit.SI);

    /// <summary>The same Permeability as an EngineeringUnits.Fast struct. Null throws: use <c>value?.ToFast()</c> to pass null through.</summary>
    public static global::EngineeringUnits.Fast.Permeability ToFast(this global::EngineeringUnits.Permeability value) => (global::EngineeringUnits.Fast.Permeability?)value ?? throw new ArgumentNullException(nameof(value));

    /// <summary>The same Permeability as an EngineeringUnits object, in its SI unit.</summary>
    public static global::EngineeringUnits.Permeability ToClassic(this global::EngineeringUnits.Fast.Permeability value) => new(value.SI, global::EngineeringUnits.Units.PermeabilityUnit.SI);

    /// <summary>The same Permittivity as an EngineeringUnits.Fast struct. Null throws: use <c>value?.ToFast()</c> to pass null through.</summary>
    public static global::EngineeringUnits.Fast.Permittivity ToFast(this global::EngineeringUnits.Permittivity value) => (global::EngineeringUnits.Fast.Permittivity?)value ?? throw new ArgumentNullException(nameof(value));

    /// <summary>The same Permittivity as an EngineeringUnits object, in its SI unit.</summary>
    public static global::EngineeringUnits.Permittivity ToClassic(this global::EngineeringUnits.Fast.Permittivity value) => new(value.SI, global::EngineeringUnits.Units.PermittivityUnit.SI);

    /// <summary>The same PipeSize as an EngineeringUnits.Fast struct. Null throws: use <c>value?.ToFast()</c> to pass null through.</summary>
    public static global::EngineeringUnits.Fast.PipeSize ToFast(this global::EngineeringUnits.PipeSize value) => (global::EngineeringUnits.Fast.PipeSize?)value ?? throw new ArgumentNullException(nameof(value));

    /// <summary>The same PipeSize as an EngineeringUnits object, in its SI unit.</summary>
    public static global::EngineeringUnits.PipeSize ToClassic(this global::EngineeringUnits.Fast.PipeSize value) => new(value.SI, global::EngineeringUnits.Units.PipeSizeUnit.SI);

    /// <summary>The same Power as an EngineeringUnits.Fast struct. Null throws: use <c>value?.ToFast()</c> to pass null through.</summary>
    public static global::EngineeringUnits.Fast.Power ToFast(this global::EngineeringUnits.Power value) => (global::EngineeringUnits.Fast.Power?)value ?? throw new ArgumentNullException(nameof(value));

    /// <summary>The same Power as an EngineeringUnits object, in its SI unit.</summary>
    public static global::EngineeringUnits.Power ToClassic(this global::EngineeringUnits.Fast.Power value) => new(value.SI, global::EngineeringUnits.Units.PowerUnit.SI);

    /// <summary>The same PowerCost as an EngineeringUnits.Fast struct. Null throws: use <c>value?.ToFast()</c> to pass null through.</summary>
    public static global::EngineeringUnits.Fast.PowerCost ToFast(this global::EngineeringUnits.PowerCost value) => (global::EngineeringUnits.Fast.PowerCost?)value ?? throw new ArgumentNullException(nameof(value));

    /// <summary>The same PowerCost as an EngineeringUnits object, in its SI unit.</summary>
    public static global::EngineeringUnits.PowerCost ToClassic(this global::EngineeringUnits.Fast.PowerCost value) => new(value.SI, global::EngineeringUnits.Units.PowerCostUnit.SI);

    /// <summary>The same PowerDensity as an EngineeringUnits.Fast struct. Null throws: use <c>value?.ToFast()</c> to pass null through.</summary>
    public static global::EngineeringUnits.Fast.PowerDensity ToFast(this global::EngineeringUnits.PowerDensity value) => (global::EngineeringUnits.Fast.PowerDensity?)value ?? throw new ArgumentNullException(nameof(value));

    /// <summary>The same PowerDensity as an EngineeringUnits object, in its SI unit.</summary>
    public static global::EngineeringUnits.PowerDensity ToClassic(this global::EngineeringUnits.Fast.PowerDensity value) => new(value.SI, global::EngineeringUnits.Units.PowerDensityUnit.SI);

    /// <summary>The same Pressure as an EngineeringUnits.Fast struct. Null throws: use <c>value?.ToFast()</c> to pass null through.</summary>
    public static global::EngineeringUnits.Fast.Pressure ToFast(this global::EngineeringUnits.Pressure value) => (global::EngineeringUnits.Fast.Pressure?)value ?? throw new ArgumentNullException(nameof(value));

    /// <summary>The same Pressure as an EngineeringUnits object, in its SI unit.</summary>
    public static global::EngineeringUnits.Pressure ToClassic(this global::EngineeringUnits.Fast.Pressure value) => new(value.SI, global::EngineeringUnits.Units.PressureUnit.SI);

    /// <summary>The same PressureChangeRate as an EngineeringUnits.Fast struct. Null throws: use <c>value?.ToFast()</c> to pass null through.</summary>
    public static global::EngineeringUnits.Fast.PressureChangeRate ToFast(this global::EngineeringUnits.PressureChangeRate value) => (global::EngineeringUnits.Fast.PressureChangeRate?)value ?? throw new ArgumentNullException(nameof(value));

    /// <summary>The same PressureChangeRate as an EngineeringUnits object, in its SI unit.</summary>
    public static global::EngineeringUnits.PressureChangeRate ToClassic(this global::EngineeringUnits.Fast.PressureChangeRate value) => new(value.SI, global::EngineeringUnits.Units.PressureChangeRateUnit.SI);

    /// <summary>The same Ratio as an EngineeringUnits.Fast struct. Null throws: use <c>value?.ToFast()</c> to pass null through.</summary>
    public static global::EngineeringUnits.Fast.Ratio ToFast(this global::EngineeringUnits.Ratio value) => (global::EngineeringUnits.Fast.Ratio?)value ?? throw new ArgumentNullException(nameof(value));

    /// <summary>The same Ratio as an EngineeringUnits object, in its SI unit.</summary>
    public static global::EngineeringUnits.Ratio ToClassic(this global::EngineeringUnits.Fast.Ratio value) => new(value.SI, global::EngineeringUnits.Units.RatioUnit.SI);

    /// <summary>The same ReactiveEnergy as an EngineeringUnits.Fast struct. Null throws: use <c>value?.ToFast()</c> to pass null through.</summary>
    public static global::EngineeringUnits.Fast.ReactiveEnergy ToFast(this global::EngineeringUnits.ReactiveEnergy value) => (global::EngineeringUnits.Fast.ReactiveEnergy?)value ?? throw new ArgumentNullException(nameof(value));

    /// <summary>The same ReactiveEnergy as an EngineeringUnits object, in its SI unit.</summary>
    public static global::EngineeringUnits.ReactiveEnergy ToClassic(this global::EngineeringUnits.Fast.ReactiveEnergy value) => new(value.SI, global::EngineeringUnits.Units.ReactiveEnergyUnit.SI);

    /// <summary>The same ReactivePower as an EngineeringUnits.Fast struct. Null throws: use <c>value?.ToFast()</c> to pass null through.</summary>
    public static global::EngineeringUnits.Fast.ReactivePower ToFast(this global::EngineeringUnits.ReactivePower value) => (global::EngineeringUnits.Fast.ReactivePower?)value ?? throw new ArgumentNullException(nameof(value));

    /// <summary>The same ReactivePower as an EngineeringUnits object, in its SI unit.</summary>
    public static global::EngineeringUnits.ReactivePower ToClassic(this global::EngineeringUnits.Fast.ReactivePower value) => new(value.SI, global::EngineeringUnits.Units.ReactivePowerUnit.SI);

    /// <summary>The same RotationalSpeed as an EngineeringUnits.Fast struct. Null throws: use <c>value?.ToFast()</c> to pass null through.</summary>
    public static global::EngineeringUnits.Fast.RotationalSpeed ToFast(this global::EngineeringUnits.RotationalSpeed value) => (global::EngineeringUnits.Fast.RotationalSpeed?)value ?? throw new ArgumentNullException(nameof(value));

    /// <summary>The same RotationalSpeed as an EngineeringUnits object, in its SI unit.</summary>
    public static global::EngineeringUnits.RotationalSpeed ToClassic(this global::EngineeringUnits.Fast.RotationalSpeed value) => new(value.SI, global::EngineeringUnits.Units.RotationalSpeedUnit.SI);

    /// <summary>The same Snap as an EngineeringUnits.Fast struct. Null throws: use <c>value?.ToFast()</c> to pass null through.</summary>
    public static global::EngineeringUnits.Fast.Snap ToFast(this global::EngineeringUnits.Snap value) => (global::EngineeringUnits.Fast.Snap?)value ?? throw new ArgumentNullException(nameof(value));

    /// <summary>The same Snap as an EngineeringUnits object, in its SI unit.</summary>
    public static global::EngineeringUnits.Snap ToClassic(this global::EngineeringUnits.Fast.Snap value) => new(value.SI, global::EngineeringUnits.Units.SnapUnit.SI);

    /// <summary>The same SpecificEnergy as an EngineeringUnits.Fast struct. Null throws: use <c>value?.ToFast()</c> to pass null through.</summary>
    public static global::EngineeringUnits.Fast.SpecificEnergy ToFast(this global::EngineeringUnits.SpecificEnergy value) => (global::EngineeringUnits.Fast.SpecificEnergy?)value ?? throw new ArgumentNullException(nameof(value));

    /// <summary>The same SpecificEnergy as an EngineeringUnits object, in its SI unit.</summary>
    public static global::EngineeringUnits.SpecificEnergy ToClassic(this global::EngineeringUnits.Fast.SpecificEnergy value) => new(value.SI, global::EngineeringUnits.Units.SpecificEnergyUnit.SI);

    /// <summary>The same SpecificEntropy as an EngineeringUnits.Fast struct. Null throws: use <c>value?.ToFast()</c> to pass null through.</summary>
    public static global::EngineeringUnits.Fast.SpecificEntropy ToFast(this global::EngineeringUnits.SpecificEntropy value) => (global::EngineeringUnits.Fast.SpecificEntropy?)value ?? throw new ArgumentNullException(nameof(value));

    /// <summary>The same SpecificEntropy as an EngineeringUnits object, in its SI unit.</summary>
    public static global::EngineeringUnits.SpecificEntropy ToClassic(this global::EngineeringUnits.Fast.SpecificEntropy value) => new(value.SI, global::EngineeringUnits.Units.SpecificEntropyUnit.SI);

    /// <summary>The same SpecificHeatCapacity as an EngineeringUnits.Fast struct. Null throws: use <c>value?.ToFast()</c> to pass null through.</summary>
    public static global::EngineeringUnits.Fast.SpecificHeatCapacity ToFast(this global::EngineeringUnits.SpecificHeatCapacity value) => (global::EngineeringUnits.Fast.SpecificHeatCapacity?)value ?? throw new ArgumentNullException(nameof(value));

    /// <summary>The same SpecificHeatCapacity as an EngineeringUnits object, in its SI unit.</summary>
    public static global::EngineeringUnits.SpecificHeatCapacity ToClassic(this global::EngineeringUnits.Fast.SpecificHeatCapacity value) => new(value.SI, global::EngineeringUnits.Units.SpecificHeatCapacityUnit.SI);

    /// <summary>The same SpecificThermalResistance as an EngineeringUnits.Fast struct. Null throws: use <c>value?.ToFast()</c> to pass null through.</summary>
    public static global::EngineeringUnits.Fast.SpecificThermalResistance ToFast(this global::EngineeringUnits.SpecificThermalResistance value) => (global::EngineeringUnits.Fast.SpecificThermalResistance?)value ?? throw new ArgumentNullException(nameof(value));

    /// <summary>The same SpecificThermalResistance as an EngineeringUnits object, in its SI unit.</summary>
    public static global::EngineeringUnits.SpecificThermalResistance ToClassic(this global::EngineeringUnits.Fast.SpecificThermalResistance value) => new(value.SI, global::EngineeringUnits.Units.SpecificThermalResistanceUnit.SI);

    /// <summary>The same SpecificVolume as an EngineeringUnits.Fast struct. Null throws: use <c>value?.ToFast()</c> to pass null through.</summary>
    public static global::EngineeringUnits.Fast.SpecificVolume ToFast(this global::EngineeringUnits.SpecificVolume value) => (global::EngineeringUnits.Fast.SpecificVolume?)value ?? throw new ArgumentNullException(nameof(value));

    /// <summary>The same SpecificVolume as an EngineeringUnits object, in its SI unit.</summary>
    public static global::EngineeringUnits.SpecificVolume ToClassic(this global::EngineeringUnits.Fast.SpecificVolume value) => new(value.SI, global::EngineeringUnits.Units.SpecificVolumeUnit.SI);

    /// <summary>The same SpecificWeight as an EngineeringUnits.Fast struct. Null throws: use <c>value?.ToFast()</c> to pass null through.</summary>
    public static global::EngineeringUnits.Fast.SpecificWeight ToFast(this global::EngineeringUnits.SpecificWeight value) => (global::EngineeringUnits.Fast.SpecificWeight?)value ?? throw new ArgumentNullException(nameof(value));

    /// <summary>The same SpecificWeight as an EngineeringUnits object, in its SI unit.</summary>
    public static global::EngineeringUnits.SpecificWeight ToClassic(this global::EngineeringUnits.Fast.SpecificWeight value) => new(value.SI, global::EngineeringUnits.Units.SpecificWeightUnit.SI);

    /// <summary>The same Speed as an EngineeringUnits.Fast struct. Null throws: use <c>value?.ToFast()</c> to pass null through.</summary>
    public static global::EngineeringUnits.Fast.Speed ToFast(this global::EngineeringUnits.Speed value) => (global::EngineeringUnits.Fast.Speed?)value ?? throw new ArgumentNullException(nameof(value));

    /// <summary>The same Speed as an EngineeringUnits object, in its SI unit.</summary>
    public static global::EngineeringUnits.Speed ToClassic(this global::EngineeringUnits.Fast.Speed value) => new(value.SI, global::EngineeringUnits.Units.SpeedUnit.SI);

    /// <summary>The same Temperature as an EngineeringUnits.Fast struct. Null throws: use <c>value?.ToFast()</c> to pass null through.</summary>
    public static global::EngineeringUnits.Fast.Temperature ToFast(this global::EngineeringUnits.Temperature value) => (global::EngineeringUnits.Fast.Temperature?)value ?? throw new ArgumentNullException(nameof(value));

    /// <summary>The same Temperature as an EngineeringUnits object, in its SI unit.</summary>
    public static global::EngineeringUnits.Temperature ToClassic(this global::EngineeringUnits.Fast.Temperature value) => new(value.SI, global::EngineeringUnits.Units.TemperatureUnit.SI);

    /// <summary>The same TemperatureChangeRate as an EngineeringUnits.Fast struct. Null throws: use <c>value?.ToFast()</c> to pass null through.</summary>
    public static global::EngineeringUnits.Fast.TemperatureChangeRate ToFast(this global::EngineeringUnits.TemperatureChangeRate value) => (global::EngineeringUnits.Fast.TemperatureChangeRate?)value ?? throw new ArgumentNullException(nameof(value));

    /// <summary>The same TemperatureChangeRate as an EngineeringUnits object, in its SI unit.</summary>
    public static global::EngineeringUnits.TemperatureChangeRate ToClassic(this global::EngineeringUnits.Fast.TemperatureChangeRate value) => new(value.SI, global::EngineeringUnits.Units.TemperatureChangeRateUnit.SI);

    /// <summary>The same ThermalConductivity as an EngineeringUnits.Fast struct. Null throws: use <c>value?.ToFast()</c> to pass null through.</summary>
    public static global::EngineeringUnits.Fast.ThermalConductivity ToFast(this global::EngineeringUnits.ThermalConductivity value) => (global::EngineeringUnits.Fast.ThermalConductivity?)value ?? throw new ArgumentNullException(nameof(value));

    /// <summary>The same ThermalConductivity as an EngineeringUnits object, in its SI unit.</summary>
    public static global::EngineeringUnits.ThermalConductivity ToClassic(this global::EngineeringUnits.Fast.ThermalConductivity value) => new(value.SI, global::EngineeringUnits.Units.ThermalConductivityUnit.SI);

    /// <summary>The same ThermalResistance as an EngineeringUnits.Fast struct. Null throws: use <c>value?.ToFast()</c> to pass null through.</summary>
    public static global::EngineeringUnits.Fast.ThermalResistance ToFast(this global::EngineeringUnits.ThermalResistance value) => (global::EngineeringUnits.Fast.ThermalResistance?)value ?? throw new ArgumentNullException(nameof(value));

    /// <summary>The same ThermalResistance as an EngineeringUnits object, in its SI unit.</summary>
    public static global::EngineeringUnits.ThermalResistance ToClassic(this global::EngineeringUnits.Fast.ThermalResistance value) => new(value.SI, global::EngineeringUnits.Units.ThermalResistanceUnit.SI);

    /// <summary>The same Torque as an EngineeringUnits.Fast struct. Null throws: use <c>value?.ToFast()</c> to pass null through.</summary>
    public static global::EngineeringUnits.Fast.Torque ToFast(this global::EngineeringUnits.Torque value) => (global::EngineeringUnits.Fast.Torque?)value ?? throw new ArgumentNullException(nameof(value));

    /// <summary>The same Torque as an EngineeringUnits object, in its SI unit.</summary>
    public static global::EngineeringUnits.Torque ToClassic(this global::EngineeringUnits.Fast.Torque value) => new(value.SI, global::EngineeringUnits.Units.TorqueUnit.SI);

    /// <summary>The same TorquePerLength as an EngineeringUnits.Fast struct. Null throws: use <c>value?.ToFast()</c> to pass null through.</summary>
    public static global::EngineeringUnits.Fast.TorquePerLength ToFast(this global::EngineeringUnits.TorquePerLength value) => (global::EngineeringUnits.Fast.TorquePerLength?)value ?? throw new ArgumentNullException(nameof(value));

    /// <summary>The same TorquePerLength as an EngineeringUnits object, in its SI unit.</summary>
    public static global::EngineeringUnits.TorquePerLength ToClassic(this global::EngineeringUnits.Fast.TorquePerLength value) => new(value.SI, global::EngineeringUnits.Units.TorquePerLengthUnit.SI);

    /// <summary>The same Volume as an EngineeringUnits.Fast struct. Null throws: use <c>value?.ToFast()</c> to pass null through.</summary>
    public static global::EngineeringUnits.Fast.Volume ToFast(this global::EngineeringUnits.Volume value) => (global::EngineeringUnits.Fast.Volume?)value ?? throw new ArgumentNullException(nameof(value));

    /// <summary>The same Volume as an EngineeringUnits object, in its SI unit.</summary>
    public static global::EngineeringUnits.Volume ToClassic(this global::EngineeringUnits.Fast.Volume value) => new(value.SI, global::EngineeringUnits.Units.VolumeUnit.SI);

    /// <summary>The same VolumeCost as an EngineeringUnits.Fast struct. Null throws: use <c>value?.ToFast()</c> to pass null through.</summary>
    public static global::EngineeringUnits.Fast.VolumeCost ToFast(this global::EngineeringUnits.VolumeCost value) => (global::EngineeringUnits.Fast.VolumeCost?)value ?? throw new ArgumentNullException(nameof(value));

    /// <summary>The same VolumeCost as an EngineeringUnits object, in its SI unit.</summary>
    public static global::EngineeringUnits.VolumeCost ToClassic(this global::EngineeringUnits.Fast.VolumeCost value) => new(value.SI, global::EngineeringUnits.Units.VolumeCostUnit.SI);

    /// <summary>The same VolumeFlow as an EngineeringUnits.Fast struct. Null throws: use <c>value?.ToFast()</c> to pass null through.</summary>
    public static global::EngineeringUnits.Fast.VolumeFlow ToFast(this global::EngineeringUnits.VolumeFlow value) => (global::EngineeringUnits.Fast.VolumeFlow?)value ?? throw new ArgumentNullException(nameof(value));

    /// <summary>The same VolumeFlow as an EngineeringUnits object, in its SI unit.</summary>
    public static global::EngineeringUnits.VolumeFlow ToClassic(this global::EngineeringUnits.Fast.VolumeFlow value) => new(value.SI, global::EngineeringUnits.Units.VolumeFlowUnit.SI);

    /// <summary>The same VolumePerLength as an EngineeringUnits.Fast struct. Null throws: use <c>value?.ToFast()</c> to pass null through.</summary>
    public static global::EngineeringUnits.Fast.VolumePerLength ToFast(this global::EngineeringUnits.VolumePerLength value) => (global::EngineeringUnits.Fast.VolumePerLength?)value ?? throw new ArgumentNullException(nameof(value));

    /// <summary>The same VolumePerLength as an EngineeringUnits object, in its SI unit.</summary>
    public static global::EngineeringUnits.VolumePerLength ToClassic(this global::EngineeringUnits.Fast.VolumePerLength value) => new(value.SI, global::EngineeringUnits.Units.VolumePerLengthUnit.SI);

    /// <summary>The same VolumetricHeatTransferCoefficient as an EngineeringUnits.Fast struct. Null throws: use <c>value?.ToFast()</c> to pass null through.</summary>
    public static global::EngineeringUnits.Fast.VolumetricHeatTransferCoefficient ToFast(this global::EngineeringUnits.VolumetricHeatTransferCoefficient value) => (global::EngineeringUnits.Fast.VolumetricHeatTransferCoefficient?)value ?? throw new ArgumentNullException(nameof(value));

    /// <summary>The same VolumetricHeatTransferCoefficient as an EngineeringUnits object, in its SI unit.</summary>
    public static global::EngineeringUnits.VolumetricHeatTransferCoefficient ToClassic(this global::EngineeringUnits.Fast.VolumetricHeatTransferCoefficient value) => new(value.SI, global::EngineeringUnits.Units.VolumetricHeatTransferCoefficientUnit.SI);

    /// <summary>The same WarpingMomentOfInertia as an EngineeringUnits.Fast struct. Null throws: use <c>value?.ToFast()</c> to pass null through.</summary>
    public static global::EngineeringUnits.Fast.WarpingMomentOfInertia ToFast(this global::EngineeringUnits.WarpingMomentOfInertia value) => (global::EngineeringUnits.Fast.WarpingMomentOfInertia?)value ?? throw new ArgumentNullException(nameof(value));

    /// <summary>The same WarpingMomentOfInertia as an EngineeringUnits object, in its SI unit.</summary>
    public static global::EngineeringUnits.WarpingMomentOfInertia ToClassic(this global::EngineeringUnits.Fast.WarpingMomentOfInertia value) => new(value.SI, global::EngineeringUnits.Units.WarpingMomentOfInertiaUnit.SI);

}
#endif
