// <auto-generated/>
// Generated by CodeGen.Fast from the EngineeringUnits unit definitions - changes will be overwritten!
#nullable enable
// EngineeringUnits.Fast only targets net10.0
#if NET10_0_OR_GREATER

namespace EngineeringUnits
{
    public partial class Acceleration
    {
        /// <summary>
        /// The same Acceleration as an EngineeringUnits.Fast struct: its exact SI value rounded once to the nearest double. Null stays null. The EngineeringUnits.Fast
        /// analyzer reports every use as EUF0009 (info), so the places still taking EngineeringUnits values can be listed.
        /// </summary>
        public static implicit operator global::EngineeringUnits.Fast.Acceleration?(Acceleration? value) =>
            value is null ? null : global::EngineeringUnits.Fast.Acceleration.FromSI(FastConversion.SI(value, global::EngineeringUnits.Units.AccelerationUnit.SI));
    }

    public partial class AmountOfSubstance
    {
        /// <summary>
        /// The same AmountOfSubstance as an EngineeringUnits.Fast struct: its exact SI value rounded once to the nearest double. Null stays null. The EngineeringUnits.Fast
        /// analyzer reports every use as EUF0009 (info), so the places still taking EngineeringUnits values can be listed.
        /// </summary>
        public static implicit operator global::EngineeringUnits.Fast.AmountOfSubstance?(AmountOfSubstance? value) =>
            value is null ? null : global::EngineeringUnits.Fast.AmountOfSubstance.FromSI(FastConversion.SI(value, global::EngineeringUnits.Units.AmountOfSubstanceUnit.SI));
    }

    public partial class Angle
    {
        /// <summary>
        /// The same Angle as an EngineeringUnits.Fast struct: its exact SI value rounded once to the nearest double. Null stays null. The EngineeringUnits.Fast
        /// analyzer reports every use as EUF0009 (info), so the places still taking EngineeringUnits values can be listed.
        /// </summary>
        public static implicit operator global::EngineeringUnits.Fast.Angle?(Angle? value) =>
            value is null ? null : global::EngineeringUnits.Fast.Angle.FromSI(FastConversion.SI(value, global::EngineeringUnits.Units.AngleUnit.SI));
    }

    public partial class ApparentEnergy
    {
        /// <summary>
        /// The same ApparentEnergy as an EngineeringUnits.Fast struct: its exact SI value rounded once to the nearest double. Null stays null. The EngineeringUnits.Fast
        /// analyzer reports every use as EUF0009 (info), so the places still taking EngineeringUnits values can be listed.
        /// </summary>
        public static implicit operator global::EngineeringUnits.Fast.ApparentEnergy?(ApparentEnergy? value) =>
            value is null ? null : global::EngineeringUnits.Fast.ApparentEnergy.FromSI(FastConversion.SI(value, global::EngineeringUnits.Units.ApparentEnergyUnit.SI));
    }

    public partial class ApparentPower
    {
        /// <summary>
        /// The same ApparentPower as an EngineeringUnits.Fast struct: its exact SI value rounded once to the nearest double. Null stays null. The EngineeringUnits.Fast
        /// analyzer reports every use as EUF0009 (info), so the places still taking EngineeringUnits values can be listed.
        /// </summary>
        public static implicit operator global::EngineeringUnits.Fast.ApparentPower?(ApparentPower? value) =>
            value is null ? null : global::EngineeringUnits.Fast.ApparentPower.FromSI(FastConversion.SI(value, global::EngineeringUnits.Units.ApparentPowerUnit.SI));
    }

    public partial class Area
    {
        /// <summary>
        /// The same Area as an EngineeringUnits.Fast struct: its exact SI value rounded once to the nearest double. Null stays null. The EngineeringUnits.Fast
        /// analyzer reports every use as EUF0009 (info), so the places still taking EngineeringUnits values can be listed.
        /// </summary>
        public static implicit operator global::EngineeringUnits.Fast.Area?(Area? value) =>
            value is null ? null : global::EngineeringUnits.Fast.Area.FromSI(FastConversion.SI(value, global::EngineeringUnits.Units.AreaUnit.SI));
    }

    public partial class AreaCost
    {
        /// <summary>
        /// The same AreaCost as an EngineeringUnits.Fast struct: its exact SI value rounded once to the nearest double. Null stays null. The EngineeringUnits.Fast
        /// analyzer reports every use as EUF0009 (info), so the places still taking EngineeringUnits values can be listed.
        /// </summary>
        public static implicit operator global::EngineeringUnits.Fast.AreaCost?(AreaCost? value) =>
            value is null ? null : global::EngineeringUnits.Fast.AreaCost.FromSI(FastConversion.SI(value, global::EngineeringUnits.Units.AreaCostUnit.SI));
    }

    public partial class AreaDensity
    {
        /// <summary>
        /// The same AreaDensity as an EngineeringUnits.Fast struct: its exact SI value rounded once to the nearest double. Null stays null. The EngineeringUnits.Fast
        /// analyzer reports every use as EUF0009 (info), so the places still taking EngineeringUnits values can be listed.
        /// </summary>
        public static implicit operator global::EngineeringUnits.Fast.AreaDensity?(AreaDensity? value) =>
            value is null ? null : global::EngineeringUnits.Fast.AreaDensity.FromSI(FastConversion.SI(value, global::EngineeringUnits.Units.AreaDensityUnit.SI));
    }

    public partial class AreaMomentOfInertia
    {
        /// <summary>
        /// The same AreaMomentOfInertia as an EngineeringUnits.Fast struct: its exact SI value rounded once to the nearest double. Null stays null. The EngineeringUnits.Fast
        /// analyzer reports every use as EUF0009 (info), so the places still taking EngineeringUnits values can be listed.
        /// </summary>
        public static implicit operator global::EngineeringUnits.Fast.AreaMomentOfInertia?(AreaMomentOfInertia? value) =>
            value is null ? null : global::EngineeringUnits.Fast.AreaMomentOfInertia.FromSI(FastConversion.SI(value, global::EngineeringUnits.Units.AreaMomentOfInertiaUnit.SI));
    }

    public partial class BitRate
    {
        /// <summary>
        /// The same BitRate as an EngineeringUnits.Fast struct: its exact SI value rounded once to the nearest double. Null stays null. The EngineeringUnits.Fast
        /// analyzer reports every use as EUF0009 (info), so the places still taking EngineeringUnits values can be listed.
        /// </summary>
        public static implicit operator global::EngineeringUnits.Fast.BitRate?(BitRate? value) =>
            value is null ? null : global::EngineeringUnits.Fast.BitRate.FromSI(FastConversion.SI(value, global::EngineeringUnits.Units.BitRateUnit.SI));
    }

    public partial class BrakeSpecificFuelConsumption
    {
        /// <summary>
        /// The same BrakeSpecificFuelConsumption as an EngineeringUnits.Fast struct: its exact SI value rounded once to the nearest double. Null stays null. The EngineeringUnits.Fast
        /// analyzer reports every use as EUF0009 (info), so the places still taking EngineeringUnits values can be listed.
        /// </summary>
        public static implicit operator global::EngineeringUnits.Fast.BrakeSpecificFuelConsumption?(BrakeSpecificFuelConsumption? value) =>
            value is null ? null : global::EngineeringUnits.Fast.BrakeSpecificFuelConsumption.FromSI(FastConversion.SI(value, global::EngineeringUnits.Units.BrakeSpecificFuelConsumptionUnit.SI));
    }

    public partial class Capacitance
    {
        /// <summary>
        /// The same Capacitance as an EngineeringUnits.Fast struct: its exact SI value rounded once to the nearest double. Null stays null. The EngineeringUnits.Fast
        /// analyzer reports every use as EUF0009 (info), so the places still taking EngineeringUnits values can be listed.
        /// </summary>
        public static implicit operator global::EngineeringUnits.Fast.Capacitance?(Capacitance? value) =>
            value is null ? null : global::EngineeringUnits.Fast.Capacitance.FromSI(FastConversion.SI(value, global::EngineeringUnits.Units.CapacitanceUnit.SI));
    }

    public partial class CoefficientOfThermalExpansion
    {
        /// <summary>
        /// The same CoefficientOfThermalExpansion as an EngineeringUnits.Fast struct: its exact SI value rounded once to the nearest double. Null stays null. The EngineeringUnits.Fast
        /// analyzer reports every use as EUF0009 (info), so the places still taking EngineeringUnits values can be listed.
        /// </summary>
        public static implicit operator global::EngineeringUnits.Fast.CoefficientOfThermalExpansion?(CoefficientOfThermalExpansion? value) =>
            value is null ? null : global::EngineeringUnits.Fast.CoefficientOfThermalExpansion.FromSI(FastConversion.SI(value, global::EngineeringUnits.Units.CoefficientOfThermalExpansionUnit.SI));
    }

    public partial class Cost
    {
        /// <summary>
        /// The same Cost as an EngineeringUnits.Fast struct: its exact SI value rounded once to the nearest double. Null stays null. The EngineeringUnits.Fast
        /// analyzer reports every use as EUF0009 (info), so the places still taking EngineeringUnits values can be listed.
        /// </summary>
        public static implicit operator global::EngineeringUnits.Fast.Cost?(Cost? value) =>
            value is null ? null : global::EngineeringUnits.Fast.Cost.FromSI(FastConversion.SI(value, global::EngineeringUnits.Units.CostUnit.SI));
    }

    public partial class Density
    {
        /// <summary>
        /// The same Density as an EngineeringUnits.Fast struct: its exact SI value rounded once to the nearest double. Null stays null. The EngineeringUnits.Fast
        /// analyzer reports every use as EUF0009 (info), so the places still taking EngineeringUnits values can be listed.
        /// </summary>
        public static implicit operator global::EngineeringUnits.Fast.Density?(Density? value) =>
            value is null ? null : global::EngineeringUnits.Fast.Density.FromSI(FastConversion.SI(value, global::EngineeringUnits.Units.DensityUnit.SI));
    }

    public partial class Dimensionless
    {
        /// <summary>
        /// The same Dimensionless as an EngineeringUnits.Fast struct: its exact SI value rounded once to the nearest double. Null stays null. The EngineeringUnits.Fast
        /// analyzer reports every use as EUF0009 (info), so the places still taking EngineeringUnits values can be listed.
        /// </summary>
        public static implicit operator global::EngineeringUnits.Fast.Dimensionless?(Dimensionless? value) =>
            value is null ? null : global::EngineeringUnits.Fast.Dimensionless.FromSI(FastConversion.SI(value, global::EngineeringUnits.Units.DimensionlessUnit.SI));
    }

    public partial class Duration
    {
        /// <summary>
        /// The same Duration as an EngineeringUnits.Fast struct: its exact SI value rounded once to the nearest double. Null stays null. The EngineeringUnits.Fast
        /// analyzer reports every use as EUF0009 (info), so the places still taking EngineeringUnits values can be listed.
        /// </summary>
        public static implicit operator global::EngineeringUnits.Fast.Duration?(Duration? value) =>
            value is null ? null : global::EngineeringUnits.Fast.Duration.FromSI(FastConversion.SI(value, global::EngineeringUnits.Units.DurationUnit.SI));
    }

    public partial class DurationCost
    {
        /// <summary>
        /// The same DurationCost as an EngineeringUnits.Fast struct: its exact SI value rounded once to the nearest double. Null stays null. The EngineeringUnits.Fast
        /// analyzer reports every use as EUF0009 (info), so the places still taking EngineeringUnits values can be listed.
        /// </summary>
        public static implicit operator global::EngineeringUnits.Fast.DurationCost?(DurationCost? value) =>
            value is null ? null : global::EngineeringUnits.Fast.DurationCost.FromSI(FastConversion.SI(value, global::EngineeringUnits.Units.DurationCostUnit.SI));
    }

    public partial class DynamicViscosity
    {
        /// <summary>
        /// The same DynamicViscosity as an EngineeringUnits.Fast struct: its exact SI value rounded once to the nearest double. Null stays null. The EngineeringUnits.Fast
        /// analyzer reports every use as EUF0009 (info), so the places still taking EngineeringUnits values can be listed.
        /// </summary>
        public static implicit operator global::EngineeringUnits.Fast.DynamicViscosity?(DynamicViscosity? value) =>
            value is null ? null : global::EngineeringUnits.Fast.DynamicViscosity.FromSI(FastConversion.SI(value, global::EngineeringUnits.Units.DynamicViscosityUnit.SI));
    }

    public partial class ElectricCharge
    {
        /// <summary>
        /// The same ElectricCharge as an EngineeringUnits.Fast struct: its exact SI value rounded once to the nearest double. Null stays null. The EngineeringUnits.Fast
        /// analyzer reports every use as EUF0009 (info), so the places still taking EngineeringUnits values can be listed.
        /// </summary>
        public static implicit operator global::EngineeringUnits.Fast.ElectricCharge?(ElectricCharge? value) =>
            value is null ? null : global::EngineeringUnits.Fast.ElectricCharge.FromSI(FastConversion.SI(value, global::EngineeringUnits.Units.ElectricChargeUnit.SI));
    }

    public partial class ElectricChargeDensity
    {
        /// <summary>
        /// The same ElectricChargeDensity as an EngineeringUnits.Fast struct: its exact SI value rounded once to the nearest double. Null stays null. The EngineeringUnits.Fast
        /// analyzer reports every use as EUF0009 (info), so the places still taking EngineeringUnits values can be listed.
        /// </summary>
        public static implicit operator global::EngineeringUnits.Fast.ElectricChargeDensity?(ElectricChargeDensity? value) =>
            value is null ? null : global::EngineeringUnits.Fast.ElectricChargeDensity.FromSI(FastConversion.SI(value, global::EngineeringUnits.Units.ElectricChargeDensityUnit.SI));
    }

    public partial class ElectricConductivity
    {
        /// <summary>
        /// The same ElectricConductivity as an EngineeringUnits.Fast struct: its exact SI value rounded once to the nearest double. Null stays null. The EngineeringUnits.Fast
        /// analyzer reports every use as EUF0009 (info), so the places still taking EngineeringUnits values can be listed.
        /// </summary>
        public static implicit operator global::EngineeringUnits.Fast.ElectricConductivity?(ElectricConductivity? value) =>
            value is null ? null : global::EngineeringUnits.Fast.ElectricConductivity.FromSI(FastConversion.SI(value, global::EngineeringUnits.Units.ElectricConductivityUnit.SI));
    }

    public partial class ElectricCurrent
    {
        /// <summary>
        /// The same ElectricCurrent as an EngineeringUnits.Fast struct: its exact SI value rounded once to the nearest double. Null stays null. The EngineeringUnits.Fast
        /// analyzer reports every use as EUF0009 (info), so the places still taking EngineeringUnits values can be listed.
        /// </summary>
        public static implicit operator global::EngineeringUnits.Fast.ElectricCurrent?(ElectricCurrent? value) =>
            value is null ? null : global::EngineeringUnits.Fast.ElectricCurrent.FromSI(FastConversion.SI(value, global::EngineeringUnits.Units.ElectricCurrentUnit.SI));
    }

    public partial class ElectricCurrentDensity
    {
        /// <summary>
        /// The same ElectricCurrentDensity as an EngineeringUnits.Fast struct: its exact SI value rounded once to the nearest double. Null stays null. The EngineeringUnits.Fast
        /// analyzer reports every use as EUF0009 (info), so the places still taking EngineeringUnits values can be listed.
        /// </summary>
        public static implicit operator global::EngineeringUnits.Fast.ElectricCurrentDensity?(ElectricCurrentDensity? value) =>
            value is null ? null : global::EngineeringUnits.Fast.ElectricCurrentDensity.FromSI(FastConversion.SI(value, global::EngineeringUnits.Units.ElectricCurrentDensityUnit.SI));
    }

    public partial class ElectricCurrentGradient
    {
        /// <summary>
        /// The same ElectricCurrentGradient as an EngineeringUnits.Fast struct: its exact SI value rounded once to the nearest double. Null stays null. The EngineeringUnits.Fast
        /// analyzer reports every use as EUF0009 (info), so the places still taking EngineeringUnits values can be listed.
        /// </summary>
        public static implicit operator global::EngineeringUnits.Fast.ElectricCurrentGradient?(ElectricCurrentGradient? value) =>
            value is null ? null : global::EngineeringUnits.Fast.ElectricCurrentGradient.FromSI(FastConversion.SI(value, global::EngineeringUnits.Units.ElectricCurrentGradientUnit.SI));
    }

    public partial class ElectricField
    {
        /// <summary>
        /// The same ElectricField as an EngineeringUnits.Fast struct: its exact SI value rounded once to the nearest double. Null stays null. The EngineeringUnits.Fast
        /// analyzer reports every use as EUF0009 (info), so the places still taking EngineeringUnits values can be listed.
        /// </summary>
        public static implicit operator global::EngineeringUnits.Fast.ElectricField?(ElectricField? value) =>
            value is null ? null : global::EngineeringUnits.Fast.ElectricField.FromSI(FastConversion.SI(value, global::EngineeringUnits.Units.ElectricFieldUnit.SI));
    }

    public partial class ElectricInductance
    {
        /// <summary>
        /// The same ElectricInductance as an EngineeringUnits.Fast struct: its exact SI value rounded once to the nearest double. Null stays null. The EngineeringUnits.Fast
        /// analyzer reports every use as EUF0009 (info), so the places still taking EngineeringUnits values can be listed.
        /// </summary>
        public static implicit operator global::EngineeringUnits.Fast.ElectricInductance?(ElectricInductance? value) =>
            value is null ? null : global::EngineeringUnits.Fast.ElectricInductance.FromSI(FastConversion.SI(value, global::EngineeringUnits.Units.ElectricInductanceUnit.SI));
    }

    public partial class ElectricPotential
    {
        /// <summary>
        /// The same ElectricPotential as an EngineeringUnits.Fast struct: its exact SI value rounded once to the nearest double. Null stays null. The EngineeringUnits.Fast
        /// analyzer reports every use as EUF0009 (info), so the places still taking EngineeringUnits values can be listed.
        /// </summary>
        public static implicit operator global::EngineeringUnits.Fast.ElectricPotential?(ElectricPotential? value) =>
            value is null ? null : global::EngineeringUnits.Fast.ElectricPotential.FromSI(FastConversion.SI(value, global::EngineeringUnits.Units.ElectricPotentialUnit.SI));
    }

    public partial class ElectricPotentialChangeRate
    {
        /// <summary>
        /// The same ElectricPotentialChangeRate as an EngineeringUnits.Fast struct: its exact SI value rounded once to the nearest double. Null stays null. The EngineeringUnits.Fast
        /// analyzer reports every use as EUF0009 (info), so the places still taking EngineeringUnits values can be listed.
        /// </summary>
        public static implicit operator global::EngineeringUnits.Fast.ElectricPotentialChangeRate?(ElectricPotentialChangeRate? value) =>
            value is null ? null : global::EngineeringUnits.Fast.ElectricPotentialChangeRate.FromSI(FastConversion.SI(value, global::EngineeringUnits.Units.ElectricPotentialChangeRateUnit.SI));
    }

    public partial class ElectricResistance
    {
        /// <summary>
        /// The same ElectricResistance as an EngineeringUnits.Fast struct: its exact SI value rounded once to the nearest double. Null stays null. The EngineeringUnits.Fast
        /// analyzer reports every use as EUF0009 (info), so the places still taking EngineeringUnits values can be listed.
        /// </summary>
        public static implicit operator global::EngineeringUnits.Fast.ElectricResistance?(ElectricResistance? value) =>
            value is null ? null : global::EngineeringUnits.Fast.ElectricResistance.FromSI(FastConversion.SI(value, global::EngineeringUnits.Units.ElectricResistanceUnit.SI));
    }

    public partial class ElectricResistivity
    {
        /// <summary>
        /// The same ElectricResistivity as an EngineeringUnits.Fast struct: its exact SI value rounded once to the nearest double. Null stays null. The EngineeringUnits.Fast
        /// analyzer reports every use as EUF0009 (info), so the places still taking EngineeringUnits values can be listed.
        /// </summary>
        public static implicit operator global::EngineeringUnits.Fast.ElectricResistivity?(ElectricResistivity? value) =>
            value is null ? null : global::EngineeringUnits.Fast.ElectricResistivity.FromSI(FastConversion.SI(value, global::EngineeringUnits.Units.ElectricResistivityUnit.SI));
    }

    public partial class ElectricSurfaceChargeDensity
    {
        /// <summary>
        /// The same ElectricSurfaceChargeDensity as an EngineeringUnits.Fast struct: its exact SI value rounded once to the nearest double. Null stays null. The EngineeringUnits.Fast
        /// analyzer reports every use as EUF0009 (info), so the places still taking EngineeringUnits values can be listed.
        /// </summary>
        public static implicit operator global::EngineeringUnits.Fast.ElectricSurfaceChargeDensity?(ElectricSurfaceChargeDensity? value) =>
            value is null ? null : global::EngineeringUnits.Fast.ElectricSurfaceChargeDensity.FromSI(FastConversion.SI(value, global::EngineeringUnits.Units.ElectricSurfaceChargeDensityUnit.SI));
    }

    public partial class Energy
    {
        /// <summary>
        /// The same Energy as an EngineeringUnits.Fast struct: its exact SI value rounded once to the nearest double. Null stays null. The EngineeringUnits.Fast
        /// analyzer reports every use as EUF0009 (info), so the places still taking EngineeringUnits values can be listed.
        /// </summary>
        public static implicit operator global::EngineeringUnits.Fast.Energy?(Energy? value) =>
            value is null ? null : global::EngineeringUnits.Fast.Energy.FromSI(FastConversion.SI(value, global::EngineeringUnits.Units.EnergyUnit.SI));
    }

    public partial class EnergyCost
    {
        /// <summary>
        /// The same EnergyCost as an EngineeringUnits.Fast struct: its exact SI value rounded once to the nearest double. Null stays null. The EngineeringUnits.Fast
        /// analyzer reports every use as EUF0009 (info), so the places still taking EngineeringUnits values can be listed.
        /// </summary>
        public static implicit operator global::EngineeringUnits.Fast.EnergyCost?(EnergyCost? value) =>
            value is null ? null : global::EngineeringUnits.Fast.EnergyCost.FromSI(FastConversion.SI(value, global::EngineeringUnits.Units.EnergyCostUnit.SI));
    }

    public partial class Enthalpy
    {
        /// <summary>
        /// The same Enthalpy as an EngineeringUnits.Fast struct: its exact SI value rounded once to the nearest double. Null stays null. The EngineeringUnits.Fast
        /// analyzer reports every use as EUF0009 (info), so the places still taking EngineeringUnits values can be listed.
        /// </summary>
        public static implicit operator global::EngineeringUnits.Fast.Enthalpy?(Enthalpy? value) =>
            value is null ? null : global::EngineeringUnits.Fast.Enthalpy.FromSI(FastConversion.SI(value, global::EngineeringUnits.Units.EnthalpyUnit.SI));
    }

    public partial class Entropy
    {
        /// <summary>
        /// The same Entropy as an EngineeringUnits.Fast struct: its exact SI value rounded once to the nearest double. Null stays null. The EngineeringUnits.Fast
        /// analyzer reports every use as EUF0009 (info), so the places still taking EngineeringUnits values can be listed.
        /// </summary>
        public static implicit operator global::EngineeringUnits.Fast.Entropy?(Entropy? value) =>
            value is null ? null : global::EngineeringUnits.Fast.Entropy.FromSI(FastConversion.SI(value, global::EngineeringUnits.Units.EntropyUnit.SI));
    }

    public partial class Force
    {
        /// <summary>
        /// The same Force as an EngineeringUnits.Fast struct: its exact SI value rounded once to the nearest double. Null stays null. The EngineeringUnits.Fast
        /// analyzer reports every use as EUF0009 (info), so the places still taking EngineeringUnits values can be listed.
        /// </summary>
        public static implicit operator global::EngineeringUnits.Fast.Force?(Force? value) =>
            value is null ? null : global::EngineeringUnits.Fast.Force.FromSI(FastConversion.SI(value, global::EngineeringUnits.Units.ForceUnit.SI));
    }

    public partial class ForceChangeRate
    {
        /// <summary>
        /// The same ForceChangeRate as an EngineeringUnits.Fast struct: its exact SI value rounded once to the nearest double. Null stays null. The EngineeringUnits.Fast
        /// analyzer reports every use as EUF0009 (info), so the places still taking EngineeringUnits values can be listed.
        /// </summary>
        public static implicit operator global::EngineeringUnits.Fast.ForceChangeRate?(ForceChangeRate? value) =>
            value is null ? null : global::EngineeringUnits.Fast.ForceChangeRate.FromSI(FastConversion.SI(value, global::EngineeringUnits.Units.ForceChangeRateUnit.SI));
    }

    public partial class ForceCost
    {
        /// <summary>
        /// The same ForceCost as an EngineeringUnits.Fast struct: its exact SI value rounded once to the nearest double. Null stays null. The EngineeringUnits.Fast
        /// analyzer reports every use as EUF0009 (info), so the places still taking EngineeringUnits values can be listed.
        /// </summary>
        public static implicit operator global::EngineeringUnits.Fast.ForceCost?(ForceCost? value) =>
            value is null ? null : global::EngineeringUnits.Fast.ForceCost.FromSI(FastConversion.SI(value, global::EngineeringUnits.Units.ForceCostUnit.SI));
    }

    public partial class ForcePerLength
    {
        /// <summary>
        /// The same ForcePerLength as an EngineeringUnits.Fast struct: its exact SI value rounded once to the nearest double. Null stays null. The EngineeringUnits.Fast
        /// analyzer reports every use as EUF0009 (info), so the places still taking EngineeringUnits values can be listed.
        /// </summary>
        public static implicit operator global::EngineeringUnits.Fast.ForcePerLength?(ForcePerLength? value) =>
            value is null ? null : global::EngineeringUnits.Fast.ForcePerLength.FromSI(FastConversion.SI(value, global::EngineeringUnits.Units.ForcePerLengthUnit.SI));
    }

    public partial class Frequency
    {
        /// <summary>
        /// The same Frequency as an EngineeringUnits.Fast struct: its exact SI value rounded once to the nearest double. Null stays null. The EngineeringUnits.Fast
        /// analyzer reports every use as EUF0009 (info), so the places still taking EngineeringUnits values can be listed.
        /// </summary>
        public static implicit operator global::EngineeringUnits.Fast.Frequency?(Frequency? value) =>
            value is null ? null : global::EngineeringUnits.Fast.Frequency.FromSI(FastConversion.SI(value, global::EngineeringUnits.Units.FrequencyUnit.SI));
    }

    public partial class FuelEfficiency
    {
        /// <summary>
        /// The same FuelEfficiency as an EngineeringUnits.Fast struct: its exact SI value rounded once to the nearest double. Null stays null. The EngineeringUnits.Fast
        /// analyzer reports every use as EUF0009 (info), so the places still taking EngineeringUnits values can be listed.
        /// </summary>
        public static implicit operator global::EngineeringUnits.Fast.FuelEfficiency?(FuelEfficiency? value) =>
            value is null ? null : global::EngineeringUnits.Fast.FuelEfficiency.FromSI(FastConversion.SI(value, global::EngineeringUnits.Units.FuelEfficiencyUnit.SI));
    }

    public partial class HeatFlux
    {
        /// <summary>
        /// The same HeatFlux as an EngineeringUnits.Fast struct: its exact SI value rounded once to the nearest double. Null stays null. The EngineeringUnits.Fast
        /// analyzer reports every use as EUF0009 (info), so the places still taking EngineeringUnits values can be listed.
        /// </summary>
        public static implicit operator global::EngineeringUnits.Fast.HeatFlux?(HeatFlux? value) =>
            value is null ? null : global::EngineeringUnits.Fast.HeatFlux.FromSI(FastConversion.SI(value, global::EngineeringUnits.Units.HeatFluxUnit.SI));
    }

    public partial class HeatTransferCoefficient
    {
        /// <summary>
        /// The same HeatTransferCoefficient as an EngineeringUnits.Fast struct: its exact SI value rounded once to the nearest double. Null stays null. The EngineeringUnits.Fast
        /// analyzer reports every use as EUF0009 (info), so the places still taking EngineeringUnits values can be listed.
        /// </summary>
        public static implicit operator global::EngineeringUnits.Fast.HeatTransferCoefficient?(HeatTransferCoefficient? value) =>
            value is null ? null : global::EngineeringUnits.Fast.HeatTransferCoefficient.FromSI(FastConversion.SI(value, global::EngineeringUnits.Units.HeatTransferCoefficientUnit.SI));
    }

    public partial class Illuminance
    {
        /// <summary>
        /// The same Illuminance as an EngineeringUnits.Fast struct: its exact SI value rounded once to the nearest double. Null stays null. The EngineeringUnits.Fast
        /// analyzer reports every use as EUF0009 (info), so the places still taking EngineeringUnits values can be listed.
        /// </summary>
        public static implicit operator global::EngineeringUnits.Fast.Illuminance?(Illuminance? value) =>
            value is null ? null : global::EngineeringUnits.Fast.Illuminance.FromSI(FastConversion.SI(value, global::EngineeringUnits.Units.IlluminanceUnit.SI));
    }

    public partial class Information
    {
        /// <summary>
        /// The same Information as an EngineeringUnits.Fast struct: its exact SI value rounded once to the nearest double. Null stays null. The EngineeringUnits.Fast
        /// analyzer reports every use as EUF0009 (info), so the places still taking EngineeringUnits values can be listed.
        /// </summary>
        public static implicit operator global::EngineeringUnits.Fast.Information?(Information? value) =>
            value is null ? null : global::EngineeringUnits.Fast.Information.FromSI(FastConversion.SI(value, global::EngineeringUnits.Units.InformationUnit.SI));
    }

    public partial class Irradiance
    {
        /// <summary>
        /// The same Irradiance as an EngineeringUnits.Fast struct: its exact SI value rounded once to the nearest double. Null stays null. The EngineeringUnits.Fast
        /// analyzer reports every use as EUF0009 (info), so the places still taking EngineeringUnits values can be listed.
        /// </summary>
        public static implicit operator global::EngineeringUnits.Fast.Irradiance?(Irradiance? value) =>
            value is null ? null : global::EngineeringUnits.Fast.Irradiance.FromSI(FastConversion.SI(value, global::EngineeringUnits.Units.IrradianceUnit.SI));
    }

    public partial class Irradiation
    {
        /// <summary>
        /// The same Irradiation as an EngineeringUnits.Fast struct: its exact SI value rounded once to the nearest double. Null stays null. The EngineeringUnits.Fast
        /// analyzer reports every use as EUF0009 (info), so the places still taking EngineeringUnits values can be listed.
        /// </summary>
        public static implicit operator global::EngineeringUnits.Fast.Irradiation?(Irradiation? value) =>
            value is null ? null : global::EngineeringUnits.Fast.Irradiation.FromSI(FastConversion.SI(value, global::EngineeringUnits.Units.IrradiationUnit.SI));
    }

    public partial class Jerk
    {
        /// <summary>
        /// The same Jerk as an EngineeringUnits.Fast struct: its exact SI value rounded once to the nearest double. Null stays null. The EngineeringUnits.Fast
        /// analyzer reports every use as EUF0009 (info), so the places still taking EngineeringUnits values can be listed.
        /// </summary>
        public static implicit operator global::EngineeringUnits.Fast.Jerk?(Jerk? value) =>
            value is null ? null : global::EngineeringUnits.Fast.Jerk.FromSI(FastConversion.SI(value, global::EngineeringUnits.Units.JerkUnit.SI));
    }

    public partial class KinematicViscosity
    {
        /// <summary>
        /// The same KinematicViscosity as an EngineeringUnits.Fast struct: its exact SI value rounded once to the nearest double. Null stays null. The EngineeringUnits.Fast
        /// analyzer reports every use as EUF0009 (info), so the places still taking EngineeringUnits values can be listed.
        /// </summary>
        public static implicit operator global::EngineeringUnits.Fast.KinematicViscosity?(KinematicViscosity? value) =>
            value is null ? null : global::EngineeringUnits.Fast.KinematicViscosity.FromSI(FastConversion.SI(value, global::EngineeringUnits.Units.KinematicViscosityUnit.SI));
    }

    public partial class LapseRate
    {
        /// <summary>
        /// The same LapseRate as an EngineeringUnits.Fast struct: its exact SI value rounded once to the nearest double. Null stays null. The EngineeringUnits.Fast
        /// analyzer reports every use as EUF0009 (info), so the places still taking EngineeringUnits values can be listed.
        /// </summary>
        public static implicit operator global::EngineeringUnits.Fast.LapseRate?(LapseRate? value) =>
            value is null ? null : global::EngineeringUnits.Fast.LapseRate.FromSI(FastConversion.SI(value, global::EngineeringUnits.Units.LapseRateUnit.SI));
    }

    public partial class Length
    {
        /// <summary>
        /// The same Length as an EngineeringUnits.Fast struct: its exact SI value rounded once to the nearest double. Null stays null. The EngineeringUnits.Fast
        /// analyzer reports every use as EUF0009 (info), so the places still taking EngineeringUnits values can be listed.
        /// </summary>
        public static implicit operator global::EngineeringUnits.Fast.Length?(Length? value) =>
            value is null ? null : global::EngineeringUnits.Fast.Length.FromSI(FastConversion.SI(value, global::EngineeringUnits.Units.LengthUnit.SI));
    }

    public partial class LengthCost
    {
        /// <summary>
        /// The same LengthCost as an EngineeringUnits.Fast struct: its exact SI value rounded once to the nearest double. Null stays null. The EngineeringUnits.Fast
        /// analyzer reports every use as EUF0009 (info), so the places still taking EngineeringUnits values can be listed.
        /// </summary>
        public static implicit operator global::EngineeringUnits.Fast.LengthCost?(LengthCost? value) =>
            value is null ? null : global::EngineeringUnits.Fast.LengthCost.FromSI(FastConversion.SI(value, global::EngineeringUnits.Units.LengthCostUnit.SI));
    }

    public partial class Level
    {
        /// <summary>
        /// The same Level as an EngineeringUnits.Fast struct: its exact SI value rounded once to the nearest double. Null stays null. The EngineeringUnits.Fast
        /// analyzer reports every use as EUF0009 (info), so the places still taking EngineeringUnits values can be listed.
        /// </summary>
        public static implicit operator global::EngineeringUnits.Fast.Level?(Level? value) =>
            value is null ? null : global::EngineeringUnits.Fast.Level.FromSI(FastConversion.SI(value, global::EngineeringUnits.Units.LevelUnit.SI));
    }

    public partial class LinearDensity
    {
        /// <summary>
        /// The same LinearDensity as an EngineeringUnits.Fast struct: its exact SI value rounded once to the nearest double. Null stays null. The EngineeringUnits.Fast
        /// analyzer reports every use as EUF0009 (info), so the places still taking EngineeringUnits values can be listed.
        /// </summary>
        public static implicit operator global::EngineeringUnits.Fast.LinearDensity?(LinearDensity? value) =>
            value is null ? null : global::EngineeringUnits.Fast.LinearDensity.FromSI(FastConversion.SI(value, global::EngineeringUnits.Units.LinearDensityUnit.SI));
    }

    public partial class LinearPowerDensity
    {
        /// <summary>
        /// The same LinearPowerDensity as an EngineeringUnits.Fast struct: its exact SI value rounded once to the nearest double. Null stays null. The EngineeringUnits.Fast
        /// analyzer reports every use as EUF0009 (info), so the places still taking EngineeringUnits values can be listed.
        /// </summary>
        public static implicit operator global::EngineeringUnits.Fast.LinearPowerDensity?(LinearPowerDensity? value) =>
            value is null ? null : global::EngineeringUnits.Fast.LinearPowerDensity.FromSI(FastConversion.SI(value, global::EngineeringUnits.Units.LinearPowerDensityUnit.SI));
    }

    public partial class LuminousFlux
    {
        /// <summary>
        /// The same LuminousFlux as an EngineeringUnits.Fast struct: its exact SI value rounded once to the nearest double. Null stays null. The EngineeringUnits.Fast
        /// analyzer reports every use as EUF0009 (info), so the places still taking EngineeringUnits values can be listed.
        /// </summary>
        public static implicit operator global::EngineeringUnits.Fast.LuminousFlux?(LuminousFlux? value) =>
            value is null ? null : global::EngineeringUnits.Fast.LuminousFlux.FromSI(FastConversion.SI(value, global::EngineeringUnits.Units.LuminousFluxUnit.SI));
    }

    public partial class LuminousIntensity
    {
        /// <summary>
        /// The same LuminousIntensity as an EngineeringUnits.Fast struct: its exact SI value rounded once to the nearest double. Null stays null. The EngineeringUnits.Fast
        /// analyzer reports every use as EUF0009 (info), so the places still taking EngineeringUnits values can be listed.
        /// </summary>
        public static implicit operator global::EngineeringUnits.Fast.LuminousIntensity?(LuminousIntensity? value) =>
            value is null ? null : global::EngineeringUnits.Fast.LuminousIntensity.FromSI(FastConversion.SI(value, global::EngineeringUnits.Units.LuminousIntensityUnit.SI));
    }

    public partial class MagneticField
    {
        /// <summary>
        /// The same MagneticField as an EngineeringUnits.Fast struct: its exact SI value rounded once to the nearest double. Null stays null. The EngineeringUnits.Fast
        /// analyzer reports every use as EUF0009 (info), so the places still taking EngineeringUnits values can be listed.
        /// </summary>
        public static implicit operator global::EngineeringUnits.Fast.MagneticField?(MagneticField? value) =>
            value is null ? null : global::EngineeringUnits.Fast.MagneticField.FromSI(FastConversion.SI(value, global::EngineeringUnits.Units.MagneticFieldUnit.SI));
    }

    public partial class MagneticFlux
    {
        /// <summary>
        /// The same MagneticFlux as an EngineeringUnits.Fast struct: its exact SI value rounded once to the nearest double. Null stays null. The EngineeringUnits.Fast
        /// analyzer reports every use as EUF0009 (info), so the places still taking EngineeringUnits values can be listed.
        /// </summary>
        public static implicit operator global::EngineeringUnits.Fast.MagneticFlux?(MagneticFlux? value) =>
            value is null ? null : global::EngineeringUnits.Fast.MagneticFlux.FromSI(FastConversion.SI(value, global::EngineeringUnits.Units.MagneticFluxUnit.SI));
    }

    public partial class Magnetization
    {
        /// <summary>
        /// The same Magnetization as an EngineeringUnits.Fast struct: its exact SI value rounded once to the nearest double. Null stays null. The EngineeringUnits.Fast
        /// analyzer reports every use as EUF0009 (info), so the places still taking EngineeringUnits values can be listed.
        /// </summary>
        public static implicit operator global::EngineeringUnits.Fast.Magnetization?(Magnetization? value) =>
            value is null ? null : global::EngineeringUnits.Fast.Magnetization.FromSI(FastConversion.SI(value, global::EngineeringUnits.Units.MagnetizationUnit.SI));
    }

    public partial class Mass
    {
        /// <summary>
        /// The same Mass as an EngineeringUnits.Fast struct: its exact SI value rounded once to the nearest double. Null stays null. The EngineeringUnits.Fast
        /// analyzer reports every use as EUF0009 (info), so the places still taking EngineeringUnits values can be listed.
        /// </summary>
        public static implicit operator global::EngineeringUnits.Fast.Mass?(Mass? value) =>
            value is null ? null : global::EngineeringUnits.Fast.Mass.FromSI(FastConversion.SI(value, global::EngineeringUnits.Units.MassUnit.SI));
    }

    public partial class MassCost
    {
        /// <summary>
        /// The same MassCost as an EngineeringUnits.Fast struct: its exact SI value rounded once to the nearest double. Null stays null. The EngineeringUnits.Fast
        /// analyzer reports every use as EUF0009 (info), so the places still taking EngineeringUnits values can be listed.
        /// </summary>
        public static implicit operator global::EngineeringUnits.Fast.MassCost?(MassCost? value) =>
            value is null ? null : global::EngineeringUnits.Fast.MassCost.FromSI(FastConversion.SI(value, global::EngineeringUnits.Units.MassCostUnit.SI));
    }

    public partial class MassFlow
    {
        /// <summary>
        /// The same MassFlow as an EngineeringUnits.Fast struct: its exact SI value rounded once to the nearest double. Null stays null. The EngineeringUnits.Fast
        /// analyzer reports every use as EUF0009 (info), so the places still taking EngineeringUnits values can be listed.
        /// </summary>
        public static implicit operator global::EngineeringUnits.Fast.MassFlow?(MassFlow? value) =>
            value is null ? null : global::EngineeringUnits.Fast.MassFlow.FromSI(FastConversion.SI(value, global::EngineeringUnits.Units.MassFlowUnit.SI));
    }

    public partial class MassFlux
    {
        /// <summary>
        /// The same MassFlux as an EngineeringUnits.Fast struct: its exact SI value rounded once to the nearest double. Null stays null. The EngineeringUnits.Fast
        /// analyzer reports every use as EUF0009 (info), so the places still taking EngineeringUnits values can be listed.
        /// </summary>
        public static implicit operator global::EngineeringUnits.Fast.MassFlux?(MassFlux? value) =>
            value is null ? null : global::EngineeringUnits.Fast.MassFlux.FromSI(FastConversion.SI(value, global::EngineeringUnits.Units.MassFluxUnit.SI));
    }

    public partial class MassMomentOfInertia
    {
        /// <summary>
        /// The same MassMomentOfInertia as an EngineeringUnits.Fast struct: its exact SI value rounded once to the nearest double. Null stays null. The EngineeringUnits.Fast
        /// analyzer reports every use as EUF0009 (info), so the places still taking EngineeringUnits values can be listed.
        /// </summary>
        public static implicit operator global::EngineeringUnits.Fast.MassMomentOfInertia?(MassMomentOfInertia? value) =>
            value is null ? null : global::EngineeringUnits.Fast.MassMomentOfInertia.FromSI(FastConversion.SI(value, global::EngineeringUnits.Units.MassMomentOfInertiaUnit.SI));
    }

    public partial class MolarEnergy
    {
        /// <summary>
        /// The same MolarEnergy as an EngineeringUnits.Fast struct: its exact SI value rounded once to the nearest double. Null stays null. The EngineeringUnits.Fast
        /// analyzer reports every use as EUF0009 (info), so the places still taking EngineeringUnits values can be listed.
        /// </summary>
        public static implicit operator global::EngineeringUnits.Fast.MolarEnergy?(MolarEnergy? value) =>
            value is null ? null : global::EngineeringUnits.Fast.MolarEnergy.FromSI(FastConversion.SI(value, global::EngineeringUnits.Units.MolarEnergyUnit.SI));
    }

    public partial class MolarEntropy
    {
        /// <summary>
        /// The same MolarEntropy as an EngineeringUnits.Fast struct: its exact SI value rounded once to the nearest double. Null stays null. The EngineeringUnits.Fast
        /// analyzer reports every use as EUF0009 (info), so the places still taking EngineeringUnits values can be listed.
        /// </summary>
        public static implicit operator global::EngineeringUnits.Fast.MolarEntropy?(MolarEntropy? value) =>
            value is null ? null : global::EngineeringUnits.Fast.MolarEntropy.FromSI(FastConversion.SI(value, global::EngineeringUnits.Units.MolarEntropyUnit.SI));
    }

    public partial class MolarFlow
    {
        /// <summary>
        /// The same MolarFlow as an EngineeringUnits.Fast struct: its exact SI value rounded once to the nearest double. Null stays null. The EngineeringUnits.Fast
        /// analyzer reports every use as EUF0009 (info), so the places still taking EngineeringUnits values can be listed.
        /// </summary>
        public static implicit operator global::EngineeringUnits.Fast.MolarFlow?(MolarFlow? value) =>
            value is null ? null : global::EngineeringUnits.Fast.MolarFlow.FromSI(FastConversion.SI(value, global::EngineeringUnits.Units.MolarFlowUnit.SI));
    }

    public partial class MolarMass
    {
        /// <summary>
        /// The same MolarMass as an EngineeringUnits.Fast struct: its exact SI value rounded once to the nearest double. Null stays null. The EngineeringUnits.Fast
        /// analyzer reports every use as EUF0009 (info), so the places still taking EngineeringUnits values can be listed.
        /// </summary>
        public static implicit operator global::EngineeringUnits.Fast.MolarMass?(MolarMass? value) =>
            value is null ? null : global::EngineeringUnits.Fast.MolarMass.FromSI(FastConversion.SI(value, global::EngineeringUnits.Units.MolarMassUnit.SI));
    }

    public partial class Molarity
    {
        /// <summary>
        /// The same Molarity as an EngineeringUnits.Fast struct: its exact SI value rounded once to the nearest double. Null stays null. The EngineeringUnits.Fast
        /// analyzer reports every use as EUF0009 (info), so the places still taking EngineeringUnits values can be listed.
        /// </summary>
        public static implicit operator global::EngineeringUnits.Fast.Molarity?(Molarity? value) =>
            value is null ? null : global::EngineeringUnits.Fast.Molarity.FromSI(FastConversion.SI(value, global::EngineeringUnits.Units.MolarityUnit.SI));
    }

    public partial class Permeability
    {
        /// <summary>
        /// The same Permeability as an EngineeringUnits.Fast struct: its exact SI value rounded once to the nearest double. Null stays null. The EngineeringUnits.Fast
        /// analyzer reports every use as EUF0009 (info), so the places still taking EngineeringUnits values can be listed.
        /// </summary>
        public static implicit operator global::EngineeringUnits.Fast.Permeability?(Permeability? value) =>
            value is null ? null : global::EngineeringUnits.Fast.Permeability.FromSI(FastConversion.SI(value, global::EngineeringUnits.Units.PermeabilityUnit.SI));
    }

    public partial class Permittivity
    {
        /// <summary>
        /// The same Permittivity as an EngineeringUnits.Fast struct: its exact SI value rounded once to the nearest double. Null stays null. The EngineeringUnits.Fast
        /// analyzer reports every use as EUF0009 (info), so the places still taking EngineeringUnits values can be listed.
        /// </summary>
        public static implicit operator global::EngineeringUnits.Fast.Permittivity?(Permittivity? value) =>
            value is null ? null : global::EngineeringUnits.Fast.Permittivity.FromSI(FastConversion.SI(value, global::EngineeringUnits.Units.PermittivityUnit.SI));
    }

    public partial class PipeSize
    {
        /// <summary>
        /// The same PipeSize as an EngineeringUnits.Fast struct: its exact SI value rounded once to the nearest double. Null stays null. The EngineeringUnits.Fast
        /// analyzer reports every use as EUF0009 (info), so the places still taking EngineeringUnits values can be listed.
        /// </summary>
        public static implicit operator global::EngineeringUnits.Fast.PipeSize?(PipeSize? value) =>
            value is null ? null : global::EngineeringUnits.Fast.PipeSize.FromSI(FastConversion.SI(value, global::EngineeringUnits.Units.PipeSizeUnit.SI));
    }

    public partial class Power
    {
        /// <summary>
        /// The same Power as an EngineeringUnits.Fast struct: its exact SI value rounded once to the nearest double. Null stays null. The EngineeringUnits.Fast
        /// analyzer reports every use as EUF0009 (info), so the places still taking EngineeringUnits values can be listed.
        /// </summary>
        public static implicit operator global::EngineeringUnits.Fast.Power?(Power? value) =>
            value is null ? null : global::EngineeringUnits.Fast.Power.FromSI(FastConversion.SI(value, global::EngineeringUnits.Units.PowerUnit.SI));
    }

    public partial class PowerCost
    {
        /// <summary>
        /// The same PowerCost as an EngineeringUnits.Fast struct: its exact SI value rounded once to the nearest double. Null stays null. The EngineeringUnits.Fast
        /// analyzer reports every use as EUF0009 (info), so the places still taking EngineeringUnits values can be listed.
        /// </summary>
        public static implicit operator global::EngineeringUnits.Fast.PowerCost?(PowerCost? value) =>
            value is null ? null : global::EngineeringUnits.Fast.PowerCost.FromSI(FastConversion.SI(value, global::EngineeringUnits.Units.PowerCostUnit.SI));
    }

    public partial class PowerDensity
    {
        /// <summary>
        /// The same PowerDensity as an EngineeringUnits.Fast struct: its exact SI value rounded once to the nearest double. Null stays null. The EngineeringUnits.Fast
        /// analyzer reports every use as EUF0009 (info), so the places still taking EngineeringUnits values can be listed.
        /// </summary>
        public static implicit operator global::EngineeringUnits.Fast.PowerDensity?(PowerDensity? value) =>
            value is null ? null : global::EngineeringUnits.Fast.PowerDensity.FromSI(FastConversion.SI(value, global::EngineeringUnits.Units.PowerDensityUnit.SI));
    }

    public partial class Pressure
    {
        /// <summary>
        /// The same Pressure as an EngineeringUnits.Fast struct: its exact SI value rounded once to the nearest double. Null stays null. The EngineeringUnits.Fast
        /// analyzer reports every use as EUF0009 (info), so the places still taking EngineeringUnits values can be listed.
        /// </summary>
        public static implicit operator global::EngineeringUnits.Fast.Pressure?(Pressure? value) =>
            value is null ? null : global::EngineeringUnits.Fast.Pressure.FromSI(FastConversion.SI(value, global::EngineeringUnits.Units.PressureUnit.SI));
    }

    public partial class PressureChangeRate
    {
        /// <summary>
        /// The same PressureChangeRate as an EngineeringUnits.Fast struct: its exact SI value rounded once to the nearest double. Null stays null. The EngineeringUnits.Fast
        /// analyzer reports every use as EUF0009 (info), so the places still taking EngineeringUnits values can be listed.
        /// </summary>
        public static implicit operator global::EngineeringUnits.Fast.PressureChangeRate?(PressureChangeRate? value) =>
            value is null ? null : global::EngineeringUnits.Fast.PressureChangeRate.FromSI(FastConversion.SI(value, global::EngineeringUnits.Units.PressureChangeRateUnit.SI));
    }

    public partial class Ratio
    {
        /// <summary>
        /// The same Ratio as an EngineeringUnits.Fast struct: its exact SI value rounded once to the nearest double. Null stays null. The EngineeringUnits.Fast
        /// analyzer reports every use as EUF0009 (info), so the places still taking EngineeringUnits values can be listed.
        /// </summary>
        public static implicit operator global::EngineeringUnits.Fast.Ratio?(Ratio? value) =>
            value is null ? null : global::EngineeringUnits.Fast.Ratio.FromSI(FastConversion.SI(value, global::EngineeringUnits.Units.RatioUnit.SI));
    }

    public partial class ReactiveEnergy
    {
        /// <summary>
        /// The same ReactiveEnergy as an EngineeringUnits.Fast struct: its exact SI value rounded once to the nearest double. Null stays null. The EngineeringUnits.Fast
        /// analyzer reports every use as EUF0009 (info), so the places still taking EngineeringUnits values can be listed.
        /// </summary>
        public static implicit operator global::EngineeringUnits.Fast.ReactiveEnergy?(ReactiveEnergy? value) =>
            value is null ? null : global::EngineeringUnits.Fast.ReactiveEnergy.FromSI(FastConversion.SI(value, global::EngineeringUnits.Units.ReactiveEnergyUnit.SI));
    }

    public partial class ReactivePower
    {
        /// <summary>
        /// The same ReactivePower as an EngineeringUnits.Fast struct: its exact SI value rounded once to the nearest double. Null stays null. The EngineeringUnits.Fast
        /// analyzer reports every use as EUF0009 (info), so the places still taking EngineeringUnits values can be listed.
        /// </summary>
        public static implicit operator global::EngineeringUnits.Fast.ReactivePower?(ReactivePower? value) =>
            value is null ? null : global::EngineeringUnits.Fast.ReactivePower.FromSI(FastConversion.SI(value, global::EngineeringUnits.Units.ReactivePowerUnit.SI));
    }

    public partial class RotationalSpeed
    {
        /// <summary>
        /// The same RotationalSpeed as an EngineeringUnits.Fast struct: its exact SI value rounded once to the nearest double. Null stays null. The EngineeringUnits.Fast
        /// analyzer reports every use as EUF0009 (info), so the places still taking EngineeringUnits values can be listed.
        /// </summary>
        public static implicit operator global::EngineeringUnits.Fast.RotationalSpeed?(RotationalSpeed? value) =>
            value is null ? null : global::EngineeringUnits.Fast.RotationalSpeed.FromSI(FastConversion.SI(value, global::EngineeringUnits.Units.RotationalSpeedUnit.SI));
    }

    public partial class Snap
    {
        /// <summary>
        /// The same Snap as an EngineeringUnits.Fast struct: its exact SI value rounded once to the nearest double. Null stays null. The EngineeringUnits.Fast
        /// analyzer reports every use as EUF0009 (info), so the places still taking EngineeringUnits values can be listed.
        /// </summary>
        public static implicit operator global::EngineeringUnits.Fast.Snap?(Snap? value) =>
            value is null ? null : global::EngineeringUnits.Fast.Snap.FromSI(FastConversion.SI(value, global::EngineeringUnits.Units.SnapUnit.SI));
    }

    public partial class SpecificEnergy
    {
        /// <summary>
        /// The same SpecificEnergy as an EngineeringUnits.Fast struct: its exact SI value rounded once to the nearest double. Null stays null. The EngineeringUnits.Fast
        /// analyzer reports every use as EUF0009 (info), so the places still taking EngineeringUnits values can be listed.
        /// </summary>
        public static implicit operator global::EngineeringUnits.Fast.SpecificEnergy?(SpecificEnergy? value) =>
            value is null ? null : global::EngineeringUnits.Fast.SpecificEnergy.FromSI(FastConversion.SI(value, global::EngineeringUnits.Units.SpecificEnergyUnit.SI));
    }

    public partial class SpecificEntropy
    {
        /// <summary>
        /// The same SpecificEntropy as an EngineeringUnits.Fast struct: its exact SI value rounded once to the nearest double. Null stays null. The EngineeringUnits.Fast
        /// analyzer reports every use as EUF0009 (info), so the places still taking EngineeringUnits values can be listed.
        /// </summary>
        public static implicit operator global::EngineeringUnits.Fast.SpecificEntropy?(SpecificEntropy? value) =>
            value is null ? null : global::EngineeringUnits.Fast.SpecificEntropy.FromSI(FastConversion.SI(value, global::EngineeringUnits.Units.SpecificEntropyUnit.SI));
    }

    public partial class SpecificHeatCapacity
    {
        /// <summary>
        /// The same SpecificHeatCapacity as an EngineeringUnits.Fast struct: its exact SI value rounded once to the nearest double. Null stays null. The EngineeringUnits.Fast
        /// analyzer reports every use as EUF0009 (info), so the places still taking EngineeringUnits values can be listed.
        /// </summary>
        public static implicit operator global::EngineeringUnits.Fast.SpecificHeatCapacity?(SpecificHeatCapacity? value) =>
            value is null ? null : global::EngineeringUnits.Fast.SpecificHeatCapacity.FromSI(FastConversion.SI(value, global::EngineeringUnits.Units.SpecificHeatCapacityUnit.SI));
    }

    public partial class SpecificThermalResistance
    {
        /// <summary>
        /// The same SpecificThermalResistance as an EngineeringUnits.Fast struct: its exact SI value rounded once to the nearest double. Null stays null. The EngineeringUnits.Fast
        /// analyzer reports every use as EUF0009 (info), so the places still taking EngineeringUnits values can be listed.
        /// </summary>
        public static implicit operator global::EngineeringUnits.Fast.SpecificThermalResistance?(SpecificThermalResistance? value) =>
            value is null ? null : global::EngineeringUnits.Fast.SpecificThermalResistance.FromSI(FastConversion.SI(value, global::EngineeringUnits.Units.SpecificThermalResistanceUnit.SI));
    }

    public partial class SpecificVolume
    {
        /// <summary>
        /// The same SpecificVolume as an EngineeringUnits.Fast struct: its exact SI value rounded once to the nearest double. Null stays null. The EngineeringUnits.Fast
        /// analyzer reports every use as EUF0009 (info), so the places still taking EngineeringUnits values can be listed.
        /// </summary>
        public static implicit operator global::EngineeringUnits.Fast.SpecificVolume?(SpecificVolume? value) =>
            value is null ? null : global::EngineeringUnits.Fast.SpecificVolume.FromSI(FastConversion.SI(value, global::EngineeringUnits.Units.SpecificVolumeUnit.SI));
    }

    public partial class SpecificWeight
    {
        /// <summary>
        /// The same SpecificWeight as an EngineeringUnits.Fast struct: its exact SI value rounded once to the nearest double. Null stays null. The EngineeringUnits.Fast
        /// analyzer reports every use as EUF0009 (info), so the places still taking EngineeringUnits values can be listed.
        /// </summary>
        public static implicit operator global::EngineeringUnits.Fast.SpecificWeight?(SpecificWeight? value) =>
            value is null ? null : global::EngineeringUnits.Fast.SpecificWeight.FromSI(FastConversion.SI(value, global::EngineeringUnits.Units.SpecificWeightUnit.SI));
    }

    public partial class Speed
    {
        /// <summary>
        /// The same Speed as an EngineeringUnits.Fast struct: its exact SI value rounded once to the nearest double. Null stays null. The EngineeringUnits.Fast
        /// analyzer reports every use as EUF0009 (info), so the places still taking EngineeringUnits values can be listed.
        /// </summary>
        public static implicit operator global::EngineeringUnits.Fast.Speed?(Speed? value) =>
            value is null ? null : global::EngineeringUnits.Fast.Speed.FromSI(FastConversion.SI(value, global::EngineeringUnits.Units.SpeedUnit.SI));
    }

    public partial class Temperature
    {
        /// <summary>
        /// The same Temperature as an EngineeringUnits.Fast struct: its exact SI value rounded once to the nearest double. Null stays null. The EngineeringUnits.Fast
        /// analyzer reports every use as EUF0009 (info), so the places still taking EngineeringUnits values can be listed.
        /// </summary>
        public static implicit operator global::EngineeringUnits.Fast.Temperature?(Temperature? value) =>
            value is null ? null : global::EngineeringUnits.Fast.Temperature.FromSI(FastConversion.SI(value, global::EngineeringUnits.Units.TemperatureUnit.SI));
    }

    public partial class TemperatureChangeRate
    {
        /// <summary>
        /// The same TemperatureChangeRate as an EngineeringUnits.Fast struct: its exact SI value rounded once to the nearest double. Null stays null. The EngineeringUnits.Fast
        /// analyzer reports every use as EUF0009 (info), so the places still taking EngineeringUnits values can be listed.
        /// </summary>
        public static implicit operator global::EngineeringUnits.Fast.TemperatureChangeRate?(TemperatureChangeRate? value) =>
            value is null ? null : global::EngineeringUnits.Fast.TemperatureChangeRate.FromSI(FastConversion.SI(value, global::EngineeringUnits.Units.TemperatureChangeRateUnit.SI));
    }

    public partial class ThermalConductivity
    {
        /// <summary>
        /// The same ThermalConductivity as an EngineeringUnits.Fast struct: its exact SI value rounded once to the nearest double. Null stays null. The EngineeringUnits.Fast
        /// analyzer reports every use as EUF0009 (info), so the places still taking EngineeringUnits values can be listed.
        /// </summary>
        public static implicit operator global::EngineeringUnits.Fast.ThermalConductivity?(ThermalConductivity? value) =>
            value is null ? null : global::EngineeringUnits.Fast.ThermalConductivity.FromSI(FastConversion.SI(value, global::EngineeringUnits.Units.ThermalConductivityUnit.SI));
    }

    public partial class ThermalResistance
    {
        /// <summary>
        /// The same ThermalResistance as an EngineeringUnits.Fast struct: its exact SI value rounded once to the nearest double. Null stays null. The EngineeringUnits.Fast
        /// analyzer reports every use as EUF0009 (info), so the places still taking EngineeringUnits values can be listed.
        /// </summary>
        public static implicit operator global::EngineeringUnits.Fast.ThermalResistance?(ThermalResistance? value) =>
            value is null ? null : global::EngineeringUnits.Fast.ThermalResistance.FromSI(FastConversion.SI(value, global::EngineeringUnits.Units.ThermalResistanceUnit.SI));
    }

    public partial class Torque
    {
        /// <summary>
        /// The same Torque as an EngineeringUnits.Fast struct: its exact SI value rounded once to the nearest double. Null stays null. The EngineeringUnits.Fast
        /// analyzer reports every use as EUF0009 (info), so the places still taking EngineeringUnits values can be listed.
        /// </summary>
        public static implicit operator global::EngineeringUnits.Fast.Torque?(Torque? value) =>
            value is null ? null : global::EngineeringUnits.Fast.Torque.FromSI(FastConversion.SI(value, global::EngineeringUnits.Units.TorqueUnit.SI));
    }

    public partial class TorquePerLength
    {
        /// <summary>
        /// The same TorquePerLength as an EngineeringUnits.Fast struct: its exact SI value rounded once to the nearest double. Null stays null. The EngineeringUnits.Fast
        /// analyzer reports every use as EUF0009 (info), so the places still taking EngineeringUnits values can be listed.
        /// </summary>
        public static implicit operator global::EngineeringUnits.Fast.TorquePerLength?(TorquePerLength? value) =>
            value is null ? null : global::EngineeringUnits.Fast.TorquePerLength.FromSI(FastConversion.SI(value, global::EngineeringUnits.Units.TorquePerLengthUnit.SI));
    }

    public partial class Volume
    {
        /// <summary>
        /// The same Volume as an EngineeringUnits.Fast struct: its exact SI value rounded once to the nearest double. Null stays null. The EngineeringUnits.Fast
        /// analyzer reports every use as EUF0009 (info), so the places still taking EngineeringUnits values can be listed.
        /// </summary>
        public static implicit operator global::EngineeringUnits.Fast.Volume?(Volume? value) =>
            value is null ? null : global::EngineeringUnits.Fast.Volume.FromSI(FastConversion.SI(value, global::EngineeringUnits.Units.VolumeUnit.SI));
    }

    public partial class VolumeCost
    {
        /// <summary>
        /// The same VolumeCost as an EngineeringUnits.Fast struct: its exact SI value rounded once to the nearest double. Null stays null. The EngineeringUnits.Fast
        /// analyzer reports every use as EUF0009 (info), so the places still taking EngineeringUnits values can be listed.
        /// </summary>
        public static implicit operator global::EngineeringUnits.Fast.VolumeCost?(VolumeCost? value) =>
            value is null ? null : global::EngineeringUnits.Fast.VolumeCost.FromSI(FastConversion.SI(value, global::EngineeringUnits.Units.VolumeCostUnit.SI));
    }

    public partial class VolumeFlow
    {
        /// <summary>
        /// The same VolumeFlow as an EngineeringUnits.Fast struct: its exact SI value rounded once to the nearest double. Null stays null. The EngineeringUnits.Fast
        /// analyzer reports every use as EUF0009 (info), so the places still taking EngineeringUnits values can be listed.
        /// </summary>
        public static implicit operator global::EngineeringUnits.Fast.VolumeFlow?(VolumeFlow? value) =>
            value is null ? null : global::EngineeringUnits.Fast.VolumeFlow.FromSI(FastConversion.SI(value, global::EngineeringUnits.Units.VolumeFlowUnit.SI));
    }

    public partial class VolumePerLength
    {
        /// <summary>
        /// The same VolumePerLength as an EngineeringUnits.Fast struct: its exact SI value rounded once to the nearest double. Null stays null. The EngineeringUnits.Fast
        /// analyzer reports every use as EUF0009 (info), so the places still taking EngineeringUnits values can be listed.
        /// </summary>
        public static implicit operator global::EngineeringUnits.Fast.VolumePerLength?(VolumePerLength? value) =>
            value is null ? null : global::EngineeringUnits.Fast.VolumePerLength.FromSI(FastConversion.SI(value, global::EngineeringUnits.Units.VolumePerLengthUnit.SI));
    }

    public partial class VolumetricHeatTransferCoefficient
    {
        /// <summary>
        /// The same VolumetricHeatTransferCoefficient as an EngineeringUnits.Fast struct: its exact SI value rounded once to the nearest double. Null stays null. The EngineeringUnits.Fast
        /// analyzer reports every use as EUF0009 (info), so the places still taking EngineeringUnits values can be listed.
        /// </summary>
        public static implicit operator global::EngineeringUnits.Fast.VolumetricHeatTransferCoefficient?(VolumetricHeatTransferCoefficient? value) =>
            value is null ? null : global::EngineeringUnits.Fast.VolumetricHeatTransferCoefficient.FromSI(FastConversion.SI(value, global::EngineeringUnits.Units.VolumetricHeatTransferCoefficientUnit.SI));
    }

    public partial class WarpingMomentOfInertia
    {
        /// <summary>
        /// The same WarpingMomentOfInertia as an EngineeringUnits.Fast struct: its exact SI value rounded once to the nearest double. Null stays null. The EngineeringUnits.Fast
        /// analyzer reports every use as EUF0009 (info), so the places still taking EngineeringUnits values can be listed.
        /// </summary>
        public static implicit operator global::EngineeringUnits.Fast.WarpingMomentOfInertia?(WarpingMomentOfInertia? value) =>
            value is null ? null : global::EngineeringUnits.Fast.WarpingMomentOfInertia.FromSI(FastConversion.SI(value, global::EngineeringUnits.Units.WarpingMomentOfInertiaUnit.SI));
    }

}

#endif
