using EngineeringUnits;
using EngineeringUnits.Units;

namespace EngineeringUnits.NumberExtensions.NumberToSpecificEnergy;

// <auto-generated/>
// This file is auto-generated; changes will be overwritten.
public static class NumberToSpecificEnergyExtensions
{
    // double receiver
    extension(double value)
    {
        public SpecificEnergy BtuPerPound => new SpecificEnergy(value, SpecificEnergyUnit.BtuPerPound);
        public SpecificEnergy CaloriePerGram => new SpecificEnergy(value, SpecificEnergyUnit.CaloriePerGram);
        public SpecificEnergy GigawattDayPerKilogram => new SpecificEnergy(value, SpecificEnergyUnit.GigawattDayPerKilogram);
        public SpecificEnergy GigawattDayPerShortTon => new SpecificEnergy(value, SpecificEnergyUnit.GigawattDayPerShortTon);
        public SpecificEnergy GigawattDayPerTonne => new SpecificEnergy(value, SpecificEnergyUnit.GigawattDayPerTonne);
        public SpecificEnergy GigawattHourPerKilogram => new SpecificEnergy(value, SpecificEnergyUnit.GigawattHourPerKilogram);
        public SpecificEnergy JoulePerKilogram => new SpecificEnergy(value, SpecificEnergyUnit.JoulePerKilogram);
        public SpecificEnergy KilocaloriePerGram => new SpecificEnergy(value, SpecificEnergyUnit.KilocaloriePerGram);
        public SpecificEnergy KilojoulePerKilogram => new SpecificEnergy(value, SpecificEnergyUnit.KilojoulePerKilogram);
        public SpecificEnergy KilowattDayPerKilogram => new SpecificEnergy(value, SpecificEnergyUnit.KilowattDayPerKilogram);
        public SpecificEnergy KilowattDayPerShortTon => new SpecificEnergy(value, SpecificEnergyUnit.KilowattDayPerShortTon);
        public SpecificEnergy KilowattDayPerTonne => new SpecificEnergy(value, SpecificEnergyUnit.KilowattDayPerTonne);
        public SpecificEnergy KilowattHourPerKilogram => new SpecificEnergy(value, SpecificEnergyUnit.KilowattHourPerKilogram);
        public SpecificEnergy MegajoulePerKilogram => new SpecificEnergy(value, SpecificEnergyUnit.MegajoulePerKilogram);
        public SpecificEnergy MegawattDayPerKilogram => new SpecificEnergy(value, SpecificEnergyUnit.MegawattDayPerKilogram);
        public SpecificEnergy MegawattDayPerShortTon => new SpecificEnergy(value, SpecificEnergyUnit.MegawattDayPerShortTon);
        public SpecificEnergy MegawattDayPerTonne => new SpecificEnergy(value, SpecificEnergyUnit.MegawattDayPerTonne);
        public SpecificEnergy MegawattHourPerKilogram => new SpecificEnergy(value, SpecificEnergyUnit.MegawattHourPerKilogram);
        public SpecificEnergy TerawattDayPerKilogram => new SpecificEnergy(value, SpecificEnergyUnit.TerawattDayPerKilogram);
        public SpecificEnergy TerawattDayPerShortTon => new SpecificEnergy(value, SpecificEnergyUnit.TerawattDayPerShortTon);
        public SpecificEnergy TerawattDayPerTonne => new SpecificEnergy(value, SpecificEnergyUnit.TerawattDayPerTonne);
        public SpecificEnergy WattDayPerKilogram => new SpecificEnergy(value, SpecificEnergyUnit.WattDayPerKilogram);
        public SpecificEnergy WattDayPerShortTon => new SpecificEnergy(value, SpecificEnergyUnit.WattDayPerShortTon);
        public SpecificEnergy WattDayPerTonne => new SpecificEnergy(value, SpecificEnergyUnit.WattDayPerTonne);
        public SpecificEnergy WattHourPerKilogram => new SpecificEnergy(value, SpecificEnergyUnit.WattHourPerKilogram);
    }

    // int receiver
    extension(int value)
    {
        public SpecificEnergy BtuPerPound => new SpecificEnergy(value, SpecificEnergyUnit.BtuPerPound);
        public SpecificEnergy CaloriePerGram => new SpecificEnergy(value, SpecificEnergyUnit.CaloriePerGram);
        public SpecificEnergy GigawattDayPerKilogram => new SpecificEnergy(value, SpecificEnergyUnit.GigawattDayPerKilogram);
        public SpecificEnergy GigawattDayPerShortTon => new SpecificEnergy(value, SpecificEnergyUnit.GigawattDayPerShortTon);
        public SpecificEnergy GigawattDayPerTonne => new SpecificEnergy(value, SpecificEnergyUnit.GigawattDayPerTonne);
        public SpecificEnergy GigawattHourPerKilogram => new SpecificEnergy(value, SpecificEnergyUnit.GigawattHourPerKilogram);
        public SpecificEnergy JoulePerKilogram => new SpecificEnergy(value, SpecificEnergyUnit.JoulePerKilogram);
        public SpecificEnergy KilocaloriePerGram => new SpecificEnergy(value, SpecificEnergyUnit.KilocaloriePerGram);
        public SpecificEnergy KilojoulePerKilogram => new SpecificEnergy(value, SpecificEnergyUnit.KilojoulePerKilogram);
        public SpecificEnergy KilowattDayPerKilogram => new SpecificEnergy(value, SpecificEnergyUnit.KilowattDayPerKilogram);
        public SpecificEnergy KilowattDayPerShortTon => new SpecificEnergy(value, SpecificEnergyUnit.KilowattDayPerShortTon);
        public SpecificEnergy KilowattDayPerTonne => new SpecificEnergy(value, SpecificEnergyUnit.KilowattDayPerTonne);
        public SpecificEnergy KilowattHourPerKilogram => new SpecificEnergy(value, SpecificEnergyUnit.KilowattHourPerKilogram);
        public SpecificEnergy MegajoulePerKilogram => new SpecificEnergy(value, SpecificEnergyUnit.MegajoulePerKilogram);
        public SpecificEnergy MegawattDayPerKilogram => new SpecificEnergy(value, SpecificEnergyUnit.MegawattDayPerKilogram);
        public SpecificEnergy MegawattDayPerShortTon => new SpecificEnergy(value, SpecificEnergyUnit.MegawattDayPerShortTon);
        public SpecificEnergy MegawattDayPerTonne => new SpecificEnergy(value, SpecificEnergyUnit.MegawattDayPerTonne);
        public SpecificEnergy MegawattHourPerKilogram => new SpecificEnergy(value, SpecificEnergyUnit.MegawattHourPerKilogram);
        public SpecificEnergy TerawattDayPerKilogram => new SpecificEnergy(value, SpecificEnergyUnit.TerawattDayPerKilogram);
        public SpecificEnergy TerawattDayPerShortTon => new SpecificEnergy(value, SpecificEnergyUnit.TerawattDayPerShortTon);
        public SpecificEnergy TerawattDayPerTonne => new SpecificEnergy(value, SpecificEnergyUnit.TerawattDayPerTonne);
        public SpecificEnergy WattDayPerKilogram => new SpecificEnergy(value, SpecificEnergyUnit.WattDayPerKilogram);
        public SpecificEnergy WattDayPerShortTon => new SpecificEnergy(value, SpecificEnergyUnit.WattDayPerShortTon);
        public SpecificEnergy WattDayPerTonne => new SpecificEnergy(value, SpecificEnergyUnit.WattDayPerTonne);
        public SpecificEnergy WattHourPerKilogram => new SpecificEnergy(value, SpecificEnergyUnit.WattHourPerKilogram);
    }

    // decimal receiver (convert as needed)
    extension(decimal value)
    {
        public SpecificEnergy BtuPerPound => new SpecificEnergy((double)value, SpecificEnergyUnit.BtuPerPound);
        public SpecificEnergy CaloriePerGram => new SpecificEnergy((double)value, SpecificEnergyUnit.CaloriePerGram);
        public SpecificEnergy GigawattDayPerKilogram => new SpecificEnergy((double)value, SpecificEnergyUnit.GigawattDayPerKilogram);
        public SpecificEnergy GigawattDayPerShortTon => new SpecificEnergy((double)value, SpecificEnergyUnit.GigawattDayPerShortTon);
        public SpecificEnergy GigawattDayPerTonne => new SpecificEnergy((double)value, SpecificEnergyUnit.GigawattDayPerTonne);
        public SpecificEnergy GigawattHourPerKilogram => new SpecificEnergy((double)value, SpecificEnergyUnit.GigawattHourPerKilogram);
        public SpecificEnergy JoulePerKilogram => new SpecificEnergy((double)value, SpecificEnergyUnit.JoulePerKilogram);
        public SpecificEnergy KilocaloriePerGram => new SpecificEnergy((double)value, SpecificEnergyUnit.KilocaloriePerGram);
        public SpecificEnergy KilojoulePerKilogram => new SpecificEnergy((double)value, SpecificEnergyUnit.KilojoulePerKilogram);
        public SpecificEnergy KilowattDayPerKilogram => new SpecificEnergy((double)value, SpecificEnergyUnit.KilowattDayPerKilogram);
        public SpecificEnergy KilowattDayPerShortTon => new SpecificEnergy((double)value, SpecificEnergyUnit.KilowattDayPerShortTon);
        public SpecificEnergy KilowattDayPerTonne => new SpecificEnergy((double)value, SpecificEnergyUnit.KilowattDayPerTonne);
        public SpecificEnergy KilowattHourPerKilogram => new SpecificEnergy((double)value, SpecificEnergyUnit.KilowattHourPerKilogram);
        public SpecificEnergy MegajoulePerKilogram => new SpecificEnergy((double)value, SpecificEnergyUnit.MegajoulePerKilogram);
        public SpecificEnergy MegawattDayPerKilogram => new SpecificEnergy((double)value, SpecificEnergyUnit.MegawattDayPerKilogram);
        public SpecificEnergy MegawattDayPerShortTon => new SpecificEnergy((double)value, SpecificEnergyUnit.MegawattDayPerShortTon);
        public SpecificEnergy MegawattDayPerTonne => new SpecificEnergy((double)value, SpecificEnergyUnit.MegawattDayPerTonne);
        public SpecificEnergy MegawattHourPerKilogram => new SpecificEnergy((double)value, SpecificEnergyUnit.MegawattHourPerKilogram);
        public SpecificEnergy TerawattDayPerKilogram => new SpecificEnergy((double)value, SpecificEnergyUnit.TerawattDayPerKilogram);
        public SpecificEnergy TerawattDayPerShortTon => new SpecificEnergy((double)value, SpecificEnergyUnit.TerawattDayPerShortTon);
        public SpecificEnergy TerawattDayPerTonne => new SpecificEnergy((double)value, SpecificEnergyUnit.TerawattDayPerTonne);
        public SpecificEnergy WattDayPerKilogram => new SpecificEnergy((double)value, SpecificEnergyUnit.WattDayPerKilogram);
        public SpecificEnergy WattDayPerShortTon => new SpecificEnergy((double)value, SpecificEnergyUnit.WattDayPerShortTon);
        public SpecificEnergy WattDayPerTonne => new SpecificEnergy((double)value, SpecificEnergyUnit.WattDayPerTonne);
        public SpecificEnergy WattHourPerKilogram => new SpecificEnergy((double)value, SpecificEnergyUnit.WattHourPerKilogram);
    }
}