using EngineeringUnits;
using EngineeringUnits.Units;

namespace EngineeringUnits.NumberExtensions.NumberToElectricInductance;

// <auto-generated/>
// This file is auto-generated; changes will be overwritten.
public static class NumberToElectricInductanceExtensions
{
    // double receiver
    extension(double value)
    {
        public ElectricInductance Henry => new ElectricInductance(value, ElectricInductanceUnit.Henry);
        public ElectricInductance Microhenry => new ElectricInductance(value, ElectricInductanceUnit.Microhenry);
        public ElectricInductance Millihenry => new ElectricInductance(value, ElectricInductanceUnit.Millihenry);
        public ElectricInductance Nanohenry => new ElectricInductance(value, ElectricInductanceUnit.Nanohenry);
    }

    // int receiver
    extension(int value)
    {
        public ElectricInductance Henry => new ElectricInductance(value, ElectricInductanceUnit.Henry);
        public ElectricInductance Microhenry => new ElectricInductance(value, ElectricInductanceUnit.Microhenry);
        public ElectricInductance Millihenry => new ElectricInductance(value, ElectricInductanceUnit.Millihenry);
        public ElectricInductance Nanohenry => new ElectricInductance(value, ElectricInductanceUnit.Nanohenry);
    }

    // decimal receiver (convert as needed)
    extension(decimal value)
    {
        public ElectricInductance Henry => new ElectricInductance((double)value, ElectricInductanceUnit.Henry);
        public ElectricInductance Microhenry => new ElectricInductance((double)value, ElectricInductanceUnit.Microhenry);
        public ElectricInductance Millihenry => new ElectricInductance((double)value, ElectricInductanceUnit.Millihenry);
        public ElectricInductance Nanohenry => new ElectricInductance((double)value, ElectricInductanceUnit.Nanohenry);
    }
}