using EngineeringUnits;
using EngineeringUnits.Units;

namespace EngineeringUnits.NumberExtensions.NumberToVolume;

// <auto-generated/>
// This file is auto-generated; changes will be overwritten.
public static class NumberToVolumeExtensions
{
    // double receiver
    extension(double value)
    {
        public Volume AcreFoot => new Volume(value, VolumeUnit.AcreFoot);
        public Volume AuTablespoon => new Volume(value, VolumeUnit.AuTablespoon);
        public Volume BoardFoot => new Volume(value, VolumeUnit.BoardFoot);
        public Volume Centiliter => new Volume(value, VolumeUnit.Centiliter);
        public Volume CubicCentimeter => new Volume(value, VolumeUnit.CubicCentimeter);
        public Volume CubicDecimeter => new Volume(value, VolumeUnit.CubicDecimeter);
        public Volume CubicFoot => new Volume(value, VolumeUnit.CubicFoot);
        public Volume CubicHectometer => new Volume(value, VolumeUnit.CubicHectometer);
        public Volume CubicInch => new Volume(value, VolumeUnit.CubicInch);
        public Volume CubicKilometer => new Volume(value, VolumeUnit.CubicKilometer);
        public Volume CubicMeter => new Volume(value, VolumeUnit.CubicMeter);
        public Volume CubicMicrometer => new Volume(value, VolumeUnit.CubicMicrometer);
        public Volume CubicMile => new Volume(value, VolumeUnit.CubicMile);
        public Volume CubicMillimeter => new Volume(value, VolumeUnit.CubicMillimeter);
        public Volume CubicYard => new Volume(value, VolumeUnit.CubicYard);
        public Volume DecausGallon => new Volume(value, VolumeUnit.DecausGallon);
        public Volume Deciliter => new Volume(value, VolumeUnit.Deciliter);
        public Volume DeciusGallon => new Volume(value, VolumeUnit.DeciusGallon);
        public Volume HectocubicFoot => new Volume(value, VolumeUnit.HectocubicFoot);
        public Volume HectocubicMeter => new Volume(value, VolumeUnit.HectocubicMeter);
        public Volume Hectoliter => new Volume(value, VolumeUnit.Hectoliter);
        public Volume HectousGallon => new Volume(value, VolumeUnit.HectousGallon);
        public Volume ImperialBeerBarrel => new Volume(value, VolumeUnit.ImperialBeerBarrel);
        public Volume ImperialGallon => new Volume(value, VolumeUnit.ImperialGallon);
        public Volume ImperialOunce => new Volume(value, VolumeUnit.ImperialOunce);
        public Volume ImperialPint => new Volume(value, VolumeUnit.ImperialPint);
        public Volume KilocubicFoot => new Volume(value, VolumeUnit.KilocubicFoot);
        public Volume KilocubicMeter => new Volume(value, VolumeUnit.KilocubicMeter);
        public Volume KiloimperialGallon => new Volume(value, VolumeUnit.KiloimperialGallon);
        public Volume Kiloliter => new Volume(value, VolumeUnit.Kiloliter);
        public Volume KilousGallon => new Volume(value, VolumeUnit.KilousGallon);
        public Volume Liter => new Volume(value, VolumeUnit.Liter);
        public Volume MegacubicFoot => new Volume(value, VolumeUnit.MegacubicFoot);
        public Volume MegaimperialGallon => new Volume(value, VolumeUnit.MegaimperialGallon);
        public Volume Megaliter => new Volume(value, VolumeUnit.Megaliter);
        public Volume MegausGallon => new Volume(value, VolumeUnit.MegausGallon);
        public Volume MetricCup => new Volume(value, VolumeUnit.MetricCup);
        public Volume MetricTeaspoon => new Volume(value, VolumeUnit.MetricTeaspoon);
        public Volume Microliter => new Volume(value, VolumeUnit.Microliter);
        public Volume Milliliter => new Volume(value, VolumeUnit.Milliliter);
        public Volume Nanoliter => new Volume(value, VolumeUnit.Nanoliter);
        public Volume OilBarrel => new Volume(value, VolumeUnit.OilBarrel);
        public Volume Picoliter => new Volume(value, VolumeUnit.Picoliter);
        public Volume UkTablespoon => new Volume(value, VolumeUnit.UkTablespoon);
        public Volume UsBeerBarrel => new Volume(value, VolumeUnit.UsBeerBarrel);
        public Volume UsCustomaryCup => new Volume(value, VolumeUnit.UsCustomaryCup);
        public Volume UsGallon => new Volume(value, VolumeUnit.UsGallon);
        public Volume UsLegalCup => new Volume(value, VolumeUnit.UsLegalCup);
        public Volume UsOunce => new Volume(value, VolumeUnit.UsOunce);
        public Volume UsPint => new Volume(value, VolumeUnit.UsPint);
        public Volume UsQuart => new Volume(value, VolumeUnit.UsQuart);
        public Volume UsTablespoon => new Volume(value, VolumeUnit.UsTablespoon);
        public Volume UsTeaspoon => new Volume(value, VolumeUnit.UsTeaspoon);
    }

    // int receiver
    extension(int value)
    {
        public Volume AcreFoot => new Volume(value, VolumeUnit.AcreFoot);
        public Volume AuTablespoon => new Volume(value, VolumeUnit.AuTablespoon);
        public Volume BoardFoot => new Volume(value, VolumeUnit.BoardFoot);
        public Volume Centiliter => new Volume(value, VolumeUnit.Centiliter);
        public Volume CubicCentimeter => new Volume(value, VolumeUnit.CubicCentimeter);
        public Volume CubicDecimeter => new Volume(value, VolumeUnit.CubicDecimeter);
        public Volume CubicFoot => new Volume(value, VolumeUnit.CubicFoot);
        public Volume CubicHectometer => new Volume(value, VolumeUnit.CubicHectometer);
        public Volume CubicInch => new Volume(value, VolumeUnit.CubicInch);
        public Volume CubicKilometer => new Volume(value, VolumeUnit.CubicKilometer);
        public Volume CubicMeter => new Volume(value, VolumeUnit.CubicMeter);
        public Volume CubicMicrometer => new Volume(value, VolumeUnit.CubicMicrometer);
        public Volume CubicMile => new Volume(value, VolumeUnit.CubicMile);
        public Volume CubicMillimeter => new Volume(value, VolumeUnit.CubicMillimeter);
        public Volume CubicYard => new Volume(value, VolumeUnit.CubicYard);
        public Volume DecausGallon => new Volume(value, VolumeUnit.DecausGallon);
        public Volume Deciliter => new Volume(value, VolumeUnit.Deciliter);
        public Volume DeciusGallon => new Volume(value, VolumeUnit.DeciusGallon);
        public Volume HectocubicFoot => new Volume(value, VolumeUnit.HectocubicFoot);
        public Volume HectocubicMeter => new Volume(value, VolumeUnit.HectocubicMeter);
        public Volume Hectoliter => new Volume(value, VolumeUnit.Hectoliter);
        public Volume HectousGallon => new Volume(value, VolumeUnit.HectousGallon);
        public Volume ImperialBeerBarrel => new Volume(value, VolumeUnit.ImperialBeerBarrel);
        public Volume ImperialGallon => new Volume(value, VolumeUnit.ImperialGallon);
        public Volume ImperialOunce => new Volume(value, VolumeUnit.ImperialOunce);
        public Volume ImperialPint => new Volume(value, VolumeUnit.ImperialPint);
        public Volume KilocubicFoot => new Volume(value, VolumeUnit.KilocubicFoot);
        public Volume KilocubicMeter => new Volume(value, VolumeUnit.KilocubicMeter);
        public Volume KiloimperialGallon => new Volume(value, VolumeUnit.KiloimperialGallon);
        public Volume Kiloliter => new Volume(value, VolumeUnit.Kiloliter);
        public Volume KilousGallon => new Volume(value, VolumeUnit.KilousGallon);
        public Volume Liter => new Volume(value, VolumeUnit.Liter);
        public Volume MegacubicFoot => new Volume(value, VolumeUnit.MegacubicFoot);
        public Volume MegaimperialGallon => new Volume(value, VolumeUnit.MegaimperialGallon);
        public Volume Megaliter => new Volume(value, VolumeUnit.Megaliter);
        public Volume MegausGallon => new Volume(value, VolumeUnit.MegausGallon);
        public Volume MetricCup => new Volume(value, VolumeUnit.MetricCup);
        public Volume MetricTeaspoon => new Volume(value, VolumeUnit.MetricTeaspoon);
        public Volume Microliter => new Volume(value, VolumeUnit.Microliter);
        public Volume Milliliter => new Volume(value, VolumeUnit.Milliliter);
        public Volume Nanoliter => new Volume(value, VolumeUnit.Nanoliter);
        public Volume OilBarrel => new Volume(value, VolumeUnit.OilBarrel);
        public Volume Picoliter => new Volume(value, VolumeUnit.Picoliter);
        public Volume UkTablespoon => new Volume(value, VolumeUnit.UkTablespoon);
        public Volume UsBeerBarrel => new Volume(value, VolumeUnit.UsBeerBarrel);
        public Volume UsCustomaryCup => new Volume(value, VolumeUnit.UsCustomaryCup);
        public Volume UsGallon => new Volume(value, VolumeUnit.UsGallon);
        public Volume UsLegalCup => new Volume(value, VolumeUnit.UsLegalCup);
        public Volume UsOunce => new Volume(value, VolumeUnit.UsOunce);
        public Volume UsPint => new Volume(value, VolumeUnit.UsPint);
        public Volume UsQuart => new Volume(value, VolumeUnit.UsQuart);
        public Volume UsTablespoon => new Volume(value, VolumeUnit.UsTablespoon);
        public Volume UsTeaspoon => new Volume(value, VolumeUnit.UsTeaspoon);
    }

    // decimal receiver (convert as needed)
    extension(decimal value)
    {
        public Volume AcreFoot => new Volume((double)value, VolumeUnit.AcreFoot);
        public Volume AuTablespoon => new Volume((double)value, VolumeUnit.AuTablespoon);
        public Volume BoardFoot => new Volume((double)value, VolumeUnit.BoardFoot);
        public Volume Centiliter => new Volume((double)value, VolumeUnit.Centiliter);
        public Volume CubicCentimeter => new Volume((double)value, VolumeUnit.CubicCentimeter);
        public Volume CubicDecimeter => new Volume((double)value, VolumeUnit.CubicDecimeter);
        public Volume CubicFoot => new Volume((double)value, VolumeUnit.CubicFoot);
        public Volume CubicHectometer => new Volume((double)value, VolumeUnit.CubicHectometer);
        public Volume CubicInch => new Volume((double)value, VolumeUnit.CubicInch);
        public Volume CubicKilometer => new Volume((double)value, VolumeUnit.CubicKilometer);
        public Volume CubicMeter => new Volume((double)value, VolumeUnit.CubicMeter);
        public Volume CubicMicrometer => new Volume((double)value, VolumeUnit.CubicMicrometer);
        public Volume CubicMile => new Volume((double)value, VolumeUnit.CubicMile);
        public Volume CubicMillimeter => new Volume((double)value, VolumeUnit.CubicMillimeter);
        public Volume CubicYard => new Volume((double)value, VolumeUnit.CubicYard);
        public Volume DecausGallon => new Volume((double)value, VolumeUnit.DecausGallon);
        public Volume Deciliter => new Volume((double)value, VolumeUnit.Deciliter);
        public Volume DeciusGallon => new Volume((double)value, VolumeUnit.DeciusGallon);
        public Volume HectocubicFoot => new Volume((double)value, VolumeUnit.HectocubicFoot);
        public Volume HectocubicMeter => new Volume((double)value, VolumeUnit.HectocubicMeter);
        public Volume Hectoliter => new Volume((double)value, VolumeUnit.Hectoliter);
        public Volume HectousGallon => new Volume((double)value, VolumeUnit.HectousGallon);
        public Volume ImperialBeerBarrel => new Volume((double)value, VolumeUnit.ImperialBeerBarrel);
        public Volume ImperialGallon => new Volume((double)value, VolumeUnit.ImperialGallon);
        public Volume ImperialOunce => new Volume((double)value, VolumeUnit.ImperialOunce);
        public Volume ImperialPint => new Volume((double)value, VolumeUnit.ImperialPint);
        public Volume KilocubicFoot => new Volume((double)value, VolumeUnit.KilocubicFoot);
        public Volume KilocubicMeter => new Volume((double)value, VolumeUnit.KilocubicMeter);
        public Volume KiloimperialGallon => new Volume((double)value, VolumeUnit.KiloimperialGallon);
        public Volume Kiloliter => new Volume((double)value, VolumeUnit.Kiloliter);
        public Volume KilousGallon => new Volume((double)value, VolumeUnit.KilousGallon);
        public Volume Liter => new Volume((double)value, VolumeUnit.Liter);
        public Volume MegacubicFoot => new Volume((double)value, VolumeUnit.MegacubicFoot);
        public Volume MegaimperialGallon => new Volume((double)value, VolumeUnit.MegaimperialGallon);
        public Volume Megaliter => new Volume((double)value, VolumeUnit.Megaliter);
        public Volume MegausGallon => new Volume((double)value, VolumeUnit.MegausGallon);
        public Volume MetricCup => new Volume((double)value, VolumeUnit.MetricCup);
        public Volume MetricTeaspoon => new Volume((double)value, VolumeUnit.MetricTeaspoon);
        public Volume Microliter => new Volume((double)value, VolumeUnit.Microliter);
        public Volume Milliliter => new Volume((double)value, VolumeUnit.Milliliter);
        public Volume Nanoliter => new Volume((double)value, VolumeUnit.Nanoliter);
        public Volume OilBarrel => new Volume((double)value, VolumeUnit.OilBarrel);
        public Volume Picoliter => new Volume((double)value, VolumeUnit.Picoliter);
        public Volume UkTablespoon => new Volume((double)value, VolumeUnit.UkTablespoon);
        public Volume UsBeerBarrel => new Volume((double)value, VolumeUnit.UsBeerBarrel);
        public Volume UsCustomaryCup => new Volume((double)value, VolumeUnit.UsCustomaryCup);
        public Volume UsGallon => new Volume((double)value, VolumeUnit.UsGallon);
        public Volume UsLegalCup => new Volume((double)value, VolumeUnit.UsLegalCup);
        public Volume UsOunce => new Volume((double)value, VolumeUnit.UsOunce);
        public Volume UsPint => new Volume((double)value, VolumeUnit.UsPint);
        public Volume UsQuart => new Volume((double)value, VolumeUnit.UsQuart);
        public Volume UsTablespoon => new Volume((double)value, VolumeUnit.UsTablespoon);
        public Volume UsTeaspoon => new Volume((double)value, VolumeUnit.UsTeaspoon);
    }
}