using EngineeringUnits;
using EngineeringUnits.Units;

namespace EngineeringUnits.NumberExtensions.NumberToElectricCurrentDensity;

// <auto-generated/>
// This file is auto-generated; changes will be overwritten.
public static class NumberToElectricCurrentDensityExtensions
{
    // double receiver
    extension(double value)
    {
        public ElectricCurrentDensity AmperePerSquareFoot => new ElectricCurrentDensity(value, ElectricCurrentDensityUnit.AmperePerSquareFoot);
        public ElectricCurrentDensity AmperePerSquareInch => new ElectricCurrentDensity(value, ElectricCurrentDensityUnit.AmperePerSquareInch);
        public ElectricCurrentDensity AmperePerSquareMeter => new ElectricCurrentDensity(value, ElectricCurrentDensityUnit.AmperePerSquareMeter);
    }

    // int receiver
    extension(int value)
    {
        public ElectricCurrentDensity AmperePerSquareFoot => new ElectricCurrentDensity(value, ElectricCurrentDensityUnit.AmperePerSquareFoot);
        public ElectricCurrentDensity AmperePerSquareInch => new ElectricCurrentDensity(value, ElectricCurrentDensityUnit.AmperePerSquareInch);
        public ElectricCurrentDensity AmperePerSquareMeter => new ElectricCurrentDensity(value, ElectricCurrentDensityUnit.AmperePerSquareMeter);
    }

    // decimal receiver (convert as needed)
    extension(decimal value)
    {
        public ElectricCurrentDensity AmperePerSquareFoot => new ElectricCurrentDensity((double)value, ElectricCurrentDensityUnit.AmperePerSquareFoot);
        public ElectricCurrentDensity AmperePerSquareInch => new ElectricCurrentDensity((double)value, ElectricCurrentDensityUnit.AmperePerSquareInch);
        public ElectricCurrentDensity AmperePerSquareMeter => new ElectricCurrentDensity((double)value, ElectricCurrentDensityUnit.AmperePerSquareMeter);
    }
}