using EngineeringUnits;
using EngineeringUnits.Units;

namespace EngineeringUnits.NumberExtensions.NumberToHeatTransferCoefficient;

// <auto-generated/>
// This file is auto-generated; changes will be overwritten.
public static class NumberToHeatTransferCoefficientExtensions
{
    // double receiver
    extension(double value)
    {
        public HeatTransferCoefficient BtuPerSquareFootDegreeFahrenheit => new HeatTransferCoefficient(value, HeatTransferCoefficientUnit.BtuPerSquareFootDegreeFahrenheit);
        public HeatTransferCoefficient WattPerSquareMeterCelsius => new HeatTransferCoefficient(value, HeatTransferCoefficientUnit.WattPerSquareMeterCelsius);
        public HeatTransferCoefficient WattPerSquareMeterKelvin => new HeatTransferCoefficient(value, HeatTransferCoefficientUnit.WattPerSquareMeterKelvin);
    }

    // int receiver
    extension(int value)
    {
        public HeatTransferCoefficient BtuPerSquareFootDegreeFahrenheit => new HeatTransferCoefficient(value, HeatTransferCoefficientUnit.BtuPerSquareFootDegreeFahrenheit);
        public HeatTransferCoefficient WattPerSquareMeterCelsius => new HeatTransferCoefficient(value, HeatTransferCoefficientUnit.WattPerSquareMeterCelsius);
        public HeatTransferCoefficient WattPerSquareMeterKelvin => new HeatTransferCoefficient(value, HeatTransferCoefficientUnit.WattPerSquareMeterKelvin);
    }

    // decimal receiver (convert as needed)
    extension(decimal value)
    {
        public HeatTransferCoefficient BtuPerSquareFootDegreeFahrenheit => new HeatTransferCoefficient((double)value, HeatTransferCoefficientUnit.BtuPerSquareFootDegreeFahrenheit);
        public HeatTransferCoefficient WattPerSquareMeterCelsius => new HeatTransferCoefficient((double)value, HeatTransferCoefficientUnit.WattPerSquareMeterCelsius);
        public HeatTransferCoefficient WattPerSquareMeterKelvin => new HeatTransferCoefficient((double)value, HeatTransferCoefficientUnit.WattPerSquareMeterKelvin);
    }
}