using EngineeringUnits;
using EngineeringUnits.Units;

namespace EngineeringUnits.NumberExtensions.NumberToAngle;

// <auto-generated/>
// This file is auto-generated; changes will be overwritten.
public static class NumberToAngleExtensions
{
    // double receiver
    extension(double value)
    {
        public Angle Arcminute => new Angle(value, AngleUnit.Arcminute);
        public Angle Arcsecond => new Angle(value, AngleUnit.Arcsecond);
        public Angle Centiradian => new Angle(value, AngleUnit.Centiradian);
        public Angle Deciradian => new Angle(value, AngleUnit.Deciradian);
        public Angle Degree => new Angle(value, AngleUnit.Degree);
        public Angle Gradian => new Angle(value, AngleUnit.Gradian);
        public Angle Microdegree => new Angle(value, AngleUnit.Microdegree);
        public Angle Microradian => new Angle(value, AngleUnit.Microradian);
        public Angle Millidegree => new Angle(value, AngleUnit.Millidegree);
        public Angle Milliradian => new Angle(value, AngleUnit.Milliradian);
        public Angle Nanodegree => new Angle(value, AngleUnit.Nanodegree);
        public Angle Nanoradian => new Angle(value, AngleUnit.Nanoradian);
        public Angle Radian => new Angle(value, AngleUnit.Radian);
        public Angle Revolution => new Angle(value, AngleUnit.Revolution);
    }

    // int receiver
    extension(int value)
    {
        public Angle Arcminute => new Angle(value, AngleUnit.Arcminute);
        public Angle Arcsecond => new Angle(value, AngleUnit.Arcsecond);
        public Angle Centiradian => new Angle(value, AngleUnit.Centiradian);
        public Angle Deciradian => new Angle(value, AngleUnit.Deciradian);
        public Angle Degree => new Angle(value, AngleUnit.Degree);
        public Angle Gradian => new Angle(value, AngleUnit.Gradian);
        public Angle Microdegree => new Angle(value, AngleUnit.Microdegree);
        public Angle Microradian => new Angle(value, AngleUnit.Microradian);
        public Angle Millidegree => new Angle(value, AngleUnit.Millidegree);
        public Angle Milliradian => new Angle(value, AngleUnit.Milliradian);
        public Angle Nanodegree => new Angle(value, AngleUnit.Nanodegree);
        public Angle Nanoradian => new Angle(value, AngleUnit.Nanoradian);
        public Angle Radian => new Angle(value, AngleUnit.Radian);
        public Angle Revolution => new Angle(value, AngleUnit.Revolution);
    }

    // decimal receiver (convert as needed)
    extension(decimal value)
    {
        public Angle Arcminute => new Angle((double)value, AngleUnit.Arcminute);
        public Angle Arcsecond => new Angle((double)value, AngleUnit.Arcsecond);
        public Angle Centiradian => new Angle((double)value, AngleUnit.Centiradian);
        public Angle Deciradian => new Angle((double)value, AngleUnit.Deciradian);
        public Angle Degree => new Angle((double)value, AngleUnit.Degree);
        public Angle Gradian => new Angle((double)value, AngleUnit.Gradian);
        public Angle Microdegree => new Angle((double)value, AngleUnit.Microdegree);
        public Angle Microradian => new Angle((double)value, AngleUnit.Microradian);
        public Angle Millidegree => new Angle((double)value, AngleUnit.Millidegree);
        public Angle Milliradian => new Angle((double)value, AngleUnit.Milliradian);
        public Angle Nanodegree => new Angle((double)value, AngleUnit.Nanodegree);
        public Angle Nanoradian => new Angle((double)value, AngleUnit.Nanoradian);
        public Angle Radian => new Angle((double)value, AngleUnit.Radian);
        public Angle Revolution => new Angle((double)value, AngleUnit.Revolution);
    }
}