using EngineeringUnits;
using EngineeringUnits.Units;

namespace EngineeringUnits.NumberExtensions.NumberToElectricConductivity;

// <auto-generated/>
// This file is auto-generated; changes will be overwritten.
public static class NumberToElectricConductivityExtensions
{
    // double receiver
    extension(double value)
    {
        public ElectricConductivity SiemensPerFoot => new ElectricConductivity(value, ElectricConductivityUnit.SiemensPerFoot);
        public ElectricConductivity SiemensPerInch => new ElectricConductivity(value, ElectricConductivityUnit.SiemensPerInch);
        public ElectricConductivity SiemensPerMeter => new ElectricConductivity(value, ElectricConductivityUnit.SiemensPerMeter);
    }

    // int receiver
    extension(int value)
    {
        public ElectricConductivity SiemensPerFoot => new ElectricConductivity(value, ElectricConductivityUnit.SiemensPerFoot);
        public ElectricConductivity SiemensPerInch => new ElectricConductivity(value, ElectricConductivityUnit.SiemensPerInch);
        public ElectricConductivity SiemensPerMeter => new ElectricConductivity(value, ElectricConductivityUnit.SiemensPerMeter);
    }

    // decimal receiver (convert as needed)
    extension(decimal value)
    {
        public ElectricConductivity SiemensPerFoot => new ElectricConductivity((double)value, ElectricConductivityUnit.SiemensPerFoot);
        public ElectricConductivity SiemensPerInch => new ElectricConductivity((double)value, ElectricConductivityUnit.SiemensPerInch);
        public ElectricConductivity SiemensPerMeter => new ElectricConductivity((double)value, ElectricConductivityUnit.SiemensPerMeter);
    }
}