using EngineeringUnits;
using EngineeringUnits.Units;

namespace EngineeringUnits.NumberExtensions.NumberToPermittivity;

// <auto-generated/>
// This file is auto-generated; changes will be overwritten.
public static class NumberToPermittivityExtensions
{
    // double receiver
    extension(double value)
    {
        public Permittivity FaradPerMeter => new Permittivity(value, PermittivityUnit.FaradPerMeter);
    }

    // int receiver
    extension(int value)
    {
        public Permittivity FaradPerMeter => new Permittivity(value, PermittivityUnit.FaradPerMeter);
    }

    // decimal receiver (convert as needed)
    extension(decimal value)
    {
        public Permittivity FaradPerMeter => new Permittivity((double)value, PermittivityUnit.FaradPerMeter);
    }
}